### ISSUE TITLE
 cannot import name 'GceClusterResolver'

### ISSUE THREAD

**Issue by DuanWei-fudan** [DeepLabCut/DeepLabCut#1024]
i can't find my last issues in the Github,mybe it's a bug.So i creat a new issue.

when i **import deeplabcutcore as deeplabcut**

```python 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\__init__.py", line 20, in <module>
    from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\__init__.py", line 4, in <module>
    from deeplabcutcore.create_project.demo_data import load_demo_data
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\demo_data.py", line 14, in <module>
    from deeplabcutcore.utils import auxiliaryfunctions
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\__init__.py", line 1, in <module>
    from deeplabcutcore.utils.make_labeled_video import *
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\make_labeled_video.py", line 38, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.config import load_config
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\__init__.py", line 13, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet import *
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\__init__.py", line 16, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet.pose_net import *
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\pose_net.py", line 9, in <module>
    import tensorflow.contrib.slim as slim
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\__init__.py", line 31, in <module>
    from tensorflow.contrib import cluster_resolver
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\cluster_resolver\__init__.py", line 26, in <module>
    from tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver import GceClusterResolver
ImportError: cannot import name 'GceClusterResolver' from 'tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver' (C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\distribute\cluster_resolver\gce_cluster_resolver.py)

```

**Comment by DuanWei-fudan** [comment]
another question : how can I solve the TF2.x  **No module named 'tensorflow.contrib'**????

**Comment by DuanWei-fudan** [comment]
```python 

 **import deeplabcutcore as deeplabcut**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\__init__.py", line 20, in <module>
    from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\create_project\__init__.py", line 4, in <module>
    from deeplabcutcore.create_project.demo_data import load_demo_data
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\create_project\demo_data.py", line 14, in <module>
    from deeplabcutcore.utils import auxiliaryfunctions
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\utils\__init__.py", line 1, in <module>
    from deeplabcutcore.utils.make_labeled_video import *
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\utils\make_labeled_video.py", line 38, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.config import load_config
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\__init__.py", line 13, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet import *
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\__init__.py", line 16, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet.pose_net import *
  File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\pose_net.py", line 9, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'

```

**Comment by MMathisLab** [comment]
I answered here: https://github.com/DeepLabCut/DeepLabCut/issues/1017

Can you please post on the deeplabcutcore repo if you have issues (https://github.com/DeepLabCut/DeepLabCut-core), and I would ask you first please try colab and be sure it makes sense for you. 

For your second issue, you are trying to use TF2 code within TF1 env: 
```python
File "C:\Users\Administrator\anaconda3\envs\TF1.0\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\pose_net.py", line 9, in <module>
    import tensorflow.contrib.slim as slim
```

**Comment by DuanWei-fudan** [comment]
Yuo can't image how terrible I was. I did it you mentioned in #1017  already.
**pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha
pip install tf_slim**

But when I **import deeplabcutcore as deeplabcut**,the same problem has occurred.

ImportError: cannot import name 'GceClusterResolver' from 'tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver' (C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\sitepackages\tensorflow\python\distribute\ cluster_resolver\gce_cluster_resolver.py)

I search it on the internet,they all say I should change my tensorflow to TF1.X What should I do?

**Comment by DuanWei-fudan** [comment]
Maybe I am not suitable for this.I read the #944 you mentioned.So I update my CUDA to 1.11 and cudnn to 8.0.
When I test in the DLC-GPU with the code **python testscript.py**,this is a problem named **AttributeError: module 'TensorFlow' has no attribute 'logging'**,so I change the tf.logging to tf.compat.v1.logging.After that ,the same problem occurred,**" cannot import name 'GceClusterResolver' from 'tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver' "**.
It is the all error:
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
Traceback (most recent call last):
  File "testscript.py", line 19, in <module>
    import os, subprocess, deeplabcut
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\__init__.py", line 38, in <module>
    from deeplabcut import generate_training_dataset
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py", line 23, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 18, in <module>
    from deeplabcut.pose_estimation_tensorflow.export import export_model
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\export.py", line 29, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet import predict
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\__init__.py", line 16, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet.pose_net import *
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 17, in <module>
    import tensorflow.contrib.slim as slim
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\__init__.py", line 31, in <module>
    from tensorflow.contrib import cluster_resolver
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\cluster_resolver\__init__.py", line 26, in <module>
    from tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver import GceClusterResolver
ImportError: cannot import name 'GceClusterResolver' from 'tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver' (C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\distribute\cluster_resolver\gce_cluster_resolver.py)

**Comment by DuanWei-fudan** [comment]
Maybe is there a singe steps for the deeplabcutcore?

**Comment by MMathisLab** [comment]
it just sounds like you did not installed deeplabutcore correctly. 

you need to be sure TF 2.x is installed first. 

then run:
```
!pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha
!pip install tf_slim
```

**Comment by DuanWei-fudan** [comment]
Maybe the reason is that I use the TF-gpu not the Tensorflow. I am sure that Tensorflow-gpu is 2.x.So the deeplabcutcore just is supported by the TF-CPU?

**Comment by MMathisLab** [comment]
No, it definitely works with GPUs I would urge you to try the colab link as a tes; you just upload your project folder to google drive, the use that notebook as is. At least you will see the code works ;). 

you just need to install `pip install tensorflow==2.3` for example; tf dropped the gpu vs cpu, btw.

**Comment by DuanWei-fudan** [comment]
I will try the colab tomorrow.Maybe I can create a new TF enviroment to install the tensorflow again.WOO OHH.
it's my steps,maybe there are some mistakes?
I download the CUDA 1.11 with cudnn  firstly;
I use the Anoconda 3 to create a TF enviroment with python 3.7;
I install the tensorflow-gpu after activating the TF env;
I install the deeplabcut and the deeplabcutcore .
Maybe I just need install the Tensorflow?But how can I use the GPUs to train my network?

**Comment by MMathisLab** [comment]
In your env: if you do, what version are you using?
```python
import tensorflow 
tensorflow.__version__

```

**Comment by DuanWei-fudan** [comment]
I find my tensorflow version is 2.2.0,so I change it by **pip install tensorflow==2.3**.
I run it 👍 
    _pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha_
    _pip install tf_slim_
When I run 
   _import tensorflow as tf_ 
the computer tell me **Successfully opened dynamic library cudart64_101.dll**,maybe there is not any mistakes.
However ,when I run
 _import deeplabcutcore as deeplabcut_
the computer tell me **ModuleNotFoundError: No module named 'tensorflow.contrib'**
So how can I solve it?The module has removed  in TF2.x.

**Comment by DuanWei-fudan** [comment]
Hey,I tested the code you mentioned in [colab.research.google.com/github/DeepLabCut/DeepLabCut-core/blob/tf2.2alpha/Colab_TrainNetwork_VideoAnalysis_TF2.ipynb#scrollTo=3K9Ndy1beyfG](url),but it  also owns some mistakes,when I run : _import deeplancutcore as deeplabcut_,it told me **ModuleNotFoundError: No module named 'deeplabcutcore'**

**Comment by MMathisLab** [comment]
this 100% works for me (and others): 

https://github.com/DeepLabCut/DeepLabCut-core/blob/tf2.2alpha/Colab_TrainNetwork_VideoAnalysis_TF2.ipynb

VIDEO:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/28102185/102020957-cda03600-3d7c-11eb-83b5-67b72bdea54f.gif)

**Comment by DuanWei-fudan** [comment]
I removed the envs and created a new one with  python=3.6
I installed TensorFlow==2.3 and deeplabcutcore
I also installed the branches with
   **pip install pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha**
      **pip install tf_slim**
However when I _import the deeplabcutcore as deeplabcut_ ,it told me **No module named 'tensorflow.contrib'**
Maybe it wants TF1.X?
And then I searched the packages in the envs,I didn't see the cudnn(7.6.5) and cudatoolkit(10.2.89), so I installed them. 
The same ModuleNotFoundError had occurred.Maybe I lacked the deeplabcut? So I installed  deeplabcut==2.2b8. However 
it didn't works again.

**Comment by DuanWei-fudan** [comment]
Oh my god,I am sorry for that.I mistake your meaning.I can use the deeplabcutcore right now!
So how can I label my data?I find that the deeplabcutcore' has no attribute 'label_frames'.

**Comment by DuanWei-fudan** [comment]
Well,how can I chose the GPU to train when I create my own project?
Thank you so much!!!!!!

**Comment by MMathisLab** [comment]
You can have the normal `pip install deeplabcut` either in another env, or the same environment to create the project + Label, then use the dlccore alpha branch to create the training set and train, evaluate, and analyze videos.

you're welcome.

**Comment by DuanWei-fudan** [comment]
Well ,so why don't you add the part of label into the deeplabcutcore?Maybe it is more convenient.

**Comment by MMathisLab** [comment]
because core is for the docker; which does not have GUI support. We are in the process of splitting the package such that core will be a dependency of dlc. Right now we do not want to force people to use TF2. https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/roadmap.md

**Comment by DuanWei-fudan** [comment]
Actually for me,the deeplabcutcore is better than deeplabcut. I always stopped at the stage of training my network.I maybe works one time in ten trails.As foe now,I can label my data in deeplabcut and train in deeplabcutcore. Although I don't know how to select the GPU in deeplabcutcore. Just a little slow in the training speed! This is a huge step forward for me! 
I hope the amazing tools can help me a lot in the future research work.

**Comment by DuanWei-fudan** [comment]
I'm so sorry for disturbing you again. Could you please help me for how to chose a GPU in deeplabcutcore?I trained my network for 2000 in CPU for about 4 hours! I searched on the GitHub and used the code like:
_import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"_
But it didn't works.
So what the code do you use?
