### ISSUE TITLE
No module named 'tensorflow.contrib

### ISSUE THREAD

**Issue by DuanWei-fudan** [DeepLabCut/DeepLabCut#1042]
I created a python=3.7 env in Anaconda 3.And then I installed the deeplabcutcore and tf-nightly-gpu==2.5.0.dev20201019(OR TF==2.3).
Maybe I also needed some branches with 
**pip install tf_slim 
pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha**

But the same problems occurred every time: 
_>>> import tensorflow
2020-12-22 15:29:29.648746: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> import deeplabcutcore as deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\__init__.py", line 20, in <module>
    from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\__init__.py", line 4, in <module>
    from deeplabcutcore.create_project.demo_data import load_demo_data
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\create_project\demo_data.py", line 14, in <module>
    from deeplabcutcore.utils import auxiliaryfunctions
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\__init__.py", line 1, in <module>
    from deeplabcutcore.utils.make_labeled_video import *
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\utils\make_labeled_video.py", line 38, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.config import load_config
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\__init__.py", line 13, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet import *
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\__init__.py", line 16, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet.pose_net import *
  File "C:\Users\Administrator\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\nnet\pose_net.py", line 9, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'_
What should I do?

**Comment by MMathisLab** [comment]
@DuanWei-fudan please, can you post issues on the repo that the code is from; that is not from this repo, and I have answered all your questions beforehand, gave you a COLAB notebook to run the code with TF2, etc. I kindly ask you please do not open more issues here. thank you. 

https://github.com/DeepLabCut/DeepLabCut/issues/1024

https://github.com/DeepLabCut/DeepLabCut/issues/1017

As I said several times, do NOT install deeplabcut-core from pypi, you can only run to get TF2 support.
```python
pip install git+https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha
!pip install tf_slim
```
