### ISSUE TITLE
Kmeans Extract Frames - ValueError: Input contains NaN

### ISSUE THREAD

**Issue by neurologic** [DeepLabCut/DeepLabCut#1175]
**Describe the bug**

When using the gui to 'extract frames' via kmeans algorithm (but not uniform), I receive the error "ValueError: Input contains NaN, infinity or a value too large for dtype('float64')." I have only tried this via the GUI (rather than using the extract frames function directly); not sure if there would be a difference?

**Desktop (please complete the following information about your system):**
 - OS: MacOS 10.15.7
 - DeepLabCut Version 2.1.10.2 (from within git cloned DeepLabCut; latest git pull was this morning)
 - DeepLabCut mode multi-animal tracking
 - environment DLC_CPU

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. pythonw; import deeplabcut; deeplabcut_launch_dlc()
2. Created new project with a loaded video (symlinked)
3. Go to Extract Frames tab; specify kmeans
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!

Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 51.67  seconds.
Extracting and downsampling... 775  frames from the video.
775it [01:35,  8.13it/s]
Kmeans clustering ... (this might take a while)
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/numpy/core/_methods.py:75: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)
/Users/kperks/DeepLabCut/deeplabcut/utils/frameselectiontools.py:386: RuntimeWarning: invalid value encountered in subtract
  data = DATA - DATA.mean(axis=0)
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Traceback (most recent call last):
  File "/Users/kperks/DeepLabCut/deeplabcut/gui/extract_frames.py", line 241, in extract_frames
    slider_width=slider_width,
  File "/Users/kperks/DeepLabCut/deeplabcut/generate_training_dataset/frame_extraction.py", line 306, in extract_frames
    color=cluster_color,
  File "/Users/kperks/DeepLabCut/deeplabcut/utils/frameselectiontools.py", line 392, in KmeansbasedFrameselectioncv2
    kmeans.fit(data)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1662, in fit
    order='C', accept_large_sparse=False)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 664, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

do not delete below this line, leave the blank line and the ```

```
</p></details>

**Expected behavior**
Frames to be extracted with no error

**Additional context**
It seems like I have run into this problem before. One solution was to work from the latest version via git clone. Sometimes this error does not occur, but sometimes it does. I cannot figure out anything different on our end that correlates with this error or not. Any ideas?

Thank you so much as always for your help!

**Comment by MMathisLab** [comment]
if you have the git clones version, can you please cd into the DeepLabCut main folder, and run `./reinstall.sh` in your conda env; then you should be able to cd into `examples` and run `pythonw testscipt.py` this will test every function.

**Comment by MMathisLab** [comment]
^ from our tests, this is passing from current repo; if you reinstall, it should also install a new version of numpy.

**Comment by neurologic** [comment]
Thank you! I will try this now. Should I run testscript_multianimal.py or
does the plain testscript.py cover this now?

**Comment by neurologic** [comment]
Also, does ./reinstall.sh mean that it will be installed in the environment
in a way that it can be run from any directory? (we have just been
operating out of DeepLabCut directory for now to use the latest functions).

**Comment by neurologic** [comment]
Not that this is an error, but I do get this message when I import deeplabcut within pythonw now (after running ./reinstall.sh):

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!
>>> import deeplabcut
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
do not delete below this line, leave the blank line and the ```

```
</p></details>

**Comment by neurologic** [comment]
Yay! The "ValueError: NaN...etc" error is no longer occurring with kmeans extract frames. Thank you so much!

**Comment by MMathisLab** [comment]
^ you can run both test scripts, but the kmeans is identical between the two. You should still import from the main folder, but the latest is now installed into the conda, correct. If you want to force numpy to be the latest, that message should go away, but otherwise, just ugly, no functional consequence.

**Comment by neurologic** [comment]
@MMathisLab Ok sounds good. That makes sense. Thank you again.
