### ISSUE TITLE
Labels Placed Outside Image

### ISSUE THREAD

**Issue by NickBardjis** [DeepLabCut/DeepLabCut#1185]
When labeling frames it is possible to right click to place a label outside of the image.  If you do so, the program moves to the next body part as if a label was actually placed, but no visible label exists.  If you select the same body part and try to place a label elsewhere, it tells you a label already exists.  As the label cannot be seen, the user cannot click on it to delete it.
This can occur both when zoomed in and when viewing the whole image.  Notably any labels placed like this when zoomed in do not simply appear in a part of the image that is currently out of view.
Error output for 3 such incidents given below

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version 2.1.10.2
 - multi-animal tracking

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. In the command line run deeplabcut.label_frames(config_path)
2. Select "Load Frames" and choose any folder of frames
3. On any frame, select a body part that does not have a label
4. Right click in the GUI outside of the image of the frame
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

Traceback (most recent call last):
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in OnKeyPressed
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in <listcomp>
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 351, in calc_distance
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in OnKeyPressed
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in <listcomp>
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 351, in calc_distance
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in OnKeyPressed
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in <listcomp>
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 351, in calc_distance
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in OnKeyPressed
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in <listcomp>
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 351, in calc_distance
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in OnKeyPressed
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in <listcomp>
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 351, in calc_distance
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in OnKeyPressed
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 333, in <listcomp>
    [self.calc_distance(*dp.point.center, *pos_rel) for dp in self.drs]
  File "C:\Users\astro\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 351, in calc_distance
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

```
</p></details>

**Comment by NickBardjis** [comment]
The problematic labels are removed if you close and reopen the GUI, even after saving.  Meant to check that before posting, but forgot.  Sorry.

**Comment by MMathisLab** [comment]
Hi @NickBardjis if you do this, you can "pan" outside the image. A good trick is to just make the markers huge, then look for it by pan:

<img width="1234" alt="Screen Shot 2021-04-08 at 10 10 43 PM" src="https://user-images.githubusercontent.com/28102185/114090094-450f4d80-98b7-11eb-9492-5e18123aa3d5.png">
