### ISSUE TITLE
FileNotFoundError after upgrading -- FileNotFoundError: [Errno 2] No such file or directory: (wrong project path)

### ISSUE THREAD

**Issue by Idavr** [DeepLabCut/DeepLabCut#1206]
OS: Windows 10
DeepLabCut Version: 2.2b8
Anaconda Environment

I upgraded to the latest update of the maDLC that I have had some issues to work correctly previously, and when trying to re-train the previous model (after some reading of different issues on this site) I got the error pasted below. It makes complete sense that the file is not found as there is no such directory. It seems the issue is that the path of the metadataset gets appended to the project_path, but I do not know how to adjust this as there is only the project path in the config file and also it was not an issue before the update. How do I correct this?
```python

Selecting multi-animal trainer
Config:
{'Task': None,
 'TrainingFraction': None,
 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7]],
 'all_joints_names': ['nose',
                      'leftear',
                      'rightear',
                      'neck',
                      'back',
                      'tailbase',
                      'LED1',
                      'LED2'],
 'alpha_r': 0.02,
 'alphavalue': None,
 'batch_size': 8,
 'bodyparts': None,
 'colormap': None,
 'corner2move2': None,
 'crop_pad': 0,
 'croppedtraining': None,
 'cropping': None,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_ObsLearJan17\\ObsLear_Idavr95shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'date': None,
 'decay_steps': 30000,
 'default_augmenter': None,
 'default_net_type': None,
 'deterministic': False,
 'display_iters': 500,
 'dotsize': None,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\idavalik\\DeepLabCut\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'iteration': None,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_ObsLearJan17\\Documentation_data-ObsLear_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'move2corner': None,
 'multi_step': [[0.0001, 7500], [5e-05, 12000], [1e-05, 200000]],
 'multianimalproject': None,
 'net_type': 'resnet_50',
 'num_joints': 8,
 'num_limbs': 12,
 'numframes2pick': None,
 'optimizer': 'adam',
 'pafwidth': 20,
 'pairwise_huber_loss': False,
 'pairwise_loss_weight': 0.1,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[1, 2],
                             [0, 1],
                             [1, 3],
                             [4, 5],
                             [0, 2],
                             [1, 4],
                             [1, 5],
                             [2, 3],
                             [0, 4],
                             [2, 5],
                             [3, 4],
                             [2, 4]],
 'partaffinityfield_predict': True,
 'pcutoff': None,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\idavalik\\DLC\\ObsLear-Idavr-2021-01-17\\dlc-models\\iteration-0\\ObsLearJan17-trainset95shuffle1\\train',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 10000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'scorer': None,
 'shuffle': True,
 'skeleton': [],
 'skeleton_color': 'black',
 'snapshot_prefix': 'C:\\Users\\idavalik\\DLC\\ObsLear-Idavr-2021-01-17\\dlc-models\\iteration-0\\ObsLearJan17-trainset95shuffle1\\train\\snapshot',
 'snapshotindex': None,
 'start': None,
 'stop': None,
 'stride': 8.0,
 'video_sets': None,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001,
 'x1': None,
 'x2': None,
 'y1': None,
 'y2': None}
Activating limb prediction...
Starting with multi-animal imaug + adam pose-dataset loader.
Traceback (most recent call last):
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 193, in train_network
    raise e
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    allow_growth=allow_growth,
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 137, in train
    dataset = create_dataset(cfg)
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\dataset\factory.py", line 56, in create
    data = MAPoseDataset(cfg)
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\dataset\pose_multianimal_imgaug.py", line 34, in __init__
    self.data = self.load_dataset()
  File "C:\Users\idavalik\AppData\Local\Continuum\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\dataset\pose_multianimal_imgaug.py", line 42, in load_dataset
    with open(os.path.join(self.cfg.project_path, file_name), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\idavalik\\DLC\\ObsLear-Idavr-2021-01-17\\dlc-models\\iteration-0\\ObsLearJan17-trainset95shuffle1\\train\\training-datasets\\iteration-0\\UnaugmentedDataSet_ObsLearJan17\\ObsLear_Idavr95shuffle1.pickle'
```

**Comment by MMathisLab** [comment]
Hi @Idavr 2.2 does not exist yet. could you please run `deeplabcut.__version__ ` to give us a version #.

Also, this is a mash-up of two configs...  clearly something wrong here in your pose_cfg.yaml file.

**Comment by Idavr** [comment]
I am so sorry, I was certain I had added it but apparently not. Apologies, the original post has been updated accordingly with version 2.2b8.

I have not adjusted the pose_cfg.yaml file directly in any way so I am uncertain as to what has happened, but there seems to be missing information in certain areas as well. I am attaching it below:
```python
    Project definitions (do not edit)
Task:
scorer:
date:
multianimalproject:

    Project path (change when moving around)
project_path: C:\Users\idavalik\DLC\ObsLear-Idavr-2021-01-17\dlc-models\iteration-0\ObsLearJan17-trainset95shuffle1\train

    Annotation data set configuration (and individual video cropping parameters)
video_sets:
bodyparts:
start:
stop:
numframes2pick:

    Plotting configuration
skeleton: []
skeleton_color: black
pcutoff:
dotsize:
alphavalue:
colormap:

    Training,Evaluation and Analysis configuration
TrainingFraction:
iteration:
default_net_type:
default_augmenter:
snapshotindex:
batch_size: 8

    Cropping Parameters (for analysis and outlier frame detection)
cropping:
croppedtraining:
   if cropping is true for analysis, then set the values here:
x1:
x2:
y1:
y2:

    Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
move2corner:
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
all_joints_names:
- nose
- leftear
- rightear
- neck
- back
- tailbase
- LED1
- LED2
alpha_r: 0.02
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_ObsLearJan17\ObsLear_Idavr95shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
global_scale: 0.8
init_weights: C:\Users\idavalik\DeepLabCut\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_ObsLearJan17\Documentation_data-ObsLear_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_joints: 8
num_limbs: 12
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 1
  - 2
- - 0
  - 1
- - 1
  - 3
- - 4
  - 5
- - 0
  - 2
- - 1
  - 4
- - 1
  - 5
- - 2
  - 3
- - 0
  - 4
- - 2
  - 5
- - 3
  - 4
- - 2
  - 4
partaffinityfield_predict: true
pos_dist_thresh: 17
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false
```

**Comment by MMathisLab** [comment]
can you delete this:

```python
    Project definitions (do not edit)
Task:
scorer:
date:
multianimalproject:

    Project path (change when moving around)
project_path: C:\Users\idavalik\DLC\ObsLear-Idavr-2021-01-17\dlc-models\iteration-0\ObsLearJan17-trainset95shuffle1\train

    Annotation data set configuration (and individual video cropping parameters)
video_sets:
bodyparts:
start:
stop:
numframes2pick:

    Plotting configuration
skeleton: []
skeleton_color: black
pcutoff:
dotsize:
alphavalue:
colormap:

    Training,Evaluation and Analysis configuration
TrainingFraction:
iteration:
default_net_type:
default_augmenter:
snapshotindex:
batch_size: 8

    Cropping Parameters (for analysis and outlier frame detection)
cropping:
croppedtraining:
   if cropping is true for analysis, then set the values here:
x1:
x2:
y1:
y2:

    Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
move2corner:
```

that should not be there! 

*also you might want to wait 24 hours; 2.2rc1 is nearly released / much better.

**Comment by Idavr** [comment]
Thanks for the input and swift response! Will wait until 2.2rc1 is released and then try again with these adjustments in mind and get back to you :)

**Comment by AlexEMG** [comment]
In any case, your `pose_cfg.yaml` file looks off (it is a merge of a `config.yaml` and `pose_cfg.yaml`) and indeed the `project_path` is wrong... 
`
project_path: C:\Users\idavalik\DLC\ObsLear-Idavr-2021-01-17\dlc-models\iteration-0\ObsLearJan17-trainset95shuffle1\train`
Then in order to find the training data this piece is appended: 
`dataset: training-datasets\iteration-0\UnaugmentedDataSet_ObsLearJan17\ObsLear_Idavr95shuffle1.pickle`

and thus your machine complains:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\idavalik\\DLC\\ObsLear-Idavr-2021-01-17\\dlc-models\\iteration-0\\ObsLearJan17-trainset95shuffle1\\train\\training-datasets\\iteration-0\\UnaugmentedDataSet_ObsLearJan17\\ObsLear_Idavr95shuffle1.pickle'`

That's expected ... training-datasets will be directly under the project folder (not in `/dlc-models/..`). I.e. here:

`C:\\Users\\idavalik\\DLC\\ObsLear-Idavr-2021-01-17\\training-datasets\\iteration-0\\UnaugmentedDataSet_ObsLearJan17\\ObsLear_Idavr95shuffle1.pickle'`

So just change the project path to:
`project_path: C:\Users\idavalik\DLC\ObsLear-Idavr-2021-01-17`
and you should be good!
