### ISSUE TITLE
issue during training maDLC (training stopped way too early)

### ISSUE THREAD

**Issue by rosalba3574** [DeepLabCut/DeepLabCut#1214]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

GPU Geforce 3070 RTX
Cuda v.11.2
cuDNN v.8
python 3.8.5
tensorflow-gpu 1.14
deeplabcut 2.1.10.4
Windows 10 Pro with anaconda env DLC-GPU

Hello, thank you so much for developing deeplabcut :)
I am new to programming so I hope I gave you all the important information. I used deeplabcut without problems for single animal tracking and now I am trying to use it for a multi-animal tracking project, and I tried to run my data but it didn´t work so I tried with your example but I found some errors between the network training and its evaluation. I can open the GUI and import projects, extract frames, label the frames, check them and create a training dataset without problems. I also left all your pre-settings, but when I run the train network it gives some error message but at the end, it says that it was able to train the network. The real errors appear with the evaluate network it reaches a point and then it blocks there, I´ll report the entire code here, I hope you can help me, Thank you so much in advance.
Rosalba

Please place code inside this:

<details><summary>Code output</summary><p>

[In [3]: import deeplabcut

In [4]: deeplabcut.launch_dlc()
more networks are available soon for maDLC, but currenlty this uses DLC-ResNet50 only
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 77.67  seconds.
Extracting and downsampling... 2330  frames from the video.
2330it [00:04, 517.30it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted, for the videos of interest.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
Found new frames..
You can now check the labels, using 'check_labels' before proceeding. Then,  you can use the function 'create_training_dataset' to create the training dataset.
Creating images with labels by dlc_team.
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\labeled-data\m3v1mp4_cropped_labeled  already exists!
100%|███████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 30.12it/s]
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\labeled-data\m3v1mp4_cropped  already exists!
100%|███████████████████████████████████████████████████████████████████████████████| 10/10 [00:20<00:00,  2.00s/it]
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\training-datasets\iteration-0\UnaugmentedDataSet_multi_mouseMay3  already exists!
Utilizing the following graph: [[0, 1], [1, 2], [0, 2]]
Creating training data for  1 0.8
This can take some time...
100%|█████████████████████████████████████████████████████████████████████████████| 120/120 [00:01<00:00, 97.97it/s]
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\dlc-models\iteration-0\multi_mouseMay3-trainset80shuffle1  already exists!
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\dlc-models\iteration-0\multi_mouseMay3-trainset80shuffle1\train  already exists!
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\dlc-models\iteration-0\multi_mouseMay3-trainset80shuffle1\test  already exists!
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
Selecting multi-animal trainer
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3'],
 'alpha_r': 0.02,
 'batch_size': 8,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_multi_mouseMay3\\multi_mouse_dlc_team80shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 500,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\Users\\rproce\\AppData\\Roaming\\Python\\Python37\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_multi_mouseMay3\\Documentation_data-multi_mouse_80shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_step': [[0.0001, 7500], [5e-05, 12000], [1e-05, 200000]],
 'net_type': 'resnet_50',
 'num_joints': 3,
 'num_limbs': 3,
 'optimizer': 'adam',
 'pafwidth': 20,
 'pairwise_huber_loss': False,
 'pairwise_loss_weight': 0.1,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1], [1, 2], [0, 2]],
 'partaffinityfield_predict': True,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\rproce\\DeepLabCut\\examples\\multi_mouse-dlc_team-2021-05-03',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 10000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\rproce\\DeepLabCut\\examples\\multi_mouse-dlc_team-2021-05-03\\dlc-models\\iteration-0\\multi_mouseMay3-trainset80shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Activating limb prediction...
Starting with multi-animal imaug + adam pose-dataset loader.
Batch Size is 8
Getting specs multi-animal-imgaug 3 3
Initializing ResNet
Loading ImageNet-pretrained resnet_50
2021-05-03 11:00:35.253805: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2021-05-03 11:00:35.286404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 3070 major: 8 minor: 6 memoryClockRate(GHz): 1.755
pciBusID: 0000:01:00.0
2021-05-03 11:00:35.290309: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2021-05-03 11:00:35.293188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2021-05-03 11:00:35.295912: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-05-03 11:00:35.302900: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 3070 major: 8 minor: 6 memoryClockRate(GHz): 1.755
pciBusID: 0000:01:00.0
2021-05-03 11:00:35.307743: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2021-05-03 11:00:35.310323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2021-05-03 11:03:45.052211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-03 11:03:45.054622: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2021-05-03 11:03:45.056097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2021-05-03 11:03:45.057861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6268 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6)
Max_iters overwritten as 50
Display_iters overwritten as 10
Save_iters overwritten as 5
Training parameters:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\rproce\\DeepLabCut\\examples\\multi_mouse-dlc_team-2021-05-03\\dlc-models\\iteration-0\\multi_mouseMay3-trainset80shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 8, 'dataset_type': 'multi-animal-imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': True, 'pairwise_predict': True, 'all_joints': [[0], [1], [2]], 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3'], 'alpha_r': 0.02, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_multi_mouseMay3\\multi_mouse_dlc_team80shuffle1.pickle', 'decay_steps': 30000, 'display_iters': 500, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\Users\\rproce\\AppData\\Roaming\\Python\\Python37\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_multi_mouseMay3\\Documentation_data-multi_mouse_80shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.0001, 7500], [5e-05, 12000], [1e-05, 200000]], 'net_type': 'resnet_50', 'num_joints': 3, 'num_limbs': 3, 'pafwidth': 20, 'pairwise_loss_weight': 0.1, 'partaffinityfield_graph': [[0, 1], [1, 2], [0, 2]], 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\rproce\\DeepLabCut\\examples\\multi_mouse-dlc_team-2021-05-03', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 10000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3}
Starting multi-animal training....
iteration: 10 loss: 0.6911 scmap loss: 0.6841 locref loss: 0.0016 limb loss: 0.0054 lr: 0.0001
iteration: 20 loss: 0.4658 scmap loss: 0.4617 locref loss: 0.0008 limb loss: 0.0032 lr: 0.0001
iteration: 30 loss: 0.3654 scmap loss: 0.3622 locref loss: 0.0007 limb loss: 0.0026 lr: 0.0001
iteration: 40 loss: 0.2971 scmap loss: 0.2943 locref loss: 0.0006 limb loss: 0.0022 lr: 0.0001
iteration: 50 loss: 0.2476 scmap loss: 0.2440 locref loss: 0.0007 limb loss: 0.0029 lr: 0.0001
2021-05-03 11:16:40.779018: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-64:
Traceback (most recent call last):
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 78, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py:64) ]]

Errors may have originated from an input operation.
Input Source operations connected to node fifo_queue_enqueue:
 Placeholder (defined at C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py:53)
 fifo_queue (defined at C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py:61)

Original stack trace for 'fifo_queue_enqueue':
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 564, in mainloop
    self.interact()
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 555, in interact
    self.run_cell(code, store_history=True)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2895, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in _run_cell
    return runner(coro)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3166, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3357, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-1ced4355ffc5>", line 1, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\launch_script.py", line 46, in launch_dlc
    app.MainLoop()
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\label_frames.py", line 211, in label_frames
    label_frames(self.config)
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\label_frames.py", line 76, in label_frames
    multiple_individuals_labeling_toolbox.show(config, config3d, sourceCam)
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\multiple_individuals_labeling_toolbox.py", line 1312, in show
    app.MainLoop()
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\train_network.py", line 328, in train_network
    maxiters=maxiters,
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    allow_growth=allow_growth,
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 147, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "C:\Users\rproce\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 64, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 345, in enqueue
    self._queue_ref, vals, name=scope)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4807, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03/evaluation-results/  already exists!
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_multi_mouseMay3\\multi_mouse_dlc_team80shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\rproce\\AppData\\Roaming\\Python\\Python37\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'minconfidence': 0.01,
 'mirror': False,
 'net_type': 'resnet_50',
 'nmsradius': 5.0,
 'num_joints': 3,
 'num_limbs': 3,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1], [1, 2], [0, 2]],
 'partaffinityfield_predict': True,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\rproce\\DeepLabCut\\examples\\multi_mouse-dlc_team-2021-05-03\\dlc-models\\iteration-0\\multi_mouseMay3-trainset80shuffle1\\test\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\evaluation-results\iteration-0\multi_mouseMay3-trainset80shuffle1  already exists!
Running  DLC_resnet50_multi_mouseMay3shuffle1_50  with # of trainingiterations: 50
C:\Users\rproce\DeepLabCut\examples\multi_mouse-dlc_team-2021-05-03\evaluation-results\iteration-0\multi_mouseMay3-trainset80shuffle1\LabeledImages_DLC_resnet50_multi_mouseMay3shuffle1_50_snapshot-50  already exists!
Initializing ResNet
Activating extracting of PAFs
2021-05-03 11:16:50.318485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 3070 major: 8 minor: 6 memoryClockRate(GHz): 1.755
pciBusID: 0000:01:00.0
2021-05-03 11:16:50.323240: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2021-05-03 11:16:50.325407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2021-05-03 11:16:50.327394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-03 11:16:50.329593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2021-05-03 11:16:50.330825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2021-05-03 11:16:50.332167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6268 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6)
Analyzing data...
12it [10:57, 70.74s/it]C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\numpy\lib\function_base.py:4069: RuntimeWarning: invalid value encountered in add
  ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
13it [12:13, 72.13s/it]C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\numpy\lib\function_base.py:4069: RuntimeWarning: invalid value encountered in add
  ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
14it [13:29, 73.46s/it]C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\numpy\lib\function_base.py:4069: RuntimeWarning: invalid value encountered in add
  ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
C:\Users\rproce\Anaconda3\envs\DLC-GPU\lib\site-packages\numpy\core\_methods.py:38: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
14it [14:18, 61.33s/it]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\evaluate_network.py in evaluate_network(self, event)
    335             plotting=plotting,
    336             show_errors=True,
--> 337             comparisonbodyparts=self.bodyparts,
    338         )
    339

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix, c_engine)
    568             gputouse=gputouse,
    569             modelprefix=modelprefix,
--> 570             c_engine=c_engine,
    571         )
    572     else:

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix, c_engine)
    378                                     # rather than the ones the model has most confident in
    379                                     d = cdist(xy_gt.iloc[inds_gt], xy)
--> 380                                     rows, cols = linear_sum_assignment(d)
    381                                     min_dists = d[rows, cols]
    382                                     inds = np.flatnonzero(all_bpts == bpt)

~\Anaconda3\envs\DLC-GPU\lib\site-packages\scipy\optimize\_lsap.py in linear_sum_assignment(cost_matrix, maximize)
     91
     92     if np.any(np.isneginf(cost_matrix) | np.isnan(cost_matrix)):
---> 93         raise ValueError("matrix contains invalid numeric entries")
     94
     95     cost_matrix = cost_matrix.astype(np.double)

ValueError: matrix contains invalid numeric entries]

**Comment by AlexEMG** [comment]
Ok -- you trained your network only for 50 iterations (then it stopped). That is not enough for reasonable convergence. Due to  suboptimal predictions it then fails during evaluation. Please check out the new preprint for more details on maDLC:
https://www.biorxiv.org/content/10.1101/2021.04.30.442096v1 (fresh on biorxiv)

**Comment by rosalba3574** [comment]
![image](https://user-images.githubusercontent.com/83355542/116889639-16be2d00-ac2d-11eb-9c93-9b99f8fb72ba.png)

Thank you so much for your answer, as you suggest I trained more, for 50´000 iterations but it says that there are some problems in the training, do you know what this could be?

**Comment by rosalba3574** [comment]
Hello, sorry to keep posting but I updated deeplabcut to the new 2.2rc1 and create a new project now when I try to evaluate the network after 50000 iterations for the training it just says analyzing data but not working.. Can you please help me understand how to solve this?
![image](https://user-images.githubusercontent.com/83355542/117032086-7f76d980-ad01-11eb-9c07-cb2c0aa9e624.png)
