### ISSUE TITLE
Install wxPython on Ubuntu 20.04

### ISSUE THREAD

**Issue by m-beau** [DeepLabCut/DeepLabCut#1233]
**Describe the bug**

Impossible to build wxpython from pip, as the default deeplabcut environment install does under the hood.

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 20.04
 - DeepLabCut Version 2.1.10.4
 - DeepLabCut mode does not matter

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. try to install deeplabcut using DLC_CPU.yml
2. Observe that it fails

I found a solution to the problem: using the [conda channel](https://anaconda.org/anaconda/wxpython) of wxpython phoenix instead of pip: `conda install -c anaconda wxpython`.

To ensure that it works in the future: change the DLC-CPU.yml file so that conda is used to install wxpython instead of pip, if the OS is ubuntu (prob linux overall).

**Comment by m-beau** [comment]
To help find this issue if people encounter this bug, here is the full log:

```Finished command: build_wx (2m58.144s)
  Running command: build_py
  Checking for /tmp/pip-req-build-a65r_qz9/bin/waf-2.0.19...
  "/home/maxime/anaconda3/envs/dlc/bin/python3.7" /tmp/pip-req-build-a65r_qz9/bin/waf-2.0.19 --wx_config=/tmp/pip-req-build-a65r_qz9/build/wxbld/gtk3/wx-config --gtk3 --python="/home/maxime/anaconda3/envs/dlc/bin/python3.7" --out=build/waf/3.7/gtk3 configure build
  Setting top to                           : /tmp/pip-req-build-a65r_qz9
  Setting out to                           : /tmp/pip-req-build-a65r_qz9/build/waf/3.7/gtk3
  Checking for 'gcc' (C compiler)          : /usr/bin/gcc
  Checking for 'g++' (C++ compiler)        : /usr/bin/g++
  Checking for program 'python'            : /home/maxime/anaconda3/envs/dlc/bin/python3.7
  Checking for python version >= 2.7.0     : 3.7.10
  python-config                            : /home/maxime/anaconda3/envs/dlc/bin/python3.7-config
  Asking python-config for pyext '--cflags --libs --ldflags' flags : yes
  Testing pyext configuration                                      : Could not build python extensions
  The configuration failed
  (complete log in /tmp/pip-req-build-a65r_qz9/build/waf/3.7/gtk3/config.log)
  Command '"/home/maxime/anaconda3/envs/dlc/bin/python3.7" /tmp/pip-req-build-a65r_qz9/bin/waf-2.0.19 --wx_config=/tmp/pip-req-build-a65r_qz9/build/wxbld/gtk3/wx-config --gtk3 --python="/home/maxime/anaconda3/envs/dlc/bin/python3.7" --out=build/waf/3.7/gtk3 configure build ' failed with exit code 1.
  Finished command: build_py (0.851s)
  Finished command: build (2m58.995s)
  Command '"/home/maxime/anaconda3/envs/dlc/bin/python3.7" -u build.py build' failed with exit code 1.
  Building wheel for wxPython (setup.py): finished with status 'error'
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
  Running command /home/maxime/anaconda3/envs/dlc/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-a65r_qz9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-a65r_qz9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  'build/lib.linux-x86_64-3.7' does not exist -- can't clean it
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
Failed to build wxPython
ERROR: Failed to build one or more wheels
Exception information:
Traceback (most recent call last):
  File "/home/maxime/anaconda3/envs/dlc/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/maxime/anaconda3/envs/dlc/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/maxime/anaconda3/envs/dlc/lib/python3.7/site-packages/pip/_internal/commands/wheel.py", line 175, in run
    "Failed to build one or more wheels"
pip._internal.exceptions.CommandError: Failed to build one or more wheels```

**Comment by MMathisLab** [comment]
Thanks! Note, this is why for ubuntu, etc we recommend making your own env: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md#creating-your-own-customized-conda-env-recommended-route-for-linux-ubuntu-centos-mint-etc 

note that wxPython we will soon be dropping due to this limitation in general with this package.

**Comment by turin331** [comment]
> I found a solution to the problem: using the [conda channel](https://anaconda.org/anaconda/wxpython) of wxpython phoenix instead of pip: `conda install -c anaconda wxpython`.
> 

This solution did not work for me. The command is looking at the system version of python that is 3,8 and the install fails. Any suggestions about this? 

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - wxpython -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

```
