### ISSUE TITLE
Issue during Create Labeled Videos - Key error for Individual 1

### ISSUE THREAD

**Issue by writerjbmarks** [DeepLabCut/DeepLabCut#1241]
**Windows 10, DeepLabCut Version 2.2rc1, with an Anaconda Environment**

**Describe the problem**

Hello! I'm attempting to create a video after refining tracklets and following the steps so far, but i'm running into a key error when i'm attempting to render a video. 

In the input, i used the same config.yaml file, and my input is in the video folder - not my pickle file or any of the labeled videos, as those couldn't be read through the GUI. The specified tracker method is ellipses, and i didn't get this error when creating the labels, training the dataset, or refining the tracklets. 

Please place code inside this:

<details><summary>Code output</summary><p>

Creating a video with the ellipse tracker method!
2021-05-13 12:04:29.470564: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
C:\Users\write\Documents\Grad School\RVT\Rat Projects\Rat Videos\Rat_Videos\models\DLC Downscaled  already exists!
Starting to process video: C:\Users\write\Documents\Grad School\RVT\Rat Projects\Rat Videos\Rat_Videos\models\DLC Downscaled\E1E6_320.mp4
Loading C:\Users\write\Documents\Grad School\RVT\Rat Projects\Rat Videos\Rat_Videos\models\DLC Downscaled\E1E6_320.mp4 and data.
Labeled video already created. Skipping...
Loading  C:\Users\write\Documents\Grad School\RVT\Rat Projects\Rat Videos\Rat_Videos\models\DLC Downscaled\E1E6_320.mp4 and data.
C:\Users\write\Documents\Grad School\RVT\Rat Projects\Rat Videos\Rat_Videos\models\DLC Downscaled\plot-poses\E1E6_320  already exists!
Traceback (most recent call last):
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'individual1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\deeplabcut\gui\create_videos.py", line 363, in create_videos
    track_method=self.trackertypes.GetValue(),
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\deeplabcut\utils\plotting.py", line 279, in plot_trajectories
    linewidth=linewidth,
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\deeplabcut\utils\plotting.py", line 51, in PlottingResults
    Dataframe = Dataframe.loc(axis=1)[:, individuals2plot]
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexing.py", line 889, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexing.py", line 1060, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexing.py", line 787, in _getitem_lowerdim
    return self._getitem_axis(tup, axis=axis)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexing.py", line 1117, in _getitem_axis
    locs = labels.get_locs(key)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexes\multi.py", line 3305, in get_locs
    self.get_loc_level(k, level=i, drop_level=False)[0]
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexes\multi.py", line 2965, in get_loc_level
    return self._get_loc_level(key, level=level, drop_level=drop_level)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexes\multi.py", line 3068, in _get_loc_level
    indexer = self._get_level_indexer(key, level=level)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexes\multi.py", line 3158, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexes\multi.py", line 2809, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "C:\Users\write\anaconda3\envs\tf\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'individual1'

</p></details>

**How to Reproduce the problem**

**Screenshots**
![image](https://user-images.githubusercontent.com/74156405/118174337-89749880-b3e3-11eb-8bf5-04b5d51a81f0.png)
![image](https://user-images.githubusercontent.com/74156405/118174394-98f3e180-b3e3-11eb-9f44-dcd779c8835b.png)
![image](https://user-images.githubusercontent.com/74156405/118174421-a0b38600-b3e3-11eb-8a6f-1bf62318f258.png)

**Additional context**
I've included screenshots of my config file in Atom in case there is an issue with the skeleton. Since the error is for individual 1, i assumed there was something wrong with the formatting there, but i can't find anything.

Thanks for all of this incredible stuff, Mathis team!

**Comment by jeylau** [comment]
Hey! How many tracks did you try to reconstruct when stitching the tracklets? 2?

**Comment by writerjbmarks** [comment]
Wouldn't you know it - as soon as you said that, I went and double-checked that the tracklets were merged, and though I'd only created one set - it worked! I'm so glad!

**Comment by writerjbmarks** [comment]
As a side note - it didn't impact the workflow but before i close the issue i thought i would check something i had posted under the gitter page - the only step i'm having trouble with is the analysis for the video - it reads as an error in my shape formatting, as my shape is [1, 256, 256, 4] when it needs to be [1, ?, ?, 3] - I found out from a search that this is because the shape is restricted to RGB, but i'm not sure how to edit to change that in the config.yaml file - the colormap didn't work. Anyone have a quick fix for this?

**Comment by AlexEMG** [comment]
Related to #1236

**Comment by AlexEMG** [comment]
The second issue is different, can you please give more context on that one (I'lll close this issue for now).

**Comment by AlexEMG** [comment]
Will be addressed in #1239
