### ISSUE TITLE
Problem when trying to analyze video after I re-trained the network

### ISSUE THREAD

**Issue by pamelaosuna** [DeepLabCut/DeepLabCut#1244]
Operating System: Windows10
Anconda environment:  DLC-GPU
DLC version: 2.2rc1
DLC project type: multi-animal

I am trying to analyze a video with a network that I have just finished training. The initial weights that I set for the training (iteration-1) belong to a previous training (iteration-0). The first training was done for 200 000 its and the second for 300 000. I did this after adding new videos and extracting outlier frames, so I could improve the training dataset. The body parts and skeleton I used are the same that for the previous training. However, I get the following error:

<details><summary>Code output</summary><p>

Traceback (most recent call last):
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,90,2048] rhs shape= [3,3,52,2048]
         [[{{node save/Assign_3}}]]
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,90,2048] rhs shape= [3,3,52,2048]
         [[node save/Assign_3 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]
         [[node save/RestoreV2 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]

Caused by op 'save/Assign_3', defined at:
  File "run_video_analysis.py", line 38, in <module>
    scorername = dlc.analyze_videos(config_path, [video_path], save_as_csv=True, gputouse=gputouse)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 273, in analyze_videos
    sess, inputs, outputs = predict.setup_pose_prediction(dlc_cfg)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py", line 48, in setup_pose_prediction
    restorer = TF.train.Saver()
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 832, in __init__
    self.build()
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,90,2048] rhs shape= [3,3,52,2048]
         [[node save/Assign_3 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]
         [[node save/RestoreV2 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_video_analysis.py", line 38, in <module>
    scorername = dlc.analyze_videos(config_path, [video_path], save_as_csv=True, gputouse=gputouse)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 273, in analyze_videos
    sess, inputs, outputs = predict.setup_pose_prediction(dlc_cfg)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py", line 54, in setup_pose_prediction
    restorer.restore(sess, cfg["init_weights"])
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 1312, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,90,2048] rhs shape= [3,3,52,2048]
         [[node save/Assign_3 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]
         [[node save/RestoreV2 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]

Caused by op 'save/Assign_3', defined at:
  File "run_video_analysis.py", line 38, in <module>
    scorername = dlc.analyze_videos(config_path, [video_path], save_as_csv=True, gputouse=gputouse)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 273, in analyze_videos
    sess, inputs, outputs = predict.setup_pose_prediction(dlc_cfg)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py", line 48, in setup_pose_prediction
    restorer = TF.train.Saver()
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 832, in __init__
    self.build()
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,90,2048] rhs shape= [3,3,52,2048]
         [[node save/Assign_3 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]
         [[node save/RestoreV2 (defined at C:\Users\ana.osuna\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py:48) ]]

</p></details>

deeplabcut.analyze_videos(config_path, [video_path], gputouse=gpu_num)

I remember having a similar message before successfully started the second training. I thought that this was related to the parameter *partaffinityfield_graph* inside the pose_cfg.yaml file (from iteration-1), so what I did was a copy-paste only of this parameter from the pose_cfg.yaml old file (from iteration-0). Also, I changed the *num_libs* parameter as set for the older file. After that, I retried to do the training and it was done without a problem.

What would you recommend?

Thank you in advance!

**Comment by pamelaosuna** [comment]
Actually, when looking at the log file of the training (iteration-1), I see that I have two different config parameters printed, and I am not sure why. Please find the log file here attached:
[log.txt](https://github.com/DeepLabCut/DeepLabCut/files/6478809/log.txt)

**Comment by jeylau** [comment]
You're right, the difference is in the definition of the part affinity graph. Prior to 2.2rc1, graphs (i.e., skeletons) were user-defined, whereas the model is now trained on the complete graph. Changing it manually has no effect though, as its definition is overwritten anyway  (as you can see in the log.txt, all graph connections are being evaluated). Reverting 'num_limbs' and 'partaffinityfield_graph' should fix the mismatch between the model and the corresponding config :)

**Comment by AlexEMG** [comment]
Exactly, when you create a trainingset with DLC2.2rc1 it does so for the complete graph and also trains for this (compare: `https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py#L115` Thus, there is a mismatch in comparison to your prior model. For now you can overwrite it before training (in `pose_cfg.yaml`) and you are fine. 

Anyway, I think we should also allow a user to pass a `partaffinityfield_graph` (e.g. the one from the config file) to allow more flexibility (if somebody already knows a good graph, or wants to use a specific one).

**Comment by pamelaosuna** [comment]
Thank you very much for your response! 
I've just tried reversing the parameters `partaffinityfield_graph` and `num_limbs` from the `pose_cfg.yaml` file in `iteration-1/train`, then tried to analyze a video, but got the same error. Indeed, when I trained the model on iteration-1, I overwrote the graph as the one in iteration-1, because an error was thrown and the training would not start otherwise. So, should I train the model from zero (using the up-to-date training set), for now? Or maybe I misunderstood something and there is a way to make it work from its current state?

**Comment by jeylau** [comment]
Hi @pamelaosuna, I've just tested your use case. As long as you also update the `pose_cfg.yaml` in the iteration-1/test directory; this is the one that matters for inference. Update  `partaffinityfield_graph` and `num_limbs` with your 26-edge graph as you had done prior to training, and you should be fine. 😊

**Comment by pamelaosuna** [comment]
Thank you very much, @jeylau! :) That worked for me.
