### ISSUE TITLE
Unable to reconstruct tracks from tracklets given. 

### ISSUE THREAD

**Issue by BKTidswell** [DeepLabCut/DeepLabCut#1260]
OS: MacOS Big Sur 11.3.1
DeepLabCut Version: 2.2rc1
Anaconda env used: Yes, DLC-CPU

When I try to refine some of my tracklets I am unable to create the tracks in the first place. When I load in the `_el.pickle` in the GUI and press "Step1: Create Tracks" on the "Refine tracklets" tab I get an error. Most of the tracklets work, but I get this error with about a dozen of them. And the detections video for each of them seems to show enough points for all 8 of the fish. 

<details><summary>Code output</summary><p>
/Users/Ben/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py:634: UserWarning: No optimal solution found. Employing black magic...
  warnings.warn("No optimal solution found. Employing black magic...")
Traceback (most recent call last):
  File "/Users/Ben/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 631, in stitch
    _, self.flow = nx.capacity_scaling(self.G)
  File "/Users/Ben/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/networkx/algorithms/flow/capacityscaling.py", line 373, in capacity_scaling
    raise nx.NetworkXUnfeasible('No flow satisfying all demands.')
networkx.exception.NetworkXUnfeasible: No flow satisfying all demands.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Ben/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 697, in stitch
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Ben/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/gui/refine_tracklets.py", line 318, in create_tracks
    animal_names=self.cfg["individuals"],
  File "/Users/Ben/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 1007, in stitch_tracklets
    stitcher.stitch()
  File "/Users/Ben/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 702, in stitch
    f"Could not reconstruct {self.n_tracks} tracks from the tracklets given."
ValueError: Could not reconstruct 8 tracks from the tracklets given.
</p></details>

I have attached here one of the pickle files that I am unable to create tracks from as a zip file, since github does not seem to like .pickle files. I also have the video with points at the Tufts Box link. 

[2020_7_28_27_TN_DN_F0_V1DLC_resnet50_DLC_2-2_4P_8F_Light_VentralMay10shuffle1_100000_el.pickle.zip](https://github.com/DeepLabCut/DeepLabCut/files/6517291/2020_7_28_27_TN_DN_F0_V1DLC_resnet50_DLC_2-2_4P_8F_Light_VentralMay10shuffle1_100000_el.pickle.zip)

https://tufts.box.com/s/kb4sgkcyyjcr9atn0hr0levwp4yg5gyk

**Comment by jeylau** [comment]
Hello @BKTidswell, I'll take a look at it. Is this the video with the detections corresponding to the pickle you uploaded? Out of curiosity, do you face the same error with the box tracker?

**Comment by BKTidswell** [comment]
Hello @jeylau The video does correspond to the pickle I uploaded. I just tried it and I do run into the same error with the box tracker, though I did not in version 2.2b8. This zip file is from the results of the box tracker.

[2020_7_28_27_TN_DN_F0_V1DLC_resnet50_DLC_2-2_4P_8F_Light_VentralMay10shuffle1_100000_bx.pickle.zip](https://github.com/DeepLabCut/DeepLabCut/files/6524787/2020_7_28_27_TN_DN_F0_V1DLC_resnet50_DLC_2-2_4P_8F_Light_VentralMay10shuffle1_100000_bx.pickle.zip)

**Comment by jeylau** [comment]
Hey @BKTidswell, I figured what went on. When building the graph, we automatically calculate what the minimal gap size between pairs of tracklets is to ensure any pair can be stitched together. In your case, the value is not conservative enough and causes stitching to fail. While I work on a fix, you could programmatically stitch your tracklets as follows:
```
from deeplabcut.refine_training_dataset.stitch import TrackletStitcher

cfg = read_config(config_path)
stitcher = TrackletStitcher.from_pickle('your_pickle_file', n_tracks=8)
stitcher.build_graph(max_gap=50)
stitcher.stitch()
stitcher.write_tracks(output_name, cfg["individuals"])
```

**Comment by backyardbiomech** [comment]
I just now  pulled and installed #1270 [latest commit](https://github.com/DeepLabCut/DeepLabCut/pull/1270/commits/67d1f3e9375d80008daa1fd233b0b6becbdc01d5) after running into a similar problem.  

In one set of videos (3 cameras of the same behavior for 3D), I have three birds. Based on the output of `create_video_with_all_detections`, one bird is well detected, one is mostly obscured (just 2 of 7 points visible), and one is visible but not well detected at all, so I wanted to extract outliers. The current model is working well for tracking most videos, so there is something about this particular video that is throwing it off.

The one bird is so poorly tracked that I know I really just need to extract frames and label. I'm thinking that simply a clearer error statement may be helpful for some users for when tracking is so poor that tracklets can't be stitched even with the fixes in this commit - and possibly an addition to the docs.

When I run `dlc.stitch_tracklets(config, pickle, n_tracks=3)` I get the following traceback:
<details>
<summary> n_tracks=3 Traceback</summary>

```python

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1675                     make_block(
-> 1676                         values=blocks[0], placement=slice(0, len(axes[0])), ndim=2
   1677                     )

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\blocks.py in make_block(values, placement, klass, ndim, dtype)
   2741 
-> 2742     return klass(values, ndim=ndim, placement=placement)
   2743 

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\blocks.py in __init__(self, values, placement, ndim)
    142             raise ValueError(
--> 143                 f"Wrong number of items passed {len(self.values)}, "
    144                 f"placement implies {len(self.mgr_locs)}"

ValueError: Wrong number of items passed 42, placement implies 36

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-8-c1ec2e01a9bf> in <module>
      5 for pick in pickles:
      6     print(pick)
----> 7     dlc.stitch_tracklets(config, pick, n_tracks=3)
      8 
      9 #    "C:\Users\jacksonbe3\Box\research\studentProjects\birdTails\catherineSwinsky\data\20190603\wand02\trial19\cam1_03-Jun-19_16-07-34DLC_dlcrnetms5_cleantailsNov23shuffle1_200000_el.pickle"

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in stitch_tracklets(config_path, pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals, max_gap, weight_func, output_name)
   1050     stitcher.build_graph(max_gap=max_gap, weight_func=weight_func)
   1051     stitcher.stitch()
-> 1052     stitcher.write_tracks(output_name, animal_names)
   1053     return stitcher

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in write_tracks(self, output_name, animal_names)
    864 
    865     def write_tracks(self, output_name="", animal_names=None):
--> 866         df = self.format_df(animal_names)
    867         if not output_name:
    868             output_name = self.filename.replace("pickle", "h5")

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in format_df(self, animal_names)
    850         )
    851         inds = range(self._first_frame, self._last_frame + 1)
--> 852         df = pd.DataFrame(data, columns=columns, index=inds)
    853         df = df.reindex(range(self._last_frame + 1))
    854         if self.single is not None:

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    556                 mgr = init_dict({data.name: data}, index, columns, dtype=dtype)
    557             else:
--> 558                 mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
    559 
    560         # For data is list-like, or Iterable (will consume into list)

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\construction.py in init_ndarray(values, index, columns, dtype, copy)
    236         block_values = [values]
    237 
--> 238     return create_block_manager_from_blocks(block_values, [columns, index])
    239 
    240 

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1685         blocks = [getattr(b, "values", b) for b in blocks]
   1686         tot_items = sum(b.shape[0] for b in blocks)
-> 1687         raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
   1688 
   1689 

ValueError: Shape of passed values is (111, 42), indices imply (111, 36)
```

</details>

Just for fun, I tried `n_tracks=2` and got a similar, but proportionally scaled down error:
<details>
<summary> n_tracks=2 Traceback </summary>

```python

ValueError                                Traceback (most recent call last)
~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1675                     make_block(
-> 1676                         values=blocks[0], placement=slice(0, len(axes[0])), ndim=2
   1677                     )

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\blocks.py in make_block(values, placement, klass, ndim, dtype)
   2741 
-> 2742     return klass(values, ndim=ndim, placement=placement)
   2743 

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\blocks.py in __init__(self, values, placement, ndim)
    142             raise ValueError(
--> 143                 f"Wrong number of items passed {len(self.values)}, "
    144                 f"placement implies {len(self.mgr_locs)}"

ValueError: Wrong number of items passed 21, placement implies 18

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-e5adda754292> in <module>
      5 for pick in pickles:
      6     print(pick)
----> 7     dlc.stitch_tracklets(config, pick, n_tracks=2)
      8 
      9 #    "C:\Users\jacksonbe3\Box\research\studentProjects\birdTails\catherineSwinsky\data\20190603\wand02\trial19\cam1_03-Jun-19_16-07-34DLC_dlcrnetms5_cleantailsNov23shuffle1_200000_el.pickle"

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in stitch_tracklets(config_path, pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals, max_gap, weight_func, output_name)
   1050     stitcher.build_graph(max_gap=max_gap, weight_func=weight_func)
   1051     stitcher.stitch()
-> 1052     stitcher.write_tracks(output_name, animal_names)
   1053     return stitcher

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in write_tracks(self, output_name, animal_names)
    864 
    865     def write_tracks(self, output_name="", animal_names=None):
--> 866         df = self.format_df(animal_names)
    867         if not output_name:
    868             output_name = self.filename.replace("pickle", "h5")

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in format_df(self, animal_names)
    850         )
    851         inds = range(self._first_frame, self._last_frame + 1)
--> 852         df = pd.DataFrame(data, columns=columns, index=inds)
    853         df = df.reindex(range(self._last_frame + 1))
    854         if self.single is not None:

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    556                 mgr = init_dict({data.name: data}, index, columns, dtype=dtype)
    557             else:
--> 558                 mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
    559 
    560         # For data is list-like, or Iterable (will consume into list)

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\construction.py in init_ndarray(values, index, columns, dtype, copy)
    236         block_values = [values]
    237 
--> 238     return create_block_manager_from_blocks(block_values, [columns, index])
    239 
    240 

~\Miniconda3\envs\DLC22\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1685         blocks = [getattr(b, "values", b) for b in blocks]
   1686         tot_items = sum(b.shape[0] for b in blocks)
-> 1687         raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
   1688 
   1689 

ValueError: Shape of passed values is (111, 21), indices imply (111, 18)
```

</details>

So, I figured one bird seemed to be tracked well enough (well, at least three points of the seven were tracked well enough) that I should at least be able to get that track to save some labelling time, but I got the following:

<details>
<summary> n_tracks=1 Traceback </summary>

```python
-------------------------------------------------------------------------
NetworkXUnfeasible                        Traceback (most recent call last)
~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in stitch(self, add_back_residuals)
    646         try:
--> 647             _, self.flow = nx.capacity_scaling(self.G)
    648             self.paths = self.reconstruct_paths()

~\AppData\Roaming\Python\Python37\site-packages\networkx\algorithms\flow\capacityscaling.py in capacity_scaling(G, demand, capacity, weight, heap)
    398     if any(R.nodes[u]["excess"] != 0 for u in R):
--> 399         raise nx.NetworkXUnfeasible("No flow satisfying all demands.")
    400 

NetworkXUnfeasible: No flow satisfying all demands.

During handling of the above exception, another exception occurred:

NetworkXNoPath                            Traceback (most recent call last)
~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in stitch(self, add_back_residuals)
    672             for path in nx.node_disjoint_paths(
--> 673                 self.G, "source", "sink", preflow_push, self.n_tracks
    674             ):

~\AppData\Roaming\Python\Python37\site-packages\networkx\algorithms\connectivity\disjoint_paths.py in node_disjoint_paths(G, s, t, flow_func, cutoff, auxiliary, residual)
    379     paths_edges = edge_disjoint_paths(H, f"{mapping[s]}B", f"{mapping[t]}A", **kwargs)
--> 380     for path in paths_edges:
    381         # Each node in the original graph maps to two nodes in auxiliary graph

~\AppData\Roaming\Python\Python37\site-packages\networkx\algorithms\connectivity\disjoint_paths.py in edge_disjoint_paths(G, s, t, flow_func, cutoff, auxiliary, residual)
    186     if R.graph["flow_value"] == 0:
--> 187         raise NetworkXNoPath
    188 

NetworkXNoPath: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-10-9255e6665959> in <module>
      5 for pick in pickles:
      6     print(pick)
----> 7     dlc.stitch_tracklets(config, pick, n_tracks=1)
      8 
      9 #    "C:\Users\jacksonbe3\Box\research\studentProjects\birdTails\catherineSwinsky\data\20190603\wand02\trial19\cam1_03-Jun-19_16-07-34DLC_dlcrnetms5_cleantailsNov23shuffle1_200000_el.pickle"

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in stitch_tracklets(config_path, pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals, max_gap, weight_func, output_name)
   1049             return w * stitcher.calculate_edge_weight(t1, t2)
   1050     stitcher.build_graph(max_gap=max_gap, weight_func=weight_func)
-> 1051     stitcher.stitch()
   1052     stitcher.write_tracks(output_name, animal_names)
   1053     return stitcher

~\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in stitch(self, add_back_residuals)
    725             if self.paths is None:
    726                 raise ValueError(
--> 727                     f"Could not reconstruct {self.n_tracks} tracks from the tracklets given."
    728                 )
    729 

ValueError: Could not reconstruct 1 tracks from the tracklets given.
```
</details>
