### ISSUE TITLE
maDLC number of individuals mismatch with config in refine_labels

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#1266]
When loading individual names, the `refine_labels` gui looks at the number of individuals in the config file, but when the number of animals has been set lower than that number to create tracks, loading the machine labels generates a key error.

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version: 2.2rc1
 - DeepLabCut mode: maDLC, GUI and jupyter

**To Reproduce**
In my config file, I have three individuals:
```
individuals: 
- ind1 
- ind2 
- ind3
```

For a specific set of videos, there are only 2 animals, so I set that in the GUI before creating tracks, and then I extract outliers.

When selecting the relevant `machinelabels` file in the refine labels GUI, I get: 
```
KeyError: 'ind3'
```
See full error:

<details><summary>TRACEBACK</summary><p>

```python

Traceback (most recent call last):
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ind3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\deeplabcut\gui\multiple_individuals_refinement_toolbox.py", line 499, in browseDir
    MainFrame.plot(self, self.img)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\deeplabcut\gui\multiple_individuals_refinement_toolbox.py", line 1051, in plot
    self.Dataframe[self.scorer][ind][bp]["x"].values[self.iter],
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\pandas\core\frame.py", line 3023, in __getitem__
    return self._getitem_multilevel(key)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\pandas\core\frame.py", line 3074, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\pandas\core\indexes\multi.py", line 2876, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\pandas\core\indexes\multi.py", line 3158, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\pandas\core\indexes\multi.py", line 2809, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc22\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'ind3'

```
</p></details>

This is quickly avoided for now by editing the config file, but that is not ideal.

**Comment by ZZysh** [comment]
Hi I confront almost the same problem. I use the maDLC and when I extract outlier frame from 4 videos. 2 of them are not working and the code shows that KeyError: 'leftear_mice2 and many error code.  Did you solve the problem? what can i do
