### ISSUE TITLE
Corruption of Month in config.yaml in Japanese Windows environment

### ISSUE THREAD

**Issue by bobfromjapan** [DeepLabCut/DeepLabCut#1279]
**Is your feature request related to a problem? Please describe.**

In Japanese windows system, when I create a new project, the month in `config.yaml` is garbled.

```config.yaml
Task: aa
scorer: aa
date: 5��27     # this is corrupted `5月`, May in japanese 
multianimalproject: false
identity:
```

This corruption often causes problems in other parts of the workflow. (For example, an error occurs when running `create_training_dataset`)

<details><summary>TRACEBACK</summary><p>

```python

You can now check the labels, using 'check_labels' before proceeding. Then, you can use the function 'create_training_dataset' to create the training dataset.
Traceback (most recent call last):
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\create_training_dataset.py", line 394, in create_training_dataset
    augmenter_type=self.aug_choice.GetValue(),
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 894, in create_training_dataset
    cfg, Path(os.path.join(project_path, trainingsetfolder)), windows2linux
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 646, in merge_annotateddatasets
    AnnotationData.to_hdf(filename + ".h5", key="df_with_missing", mode="w")
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\pandas\core\generic.py", line 2621, in to_hdf
    encoding=encoding,
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\pandas\io\pytables.py", line 278, in to_hdf
    path_or_buf, mode=mode, complevel=complevel, complib=complib
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\pandas\io\pytables.py", line 561, in __init__
    self.open(mode=mode, **kwargs)
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\pandas\io\pytables.py", line 710, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\tables\file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "C:\Users\XXX\miniconda3\envs\DLC-CPU\lib\site-packages\tables\file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables\hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5F.c", line 444, in H5Fcreate
    unable to create file
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5Fint.c", line 1509, in H5F_open
    unable to open file: time = Thu May 27 22:26:18 2021
, name = 'C:\Users\XXX\aa-aa-2021-05-27\training-datasets\iteration-0\UnaugmentedDataSet_aa5月27\CollectedData_aa.h5', tent_flags = 13
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5FD.c", line 734, in H5FD_open
    open failed
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = 'C:\Users\XXX\aa-aa-2021-05-27\training-datasets\iteration-0\UnaugmentedDataSet_aa5月27\CollectedData_aa.h5', errno = -1, error message = 'Unknown error', flags = 13, o_flags = 302

End of HDF5 error back trace

Unable to open/create file 'C:\Users\XXX\aa-aa-2021-05-27\training-datasets\iteration-0\UnaugmentedDataSet_aa5月27\CollectedData_aa.h5'

```
</p></details>

**Describe the solution you'd like**

It is preferable to write in English (like `May27`), regardless of the language setting of the OS.

**Describe alternatives you've considered**

The problem is not that serious and can be solved by manually modifying `config.yaml`. This is probably what most non-ASCII Windows users are doing.

It is not difficult to fix the problem manually, but it is a bit tedious. 
I have found that it can be fixed by setting the `locale` to 'en_US.UTF-8' before setting the date in `new.py`/`new_3d.py` .

```python
  from datetime import datetime as dt
  from deeplabcut.utils import auxiliaryfunctions
  
  # added code
  import locale
  locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
  # end

  date = dt.today()
  month = date.strftime("%B")
  day = date.day
  d = str(month[0:3] + str(day))
  date = dt.today().strftime("%Y-%m-%d")
```

**Additional context**

In detail, it seems that this is caused by `InitLocale` being done when the `wx.App()` is executed in `gui/launch_script.py`.

https://wxpython.org/Phoenix/docs/html/wx.App.html

>InitLocale(self)
>Starting with version 3.8 on Windows, Python is now setting the locale to what is defined by the system as the default locale. This causes problems with wxWidgets which expects to be able to manage the locale via the wx.Locale class, so the locale will be reset here to be the default “C” locale settings.
>If you have troubles from the default behavior of this method you can override it in a derived class to behave differently. Please report the problem you encountered.

<details><summary>demo: locale change by wx.App()</summary><p>

```python
(DLC-CPU) C:\Users\XXX>python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> import locale
>>> import datetime
>>> locale.getlocale(locale.LC_TIME)
(None, None)
>>> datetime.datetime.today().strftime("%B")
'May'
>>> wx.App()
<wx.core.App object at 0x0000021391058048>
>>> locale.getlocale(locale.LC_TIME)
('Japanese_Japan', '932')                                      # THIS IS CAUSE OF PROBLEM!!!
>>> datetime.datetime.today().strftime("%B")
'5月'
>>> locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
'en_US.UTF-8'
>>> locale.getlocale(locale.LC_TIME)
('en_US', 'UTF-8')
>>> datetime.datetime.today().strftime("%B")
'May'                                                             # Fixed!
```

</p></details>

Since this is a very environment-dependent issue and the scope of the impact of this change is unclear, I think that if there is any problem, the above fix should not be done. 
Again, it's not that hard to fix `config.yaml` manually :)

I'd appreciate it if you could give me your opinion. Thanks!

**Comment by jeylau** [comment]
Thank you @bobfromjapan for the excellent report! I'd encourage you to submit a pull request with your changes so you get credited for fixing this bug 😊

**Comment by bobfromjapan** [comment]
Thank you for your kindness!

I made PR just a while ago, #1284. I hope this will be useful!
