### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Darkweiss** [DeepLabCut/DeepLabCut#1299]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**
Windows 10, Anaconda Env, Deeplabcut 2.2

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: 2.2rc2
Anaconda env used: DLC-GPU

**Describe the problem**
Crash when starting training.

Please place code inside this:

<details><summary>Code output</summary><p>

```python

In [2]: deeplabcut.launch_dlc()
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1]],
 'all_joints_names': ['Snout', 'Tailbase'],
 'alpha_r': 0.02,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing_DLCJun2\\Testing_DLC_Luka95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\ProgramData\\Anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing_DLCJun2\\Documentation_data-Testing_DLC_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 2,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\DeepLabCut\\Testing_DLC-Luka-2021-06-02',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'C:\\DeepLabCut\\Testing_DLC-Luka-2021-06-02\\dlc-models\\iteration-0\\Testing_DLCJun2-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Starting with imgaug pose-dataset loader (=default).
Batch Size is 1
Initializing ResNet
Loading ImageNet-pretrained resnet_50
2021-06-02 12:02:35.097373: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-06-02 12:02:35.213725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:65:00.0
2021-06-02 12:02:35.229447: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-06-02 12:02:35.250762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-06-02 12:02:35.259985: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-06-02 12:02:35.270502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-06-02 12:02:35.278978: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-06-02 12:02:35.290691: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2021-06-02 12:02:35.307684: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-06-02 12:02:35.312047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2021-06-02 12:02:35.313979: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-06-02 12:02:35.326113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:65:00.0
2021-06-02 12:02:35.338366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-06-02 12:02:35.348664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-06-02 12:02:35.356684: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-06-02 12:02:35.361357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-06-02 12:02:35.370825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-06-02 12:02:35.374541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2021-06-02 12:02:35.383344: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-06-02 12:02:35.388759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2021-06-02 12:02:35.968210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-02 12:02:35.975078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0
2021-06-02 12:02:35.983644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N
2021-06-02 12:02:35.991932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6249 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:65:00.0, compute capability: 7.5)
Max_iters overwritten as 1030000
Display_iters overwritten as 10
Save_iters overwritten as 50000
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\DeepLabCut\\Testing_DLC-Luka-2021-06-02\\dlc-models\\iteration-0\\Testing_DLCJun2-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1]], 'all_joints_names': ['Snout', 'Tailbase'], 'alpha_r': 0.02, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing_DLCJun2\\Testing_DLC_Luka95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\ProgramData\\Anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing_DLCJun2\\Documentation_data-Testing_DLC_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 2, 'pos_dist_thresh': 17, 'project_path': 'C:\\DeepLabCut\\Testing_DLC-Luka-2021-06-02', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2021-06-02 12:02:42.618286: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-06-02 12:02:42.622462: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2021-06-02 12:02:42.625778: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2021-06-02 12:02:42.634179: W .\tensorflow/stream_executor/stream.h:2039] attempting to perform DNN operation using StreamExecutor without DNN support
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\client\session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1350                                       target_list, run_metadata)
   1351

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1442                                             fetch_list, target_list,
-> 1443                                             run_metadata)
   1444

InternalError: 2 root error(s) found.
  (0) Internal: cuDNN launch failure : input shape([1,3,826,1030]) filter shape([7,7,3,64])
         [[{{node resnet_v1_50/conv1/Conv2D}}]]
         [[absolute_difference/weighted_loss/num_present/broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/concat/_595]]
  (1) Internal: cuDNN launch failure : input shape([1,3,826,1030]) filter shape([7,7,3,64])
         [[{{node resnet_v1_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\train_network.py in train_network(self, event)
    326             displayiters=displayiters,
    327             saveiters=saveiters,
--> 328             maxiters=maxiters,
    329         )
    330

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    191
    192     except BaseException as e:
--> 193         raise e
    194     finally:
    195         os.chdir(str(start_path))

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    187                 max_to_keep=max_snapshots_to_keep,
    188                 keepdeconvweights=keepdeconvweights,
--> 189                 allow_growth=allow_growth,
    190             )  # pass on path and file name for pose_cfg.yaml!
    191

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep, keepdeconvweights, allow_growth)
    275
    276         [_, loss_val, summary] = sess.run(
--> 277             [train_op, total_loss, merged_summaries], feed_dict=dict
    278         )
    279         cum_loss += loss_val

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1178     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:
   1182       results = []

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\client\session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385
   1386   def _extend_graph(self):

InternalError: 2 root error(s) found.
  (0) Internal: cuDNN launch failure : input shape([1,3,826,1030]) filter shape([7,7,3,64])
         [[node resnet_v1_50/conv1/Conv2D (defined at C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
         [[absolute_difference/weighted_loss/num_present/broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/concat/_595]]
  (1) Internal: cuDNN launch failure : input shape([1,3,826,1030]) filter shape([7,7,3,64])
         [[node resnet_v1_50/conv1/Conv2D (defined at C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'resnet_v1_50/conv1/Conv2D':
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 564, in mainloop
    self.interact()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 555, in interact
    self.run_cell(code, store_history=True)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2899, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2944, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3170, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3361, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
    deeplabcut.launch_dlc()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 46, in launch_dlc
    app.MainLoop()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\train_network.py", line 328, in train_network
    maxiters=maxiters,
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 178, in train
    losses = pose_net(cfg).train(batch)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 284, in train
    heads = self.get_net(batch[Batch.inputs])
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 183, in get_net
    net, end_points = self.extract_features(inputs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 133, in extract_features
    im_centered, global_pool=False, output_stride=16, is_training=False
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\contrib\slim\python\slim\nets\resnet_v1.py", line 274, in resnet_v1_50
    scope=scope)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\contrib\slim\python\slim\nets\resnet_v1.py", line 205, in resnet_v1
    net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\contrib\slim\python\slim\nets\resnet_utils.py", line 146, in conv2d_same
    scope=scope)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\layers\base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 234, in wrapper
    return converted_call(f, options, args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 439, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 330, in _call_unconverted
    return f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py", line 197, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 1134, in __call__
    return self.conv_op(inp, filter)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 238, in __call__
    name=self.name)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 2010, in conv2d
    name=name)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```
</p></details>

**How to Reproduce the problem**
Start training

**Screenshots**

**Additional context**
CUDA 10.0.130
Driver version 411.31

**Comment by MMathisLab** [comment]
hello @Darkweiss this could be a cuDNN/GPU/driver/TF mismatch. See here: https://github.com/tensorflow/tensorflow/issues/46309#issuecomment-758057275

or your GPU is too small for your images. `GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71`

**Comment by Darkweiss** [comment]
I installed all the right cudnn, cudatoolkit and tf versions and it still didn't work. Using 
`os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'` solved the issue of it crashing. Thanks for the quick replies. https://github.com/DeepLabCut/DeepLabCut/issues/1
