### ISSUE TITLE
IndexError: list index out of range (ffmpeg not installed)

### ISSUE THREAD

**Issue by hengzhangmiivii** [DeepLabCut/DeepLabCut#130]
deeplabcut.extract_frames(path_config, 'automatic', 'kmeans')
Reading config file successfully...
Traceback (most recent call last):
 ` File "/home/zhh/.conda/envs/dlc/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-caf2905c8f6f>", line 1, in <module>
    deeplabcut.extract_frames(path_config, 'automatic', 'kmeans')
  File "/home/zhh/.conda/envs/dlc/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/frame_extraction.py", line 93, in extract_frames
    clip = VideoFileClip(video)
  File "/home/zhh/.conda/envs/dlc/lib/python3.6/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/home/zhh/.conda/envs/dlc/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "/home/zhh/.conda/envs/dlc/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 269, in ffmpeg_parse_infos
    if "No such file or directory" in lines[-1]:
IndexError: list index out of range`

**Comment by MMathisLab** [comment]
Seems your ffmpeg did not install. Try installing it inside your env
