### ISSUE TITLE
Appropriate CSV file and labelled video produced but receiving AxisError

### ISSUE THREAD

**Issue by MoritzSteinruecke** [DeepLabCut/DeepLabCut#1340]
Hi,

Thank you for developing this incredible software, I have thoroughly enjoyed using it.

**Your Operating system and DeepLabCut version**
OS: Windows 10
DeepLabCut Version: 2.1.10.4
Anaconda env used: DLC-CPU

**Describe the problem**
I have been using DLC to label 120 videos of mice. I started by training the network on Colab using frames from a subset of videos. I then used deeplabcut.analyze_videos() on the other videos in my set, which produced appropriate CSV files in the Google Drive folder. The appropriate plots are also produced with deeplabcut.plot_trajectories(). When I use deeplabcut.create_labeled_video() on these videos, it produces appropriately labelled videos, but I receive the following error message after the code has run. I'm not sure if this is an issue as I seem to receive all the information I need for my analysis (the CSV and labelled video).

Please place code inside this:

<details><summary>Code output</summary><p>

```python
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/make_labeled_video.py", line 671, in proc_video
    color_by,
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/make_labeled_video.py", line 177, in CreateVideo
    clip.save_frame(image)
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/video_processor.py", line 146, in save_frame
    self.svid.write(np.flip(frame, 2))
  File "<__array_function__ internals>", line 6, in flip
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py", line 249, in flip
    axis = _nx.normalize_axis_tuple(axis, m.ndim)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 1323, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 1323, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
"""

The above exception was the direct cause of the following exception:

AxisError                                 Traceback (most recent call last)
<ipython-input-11-2be3377f75ca> in <module>()
----> 1 deeplabcut.create_labeled_video(path_config_file,videofile_path, videotype=VideoType)

10 frames
/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/make_labeled_video.py in create_labeled_video(config, videos, videotype, shuffle, trainingsetindex, filtered, fastmode, save_frames, keypoints_only, Frames2plot, displayedbodyparts, displayedindividuals, codec, outputframerate, destfolder, draw_skeleton, trailpoints, displaycropped, color_by, modelprefix, track_method)
    509 
    510     with Pool(min(os.cpu_count(), len(Videos))) as pool:
--> 511         pool.map(func, Videos)
    512 
    513     os.chdir(start_path)

/usr/lib/python3.7/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

/usr/lib/python3.7/multiprocessing/pool.py in worker()
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

/usr/lib/python3.7/multiprocessing/pool.py in mapstar()
     42 
     43 def mapstar(args):
---> 44     return list(map(*args))
     45 
     46 def starmapstar(args):

/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/make_labeled_video.py in proc_video()
    669                     draw_skeleton,
    670                     displaycropped,
--> 671                     color_by,
    672                 )
    673 

/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/make_labeled_video.py in CreateVideo()
    175                     image[rr, cc] = color
    176 
--> 177             clip.save_frame(image)
    178     clip.close()
    179 

/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/video_processor.py in save_frame()
    144 
    145     def save_frame(self, frame):
--> 146         self.svid.write(np.flip(frame, 2))
    147 
    148     def close(self):

<__array_function__ internals> in flip()

/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py in flip()
    247         indexer = (np.s_[::-1],) * m.ndim
    248     else:
--> 249         axis = _nx.normalize_axis_tuple(axis, m.ndim)
    250         indexer = [np.s_[:]] * m.ndim
    251         for ax in axis:

/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py in normalize_axis_tuple()
   1321             pass
   1322     # Going via an iterator directly is slower than via list comprehension.
-> 1323     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1324     if not allow_duplicate and len(set(axis)) != len(axis):
   1325         if argname:

/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py in <listcomp>()
   1321             pass
   1322     # Going via an iterator directly is slower than via list comprehension.
-> 1323     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1324     if not allow_duplicate and len(set(axis)) != len(axis):
   1325         if argname:

AxisError: axis 2 is out of bounds for array of dimension 0
```

</p></details>

**How to Reproduce the problem**
1. Create new project, label frames from a subset of videos and train the network on Colab
2. Run deeplabcut.analyze_videos(path_config_file,videofile_path, videotype=VideoType, save_as_csv=True) and deeplabcut.create_labeled_video(path_config_file,videofile_path, videotype=VideoType) on a new video
3. See error

Thanks very much for your help!
Moritz

**Comment by MMathisLab** [comment]
strange! glad it's giving the appropriate output (i.e, the video, but unclear why this numpy error), we can look into it.

**Comment by MMathisLab** [comment]
@MoritzSteinruecke coud you try updating numpy and matplotlib? I can't reproduce the error

**Comment by MoritzSteinruecke** [comment]
@MMathisLab that's worked - thanks so much!
