### ISSUE TITLE
pytables error in 2.2rc3

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#1368]
**Describe the bug**

To test out 2.2rc3, I followed the installation instructions to install a new environment on my DLC computer (env file downloaded from the blog), rather than the latest from the repo. I've encountered two errors:

1. the instructions to run `pip install deeplabcut[gui]` from within the env did not grab rc3 (got 2.1.10.4 instead). I had to run `pip install deeplabcut[gui]==2.2rc3` Instructions should be clarified.
2. I was in the middle of a workflow, so I decided to jump right into evaluating a new network, but got a tables error, which I know was a bit of a problem during rc3 testing.

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version `2.2rc3`
 - conda version 4.10.1 (ran `conda update conda` just before installation of rc3)
 - Single animal, called in jupyter lab nb

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. create env with `DEEPLABCUT.yaml`
2. activate env, and run `pip install deeplabcut[gui]==2.2rc3`
3. confirm version with `deeplabcut.__version__`
4. ran `dlc.evaluate_network(config, plotting=True, gputouse=0, show_errors=True, Shuffles=[1])`
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

----> 5 dlc.evaluate_network(config, plotting=True, gputouse=0, show_errors=True, Shuffles=[1])

~\Miniconda3\envs\dlc22rc3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix, c_engine)
    613         # Loading human annotatated data
    614         trainingsetfolder = auxiliaryfunctions.GetTrainingSetFolder(cfg)
--> 615         Data = pd.read_hdf(
    616             os.path.join(
    617                 cfg["project_path"],

~\Miniconda3\envs\dlc22rc3\lib\site-packages\pandas\io\pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    397             raise FileNotFoundError(f"File {path_or_buf} does not exist")
    398 
--> 399         store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
    400         # can't auto open/close if we are using an iterator
    401         # so delegate to the iterator

~\Miniconda3\envs\dlc22rc3\lib\site-packages\pandas\io\pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    540             raise ValueError("format is not a defined argument for HDFStore")
    541 
--> 542         tables = import_optional_dependency("tables")
    543 
    544         if complib is not None and complib not in tables.filters.all_complibs:

~\Miniconda3\envs\dlc22rc3\lib\site-packages\pandas\compat\_optional.py in import_optional_dependency(name, extra, raise_on_missing, on_version)
    107     except ImportError:
    108         if raise_on_missing:
--> 109             raise ImportError(msg) from None
    110         else:
    111             return None

ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.

```
</p></details>

`conda list`  shows `pytables==3.6.1` from conda-forge

<details><summary>full conda list</summary><p>

```

(dlc22rc3) C:\>conda list
# packages in environment at C:\Users\jacksonbe3\Miniconda3\envs\dlc22rc3:
#
# Name                    Version                   Build  Channel
absl-py                   0.13.0                   pypi_0    pypi
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bayesian-optimization     1.2.0                    pypi_0    pypi
bleach                    3.3.0              pyh44b312d_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py38haa244fe_0    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
chardet                   4.0.0                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23                  pypi_0    pypi
debugpy                   1.3.0            py38h885f38d_0    conda-forge
decorator                 4.4.2                    pypi_0    pypi
deeplabcut                2.2rc3                   pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               1.32.1                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.4                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        4.6.0            py38haa244fe_0    conda-forge
intel-openmp              2021.3.0                 pypi_0    pypi
ipykernel                 6.0.0            py38h43734a8_0    conda-forge
ipython                   7.25.0           py38h43734a8_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.18.0           py38haa244fe_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py38haa244fe_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
krb5                      1.19.1               hbae68bd_0    conda-forge
libblas                   3.9.0                     9_mkl    conda-forge
libcblas                  3.9.0                     9_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.77.0               h789b8ee_0    conda-forge
liblapack                 3.9.0                     9_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
llvmlite                  0.34.0                   pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py38h294d835_0    conda-forge
matplotlib                3.1.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mistune                   0.8.4           py38h294d835_1004    conda-forge
mkl                       2021.2.0           hb70f87d_389    conda-forge
mock                      4.0.3            py38haa244fe_1    conda-forge
moviepy                   1.0.1                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
nb_conda                  2.2.1            py38haa244fe_4    conda-forge
nb_conda_kernels          2.3.1            py38haa244fe_0    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py38haa244fe_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.5.1                    pypi_0    pypi
notebook                  6.4.0              pyha770c72_0    conda-forge
numba                     0.51.1                   pypi_0    pypi
numexpr                   2.7.3            py38h4c96930_0    conda-forge
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
opencv-python             4.5.2.54                 pypi_0    pypi
opencv-python-headless    3.4.9.33                 pypi_0    pypi
openssl                   1.1.1k               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.5                    pypi_0    pypi
pandoc                    2.14.0.3             h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
patsy                     0.5.1                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.0                    pypi_0    pypi
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
proglog                   0.1.9                    pypi_0    pypi
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
prompt_toolkit            3.0.19               hd8ed1ab_0    conda-forge
protobuf                  3.17.3                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pytables                  3.6.1            py38h153c448_3    conda-forge
python                    3.8.10          h7840368_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   300              py38h294d835_0    conda-forge
pywinpty                  1.1.3            py38hd3f51b4_0    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.1.0           py38h09162b1_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.1.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
ruamel-yaml               0.17.10                  pypi_0    pypi
ruamel-yaml-clib          0.2.4                    pypi_0    pypi
scikit-image              0.18.2                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.7.0                    pypi_0    pypi
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
shapely                   1.7.1                    pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sqlite                    3.36.0               h8ffe710_0    conda-forge
statsmodels               0.12.2                   pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tbb                       2021.2.0             h2d74725_1    conda-forge
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
tensorpack                0.9.8                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.10.1           py38haa244fe_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2021.6.14                pypi_0    pypi
tk                        8.6.10               h8ffe710_1    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.61.1                   pypi_0    pypi
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.6                   pypi_0    pypi
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py38haa244fe_4    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
wxpython                  4.0.7.post2              pypi_0    pypi
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
```
</p></details>

### attempted fix

1. `conda uninstall pytables` which led to a lot of changes (mostly superseding) of various modules
2. `pip install tables` 
3. The code seemed to work (but my GPU was not being engaged, so now I'm off to try to fix that...)

**Comment by MMathisLab** [comment]
also @backyardbiomech good catch on blog, it's updated, and for ease, I just pinned the 2.2rc3 in the file now *and dropped pytables, if you want to try this again! http:\\blog.deeplabcut.org

**Comment by backyardbiomech** [comment]
On my mac, tables installs with pip. 

I'll check on the windows computer again, but it just decided to force a windows update so now I'm left waiting (remotely) for it to (hopefully) restart.

**Comment by MMathisLab** [comment]
thanks so much 👯

**Comment by backyardbiomech** [comment]
The blog's version of `DEEPLABCUT.yaml` worked on windows, mostly. Windows pip does not like the single quotes in `'deeplabcut[gui]'==2.2rc3`. When running in pip, it produces a somewhat helpful error, but when using the `DEEPLABCUT.yaml` file, it produces a scary looking anaconda error that's not very helpful. Simply removing the single quotes from that line works.

**Comment by neuropil** [comment]
@backyardbiomech What was the anaconda error?

**Comment by backyardbiomech** [comment]
I can't remember the anaconda error, but there was some hint buried deep in there that it was a problem with pip or the deeplabcut installation.

**Comment by backyardbiomech** [comment]
I just reproduced the error. 

<details>

```
conda env create -n rc3test -f DEEPLABCUT.yaml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda_env\cli\main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda_env\specs\__init__.py", line 43, in detect
        if spec.can_handle():
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda_env\env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda_env\env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\conda\common\serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 101, in compose_document
        node = self.compose_node(None, None)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 218, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 136, in compose_node
        node = self.compose_sequence_node(anchor)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 180, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\composer.py", line 211, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\parser.py", line 141, in check_event
        self.current_event = self.state()
      File "C:\Users\jacksonbe3\Miniconda3\lib\site-packages\ruamel_yaml\parser.py", line 581, in parse_block_mapping_key
        token.start_mark,
    ruamel_yaml.parser.ParserError: while parsing a block mapping
      in "<unicode string>", line 26, column 5:
          - pip:
            ^ (line: 26)
    expected <block end>, but found '<scalar>'
      in "<unicode string>", line 27, column 24:
            - 'deeplabcut[gui]'==2.2rc3
                               ^ (line: 27)

`$ C:\Users\jacksonbe3\Miniconda3\Scripts\conda-env-script.py create -n rc3test -f DEEPLABCUT.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\jacksonbe3\Miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\jacksonbe3\Miniconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\jacksonbe3\Miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\jacksonbe3\Miniconda3\python.exe
               CONDA_ROOT=C:\Users\jacksonbe3\Miniconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\jacksonbe3\Miniconda3;C:\Users\jacksonbe3\Miniconda3\Library\
                          mingw-w64\bin;C:\Users\jacksonbe3\Miniconda3\Library\usr\bin;C:\Users\
                          jacksonbe3\Miniconda3\Library\bin;C:\Users\jacksonbe3\Miniconda3\Scrip
                          ts;C:\Users\jacksonbe3\Miniconda3\bin;C:\Users\jacksonbe3\Miniconda3;C
                          :\Users\jacksonbe3\Miniconda3\Library\mingw-w64\bin;C:\Users\jacksonbe
                          3\Miniconda3\Library\usr\bin;C:\Users\jacksonbe3\Miniconda3\Library\bi
                          n;C:\Users\jacksonbe3\Miniconda3\Scripts;C:\Users\jacksonbe3\Miniconda
                          3\bin;C:\Users\jacksonbe3\Miniconda3\condabin;C:\Program Files\NVIDIA
                          GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.4\libnvvp;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\libnvvp;C:\oracle\product\12.1.0\client_1\bin;C:\wi
                          ndows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32
                          \WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\ffmpeg\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 20
                          21.2.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WIND
                          OWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Use
                          rs\jacksonbe3\AppData\Local\Microsoft\WindowsApps;C:\Users\jacksonbe3\
                          AppData\Local\Programs\Git\cmd;C:\Users\jacksonbe3\AppData\Local\GitHu
                          bDesktop\bin;C:\Users\jacksonbe3\AppData\Local\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
               PYTHONPATH=C:\Users\jacksonbe3\Documents\repos
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\jacksonbe3\Miniconda3
            shell level : 1
       user config file : C:\Users\jacksonbe3\.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __cuda=11.4=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\jacksonbe3\Miniconda3  (writable)
      conda av data dir : C:\Users\jacksonbe3\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\jacksonbe3\Miniconda3\pkgs
                          C:\Users\jacksonbe3\.conda\pkgs
                          C:\Users\jacksonbe3\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jacksonbe3\Miniconda3\envs
                          C:\Users\jacksonbe3\.conda\envs
                          C:\Users\jacksonbe3\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.7.7 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:

```

</details>

The key line it is:

```
      in "<unicode string>", line 27, column 24:
            - 'deeplabcut[gui]'==2.2rc3
                               ^ (line: 27)
```

If you see that, then open `DEEPLABCUT.yaml` in a text editor, remove the single quotes around deeplabbut[gui], save, and run the env create command again.

**Comment by MMathisLab** [comment]
@jeylau seems quotes are required for ubuntu, not for windows - maybe we need a work around?

**Comment by MMathisLab** [comment]
@backyardbiomech is you do this, can this install on windows? `  "deeplabcut[gui]" `

**Comment by backyardbiomech** [comment]
### on the anaconda command line in windows 10
`pip install "deeplabcut[gui]"`  installs 2.1.10.4
`pip install 'deeplabcut[gui]'`  installs 2.1.10.4
`pip install 'deeplabcut[gui]'==2.2rc3`  produces `ERROR: Invalid requirement: "'deeplabcut[gui]'==2.2rc3"`
`pip install "deeplabcut[gui]"==2.2rc3`  installs 2.2rc3
`pip install "deeplabcut[gui]==2.2rc3"` installs 2.2rc3
`pip install 'deeplabcut[gui]==2.2rc3'` produces `ERROR: Invalid requirement:...`

### in the DEEPLABCUT.yaml env file when creating a new env
`pip install "deeplabcut[gui]"==2.2rc3`  produces an error
`pip install "deeplabcut[gui]==2.2rc3"`  installs 2.2rc3

`pip install "deeplabcut[gui]==2.2rc3"` also works on my mac.

It looks like surround the full `package==version` in double quotes is the only universal instruction across my platforms and installation pathways.
