### ISSUE TITLE
testscript.py - error in EVALUATE / pairwisedistances 

### ISSUE THREAD

**Issue by MitchFuchs** [DeepLabCut/DeepLabCut#1425]
Hi guys, 

Thanks for helping me finding out where my installation issue comes from. 
Regards, 
Mitch. 

OS: Windows 10
DLC version: 2.2rc3 (installed via conda)
Tensorflow: 2.5.0
CUDA: 11.0
CuDNN: 8.2
GPU: GTX 1080 (locally)

While running testscript.py, I encounter the following error, in EVALUATE (def pairwisedistances) : 

<details><summary>Code output</summary><p>

2021-07-19 09:31:57.147350: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
Imported DLC!
2.5.0
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Created "C:\Users\micha\DeepLabCut\examples\TEST-Alex-2021-07-19\videos"
Created "C:\Users\micha\DeepLabCut\examples\TEST-Alex-2021-07-19\labeled-data"
Created "C:\Users\micha\DeepLabCut\examples\TEST-Alex-2021-07-19\training-datasets"
Created "C:\Users\micha\DeepLabCut\examples\TEST-Alex-2021-07-19\dlc-models"
Copying the videos
C:\Users\micha\DeepLabCut\examples\TEST-Alex-2021-07-19\videos\reachingvideo1.avi
Generated "C:\Users\micha\DeepLabCut\examples\TEST-Alex-2021-07-19\config.yaml"

A new project with name TEST-Alex-2021-07-19 is created at C:\Users\micha\DeepLabCut\examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:02, 87.59it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted, for the videos of interest.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.32it/s]
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
CREATING TRAININGSET
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
CHANGING training parameters to end quickly!
TRAIN
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'alpha_r': 0.02,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTJul19\\TEST_Alex80shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 2,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\Users\\micha\\OneDrive\\PhD\\Python\\conda\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTJul19\\Documentation_data-TEST_80shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.001, 5]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\micha\\DeepLabCut\\examples\\TEST-Alex-2021-07-19',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 5,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\micha\\DeepLabCut\\examples\\TEST-Alex-2021-07-19\\dlc-models\\iteration-0\\TESTJul19-trainset80shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2021-07-19 09:32:21.449929: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2021-07-19 09:32:21.501355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0b:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 8,00GiB deviceMemoryBandwidth: 298,32GiB/s
2021-07-19 09:32:21.501521: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-07-19 09:32:21.512436: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2021-07-19 09:32:21.512598: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
2021-07-19 09:32:21.518184: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
2021-07-19 09:32:21.520082: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2021-07-19 09:32:21.529725: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2021-07-19 09:32:21.533577: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
2021-07-19 09:32:21.534937: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-07-19 09:32:21.535283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-19 09:32:21.536581: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-19 09:32:21.580538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0b:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 8,00GiB deviceMemoryBandwidth: 298,32GiB/s
2021-07-19 09:32:21.580716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-19 09:32:22.318651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-19 09:32:22.318781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-07-19 09:32:22.319854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-07-19 09:32:22.320596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6609 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:0b:00.0, compute capability: 6.1)
Loading ImageNet-pretrained resnet_50
2021-07-19 09:32:22.949196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0b:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 8,00GiB deviceMemoryBandwidth: 298,32GiB/s
2021-07-19 09:32:22.949419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-19 09:32:22.950518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-19 09:32:22.950892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-07-19 09:32:22.951360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-07-19 09:32:22.951955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6609 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:0b:00.0, compute capability: 6.1)
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\micha\\DeepLabCut\\examples\\TEST-Alex-2021-07-19\\dlc-models\\iteration-0\\TESTJul19-trainset80shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'], 'alpha_r': 0.02, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTJul19\\TEST_Alex80shuffle1.mat', 'decay_steps': 30000, 'display_iters': 2, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\Users\\micha\\OneDrive\\PhD\\Python\\conda\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTJul19\\Documentation_data-TEST_80shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.001, 5]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\micha\\DeepLabCut\\examples\\TEST-Alex-2021-07-19', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 5, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2021-07-19 09:32:30.215461: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-07-19 09:32:30.687575: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8100
2021-07-19 09:32:31.249999: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2021-07-19 09:32:31.616981: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
iteration: 2 loss: 1.1745 lr: 0.001
iteration: 4 loss: 0.5831 lr: 0.001
2021-07-19 09:32:36.078725: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 82, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py:68) ]]

Errors may have originated from an input operation.
Input Source operations connected to node fifo_queue_enqueue:
 fifo_queue (defined at C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py:67)
 Placeholder_1 (defined at C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py:60)

Original stack trace for 'fifo_queue_enqueue':
  File "testscript.py", line 147, in <module>
    deeplabcut.train_network(path_config_file)
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    train(
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 171, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 68, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 344, in enqueue
    return gen_data_flow_ops.queue_enqueue_v2(
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4040, in queue_enqueue_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
EVALUATE
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTJul19\\TEST_Alex80shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\micha\\OneDrive\\PhD\\Python\\conda\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\micha\\DeepLabCut\\examples\\TEST-Alex-2021-07-19\\dlc-models\\iteration-0\\TESTJul19-trainset80shuffle1\\test\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Running  DLC_resnet50_TESTJul19shuffle1_5  with # of trainingiterations: 5
2021-07-19 09:32:39.173421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0b:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 8,00GiB deviceMemoryBandwidth: 298,32GiB/s
2021-07-19 09:32:39.173649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-19 09:32:39.175228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-19 09:32:39.175590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-07-19 09:32:39.176134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-07-19 09:32:39.176688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6609 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:0b:00.0, compute capability: 6.1)
Analyzing data...
5it [00:01,  3.93it/s]
Done and results stored for snapshot:  snapshot-5
Traceback (most recent call last):
  File "testscript.py", line 150, in <module>
    deeplabcut.evaluate_network(path_config_file, plotting=True)
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py", line 832, in evaluate_network
    RMSE, RMSEpcutoff = pairwisedistances(
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py", line 34, in pairwisedistances
    DataCombined[scorer1][bodyparts] - DataCombined[scorer2][bodyparts]
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py", line 3445, in __getitem__
    if com.is_bool_indexer(key):
  File "C:\Users\micha\OneDrive\PhD\Python\conda\envs\DEEPLABCUT\lib\site-packages\pandas\core\common.py", line 146, in is_bool_indexer
    return len(key) > 0 and lib.is_bool_list(key)
TypeError: Argument 'obj' has incorrect type (expected list, got CommentedSeq)

**Comment by jeylau** [comment]
Hi @MitchFuchs, pandas 1.3.0 caused this issue, which was recently fixed with https://github.com/DeepLabCut/DeepLabCut/commit/5afe853a2fbfcf74674b635a8966e5ea94de3716.
You could edit that line yourself, or, perhaps simpler, run: `pip install pandas<1.3`

**Comment by MitchFuchs** [comment]
Thanks a lot Jessy for your fast reply. I kept pandas 1.3.0 and fixed the line as mention in your commit. Testscript.py now works fine!

Happy DeepLabCutting and thanks for the great support!
Mitch
