### ISSUE TITLE
`plot_trajectories` is not name agnostic if n_tracks differs from config.yaml

### ISSUE THREAD

**Issue by neurologic** [DeepLabCut/DeepLabCut#1439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When calling plot_trajectories(), obtain plot of trajectories.

After calling: 
1) analyze_videos() 
2) convert_detections2tracklets()
3) stitch_tracklets()
(I did not refine_tracklets() for this test)

### Operating System

MacOS Catalina

### DeepLabCut version

2.2rc3

### DeepLabCut mode

multi animal

### Device type

CPU

### Steps To Reproduce

In the DEEPLABCUT_M1 environment

[with a _el.h5 and _el.pickle files in the folder that contains the analyzed video)

1) pythonw
2) import deeplabcut
3) deeplabcut.plot_trajectories(configpath,[videopath],filtered=False,track_method='ellipse')
     videopath is path to the analyzed video
4) KeyError(key)

### Relevant log output

```shell
>>> deeplabcut.plot_trajectories(configpath,[videopath],filtered=False,track_method='ellipse')
Loading  /Users/kperks/mnt/PerksLab_rstore/KP/DLC/videos/fish_divider.avi and data.
Traceback (most recent call last):
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'F1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/deeplabcut/utils/plotting.py", line 279, in plot_trajectories
    linewidth=linewidth,
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/deeplabcut/utils/plotting.py", line 51, in PlottingResults
    Dataframe = Dataframe.loc(axis=1)[:, individuals2plot]
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexing.py", line 818, in _getitem_lowerdim
    return self._getitem_axis(tup, axis=axis)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexing.py", line 1157, in _getitem_axis
    locs = labels.get_locs(key)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 3349, in get_locs
    self.get_loc_level(k, level=i, drop_level=False)[0]
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 3011, in get_loc_level
    return self._get_loc_level(key, level=level, drop_level=drop_level)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 3112, in _get_loc_level
    indexer = self._get_level_indexer(key, level=level)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 3204, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 2855, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "/Users/kperks/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'F1'
```

### Anything else?

Troubleshooting Steps Taken:
1) opened the .h5 in a jupyter notebook to look at the contents
2) see that the column names are 'ind1', ...'ind8' (I had set n_tracks=8 during stitch_tracklets; config file has 10 individuals)
     ***in the config file, the individuals' names are ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10'] so I assumed this is what the key error was (the function/method is looking for 'F1' in the h5 but the h5 file has 'ind1')
3) performed the operations of the function line by line from plotting.py to confirm suspicion that the keys expected were being pulled from the config file. 
4) individuals = deeplabcut.utils.auxfun_multianimal.IntersectionofIndividualsandOnesGivenbyUser(cfg,displayedindividuals) returns individuals = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10']
5) I stopped here because it seems that if the function is using this list of individuals to sort through the .h5 file containing the bodypart positions of the tracked indivuduals, then it will fail due to KeyError.
![Screen Shot 2021-07-27 at 4 41 31 PM](https://user-images.githubusercontent.com/4777333/127224490-bcfb1c19-cf5a-46d7-9c48-aef9bc09ca00.png)

Am I doing any of these steps incorrectly? Or is there an error in how the column headers are getting created/named for the .h5 (and/or pickle)? Since I can't find anyone else posting this issue I feel like it must be the former, but I can't figure it out yet. 
For these steps of the process, I am following the documentation at: https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html (PS this documentation has evolved beautifully. So inspiring)

Thank you!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
I believe this is already fixed; so rather than pip install rc3, just run `!pip install git+https://github.com/DeepLabCut/DeepLabCut.git`

**Comment by jeylau** [comment]
Hi @neurologic; animal names was fixed in #1239 back in May. Stitching tracklets once again should produce a new h5 file with the correct dataframe header 😌

**Comment by MMathisLab** [comment]
@jeylau I do think this is a bug, namely, if the user selects a diff # than config.yaml indv list ("(I had set n_tracks=8 during stitch_tracklets; config file has 10 individuals)", the plot_traj should take the config.yaml names (i.e., if less than indv in config, use them, if MORE, then it needs to grab the ind1, etc).

**Comment by neurologic** [comment]
Thanks!
When the fix gets pushed (? I think that is the term?), I should then run ```!pip install git+https://github.com/DeepLabCut/DeepLabCut.git``` within the environment to incorporate the fix locally (or work within a freshly git pulled deeplabcut folder), correct?

**Comment by MMathisLab** [comment]
@neurologic it is fixed now; just you can install from the repo to use.
