### ISSUE TITLE
`wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale. Things are going to break, please only change locale by creating wxLocale objects to avoid this!`

### ISSUE THREAD

**Issue by owadhwa** [DeepLabCut/DeepLabCut#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I tried launching the DLC GUI but I'm getting the following error:

wxAssertionError                          Traceback (most recent call last)
<ipython-input-2-1ced4355ffc5> in <module>
----> 1 deeplabcut.launch_dlc()

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py in launch_dlc()
     43 def launch_dlc():
     44     app = wx.App()
---> 45     frame = MainFrame().Show()
     46     app.MainLoop()

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py in __init__(self)
     25         media_path = os.path.join(dlcparent_path, "gui", "media")
     26         logo = os.path.join(media_path, "logo.png")
---> 27         self.SetIcon(wx.Icon(logo))
     28         # Here we create a panel and a notebook on the panel
     29         self.panel = wx.Panel(self)

wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

### Operating System

operating system Windows 10

### DeepLabCut version

dlc version 2.2rc3

### DeepLabCut mode

single animal

### Device type

gpu RTX 3060

### Steps To Reproduce

1. In the environment DEEPLABCUT
2. Type ipython --> import deeplabcut --> deeplabcut.launch_dlc()

### Relevant log output

```shell
wxAssertionError                          Traceback (most recent call last)
<ipython-input-2-1ced4355ffc5> in <module>
----> 1 deeplabcut.launch_dlc()

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py in launch_dlc()
     43 def launch_dlc():
     44     app = wx.App()
---> 45     frame = MainFrame().Show()
     46     app.MainLoop()

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py in __init__(self)
     25         media_path = os.path.join(dlcparent_path, "gui", "media")
     26         logo = os.path.join(media_path, "logo.png")
---> 27         self.SetIcon(wx.Icon(logo))
     28         # Here we create a panel and a notebook on the panel
     29         self.panel = wx.Panel(self)

wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by owadhwa** [comment]
Hello, Sorry to bother you again, but how do I fix this error? 
Thank you.

**Comment by MMathisLab** [comment]
@om-git216 currently you would need to pip install from git, so follow here: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-use-the-latest-updates-directly-from-github

Otherwise, a new version of DLC that includes this will be out tomorrow.

**Comment by om-git216** [comment]
Ok thank you. I did pip install from github and tried testing the installation on the testscript.py file.
I got the following error while labelling the frames: (this error persists even if I run pip install --upgrade deeplabcut)

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
Traceback (most recent call last):
  File "testscript.py", line 116, in <module>
    deeplabcut.check_labels(path_config_file)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 300, in check_labels
    visualization.make_labeled_images_from_dataframe(
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\visualization.py", line 322, in make_labeled_images_from_dataframe
    fig, ax = prepare_figure_axes(w, h, scale, dpi)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\visualization.py", line 210, in prepare_figure_axes
    fig = plt.figure(
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\pyplot.py", line 539, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1969, in new_figure_manager
    return super().new_figure_manager(num, *args, **kwargs)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backend_bases.py", line 3261, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1973, in new_figure_manager_given_figure
    frame = cls._frame_class(num, figure)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1087, in __init__
    _set_frame_icon(self)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1254, in _set_frame_icon
    icon = wx.Icon(_load_bitmap(image))
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1243, in _load_bitmap
    bmp = wx.Bitmap(bmpFilename)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by owadhwa** [comment]
Ok thank you. I did pip install from git. The GUI is opening now, but when I try to load the extracted frames, I get the following error:

Traceback (most recent call last):
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 698, in browseDir
    ) = self.image_panel.drawplot(
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 189, in drawplot
    self.toolbar = NavigationToolbar(self.canvas)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1377, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backend_bases.py", line 2636, in __init__
    self._init_toolbar()
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1404, in _init_toolbar
    bitmap=_load_bitmap(image_file + ".png"),
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1243, in _load_bitmap
    bmp = wx.Bitmap(bmpFilename)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by MMathisLab** [comment]
@om-git216 you can now just install the latest from pip; please run `pip install "deeplabcut[gui]==2.2"`

**Comment by owadhwa** [comment]
Ok thank you. I'm really sorry to bother you again, but I did run` pip install "deeplabcut[gui]==2.2"` and then tried testing it on the testscript.py file but this is the error that I got: 

CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
Traceback (most recent call last):
  File "testscript.py", line 116, in <module>
    deeplabcut.check_labels(path_config_file)
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 300, in check_labels
    visualization.make_labeled_images_from_dataframe(
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\deeplabcut\utils\visualization.py", line 322, in make_labeled_images_from_dataframe
    fig, ax = prepare_figure_axes(w, h, scale, dpi)
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\deeplabcut\utils\visualization.py", line 210, in prepare_figure_axes
    fig = plt.figure(
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\pyplot.py", line 797, in figure
    manager = new_figure_manager(
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\pyplot.py", line 316, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\backends\backend_wx.py", line 1500, in new_figure_manager
    return super().new_figure_manager(num, *args, **kwargs)
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\backend_bases.py", line 3545, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\backends\backend_wx.py", line 1504, in new_figure_manager_given_figure
    frame = cls._frame_class(num, figure)
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\backends\backend_wx.py", line 913, in __init__
    _set_frame_icon(self)
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\backends\backend_wx.py", line 1081, in _set_frame_icon
    icon = wx.Icon(_load_bitmap(image))
  File "C:\Users\Omika\anaconda3\envs\DLC\lib\site-packages\matplotlib\backends\backend_wx.py", line 1075, in _load_bitmap
    return wx.Bitmap(str(cbook._get_data_path('images', filename)))
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

The algorithm stopped after this and did not produce labelled images/train the network, etc. 

I also tried analysing on some of my videos (single animal Drosophila video), the GUI opened and everything went well until the labelling step when I got this error. I kept going because the algorithm didn't stop. I was able to train and evaluate my network but when it came to making the video with the labelled frames, it did not give any output. 

It would be very nice if you would help me out.
