### ISSUE TITLE
"ValueError: too many values to unpack (expected 2)" when trying to create a labeled video

### ISSUE THREAD

**Issue by gaelerobb** [DeepLabCut/DeepLabCut#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using the GUI under the "Create videos" tab, after selecting the videos and clicking run I get an error in the terminal. A video file is created, but it is not playable. 

### Operating System

Ubuntu 20.04

### DeepLabCut version

2.2rc3

### DeepLabCut mode

single animal

### Device type

cpu: Intel® Xeon(R) CPU E5-2620 v4 @ 2.10GHz × 32

### Relevant log output

```shell
(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.183: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.187: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.188: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.191: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): Gtk-WARNING **: 13:54:21.191: Error loading theme icon 'gtk-edit' for stock: Failed to load icon

(__main__.py:4421): Gtk-CRITICAL **: 13:54:21.191: render_fallback_image: assertion 'pixbuf != NULL' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 13:54:21.191: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.193: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.194: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.212: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): Gtk-WARNING **: 13:54:21.212: Error loading theme icon 'gtk-edit' for stock: Failed to load icon

(__main__.py:4421): Gtk-CRITICAL **: 13:54:21.212: render_fallback_image: assertion 'pixbuf != NULL' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 13:54:21.212: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 13:54:21.253: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): Gtk-WARNING **: 13:54:21.253: Error loading theme icon 'gtk-edit' for stock: Failed to load icon

(__main__.py:4421): Gtk-CRITICAL **: 13:54:21.253: render_fallback_image: assertion 'pixbuf != NULL' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 13:54:21.253: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Using snapshot-260000 for model /home/flybot/sync/antenna_displacement-gael-2021-07-26/dlc-models/iteration-0/antenna_displacementJul26-trainset95shuffle1
/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2021-08-05 13:55:16.034962: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-08-05 13:55:16.035010: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-05 13:55:16.035048: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Flymaster2): /proc/driver/nvidia/version does not exist
2021-08-05 13:55:16.035536: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-05 13:55:16.185783: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2095429999 Hz
Starting to analyze %  /media/flybot/DATA_2020_Opto/Gael/antenna_experiments/test_videos/267601CA381D__40068735__20210722_171906067.mp4
/media/flybot/DATA_2020_Opto/Gael/antenna_experiments/test_videos  already exists!
Loading  /media/flybot/DATA_2020_Opto/Gael/antenna_experiments/test_videos/267601CA381D__40068735__20210722_171906067.mp4
Duration of video [s]:  10.53 , recorded with  500.0 fps!
Overall # of frames:  5265  found with (before cropping) frame dimensions:  720 540
Starting to extract posture
5304it [14:40,  6.02it/s]                                                       
Saving results in /media/flybot/DATA_2020_Opto/Gael/antenna_experiments/test_videos...
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.088: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.092: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.093: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.096: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): Gtk-WARNING **: 14:10:15.096: Error loading theme icon 'gtk-edit' for stock: Failed to load icon

(__main__.py:4421): Gtk-CRITICAL **: 14:10:15.096: render_fallback_image: assertion 'pixbuf != NULL' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 14:10:15.096: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.099: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.099: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.125: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): Gtk-WARNING **: 14:10:15.125: Error loading theme icon 'gtk-edit' for stock: Failed to load icon

(__main__.py:4421): Gtk-CRITICAL **: 14:10:15.125: render_fallback_image: assertion 'pixbuf != NULL' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 14:10:15.125: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 14:10:15.125: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(__main__.py:4421): GLib-GIO-CRITICAL **: 14:10:15.161: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(__main__.py:4421): Gtk-WARNING **: 14:10:15.161: Error loading theme icon 'gtk-edit' for stock: Failed to load icon

(__main__.py:4421): Gtk-CRITICAL **: 14:10:15.161: render_fallback_image: assertion 'pixbuf != NULL' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 14:10:15.161: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(__main__.py:4421): GLib-GObject-CRITICAL **: 14:10:15.162: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
/media/flybot/DATA_2020_Opto/Gael/antenna_experiments/test_videos  already exists!
Starting to process video: /media/flybot/DATA_2020_Opto/Gael/antenna_experiments/test_videos/267601CA381D__40068735__20210722_171906067.mp4
Loading /media/flybot/DATA_2020_Opto/Gael/antenna_experiments/test_videos/267601CA381D__40068735__20210722_171906067.mp4 and data.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 655, in proc_video
    CreateVideo(
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 83, in CreateVideo
    bpts2connect = get_segment_indices(bodyparts2connect, all_bpts)
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 43, in get_segment_indices
    for bpt1, bpt2 in bodyparts2connect:
ValueError: too many values to unpack (expected 2)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/create_videos.py", line 366, in create_videos
    deeplabcut.create_labeled_video(
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 511, in create_labeled_video
    pool.map(func, Videos)
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/flybot/anaconda3/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: too many values to unpack (expected 2)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Please check the definition of the `skeleton` in the main project config.yaml file and make sure it is non-empty and that there are pairs of body parts only. There may be a typo somewhere 😄

**Comment by gaelerobb** [comment]
@jeylau That was exactly it. Small typo. Thank you for helping me so quick!
