### ISSUE TITLE
`cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-f51eratu/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

### ISSUE THREAD

**Issue by LyleSmash** [DeepLabCut/DeepLabCut#1478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to evaluate network after completing the training. I have a series of errors which I am having a hard time interpreting. I am running this through a HPC center through MobaXTERM on windows10

### Operating System

Remote-monitoring information for session farnam.hpc.yale.edu (lm966)

- Host:
    Hostname: farnam2.farnam.hpc.yale.internal
    Version:  Linux version 3.10.0-1160.21.1.el7.x86_64 (mockbuild@x86-034.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Feb 22 18:03:13 EST 2021

- CPU:
    Current CPU load:  8%

- RAM:
    Total RAM:  128111 MB
    Used RAM:   35952 MB
    Cached RAM: 8433 MB
    Buffers:    1053 MB

### DeepLabCut version

This is my yaml file 
```
#DeepLabCut2.0 Toolbox (deeplabcut.org)
#© A. & M. Mathis Labs
#https://github.com/DeepLabCut/DeepLabCut
#Please see AUTHORS for contributors.

#https://github.com/DeepLabCut/DeepLabCut/blob/master/AUTHORS
#Licensed under GNU Lesser General Public License v3.0
#
# DeepLabCut environment
# FIRST: INSTALL CORRECT DRIVER for GPU, see https://stackoverflow.com/questions/30820513/what-is-the-correct-version-of-cuda-for-my-nvidia-driver/30820690
#
# install: conda env create -f DEEPLABCUT.yaml
# update:  conda env update -f DEEPLABCUT.yaml
name: DEEPLABCUT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  - nb_conda
  - ffmpeg
  - wxpython<4.1
  - pip:
    - "deeplabcut[gui]==2.2rc3"

```
-----------------------------------------------------------------------------------------------------------------

This is environments. 
```
[lm966@farnam2 ~]$ conda list
# packages in environment at /ysm-gpfs/apps/software/miniconda/4.10.3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
brotlipy                  0.7.0           py39h27cfd23_1003
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
cffi                      1.14.6           py39h400218f_0
chardet                   4.0.0           py39h06a4308_1003
conda                     4.10.3           py39hf3d152e_0    conda-forge
conda-package-handling    1.7.3            py39h27cfd23_1
cryptography              3.4.7            py39hd23ed53_0
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyhd3eb1b0_0
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9
libarchive                3.5.1                hccf745f_2    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libiconv                  1.16                 h516909a_0    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libsolv                   0.7.19               h780b84a_5    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17
libxml2                   2.9.12               h72842e0_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.15.2           py39h951de11_0    conda-forge
ncurses                   6.2                  he6710b0_1
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.3           py39h06a4308_0
pycosat                   0.6.3            py39h27cfd23_0
pycparser                 2.20                       py_2
pyopenssl                 20.0.1             pyhd3eb1b0_1
pysocks                   1.7.1            py39h06a4308_0
python                    3.9.5                h12debd9_4
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h27cfd23_0
reproc                    14.2.1               h36c2ea0_0    conda-forge
reproc-cpp                14.2.1               h58526e2_0    conda-forge
requests                  2.25.1             pyhd3eb1b0_0
ruamel_yaml               0.15.100         py39h27cfd23_0
setuptools                52.0.0           py39h06a4308_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hc218d9a_0
tk                        8.6.10               hbc83047_0
tqdm                      4.61.2             pyhd3eb1b0_1
tzdata                    2021a                h52ac0ba_0
urllib3                   1.26.6             pyhd3eb1b0_1
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.5.0                ha95c52a_0    conda-forge
```

### DeepLabCut mode

single animal

### Device type

NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2

Tesla k80

### Steps To Reproduce

1) module load cuDNN/8.1.1.33 miniconda
2) conda activate DEEPLABCUT
3) python -m deeplab cut
4) Load config file
5)Training was already successfully completed, move to evaluate
6)Evaluate network

### Relevant log output

```shell
[lm966@c21n10 ~]$ module load cuDNN/8.1.1.33 miniconda
[lm966@c21n10 ~]$ nvidia-smi
Tue Aug 24 15:48:09 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:0E:00.0 Off |                    0 |
| N/A   47C    P8    31W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[lm966@c21n10 ~]$ ^C
[lm966@c21n10 ~]$ ^C
[lm966@c21n10 ~]$ conda activate DEEPLABCUT
(DEEPLABCUT)[lm966@c21n10 ~]$ python -m deeplabcut
2021-08-24 15:50:03.336033: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Starting GUI...

/gpfs/ysm/home/lm966/Deeplabcut/Hot_Cold_Mouse-Lyle_Murphy-2021-07-15/evaluation-results/  already exists!
/gpfs/ysm/home/lm966/Deeplabcut/Hot_Cold_Mouse-Lyle_Murphy-2021-07-15/evaluation-results/iteration-0/Hot_Cold_MouseJul15-trainset95shuffle1  already exists!
Running  DLC_resnet50_Hot_Cold_MouseJul15shuffle1_1030000  with # of trainingiterations: 1030000
/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2021-08-24 15:51:35.668174: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-08-24 15:51:35.697837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0e:00.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2021-08-24 15:51:35.698102: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-08-24 15:51:36.129573: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-08-24 15:51:36.129780: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-08-24 15:51:36.219033: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-08-24 15:51:36.345203: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-08-24 15:51:36.539816: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-08-24 15:51:36.669743: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-08-24 15:51:36.682735: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-08-24 15:51:36.685110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-08-24 15:51:36.685833: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-24 15:51:36.687146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0e:00.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2021-08-24 15:51:36.689403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-08-24 15:51:36.689534: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-08-24 15:51:40.454812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-24 15:51:40.455015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-08-24 15:51:40.455091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-08-24 15:51:40.458643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10800 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:0e:00.0, compute capability: 3.7)
2021-08-24 15:51:40.555641: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2600245000 Hz
Analyzing data...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/evaluate_network.py", line 270, in evaluate_network
    deeplabcut.evaluate_network(
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate.py", line 778, in evaluate_network
    image = imread(
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/auxfun_videos.py", line 349, in imread
    return cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-f51eratu/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@LyleSmash - did you make the project with `2.2rc3`? and/or you should roll up to `2.2`, also, it fails to plot; do you have all the original images on this machine?

**Comment by LyleSmash** [comment]
I am not sure how to "roll up" or check which version I made the project with. However, the images were not in the server as you suggested. I reran a new training network but I came up with a similar error when running the evaluate network. Here is the code from the last iteration until running the evaluation. I am using an RTX5000 GPU during this session. The ending error is

 cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-f51eratu/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


Here is the code:
```
....
iteration: 499000 loss: 0.0005 lr: 0.002
iteration: 500000 loss: 0.0005 lr: 0.002
2021-08-26 01:53:51.254455: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 82, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[node fifo_queue_enqueue (defined at /site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py:68) ]]

Errors may have originated from an input operation.
Input Source operations connected to node fifo_queue_enqueue:
 Placeholder (defined at /site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py:60)	
 fifo_queue (defined at /site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py:67)

Original stack trace for 'fifo_queue_enqueue':
  File "/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/site-packages/deeplabcut/__main__.py", line 22, in <module>
    deeplabcut.launch_dlc()
  File "/site-packages/deeplabcut/gui/launch_script.py", line 46, in launch_dlc
    app.MainLoop()
  File "/site-packages/wx/core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "/site-packages/deeplabcut/gui/train_network.py", line 319, in train_network
    deeplabcut.train_network(
  File "/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 176, in train_network
    train(
  File "/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 171, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 68, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/site-packages/tensorflow/python/ops/data_flow_ops.py", line 344, in enqueue
    return gen_data_flow_ops.queue_enqueue_v2(
  File "/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4041, in queue_enqueue_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_Mouse_testAug25/Mouse_test_lyle95shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/gpfs/ysm/home/lm966/Mouse_test-lyle-2021-08-25/dlc-models/iteration-0/Mouse_testAug25-trainset95shuffle1/test/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Running  DLC_resnet50_Mouse_testAug25shuffle1_500000  with # of trainingiterations: 500000
2021-08-26 16:22:04.000021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Quadro RTX 5000 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 48 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 417.29GiB/s
2021-08-26 16:22:04.001302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-08-26 16:22:04.001354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-26 16:22:04.001364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-08-26 16:22:04.001388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-08-26 16:22:04.002550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14802 MB memory) -> physical GPU (device: 0, name: Quadro RTX 5000, pci bus id: 0000:3b:00.0, compute capability: 7.5)
Analyzing data...
0it [00:00, ?it/s]2021-08-26 16:22:05.648501: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-08-26 16:22:10.671134: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
19it [00:08,  2.17it/s]
Traceback (most recent call last):
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/evaluate_network.py", line 270, in evaluate_network
    deeplabcut.evaluate_network(
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate.py", line 778, in evaluate_network
    image = imread(
  File "/gpfs/ysm/project/gracheva/lm966/conda_envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/auxfun_videos.py", line 349, in imread
    return cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-f51eratu/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by backyardbiomech** [comment]
Your deeplabcut.yaml file says 2.2rc3. The best thing to try would be to do a fresh install of deeplabcut following the latest instructions (new yaml file). Remake your training data, retrain, and try to evaluate. 

However, the error you are seeing is because deeplabcut can’t find the proper images from the training dataset in the project folder on this computer.

**Comment by MMathisLab** [comment]
agree with @backyardbiomech it seems it cannot read the data; so either the drive is not accessible to the GPU or data is moved, etc!
