### ISSUE TITLE
Refine tracklets tab in main GUI fails to find pickle or h5 file

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#1489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

This is related to post on the [forum](https://forum.image.sc/t/labeled-video-without-the-whole-tracking-in-colab/57076/4) by another user, and the second issue raised in #1458 - but not the primary issue raised there so I'm creating a new issue. The forum post is from a mac (dlc version unknown), and I can reproduce on Windows, DLC 2.2.0.1.  

After analyzing video, creating tracklets, and stitching tracklets, trying to load the refine tracklets GUI from the main GUI leads to a file not found error. 

However, in the same env, the refine tracklets gui opens fine when called from the command line and passing the path to the h5 or pickle file directly. Therefore, the must be a problem in the automatic construction of the filename when the refine tracklets button is pushed in the main GUI.

### Operating System

Windows 10 (other posts suggest all platforms)

### DeepLabCut version

2.2.0.1

### DeepLabCut mode

multi animal

### Device type

N/A

### Steps To Reproduce

1. In an maDLC project, analyze a video, create tracklets, stitch tracklets
2. From the main Deeplabcut GUI, open the the Refine Tracklets tab
3. Select the video, click the "refine tracklets" button

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\gui\refine_tracklets.py", line 313, in refine_tracklets
    self.manager, self.viz = deeplabcut.refine_tracklets(
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 793, in refine_tracklets
    manager.load_tracklets_from_hdf(pickle_or_h5_file)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC22\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py", line 238, in load_tracklets_from_hdf
    df = pd.read_hdf(filename)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC22\lib\site-packages\pandas\io\pytables.py", line 427, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File  does not exist
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
After a quick review of the code, at some point between 2.2rc3 and 2.2.0, the "select data file" [functions](https://github.com/DeepLabCut/DeepLabCut/blob/f75daf5464571f46285de0523517afb7e17025f7/deeplabcut/gui/refine_tracklets.py#L75) were removed from the GUI. However, I don't see any code that allows for automatic path creation to find the data files. As a result, `self.datafile` remains an empty string when it's passed to `refine_tracklets`.

For now, for current users, calling `refine_tracklets` from the command line is functional.
