### ISSUE TITLE
FileNotFoundError: It seems the model for shuffle 1 and trainFraction 0.95 does not exist.

### ISSUE THREAD

**Issue by Dvirbs** [DeepLabCut/DeepLabCut#1494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am using Windows 10 with Anaconda Env, DLC 2.1.8.2 .
I trained a 3D network and when I was planning to use it on a new video i got the next two errors:
1)
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\Experiment_Project\\2D_cam1-Dvir-2021-03-12\\dlc-models\\iteration-0\\2D_cam1Mar12-trainset95shuffle1\\test\\pose_cfg.yaml'`
2)
`FileNotFoundError: It seems the model for shuffle 1 and trainFraction 0.95 does not exist.`

This is the code I am using:
`config_path3d = r"C:\Users\Owner\Desktop\Dvir\DvirDLC\projects\3DProject_try#32-Dvir-2021-03-11-3d\config.yaml"`
`deeplabcut.triangulate(config_path3d, r"C:\Users\Owner\Desktop\Dvir\DvirDLC\P_Experiment\analysis_lib\1304_3D", filterpredictions=True,save_as_csv=True)`

Also, I checked the folder at the model and it seems to be correctly created:
![image](https://user-images.githubusercontent.com/71714798/131995961-2034d395-6fbc-4340-bf26-11f1aebb1e61.png)

*Also, I set the config.yaml file path and the video path to be the full path formatted for windows.*

The code:

```
(dlc-windowsGPU) C:\Users\Owner>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
>>> config_path3d = r"C:\Users\Owner\Desktop\Dvir\DvirDLC\projects\3DProject_try#32-Dvir-2021-03-11-3d\config.yaml"
>>> deeplabcut.triangulate(config_path3d, r"C:\Users\Owner\Desktop\Dvir\DvirDLC\P_Experiment\analysis_lib\1304_3D", filterpredictions=True,save_as_csv=True)
List of pairs: [['C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail1-camera-1.avi', 'C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail1-camera-2.avi'], ['C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail2-camera-1.avi', 'C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail2-camera-2.avi'], ['C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail3-camera-1.avi', 'C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail3-camera-2.avi'], ['C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail4-camera-1.avi', 'C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\P_Experiment\\analysis_lib\\1304_3D\\nana-300321-trail4-camera-2.avi']]
Analyzing video C:\Users\Owner\Desktop\Dvir\DvirDLC\P_Experiment\analysis_lib\1304_3D\nana-300321-trail1-camera-1.avi using config_file_camera-1
Traceback (most recent call last):
  File "C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 142, in analyze_videos
    dlc_cfg = load_config(str(path_test_config))
  File "C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\config.py", line 56, in load_config
    return cfg_from_file(filename)
  File "C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\config.py", line 42, in cfg_from_file
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Owner\\Desktop\\Dvir\\DvirDLC\\Experiment_Project\\2D_cam1-Dvir-2021-03-12\\dlc-models\\iteration-0\\2D_cam1Mar12-trainset95shuffle1\\test\\pose_cfg.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py", line 202, in triangulate
    destfolder=destfolder)
  File "C:\Users\Owner\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 144, in analyze_videos
    raise FileNotFoundError("It seems the model for shuffle %s and trainFraction %s does not exist."%(shuffle,trainFraction))
FileNotFoundError: It seems the model for shuffle 1 and trainFraction 0.95 does not exist.
>>>


```

config file 3D:
![image](https://user-images.githubusercontent.com/71714798/131997550-baff67dc-5be3-4808-aaf8-6d6c748a7706.png)

config file 2D:
camera-1
![image](https://user-images.githubusercontent.com/71714798/131997737-7f7c8903-5af7-4e1d-bfab-636920c8f371.png)

camera-2
![image](https://user-images.githubusercontent.com/71714798/131997649-e56c7ef2-714d-406e-b143-93e0edba3e9b.png)

Thank you for your help!

### Operating System

operating system

### DeepLabCut version

Windows 10 with Anaconda Env, DLC 2.1.8.2 .

### DeepLabCut mode

3d

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Dvirbs** [comment]
I found my problems on the path.
Thank you
