### ISSUE TITLE
module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'

### ISSUE THREAD

**Issue by ramonhollands** [DeepLabCut/DeepLabCut#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to get deeplabcut up and running in a tensorflow docker container, using:
-docker pull tensorflow/tensorflow  
-docker run -it tensorflow/tensorflow bash

After pip installing deeplabcut using:
- python -m pip install --upgrade pip
- pip install deeplabcut

I get the following error when importing deeplabcut:
- python
- import deeplabcut

root@aef6fcfb9ca6:/# python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
2021-09-12 09:29:16.581626: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-12 09:29:16.581711: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py", line 46, in <module>
    from deeplabcut.create_project import (
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/create_project/__init__.py", line 2, in <module>
    from deeplabcut.create_project.demo_data import load_demo_data
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/create_project/demo_data.py", line 15, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/__init__.py", line 4, in <module>
    from deeplabcut.utils.conversioncode import *
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/conversioncode.py", line 16, in <module>
    from deeplabcut.generate_training_dataset import trainingsetmanipulation
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 15, in <module>
    from deeplabcut.pose_estimation_tensorflow.core.train import *
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 29, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnets import PoseNetFactory
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/__init__.py", line 15, in <module>
    from .efficientnet import PoseEfficientNet
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/efficientnet.py", line 20, in <module>
    import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_builder as eff
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/backbones/efficientnet_builder.py", line 20, in <module>
    import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_model as efficientnet_model
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/backbones/efficientnet_model.py", line 25, in <module>
    import deeplabcut.pose_estimation_tensorflow.nnets.utils as utils
AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'

### Operating System

Tensorflow docker

### DeepLabCut version

dlc version

### DeepLabCut mode

multi animal

### Device type

Both cpu/gpu

### Steps To Reproduce

See description

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
I'm not sure that's related but you'll need to install python 3.7 at least. There are also instructions to build (old) DeepLabCut Docker containers here https://github.com/stes/deeplabcut-docker; I guess they can be slightly modified to pull the latest dlc :)

**Comment by ramonhollands** [comment]
Thanks for your quick response, Ill try python37 and the old docker-containers

**Comment by verrassendhollands** [comment]
Upgrading to python37 solves this issue. Thanks again.
