### ISSUE TITLE
No package 'gtk+-3.0' found

### ISSUE THREAD

**Issue by lsainzvillalba** [DeepLabCut/DeepLabCut#1521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description FAILURE AT INSTALLATION OF DEEPLABCUT

After creating the conda environment , I call pip install deeplabcut and it installs a dlc lite version without gui. If instead I run pip install 'deeplabcut[gui]' it continously fail to build wheel for wxpython. I have checked the nvidia-smi and I have driver version of 390.144 and also the nvcc version cuda complier which is 9.0.176. I also tried downloading manually the wxpython and installing it but it still reproduces the same error, even with different downloaded wheels of wxpython.

### Operating System

operating system
ubuntu 18.04.3 lts 64bit
python 3.8.12 

### DeepLabCut version

dlc version  deeplabcut -2.2.0.2

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce
````python
conda activate DEEPLABCUT
(DEEPLABCUT) ~~ pip install deeplabcut
succesfully installed deeplabcut -2.2.0.2
(DEEPLABCUT) ~~ python3
>> import deeplabcut

2021-09-29 14:45:04.565941: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-9.0/lib64:
2021-09-29 14:45:04.565963: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)

(DEEPLABCUT) ~~ pip uninstall deeplabcut
(DEEPLABCUT) ~~ pip install deeplabcut[gui]
...
  Building wheel for wxpython (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/anaconda3/envs/DEEPLABCUT/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4wjj2twj
       cwd: /tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/
  Complete output (413 lines):
  /home/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  /home/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/setuptools/dist.py:294: DistDeprecationWarning: use_2to3 is ignored.
    warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
  running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.
  
  "/home/anaconda3/envs/DEEPLABCUT/bin/python3.8" -u build.py build
  Will build using: "/home/anaconda3/envs/DEEPLABCUT/bin/python3.8"
  3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 02:08:29)
  [GCC 9.4.0]
  Python's architecture is 64bit
  cfg.VERSION: 4.0.7.post2
  
  Running command: build
  Running command: build_wx
  wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
  Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
  /tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
 
  
 ...
    checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gtk+-3.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gtk+-3.0' found
    no
    *** Could not run GTK+ test program, checking why...
    *** The test program failed to compile or link. See the file config.log for the
    *** exact error that occured. This usually means GTK+ is incorrectly installed.
    configure: error:
    The development files for GTK+ were not found. For GTK+ 2, please
    ensure that pkg-config is in the path and that gtk+-2.0.pc is
    installed. For GTK+ 1.2 please check that gtk-config is in the path,
    and that the version is 1.2.3 or above. Also check that the
    libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
    --libs' are in the LD_LIBRARY_PATH or equivalent.
    
    Error running configure
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "build.py", line 1468, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/buildtools/build_wxwidgets.py", line 371, in main
        exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
      File "/tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    buildtools.builder.BuildError: Error running configure
    Finished command: build_wx (0m6.93s)
    Finished command: build (0m6.93s)
    Command '"/home/lsainz/anaconda3/envs/DEEPLABCUT/bin/python3.8" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/anaconda3/envs/DEEPLABCUT/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kzplujud/wxpython_200c0a10503f4334b5cb1b58ef05ef9e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-oungmzw8/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda3/envs/DEEPLABCUT/include/python3.8/wxpython Check the logs for full command output.
````

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@lsainzvillalba the error suggest you do not have the standard gtk+ package on your ubuntu:

If you do as the error message says, does that help?
```python
    checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gtk+-3.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gtk+-3.0' found
```

also please note, the conda already had deeplabcut installed, you don't need to run this again: 

> After creating the conda environment , I call pip install deeplabcut and it installs a dlc lite version without gui. If instead I run pip install 'deeplabcut[gui]' it continously fail to build wheel for wxpython.

See the conda file here for what is installed:https://github.com/DeepLabCut/DeepLabCut/blob/master/conda-environments/DEEPLABCUT.yaml

And here for what we recommend for Ubuntu users: https://deeplabcut.github.io/DeepLabCut/docs/installation.html#creating-your-own-customized-conda-env-recommended-route-for-linux-ubuntu-centos-mint-etc

and fresh install for ubuntu users:

https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#next-deeplabcut

which points to:

`sudo apt install libcanberra-gtk-module libcanberra-gtk3-module` 

^ this is likely all you need, then just use the conda, don't re-install DLC within it. Hope that helps.

**Comment by lsainzvillalba** [comment]
Thank you for the prompt reply. I tried sudo apt install libcanberra-gtk-module libcanberra-gtk3-module but it did not work. I decided to do a fresh installation  and I had the error appearing in https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html so I followed that instructions and now it is working. Thank you!
