### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ranjitkathiriya** [DeepLabCut/DeepLabCut#1527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In GUI, at the time of training, I am getting below error. 

### Operating System

Ubuntu 20.04

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

GPU

### Steps To Reproduce

Config error

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/kuka-ai/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/train_network.py", line 319, in train_network
    deeplabcut.train_network(
  File "/home/kuka-ai/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 134, in train_network
    cfg["TrainingFraction"][trainingsetindex], shuffle, cfg, modelprefix=modelprefix
  File "/home/kuka-ai/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/ruamel/yaml/compat.py", line 217, in __getitem__
    return self.__getsingleitem__(index)
  File "/home/kuka-ai/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/ruamel/yaml/comments.py", line 527, in __getsingleitem__
    return list.__getitem__(self, idx)
IndexError: list index out of range
```

### Anything else?

My config file:

```
    # Project definitions (do not edit)
Task: CowMobilityscore
scorer: Ranjit
date: Oct6
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: /home/kuka-ai/Desktop/CowMobilityscore-Ranjit-2021-10-06

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /home/kuka-ai/Desktop/cowdata/IMG_6833.MP4:
    crop: 0, 1920, 0, 1080
  /home/kuka-ai/Desktop/cowdata/IMG_6837.MP4:
    crop: 0, 1920, 0, 1080
  /home/kuka-ai/Desktop/cowdata/IMG_6838.MP4:
    crop: 0, 1920, 0, 1080
  /home/kuka-ai/Desktop/cowdata/IMG_6839.MP4:
    crop: 0, 1920, 0, 1080
bodyparts:
- bodypart1
- bodypart2
- bodypart3
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton:
- - bodypart1
  - bodypart2
  - bodypart3
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@ranjitkathiriya your skeleton is incorrectly formated:

```
- - bodypart1
  - bodypart2
  - bodypart3
```

please see the docs, you can only connect one node to one node.

**Comment by ranjitkathiriya** [comment]
Thanks for the help! If possible can you please provide a reference for that documents?

I also was getting this error while training: Allocation of 127401984 exceeds 10% of free system memory.
