### ISSUE TITLE
Installing deeplabcut-docker on ubuntu20 - Failed to launch the DLC GUI; `as 'headless' is currently running`

### ISSUE THREAD

**Issue by albesagonzalez** [DeepLabCut/DeepLabCut#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have been trying to install DLC on ubuntu 20.04 and got the same error every trial.

After installing DLC with docker, when I run

deeplabcut-docker gui

It is able to complete all the pulls, and then at this point

`Status: Downloaded newer image for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2021-10-13T15:14:20-0400]: Configuring a local container for user USER(1000) in group GROUP (1000)
sha256:9c1223084ebac1ca13599ea183cbdac776d7aee4c12b53df3228a0b226dc75a1
[2021-10-13T15:15:02-0400]: Build succeeded
[2021-10-13T15:15:02-0400]: Using Linux config
2021-10-13 19:15:04.360495: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
`

I get the error (see LOG for trace)
```
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2021-10-13T15:15:07-0400]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/USER:/app -w /app "
Container stopped.
```

I have tried both installing and not installing conda first and got same error.

### Operating System

Ubuntu 20.04

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Install Ubuntu 20.04 (fresh)
2. Go to settings, software update, additional drivers, NVIDIA driver metapackage from nvidia-driver-470
3. Install CUDA 11.4 and cuDNN 8 following the steps in
https://medium.com/@stephengregory_69986/installing-cuda-10-1-on-ubuntu-20-04-e562a5e724a0
(the steps are for cuda 10.1, but I installed 11.4)
4. Install docker following the steps in 
https://phoenixnap.com/kb/install-docker-on-ubuntu-20-04
(option 1, steps 1 to 6 and then those in section Run Docker Commands Without Sudo)
5.Install DLC using docker (pip install deeplabcut-docker)
6.Install DLC gui deeplabcut-docker gui

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 27, in <module>
    from deeplabcut import generate_training_dataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    from .pose_deterministic import DeterministicPoseDataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    from deeplabcut.utils.auxfun_videos import imread, imresize
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2021-10-13T15:15:07-0400]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/USER:/app -w /app "
Container stopped.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by stes** [comment]
Hello @albertalbesa , thanks a lot for raising this issue.

First, could you let me know whether:
1. You run the application locally on a desktop machine, i.e., with a monitor connected to it
2. You run the application on a remote (headless) server and want to use X forwarding

Assuming that the answer is (1), to better understand your system setup, could you provide the outputs of running the following commands:

``` bash
cat /etc/gdm3/custom.conf | grep WaylandEnable
echo $XDG_SESSION_TYPE
echo $DISPLAY
```

Thanks a lot!

/Steffen

**Comment by heejaeyunajang** [comment]
Also running into the same issue :( export light doesn't solve the problem.

**Comment by stes** [comment]
Hello @heejaeyunajang , could you please also provide some info regarding my questions above, and let me know the outputs of the three commands I posted?

Thanks a lot!

**Comment by albesagonzalez** [comment]
Hi @stes !

Thank you for the support. By the time of your response I had already solved it by following the steps in 

https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#installation-on-ubuntu-20-04-lts

for the drivers installation and then used Docker. Do you think there is some test I can run that might be useful to isolate the issue without uninstalling DLC? If so I will be happy to do it.  

@heejaeyunajang you might also want to try if that works for you

**Comment by MMathisLab** [comment]
hey @albertalbesa could you just clarify what the solution was / if you don't mind answering @stes questions, it would be helpful for us.
