### ISSUE TITLE
Jupyter Notebook MacOS kernel crash

### ISSUE THREAD

**Issue by sg-s** [DeepLabCut/DeepLabCut#1544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Kernel dies when I run 

```
import deeplabcut
```

### Operating System

macOS 11.6

### DeepLabCut version

```
deeplabcut==2.2.0.2
```

### DeepLabCut mode

single animal

### Device type

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

### Steps To Reproduce

1. Install using the conda YAML file
2. Switch to that environment
3. Start a Jupyter notebook
4. Try `import deeplabcut`

It fails, and the kernel restarts. No error messages are printed to notebook

### Relevant log output

```shell
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fbb7847d4f0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fbb7847d4f0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-4' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /kernel...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/jupyter_client/manager.py:332>> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fbb7849a4c0>(<Future finis...uest\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fbb7849a4c0>(<Future finis...uest\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-5' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...quest\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/jupyter_client/manager.py:336>> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fbbb87de940>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fbbb87de940>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-6' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /nbexte...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-1' coro=<MultiKernelManager._async_start_kernel() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py:186>> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fbbb87def10>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fbbb87def10>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-7' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /nbexte...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-50' coro=<MappingKernelManager.start_kernel() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/ioloop.py:688]> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fbba8c8d430>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fbba8c8d430>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-8' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /static...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-50' coro=<MappingKernelManager.start_kernel() running at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tornado/ioloop.py:688]> is being executed.
[I 14:52:30.588 NotebookApp] Kernel started: 9d91cb57-34fa-410a-8f42-ee917d2d31f2, name: conda-env-DEEPLABCUT-py
/Users/srinivas/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 14:53:00.634 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20211015145219 (::1) 10.000000ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=conda-env-DEEPLABCUT-py
[I 14:53:27.587 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
```

### Anything else?

Similar to https://github.com/DeepLabCut/DeepLabCut/issues/1102

which has been closed without resolution 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@sg-s -- the original poster closed it, thus we can only assume they resolved it. Also, in general if it's the same issue, please post with that post ;) hence the task to say you searched and couldn't find anything. 

Note, on macOS unless you specifically edited this, Notebooks are not supported, as you need a framework build of DLC: file.https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md#option-1-demo-notebooks

You are welcome to use the docker notebook image though, which does support this on MacOS now: https://github.com/DeepLabCut/DeepLabCut/tree/master/docker
