### ISSUE TITLE
Skipping cancelled enqueue attempt with queue not closed

### ISSUE THREAD

**Issue by heejaeyunajang** [DeepLabCut/DeepLabCut#1557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

training doesn't start with "Skipping cancelled enqueue attempt with queue not closed" error.

### Operating System

Ubuntu 18.0.4

### DeepLabCut version

2.2.0.1

### DeepLabCut mode

single animal

### Device type

NVIDIA Quadro RTX 8000

### Steps To Reproduce

I'm running on a high performance computing cluster. 
I am able to do initial training with the resnet50 as the initial weight, but when I try to retrain with the initial weight to the previously trained snapshot, I get the following error. But I'm not sure if it has to do with the initial weights or not.

### Relevant log output

```shell
GPU (device: 0, name: NVIDIA Quadro RTX 8000, pci bus id: 0000:06:00.0, compute capability: 7.5)
2021-10-22 14:41:51.323882: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-10-22 14:41:57.964512: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-10-22 14:42:01.299352: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 82, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[node fifo_queue_enqueue (defined at /ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py:68) ]]

Errors may have originated from an input operation.
Input Source operations connected to node fifo_queue_enqueue:
 Placeholder_1 (defined at /ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py:60)	
 fifo_queue (defined at /ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py:67)

Original stack trace for 'fifo_queue_enqueue':
  File "train.py", line 8, in <module>
    dlc.train_network(sys.argv[1])
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 176, in train_network
    train(
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 171, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 68, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/ops/data_flow_ops.py", line 344, in enqueue
    return gen_data_flow_ops.queue_enqueue_v2(
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4026, in queue_enqueue_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3319, in _create_op_internal
    ret = Operation(
  File "/ext3/deeplabcut-2.2.0.1/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

Selecting single-animal trainer
Batch Size is 1
Loading already trained DLC with backbone: resnet_50
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/scratch/cmc472/DLC-projects/GRAB_DA_DMS_RIG104_J005_J010-HJ-2021-10-12/dlc-models/iteration-2/GRAB_DA_DMS_RIG104_J005_J010Oct12-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6]], 'all_joints_names': ['portR', 'portC', 'portL', 'earR', 'nose', 'earL', 'tailbase'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-2/UnaugmentedDataSet_GRAB_DA_DMS_RIG104_J005_J010Oct12/GRAB_DA_DMS_RIG104_J005_J010_HJ95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 250, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': '/scratch/cmc472/DLC-projects/GRAB_DA_DMS_RIG104_J005_J010-HJ-2021-10-12/dlc-models/iteration-1/GRAB_DA_DMS_RIG104_J005_J010Oct12-trainset95shuffle1/train/snapshot-1030000', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets/iteration-2/UnaugmentedDataSet_GRAB_DA_DMS_RIG104_J005_J010Oct12/Documentation_data-GRAB_DA_DMS_RIG104_J005_J010_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 7, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': '/scratch/cmc472/DLC-projects/GRAB_DA_DMS_RIG104_J005_J010-HJ-2021-10-12', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 1000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AlexEMG** [comment]
I think that's the expected behavior, as it reaches the number of trained frames and stops. Can you please increase the training iterations to verify?

**Comment by jeylau** [comment]
I agree with @AlexEMG; I could reproduce it. Retraining from a previous snapshot no longer resets the iteration counter (since #1395), so make sure you increase `maxiters` when calling `train_network` 😊

**Comment by heejaeyunajang** [comment]
@jeylau I increased maxiters to 3000000 (previous iteration ended at 1030000) but it still overwrites max_iters to 1030000 and doesn't start training. Is 1030000 the absolute threshold? If I want to use previous weights, what should I do then?

**Comment by Guillermo-Hidalgo-Gadea** [comment]
I am having the same problem as @heejaeyunajang, my pretrained model already has a `snapshot-1030000`, and increasing  `maxiters` does not seem to help. 
Can I roll back to a specific deeplabcut release previous to  #1395 to keep re-training this snapshot with new outlier frames?    
I am using `deeplabcut=2.2.0.3`.

**Comment by jeylau** [comment]
Hey @Guillermo-Hidalgo-Gadea, `max_iters` is automatically capped to the max # of iterations defined in the dlc-models/.../train/pose_cfg.yaml config file. 
https://github.com/DeepLabCut/DeepLabCut/blob/1a02aa311c17e691eeacedf8ccd5c95866dd6ef2/deeplabcut/pose_estimation_tensorflow/core/train.py#L238
So the solution is to also manually edit that value yourself; e.g.:
```
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 2000000
```
would allow you to train up to 2M iterations.
I hope that helps 😃

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi @jeylau thank you for the incredibly fast reply!    
Changing the `multi_step:` value in the `pose_cfg:yaml` together with `maxiters` in `deeplabcut.train_network()` worked and the model is now (re-)training 😃
