### ISSUE TITLE
`TypeError: 'NoneType' object is not subscriptable` & `failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`

### ISSUE THREAD

**Issue by MohammadKhorshidi4** [DeepLabCut/DeepLabCut#1599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

We weren't using DLC for a while because our system went off. When we wanted to use it again, it gives us an error and didn't and stopped in the start training position.
The error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 80, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 363, in next_batch
    ) = self.get_batch()
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 298, in get_batch
    image = imread(os.path.join(self.cfg["project_path"], im_file), mode="RGB")
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/utils/auxfun_videos.py", line 349, in imread
    return cv2.imread(path)[..., ::-1]  # ~10% faster than using cv2.cvtColor
TypeError: 'NoneType' object is not subscriptable

### Operating System

operating system= CentOS Linux V. 7 (Core)

### DeepLabCut version

dlc version =2.2

### DeepLabCut mode

single animal

### Device type

gpu = RTX 2080 Ti

### Relevant log output

```shell
deeplabcut.train_network(config_path,shuffle=1,trainingsetindex=0,gputouse=1,max_snapshots_to_keep=5, displayiters=10,saveiters=100,maxiters=1000)
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]],
 'all_joints_names': ['LeftEye',
                      'LeftEyelid',
                      'RightEyelid',
                      'RightEye',
                      'UnderNose',
                      'RightLip',
                      'LeftLip',
                      'Chin',
                      'UpperLip',
                      'LowerLip'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'crop_sampling': 'hybrid',
 'crop_size': [400, 400],
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_FACIALTRAIN1Nov24/FACIALTRAIN1_MEHRANMANI95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': '/workspace14/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'max_shift': 0.4,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_FACIALTRAIN1Nov24/Documentation_data-FACIALTRAIN1_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 10,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'pre_resize': [],
 'project_path': '/workspace14/FACIALTRAIN1-MEHRANMANI-2021-11-24',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': '/workspace14/FACIALTRAIN1-MEHRANMANI-2021-11-24/dlc-models/iteration-0/FACIALTRAIN1Nov24-trainset95shuffle1/train/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
2021-12-03 15:10:19.241970: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-12-03 15:10:19.250119: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-12-03 15:10:19.250146: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: gpunode1
2021-12-03 15:10:19.250155: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: gpunode1
2021-12-03 15:10:19.250344: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 455.23.5
2021-12-03 15:10:19.250373: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 455.23.5
2021-12-03 15:10:19.250408: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 455.23.5
Loading ImageNet-pretrained resnet_50
2021-12-03 15:10:19.504462: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-12-03 15:10:19.513403: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3600000000 Hz
2021-12-03 15:10:19.514493: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x808f7b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-12-03 15:10:19.514509: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 80, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 363, in next_batch
    ) = self.get_batch()
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 298, in get_batch
    image = imread(os.path.join(self.cfg["project_path"], im_file), mode="RGB")
  File "/home/engbrain1/.local/lib/python3.8/site-packages/deeplabcut/utils/auxfun_videos.py", line 349, in imread
    return cv2.imread(path)[..., ::-1]  # ~10% faster than using cv2.cvtColor
TypeError: 'NoneType' object is not subscriptable
Max_iters overwritten as 1000
Display_iters overwritten as 10
Save_iters overwritten as 100
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/workspace14/FACIALTRAIN1-MEHRANMANI-2021-11-24/dlc-models/iteration-0/FACIALTRAIN1Nov24-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]], 'all_joints_names': ['LeftEye', 'LeftEyelid', 'RightEyelid', 'RightEye', 'UnderNose', 'RightLip', 'LeftLip', 'Chin', 'UpperLip', 'LowerLip'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_FACIALTRAIN1Nov24/FACIALTRAIN1_MEHRANMANI95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': '/workspace14/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_FACIALTRAIN1Nov24/Documentation_data-FACIALTRAIN1_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 10, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': '/workspace14/FACIALTRAIN1-MEHRANMANI-2021-11-24', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @mehrankhorshidi, this error from opencv indicates that an image defined in your training dataset is not found at its original location (most likely because it got deleted, or make sure the "project_path" in your config.yaml file is correct). Also note the CUDA error higher up in the traceback; it is unrelated but there may be something wrong with your GPU (if you have one).

**Comment by MMathisLab** [comment]
Re the GPU part:

`failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected` 

it cannot find your GPU, which you overwrite, set to 1 (which would mean you have 2 GPUs, indexing starts at 0 and that is why we set default to 0 :). 

`gputouse=1`

**Comment by MohammadKhorshidi4** [comment]
Thank you for your answers, It helps a lot.
