### ISSUE TITLE
`Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:` [duplicate issue]

### ISSUE THREAD

**Issue by frankiechang123** [DeepLabCut/DeepLabCut#1623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In a running docker build upon the image `deeplabcut/deeplabcut:latest-gui-jupyter`, importing deeplabcut gives the error message `Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running`

### Operating System

WSL2 with Ubuntu-20.04
Docker version 20.10.11

### DeepLabCut version

`pip list | grep deeplabcut` gives `2.2.0.2`.

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1. `docker pull deeplabcut/deeplabcut:latest-gui-jupyter`
2. start the container building upon the image
3. `ipython`
4. `import deeplabcut`

### Relevant log output

```shell
In [9]: import deeplabcut
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py in <module>
     24     import wx
     25
---> 26     mpl.use("WxAgg")
     27     from deeplabcut import generate_training_dataset
     28     from deeplabcut import refine_training_dataset

/usr/local/lib/python3.8/dist-packages/matplotlib/__init__.py in use(backend, force)
   1078                 # user does not have the libraries to support their
   1079                 # chosen backend installed.
-> 1080                 plt.switch_backend(name)
   1081             except ImportError:
   1082                 if force:

/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    283         if (current_framework and required_framework
    284                 and current_framework != required_framework):
--> 285             raise ImportError(
    286                 "Cannot load backend {!r} which requires the {!r} interactive "
    287                 "framework, as {!r} is currently running".format(

ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @frankiechang123 can you please describe how you installed it; if you used the pip install deeplabcut-docker you will get the gui version wrapped as needed; i.e.. follow here:https://deeplabcut.github.io/DeepLabCut/docs/docker.html

as an aside:
`pip install deeplabcut` is the headless version; `pip install deeplabcut[gui]` is the GUI version. 
also see this issue: https://github.com/DeepLabCut/DeepLabCut/issues/1618

**Comment by frankiechang123** [comment]
Thank you for your reply!

I tried to directly pull the image and create a container in hope that I could use the deeplabcut package as normal inside the container, but it gives the error message as above when I import it in python.

I also tried using the `deeplabcut-docker` tool, as you suggested, but it gives a similar error message when I run `deeplabcut-docker gui`:

```
$ deeplabcut-docker gui

                    .--,       .--,
                    ( (  \.---./  ) )
                     '.__/o   o\__.'
                       `{=  ^  =}´
                         >  u  <
 ____________________.""`-------`"".______________________
\   ___                   __         __   _____       __  /
/  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
\ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
//____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
\_________________________________________________________/
                       ___)( )(___ `-.___.
                      (((__) (__)))      ~`

Welcome to DeepLabCut docker!

latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2021-12-23T11:40:52-0800]: Configuring a local container for user frankiechang123 (1000) in group frankiechang123 (1000)
sha256:c64dec3e371ad599c73f3f2f5ce7cb27678156256f16e56c84639b93905c6c0a
[2021-12-23T11:40:52-0800]: Build succeeded
[2021-12-23T11:40:52-0800]: Using Linux config
2021-12-23 19:40:57.243368: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 27, in <module>
    from deeplabcut import generate_training_dataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    from .pose_deterministic import DeterministicPoseDataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    from deeplabcut.utils.auxfun_videos import imread, imresize
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2021-12-23T11:41:00-0800]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/frankiechang123:/app -w /app "
Container stopped.
```

**Comment by MMathisLab** [comment]
hi @frankiechang123 but this: `Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/frankiechang123:/app -w /app "
Container stopped.` is the same error message as the other issue I linked; the solutions are:

(1) are you running this without a screen? / virtual machine / remote? that won't likely work. 
(2) you need to enable xhost, from the other post, you need to run:

`echo $DISPLAY`
`xhost + $IP`

and post the result: i.e., see here: https://github.com/DeepLabCut/DeepLabCut/issues/1618#issuecomment-997114388, then I can help ;)

**Comment by frankiechang123** [comment]
I'm attempting to run this on Ubuntu WSL2 in Windows. I was able to connect WSL2 to a X server on Windows, and `echo $DISPLAY` gives `172.18.96.1:0.0`, `xhost + $IP` gives `access control disabled, clients can connect from any host`.

Then running `deeplabcut-docker gui` gives:
```
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2021-12-27T15:25:20-0800]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix172.18.96.1:0.0 -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/frankiechang123:/app -w /app "
Container stopped.
```

Currently, my WSL2 is able to run GUI applications(like firefox etc.) From my understanding, all the DLC GUI container needs to do is just to connect its GUI application to the display, right? Is there something else I could try?

Thank you!

**Comment by MMathisLab** [comment]
sorry for delay, yes, that is true, but setting the IP for the screen might be harder; I have no exp. in a linux sim. windows, case, sorry!
