### ISSUE TITLE
Problems with wxPython not allowing deeplabcut[gui] install on Windows 10

### ISSUE THREAD

**Issue by CorinneAKelly** [DeepLabCut/DeepLabCut#1645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to do a new install of DLC with the GUI, and every time I try I get an error that prevents installation. Every other topic I can find where someone had this issue seems to be Linux/Ubuntu specific, but I am on Windows 10.

### Operating System

Windows 10

### DeepLabCut version

(trying to install the latest one, not successful yet)

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

In anaconda environment:
`pip install deeplabcut[gui]`

Everything goes smoothly until the code below.

### Relevant log output

```shell
Building wheels for collected packages: wxpython
  Building wheel for wxpython (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ckelly\Anaconda3\envs\dlc\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ckelly\\AppData\\Local\\Temp\\pip-install-l5f7lqo0\\wxpython_7860fedbfb274deb8a567c6351fd0ef4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ckelly\\AppData\\Local\\Temp\\pip-install-l5f7lqo0\\wxpython_7860fedbfb274deb8a567c6351fd0ef4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ckelly\AppData\Local\Temp\pip-wheel-3rpx0zve'
       cwd: C:\Users\ckelly\AppData\Local\Temp\pip-install-l5f7lqo0\wxpython_7860fedbfb274deb8a567c6351fd0ef4\
  Complete output (37 lines):
  C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\setuptools\dist.py:294: DistDeprecationWarning: use_2to3 is ignored.
    warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
  running bdist_wheel
  running build
  Will build using: "C:\Users\ckelly\Anaconda3\envs\dlc\python.exe"
  3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
  Python's architecture is 64bit
  cfg.VERSION: 4.0.7.post2

  Running command: build
  Running command: build_wx
  Command '"C:\Users\ckelly\Anaconda3\envs\dlc\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
  Traceback (most recent call last):

    File "<string>", line 1, in <module>

    File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\distutils\msvc9compiler.py", line 371, in initialize

      vc_env = query_vcvarsall(VERSION, plat_spec)

    File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\distutils\msvc9compiler.py", line 260, in query_vcvarsall

      raise DistutilsPlatformError("Unable to find vcvarsall.bat")

  distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
  Finished command: build_wx (0.676s)
  Finished command: build (0.677s)
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.

  "C:\Users\ckelly\Anaconda3\envs\dlc\python.exe" -u build.py build
  Command '"C:\Users\ckelly\Anaconda3\envs\dlc\python.exe" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxpython
  Running setup.py clean for wxpython
Failed to build wxpython
Installing collected packages: wxpython, deeplabcut
  Attempting uninstall: wxpython
    Found existing installation: wxpython 4.1.1
    Uninstalling wxpython-4.1.1:
      Successfully uninstalled wxpython-4.1.1
    Running setup.py install for wxpython ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ckelly\Anaconda3\envs\dlc\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ckelly\\AppData\\Local\\Temp\\pip-install-l5f7lqo0\\wxpython_7860fedbfb274deb8a567c6351fd0ef4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ckelly\\AppData\\Local\\Temp\\pip-install-l5f7lqo0\\wxpython_7860fedbfb274deb8a567c6351fd0ef4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ckelly\AppData\Local\Temp\pip-record-1qpwb9xz\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ckelly\Anaconda3\envs\dlc\Include\wxpython'
         cwd: C:\Users\ckelly\AppData\Local\Temp\pip-install-l5f7lqo0\wxpython_7860fedbfb274deb8a567c6351fd0ef4\
    Complete output (37 lines):
    C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      warnings.warn(
    C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\setuptools\dist.py:294: DistDeprecationWarning: use_2to3 is ignored.
      warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
    running install
    running build
    Will build using: "C:\Users\ckelly\Anaconda3\envs\dlc\python.exe"
    3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
    Python's architecture is 64bit
    cfg.VERSION: 4.0.7.post2

    Running command: build
    Running command: build_wx
    Command '"C:\Users\ckelly\Anaconda3\envs\dlc\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\distutils\msvc9compiler.py", line 371, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)

      File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\distutils\msvc9compiler.py", line 260, in query_vcvarsall

        raise DistutilsPlatformError("Unable to find vcvarsall.bat")

    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
    Finished command: build_wx (0.696s)
    Finished command: build (0.696s)
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "C:\Users\ckelly\Anaconda3\envs\dlc\python.exe" -u build.py build
    Command '"C:\Users\ckelly\Anaconda3\envs\dlc\python.exe" -u build.py build' failed with exit code 1.
    ----------------------------------------
  Rolling back uninstall of wxpython
  Moving to c:\users\ckelly\anaconda3\envs\dlc\lib\site-packages\wx
   from C:\Users\ckelly\Anaconda3\envs\DLC\Lib\site-packages\~x
  Moving to c:\users\ckelly\anaconda3\envs\dlc\lib\site-packages\wxpython-4.1.1-py3.9.egg-info
   from C:\Users\ckelly\Anaconda3\envs\DLC\Lib\site-packages\~xpython-4.1.1-py3.9.egg-info
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\helpviewer-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\helpviewer-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\helpviewer.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\helpviewer.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\img2png-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\img2png-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\img2png.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\img2png.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\img2py-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\img2py-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\img2py.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\img2py.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\img2xpm-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\img2xpm-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\img2xpm.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\img2xpm.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pycrust-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pycrust-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pycrust.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pycrust.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pyshell-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pyshell-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pyshell.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pyshell.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pyslices-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pyslices-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pyslices.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pyslices.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pyslicesshell-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pyslicesshell-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pyslicesshell.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pyslicesshell.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pywxrc-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pywxrc-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\pywxrc.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\pywxrc.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\wxdemo-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\wxdemo-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\wxdemo.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\wxdemo.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\wxdocs-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\wxdocs-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\wxdocs.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\wxdocs.exe
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\wxget-script.py
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\wxget-script.py
  Moving to c:\users\ckelly\anaconda3\envs\dlc\scripts\wxget.exe
   from C:\Users\ckelly\AppData\Local\Temp\pip-uninstall-lymw512v\wxget.exe
ERROR: Command errored out with exit status 1: 'C:\Users\ckelly\Anaconda3\envs\dlc\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ckelly\\AppData\\Local\\Temp\\pip-install-l5f7lqo0\\wxpython_7860fedbfb274deb8a567c6351fd0ef4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ckelly\\AppData\\Local\\Temp\\pip-install-l5f7lqo0\\wxpython_7860fedbfb274deb8a567c6351fd0ef4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ckelly\AppData\Local\Temp\pip-record-1qpwb9xz\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ckelly\Anaconda3\envs\dlc\Include\wxpython' Check the logs for full command output.
```

### Anything else?

Program Versions (if this helps): 
- Python 3.9.7
- cudatoolkit 11.2.2
- cuDNN 8.1.0.77
- tensorflow 2.5.0

Troubleshooting attempts so far:
I have tried installing wxPython separately with both pip and conda install. Using conda-forge I can successfully install wxython on its own but still get the same error when attempting to pip install deeplabcut.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @CorinneAKelly, we do not support python 3.9 yet. Could you retry with python 3.8, or directly using our conda yaml file (conda-environments/DEEPLABCUT.yaml)?

**Comment by CorinneAKelly** [comment]
Switching to 3.8 fixed the problem! Thanks so much!

**Comment by CorinneAKelly** [comment]
Looks like it wasn't as 100% fixed as I thought. I had some issues with it being unhappy after changing the python version so I created a new python 3.8 environment and installed from scratch. Everything installed fine but when I run the testscript I get as far as labeling and then the following error occurs:
`CREATING-SOME LABELS FOR THE FRAMES
Traceback (most recent call last):
  File "testscript.py", line 102, in <module>
    dataFrame.to_hdf(
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\pandas\core\generic.py", line 2703, in to_hdf
    pytables.to_hdf(
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\pandas\io\pytables.py", line 311, in to_hdf
    with HDFStore(
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\pandas\io\pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\pandas\compat\_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.`

I found some previous issues where people tried pip uninstalling numPy and then conda installing NumPy but that didn't work for me. Any idea what I did wrong here?

**Comment by jeylau** [comment]
`pip install tables==3.6.1` may be your solution https://github.com/DeepLabCut/DeepLabCut/issues/1642#issuecomment-1015293488 ☺️

**Comment by CorinneAKelly** [comment]
This fixed it! The testscipt ran fine and the GUI opens with no problems. Thanks again for all the help! 😄
