### ISSUE TITLE
Can't retrain from snapshot or evaluate after training in colab

### ISSUE THREAD

**Issue by jonpedros** [DeepLabCut/DeepLabCut#1676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I've been trying to train a model from labeled data on Colab.  I leave it training for iterations until it times out but, after trying to train again from scratch or with weights, I get the following errors. The error is similar when going for evaluating trained models.

Something that I noticed is that the pose_cfg.yaml gets its init_weights field changed back to the resnet file after trying to retrain, so my change to the file seems to not make any difference after all.

I have seen a similar issue in the forum but it did not get solved; removing and installing specific versions of tensorflow only returned a different error. 

It's also worth mentioning that this only happens after a successful (timed out) model training. After I got this I deleted my project folder from Drive, made a new Colab Notebook copy, re-uploaded my project file with only labeled data (no models), and was able to try training again. But got the same error afterwards.

After that I tried deleting only the dlc_models and training_datasets, along with making a new copy of the colab notebook and still got the same error. Only after reuploading the config.yaml file to its original state I could try training again.

### Operating System

Google Colab

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

single animal

### Device type

Python 3 Google Compute Engine backend (GPU)

### Relevant log output

```shell
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7]],
 'all_joints_names': ['right-digit1',
                      'right-digit2',
                      'right-digit3',
                      'right-digit4',
                      'left-digit1',
                      'left-digit2',
                      'left-digit3',
                      'left-digit4'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'crop_sampling': 'hybrid',
 'crop_size': [400, 400],
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/dlc_digits_Joao95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'max_shift': 0.4,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/Documentation_data-dlc_digits_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 8,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'pre_resize': [],
 'project_path': '/content/drive/My Drive/dlc_digits-Joao-2022-02-08',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': '/content/drive/My '
                    'Drive/dlc_digits-Joao-2022-02-08/dlc-models/iteration-0/dlc_digitsFeb8-trainset95shuffle1/train/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}

Selecting single-animal trainer

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)

Batch Size is 1
Loading ImageNet-pretrained resnet_50
Display_iters overwritten as 10
Save_iters overwritten as 500
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/content/drive/My Drive/dlc_digits-Joao-2022-02-08/dlc-models/iteration-0/dlc_digitsFeb8-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7]], 'all_joints_names': ['right-digit1', 'right-digit2', 'right-digit3', 'right-digit4', 'left-digit1', 'left-digit2', 'left-digit3', 'left-digit4'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/dlc_digits_Joao95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/Documentation_data-dlc_digits_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 8, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': '/content/drive/My Drive/dlc_digits-Joao-2022-02-08', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....

---------------------------------------------------------------------------

UnimplementedError                        Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1376     try:
-> 1377       return fn(*args)
   1378     except errors.OpError as e:

9 frames

UnimplementedError: 2 root error(s) found.
  (0) UNIMPLEMENTED: DNN library is not found.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
	 [[huber_loss/assert_broadcastable/AssertGuard/pivot_f/_15/_556]]
  (1) UNIMPLEMENTED: DNN library is not found.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.


During handling of the above exception, another exception occurred:

UnimplementedError                        Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1394                     '\nsession_config.graph_options.rewrite_options.'
   1395                     'disable_meta_optimizer = True')
-> 1396       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1397 
   1398   def _extend_graph(self):

UnimplementedError: Graph execution error:

Detected at node 'resnet_v1_50/conv1/Conv2D' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
      handler_func(fileobj, events)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
      self._handle_recv()
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
      self._run_callback(callback, msg)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
      callback(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
      return self.dispatch_shell(stream, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
      handler(stream, idents, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
      user_expressions, allow_stdin)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2828, in run_ast_nodes
      if self.run_code(code, result):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-10-98176c53e60f>", line 5, in <module>
      deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10,saveiters=500)
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 185, in train_network
      allow_growth=allow_growth,
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 171, in train
      losses = PoseNetFactory.create(cfg).train(batch)
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/base.py", line 22, in train
      heads = self.get_net(batch[Batch.inputs])
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py", line 76, in get_net
      net, end_points = self.extract_features(inputs)
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py", line 43, in extract_features
      is_training=False,
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py", line 279, in resnet_v1_50
      scope=scope)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py", line 210, in resnet_v1
      net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_utils.py", line 150, in conv2d_same
      scope=scope)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py", line 1191, in convolution2d
      conv_dims=2)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py", line 1089, in convolution
      outputs = layer.apply(inputs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 1697, in apply
      return self.__call__(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 568, in __call__
      outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 784, in __call__
      outputs = call_fn(cast_inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 253, in call
      outputs = self._convolution_op(inputs, self.kernel)
Node: 'resnet_v1_50/conv1/Conv2D'
Detected at node 'resnet_v1_50/conv1/Conv2D' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
      handler_func(fileobj, events)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
      self._handle_recv()
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
      self._run_callback(callback, msg)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
      callback(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
      return self.dispatch_shell(stream, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
      handler(stream, idents, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
      user_expressions, allow_stdin)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2828, in run_ast_nodes
      if self.run_code(code, result):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-10-98176c53e60f>", line 5, in <module>
      deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10,saveiters=500)
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 185, in train_network
      allow_growth=allow_growth,
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 171, in train
      losses = PoseNetFactory.create(cfg).train(batch)
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/base.py", line 22, in train
      heads = self.get_net(batch[Batch.inputs])
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py", line 76, in get_net
      net, end_points = self.extract_features(inputs)
    File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py", line 43, in extract_features
      is_training=False,
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py", line 279, in resnet_v1_50
      scope=scope)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py", line 210, in resnet_v1
      net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_utils.py", line 150, in conv2d_same
      scope=scope)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py", line 1191, in convolution2d
      conv_dims=2)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py", line 1089, in convolution
      outputs = layer.apply(inputs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 1697, in apply
      return self.__call__(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 568, in __call__
      outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 784, in __call__
      outputs = call_fn(cast_inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 253, in call
      outputs = self._convolution_op(inputs, self.kernel)
Node: 'resnet_v1_50/conv1/Conv2D'
2 root error(s) found.
  (0) UNIMPLEMENTED: DNN library is not found.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
	 [[huber_loss/assert_broadcastable/AssertGuard/pivot_f/_15/_556]]
  (1) UNIMPLEMENTED: DNN library is not found.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'resnet_v1_50/conv1/Conv2D':
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2828, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-98176c53e60f>", line 5, in <module>
    deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10,saveiters=500)
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 185, in train_network
    allow_growth=allow_growth,
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 171, in train
    losses = PoseNetFactory.create(cfg).train(batch)
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/base.py", line 22, in train
    heads = self.get_net(batch[Batch.inputs])
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py", line 76, in get_net
    net, end_points = self.extract_features(inputs)
  File "/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py", line 43, in extract_features
    is_training=False,
  File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py", line 279, in resnet_v1_50
    scope=scope)
  File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py", line 210, in resnet_v1
    net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')
  File "/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_utils.py", line 150, in conv2d_same
    scope=scope)
  File "/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py", line 1191, in convolution2d
    conv_dims=2)
  File "/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py", line 1089, in convolution
    outputs = layer.apply(inputs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 1697, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 568, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 784, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 253, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 1082, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1155, in convolution_v2
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1287, in convolution_internal
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 2763, in _conv2d_expanded_batch
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 973, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3784, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 2175, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

### Anything else?

I had the runtime hanging undefinetely for the DeepLabCut install during the statmodels dependency installation, which I fixed by upgrading pip install. I had errors when creating the training dataset with tables' version but fixed it by upgrading it and then running the DLC pip install again.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jonpedros** [comment]
Just solved it! I was re-running the cell for creating the dataset before resuming training or evaluating. This seemed to have caused the errors. Might be interesting to add a line in that cell warning (beginner) users not to run it again whenever restarting the runtime for whatever reason, since it's the only cell for the training "set-up" to cause problems. I don't know about the dependencies issues but maybe they'll be useful to someone trying to use colab in its current state.
