### ISSUE TITLE
GUI backend "WxAgg" not work in docker

### ISSUE THREAD

**Issue by caide199212** [DeepLabCut/DeepLabCut#1691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The initial bug comes in the following way:
```
>>> import deeplabcut
2022-02-17 06:18:16.078540: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 28, in <module>
    from deeplabcut import generate_training_dataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    from .pose_deterministic import DeterministicPoseDataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    from deeplabcut.utils.auxfun_videos import imread, imresize
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
```
I searched the issues in DeepLabCut and other materials, and located the minimum reproducible bug enviroment as follow:
```
>>> import wx
>>> import matplotlib
>>> matplotlib.use('WXagg')
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
```

Change the backend of matplotlib GUI to "Agg" has no import problem as below:
```import wx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
```

so I revised the matplotlib backend in 
`/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py`,  in this way, the `import deeplabcut` works.

```
import matplotlib as mpl
try:
    import wx
    #mpl.use("WxAgg")
    mpl.use("Agg")
```

However, the sub-modules and functions somewhere else in this package are solely designated as `WXagg`, such as the follow
![image](https://user-images.githubusercontent.com/24669435/154421170-a98b96f9-0732-474b-92c9-7528af3b1a3e.png)
so the workaround way of setting as "Agg" backend also failed work

### Operating System

Ubuntu 18.04 on a desktop machine, i.e., with a monitor connected to it

### DeepLabCut version

DeepLabCut version `2.2.0.2` from the below docker image:
`docker pull deeplabcut/deeplabcut:latest-gui-jupyter`

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

```
>>>docker pull deeplabcut/deeplabcut:latest-gui-jupyter
>>>docker run -it --privileged=true --net=host deeplabcut/deeplabcut:latest-gui-jupyter /bin/bash 
>>>python3
>>>import deeplabcut
```

### Relevant log output

```shell
as pointed in https://github.com/DeepLabCut/DeepLabCut/issues/1538,
I checked 
cat /etc/gdm3/custom.conf | grep WaylandEnable
echo $XDG_SESSION_TYPE
echo $DISPLAY
And the outputs are
MaylandEnable=false
x11
:0
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by dradri** [comment]
Also chiming in. Fresh Docker install on Ubuntu 20.04. Related error:

Welcome to DeepLabCut docker!

latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2022-02-17T14:50:28+0100]: Configuring a local container for user leboeufa (1003) in group dev (1006)
sha256:661de5c97732abab7970b829a0e8020988aae59fedaa36112601231b49f1e10e
[2022-02-17T14:50:28+0100]: Build succeeded
[2022-02-17T14:50:28+0100]: Using Linux config
2022-02-17 13:50:29.251085: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 27, in <module>
    from deeplabcut import generate_training_dataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    from .pose_deterministic import DeterministicPoseDataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    from deeplabcut.utils.auxfun_videos import imread, imresize
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2022-02-17T14:50:32+0100]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix:1 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/1003/gdm/Xauthority:/home/developer/.Xauthority -v /home/leboeufa/Downloads/DeepLabCut/conda-environments:/app -w /app "
Container stopped.


And note that I am on a desktop with a monitor. I don't feel headless.

**Comment by MMathisLab** [comment]
this is a duplicate issue, please see: https://github.com/DeepLabCut/DeepLabCut/issues/1618#issuecomment-996936859

**Comment by caide199212** [comment]
A lot thanks for the prompt reply @MMathisLab. The deeplabcut-docker helper started the container without  the above GUI backend problem.
