### ISSUE TITLE
cannot label data

### ISSUE THREAD

**Issue by shimesaba22** [DeepLabCut/DeepLabCut#1695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I activate DEEPLABCUT GUI, I can execute extract frames command and make some images in 'labeled-data' folder. However, I can't label frames. 

### Operating System

Windows 11

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

single animal

### Device type

cpu

### Relevant log output

```shell
Starting GUI...
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 5.0  seconds.
Extracting and downsampling... 300  frames from the video.
300it [00:00, 462.37it/s]
Kmeans clustering ... (this might take a while)
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 5.0  seconds.
Extracting and downsampling... 300  frames from the video.
300it [00:00, 456.58it/s]
Kmeans clustering ... (this might take a while)
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 5.0  seconds.
Extracting and downsampling... 300  frames from the video.
300it [00:00, 418.97it/s]
Kmeans clustering ... (this might take a while)
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 5.0  seconds.
Extracting and downsampling... 300  frames from the video.
300it [00:00, 456.55it/s]
Kmeans clustering ... (this might take a while)
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 5.0  seconds.
Extracting and downsampling... 300  frames from the video.
300it [00:00, 471.27it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
No images found!!
Traceback (most recent call last):
  File "C:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 628, in browseDir
    self.dataFrame = pd.read_hdf(
  File "C:\anaconda\envs\DEEPLABCUT\lib\site-packages\pandas\io\pytables.py", line 427, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File C:\deeplabcut\220215_09-rico-2022-02-19\labeled-data\220215_09_000[1]\CollectedData_rico.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 652, in browseDir
    index = pd.MultiIndex.from_tuples(self.relativeimagenames)
  File "C:\anaconda\envs\DEEPLABCUT\lib\site-packages\pandas\core\indexes\multi.py", line 204, in new_meth
    return meth(self_or_cls, *args, **kwargs)
  File "C:\anaconda\envs\DEEPLABCUT\lib\site-packages\pandas\core\indexes\multi.py", line 553, in from_tuples
    raise TypeError("Cannot infer number of levels from empty list")
TypeError: Cannot infer number of levels from empty list
```

### Anything else?
I'm a beginner at English and DEEPLABCUT, please help me:)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hey @shimesaba22, it says that no images were found. Can you confirm that there are extracted frames in the folder `C:\deeplabcut\220215_09-rico-2022-02-19\labeled-data\220215_09_000[1]`?

**Comment by shimesaba22** [comment]
Thank you for your reply!
Yes, I confirmed the frames in the folder, but I can solve this error in the way that I unzipped an original video file and move the file to C drive.
