### ISSUE TITLE
Cannot label videos

### ISSUE THREAD

**Issue by rbpatt2019** [DeepLabCut/DeepLabCut#1702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Any attempts to run `DeepLabCut.create_labeled_video` error. This problem occurs regardless of whether the command is run from iPython or a script. If the command is run from iPython, it also kills iPython. I receive slightly different errors when running in iPython vs as a python script. The error included under `relevant log output` is produced by the script, and the error under `additional information` is from running in iPython. Interestingly, this always occurs exactly 92% of the way into creating the video.

As far as I can tell, the root error is about the numpy index being out of bounds.

### Operating System

operating system RHEL8 (on my University HPC cluster)

### DeepLabCut version

dlc version 2.2.0.6

### DeepLabCut mode

single animal

### Device type

gpu NVIDIA A-100

### Steps To Reproduce

In a DeepLabCut Conda environment (no gui support):
```python
import deeplabcut as dlc
config_path = "/path/to/config.yaml"
dlc.create_labelled_video(config_path, ['/path/to/video.avi'])
```

### Relevant log output

```shell
"""
Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 671, in proc_video
    CreateVideo(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 177, in CreateVideo
    clip.save_frame(image)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/video_processor.py", line 149, in save_frame
    self.svid.write(np.flip(frame, 2))
  File "<__array_function__ internals>", line 5, in flip
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/numpy/lib/function_base.py", line 236, in flip
    axis = _nx.normalize_axis_tuple(axis, m.ndim)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/numpy/core/numeric.py", line 1385, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/numpy/core/numeric.py", line 1385, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/evaluate.py", line 33, in <module>
    dlc.create_labeled_video(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 518, in create_labeled_video
    pool.map(func, Videos)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
```

### Anything else?

I think this is likely related to #1698, but I opened a new error since I can't run this command at all. It seems to independent of any options passed. I've tried with various combinations of `trailingpoints`, `draw_skeleton`, `save_frames`, `filtered`, and others, all producing the same error.

The iPython error is below. Though different than the python script error above, I think the root error is the same.

<details>
  <summary>iPython interactive session error</summary>
  
```python
"""
Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 671, in proc_video
    CreateVideo(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 177, in CreateVideo
    clip.save_frame(image)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/video_processor.py", line 149, in save_frame
    self.svid.write(np.flip(frame, 2))
  File "<__array_function__ internals>", line 5, in flip
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/numpy/lib/function_base.py", line 236, in flip
    axis = _nx.normalize_axis_tuple(axis, m.ndim)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/numpy/core/numeric.py", line 1385, in normalize_axis_tuple
axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/numpy/core/numeric.py", line 1385, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-52908841c4a8>", line 1, in <module>
    dlc.create_labeled_video(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 518, in create_labeled_video
    pool.map(func, Videos)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
numpy.AxisError: axis 2 is out of bounds for array of dimension 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AxisError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rbp33/.conda/envs/DEEPLABCUT/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/rbp33/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
</details>

Sorry the attached config is a text file. Github Issues won't allow the uploading of yaml files.

<details>
  <summary>config.yaml</summary>

[config.txt](https://github.com/DeepLabCut/DeepLabCut/files/8123143/config.txt)
</details>

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
It looks like you have a corrupt video frame. Try reencoding the video first.

**Comment by rbpatt2019** [comment]
@backyardbiomech Thanks for the advice! I tried re-encoding using the command below, but nothing changes. All runs well until 92%, then same appears. I'm going to try with a different video and see if the problem persists.

```shell
ffmpeg -i "videos/021021_M00621658_CD_MET_12wk.avi" -c:v libx264 -crf 23 -c:a copy "021021_M00621658_CD_MET_12wk.avi"
```

**Comment by backyardbiomech** [comment]
It's loading the video frame by frame into numpy arrays, and it seems as though one frame simply doesn't exist. 
Since it runs until 92%, try trimming the end of the movie off (ffmpeg can also do this), and see if it works. You'll have to analyze the trimmed video to get new results file that has data for the proper number of frames. 

If that works, then you can be certain it's a bad frame in the video. If you can figure out which frame, you can either trim to then ignore everything after that frame, or you can insert a dummy frame instead (e.g. duplicate the frame before).
