### ISSUE TITLE
RuntimeError: Attempted to use a closed Session.

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

whenever i run training. it runs all the way to the end. but then gives an error
"RuntimeError: Attempted to use a closed Session."

though it appears the model is actually fine.

### Operating System

operating system: WIN10

### DeepLabCut version

dlc version
'2.2.0.6'

### DeepLabCut mode

single animal

### Device type

gpu: A6000

### Steps To Reproduce

import deeplabcut
   ...: import os
   ...: %env CUDA_DEVICE_ORDER=PCI_BUS_ID
   ...: %env CUDA_VISIBLE_DEVICES=0,1
   ...: import tensorflow as tf
   ...: gpu_devices = tf.config.experimental.list_physical_devices('GPU')
   ...: for device in gpu_devices:
   ...:     tf.config.experimental.set_memory_growth(device, True)
   ...: path_config_file=r'D:\DLC_projects\generalizard_Single-SW-2022-02-15\config.yaml'
   ...: config_path=path_config_file
   ...: path_config_file=config_path
   ...: shuffle=3
env: CUDA_DEVICE_ORDER=PCI_BUS_ID
env: CUDA_VISIBLE_DEVICES=0,1
deeplabcut.train_network(
   ...:     path_config_file, shuffle=1, max_snapshots_to_keep=11, gputouse=1, allow_growth=True
   ...: )

### Relevant log output

```shell
deeplabcut.train_network(
   ...:     path_config_file, shuffle=1, max_snapshots_to_keep=11, gputouse=1, allow_growth=True
   ...: )
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]],
 'all_joints_names': ['Red',
                      'LeftHand',
                      'LeftLeg',
                      'Pelvis',
                      'P_2',
                      'P_4',
                      'nose',
                      'Green',
                      'RightHand',
                      'RightLeg'],
 'allow_growth': True,
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'augmentationprobability': 0.5,
 'batch_size': 8,
 'clahe': True,
 'claheratio': 0.1,
 'covering': True,
 'crop_pad': 0,
 'crop_sampling': 'hybrid',
 'crop_size': [400, 400],
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-5\\UnaugmentedDataSet_generalizard_SingleFeb15\\generalizard_Single_SW95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'elastic_transform': True,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.33,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\ProgramData\\Anaconda3\\envs\\DLC202202\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'max_shift': 0.4,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-5\\UnaugmentedDataSet_generalizard_SingleFeb15\\Documentation_data-generalizard_Single_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'motion_blur': True,
 'multi_stage': False,
 'multi_step': [[0.0001, 7500], ['5e-05', 12000], ['1e-05', 50000]],
 'net_type': 'resnet_50',
 'num_joints': 10,
 'optimizer': 'adam',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'pre_resize': [],
 'project_path': 'D:\\DLC_projects\\generalizard_Single-SW-2022-02-15',
 'regularize': False,
 'rotation': 180,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.5,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'D:\\DLC_projects\\generalizard_Single-SW-2022-02-15\\dlc-models\\iteration-5\\generalizard_SingleFeb15-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 8
C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\tf_slim\layers\layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)
2022-03-03 23:35:33.488438: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-03 23:35:35.456698: E tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] The TF_FORCE_GPU_ALLOW_GROWTH environment variable is set but could not be parsed: ""true"". Valid values are "true" or "false". Using original config value of 1.
2022-03-03 23:35:35.457604: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 45894 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:4f:00.0, compute capability: 8.6
2022-03-03 23:35:35.484226: E tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] The TF_FORCE_GPU_ALLOW_GROWTH environment variable is set but could not be parsed: ""true"". Valid values are "true" or "false". Using original config value of 1.
2022-03-03 23:35:35.484462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 45894 MB memory:  -> device: 1, name: NVIDIA RTX A6000, pci bus id: 0000:d5:00.0, compute capability: 8.6
Loading ImageNet-pretrained resnet_50
2022-03-03 23:35:36.013674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 45894 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:4f:00.0, compute capability: 8.6
2022-03-03 23:35:36.026546: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 45894 MB memory:  -> device: 1, name: NVIDIA RTX A6000, pci bus id: 0000:d5:00.0, compute capability: 8.6
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'D:\\DLC_projects\\generalizard_Single-SW-2022-02-15\\dlc-models\\iteration-5\\generalizard_SingleFeb15-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.33, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 8, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]], 'all_joints_names': ['Red', 'LeftHand', 'LeftLeg', 'Pelvis', 'P_2', 'P_4', 'nose', 'Green', 'RightHand', 'RightLeg'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-5\\UnaugmentedDataSet_generalizard_SingleFeb15\\generalizard_Single_SW95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\ProgramData\\Anaconda3\\envs\\DLC202202\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets\\iteration-5\\UnaugmentedDataSet_generalizard_SingleFeb15\\Documentation_data-generalizard_Single_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.0001, 7500], ['5e-05', 12000], ['1e-05', 50000]], 'net_type': 'resnet_50', 'num_joints': 10, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': 'D:\\DLC_projects\\generalizard_Single-SW-2022-02-15', 'rotation': 180, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.5, 'sharpen': False, 'sharpenratio': 0.3, 'augmentationprobability': 0.5, 'elastic_transform': True, 'covering': True, 'motion_blur': True, 'allow_growth': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2022-03-03 23:35:43.246334: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
iteration: 1000 loss: 0.0132 lr: 0.0001
iteration: 2000 loss: 0.0055 lr: 0.0001
iteration: 3000 loss: 0.0045 lr: 0.0001
iteration: 4000 loss: 0.0039 lr: 0.0001
iteration: 5000 loss: 0.0035 lr: 0.0001
iteration: 6000 loss: 0.0031 lr: 0.0001
iteration: 7000 loss: 0.0031 lr: 0.0001
iteration: 8000 loss: 0.0027 lr: 5e-05
iteration: 9000 loss: 0.0024 lr: 5e-05
iteration: 10000 loss: 0.0023 lr: 5e-05
iteration: 11000 loss: 0.0023 lr: 5e-05
iteration: 12000 loss: 0.0023 lr: 5e-05
iteration: 13000 loss: 0.0020 lr: 1e-05
iteration: 14000 loss: 0.0020 lr: 1e-05
iteration: 15000 loss: 0.0019 lr: 1e-05
iteration: 16000 loss: 0.0020 lr: 1e-05
iteration: 17000 loss: 0.0019 lr: 1e-05
iteration: 18000 loss: 0.0019 lr: 1e-05
iteration: 19000 loss: 0.0019 lr: 1e-05
iteration: 20000 loss: 0.0018 lr: 1e-05
iteration: 21000 loss: 0.0018 lr: 1e-05
iteration: 22000 loss: 0.0018 lr: 1e-05
iteration: 23000 loss: 0.0018 lr: 1e-05
iteration: 24000 loss: 0.0018 lr: 1e-05
iteration: 25000 loss: 0.0017 lr: 1e-05
iteration: 26000 loss: 0.0017 lr: 1e-05
iteration: 27000 loss: 0.0018 lr: 1e-05
iteration: 28000 loss: 0.0017 lr: 1e-05
iteration: 29000 loss: 0.0017 lr: 1e-05
iteration: 30000 loss: 0.0017 lr: 1e-05
iteration: 31000 loss: 0.0017 lr: 1e-05
iteration: 32000 loss: 0.0017 lr: 1e-05
iteration: 33000 loss: 0.0017 lr: 1e-05
iteration: 34000 loss: 0.0017 lr: 1e-05
iteration: 35000 loss: 0.0017 lr: 1e-05
iteration: 36000 loss: 0.0017 lr: 1e-05
iteration: 37000 loss: 0.0016 lr: 1e-05
iteration: 38000 loss: 0.0016 lr: 1e-05
iteration: 39000 loss: 0.0016 lr: 1e-05
iteration: 40000 loss: 0.0017 lr: 1e-05
iteration: 41000 loss: 0.0016 lr: 1e-05
iteration: 42000 loss: 0.0016 lr: 1e-05
iteration: 43000 loss: 0.0016 lr: 1e-05
iteration: 44000 loss: 0.0016 lr: 1e-05
iteration: 45000 loss: 0.0016 lr: 1e-05
iteration: 46000 loss: 0.0016 lr: 1e-05
iteration: 47000 loss: 0.0016 lr: 1e-05
iteration: 48000 loss: 0.0016 lr: 1e-05
iteration: 49000 loss: 0.0016 lr: 1e-05
iteration: 50000 loss: 0.0016 lr: 1e-05
Exception in thread Thread-109:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 83, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\tensorflow\python\client\session.py", line 1115, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.
The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
yes, that is due to how it closes the session, not trivial to fix (and many early reports around it ;)

**Comment by WeissShahaf** [comment]
it doesn't seem to have much affect. except that the GPU memory stays allocated until the session is closed.
