### ISSUE TITLE
Prb when installing with conda with numpy version.

### ISSUE THREAD

**Issue by ANaaim** [DeepLabCut/DeepLabCut#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, 
We encounter the following problem with a colleague when installing Deep Lab Cut. The numba version was not compatible with the latest version of numpy. It was necessary to use the following command to make it work : 
pip uninstall numpy==1.22
pip install numpy==1.21

''
ImportError: Numba needs NumPy 1.21 or less
''

Best regards,

### Operating System

Windows

### DeepLabCut version

Latest version 

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1. Follow the instruction on the web site 👍 
2. conda env create -f DEEPLABCUT.yaml
3. conda activate DEEPLABCUT
4. python -m deeplabcut

### Relevant log output

```shell
D:\..\DeepLabCut>python -m deeplabcut
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "C:\..\Anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\.\Anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\..\Anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\..\DeepLabCut\deeplabcut\__init__.py", line 54, in <module>
    from deeplabcut.generate_training_dataset import (
  File "D:\..\DeepLabCut\deeplabcut\generate_training_dataset\__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "D:\..\DeepLabCut\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 24, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "D:\..\DeepLabCut\deeplabcut\pose_estimation_tensorflow\__init__.py", line 20, in <module>
    from deeplabcut.pose_estimation_tensorflow.predict_videos import *
  File "D:\..\DeepLabCut\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 34, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib import inferenceutils, trackingutils
  File "D:\..\DeepLabCut\deeplabcut\pose_estimation_tensorflow\lib\trackingutils.py", line 18, in <module>
    from numba import jit
  File "C:\..\Anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "C:\..\Anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @ANaaim, this behavior will be fixed in the next version with #1678. I have just tried it, setting lower bounds on numpy & numba versions seems to help pip resolve dependencies.
