### ISSUE TITLE
error when use train_network

### ISSUE THREAD

**Issue by Lywzz** [DeepLabCut/DeepLabCut#178]
windows 10 with anaconda python 3.6 and deeplabcut 2.x

when i get the training_dataset and use deeplabcut.train_network  i get an error

Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/DeepLabCut/myproject.py", line 19, in <module>
    deeplabcut.train_network(path_config_file)
  File "D:\DeepLabCut\deeplabcut\pose_estimation_tensorflow\training.py", line 81, in train_network
    raise e
  File "D:\DeepLabCut\deeplabcut\pose_estimation_tensorflow\training.py", line 79, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
  File "D:\DeepLabCut\deeplabcut\pose_estimation_tensorflow\train.py", line 83, in train
    cfg = load_config(config_yaml)
  File "D:\DeepLabCut\deeplabcut\pose_estimation_tensorflow\config.py", line 59, in load_config
    return cfg_from_file(filename)
  File "D:\DeepLabCut\deeplabcut\pose_estimation_tensorflow\config.py", line 45, in cfg_from_file
    yaml_cfg = edict(yaml.load(f))
File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 618, in construct_python_object_new
    return self.construct_python_object_apply(suffix, node, newobj=True)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 601, in construct_python_object_apply
    value = self.construct_mapping(node, deep=True)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 93, in construct_object
    for dummy in generator:
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 618, in construct_python_object_new
    return self.construct_python_object_apply(suffix, node, newobj=True)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 609, in construct_python_object_apply
    self.set_python_instance_state(instance, state)
  File "C:\Users\liu\AppData\Roaming\Python\Python36\site-packages\yaml\constructor.py", line 571, in set_python_instance_state
    setattr(object, key, value)
TypeError: can't set attributes of built-in/extension type 'object'

Can you help me solve the problem？
Thanks

**Comment by MMathisLab** [comment]
Please post the complete error including the call.

**Comment by Lywzz** [comment]
I used the latest version of deeplabcut and  pycharm as my python IDE.
First,i use anaconda to create a python3.6 env and install all dependency
Then，i use pycharm to run the following command
deeplabcut.create_new_project(task,experimenter,video,working_directory=r'D:\liuyiwei',copy_videos=True)

path_config_file = r'D:\liuyiwei\Javelin-liuyiwei-2019-01-17\config.yaml'
deeplabcut.extract_frames(path_config_file,'automatic','uniform',crop=True, checkcropping=True)


deeplabcut.label_frames(path_config_file)
deeplabcut.check_labels(path_config_file)

deeplabcut.create_training_dataset(path_config_file)
deeplabcut.refine_labels(path_config_file)
deeplabcut.merge_datasets(path_config_file)
deeplabcut.train_network(path_config_file)

**Comment by MMathisLab** [comment]
You should not run merge_datasets, that is **only** after you have a trained network, so this will break your config.yaml.  

If after you ran check_labels you wanted to refine your original labels, then that is fine with refine_labels, but this updates the original label file. So, you ran things out of order.

Now you need to run create_training_set again, which will create iteration 1. 

Please try to follow the user guide for the correct order of the steps, as otherwise it can get quite complicated.

**Comment by Lywzz** [comment]
it also got this error.
it seems like something wrong with the yaml package

**Comment by MMathisLab** [comment]
Yes, because you broke the iteration number from running merge_datasets out of order....

**Comment by Lywzz** [comment]
ok ,i will try it again 
thank you very much

**Comment by Lywzz** [comment]
Sorry,i have try it again and i don't use refine_lables and merge_dataset
it also got this error

**Comment by salvador-blanco** [comment]
> oh, i have fixed it by [https://github.com/diefans/pyyaml/commit/a74628731897a1612cb8890dff3c3a89bc0981a6](url)

@Lywzz Thank you very much, It worked for me !!
(Note that you have to copy paste the link, otherwise it is broken )
