### ISSUE TITLE
3D Create Labeled Video

### ISSUE THREAD

**Issue by mendlen** [DeepLabCut/DeepLabCut#1784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm running a 3D DLC project with two cameras.

After successfully running all steps up to this point, I get an error when I run deeplabcut.create_labeled_video_3d(). I've tried playing with the start and end inputs, and reviewing my config files, and so far no luck finding the source of my problem. Any help would be greatly appreciated!

### Operating System

Windows 10

### DeepLabCut mode

3d

### Relevant log output

```shell
(DEEPLABCUT) C:\Users\madComp\Desktop\chaosdbsdlc3d\VM05_3d\COTask-Linea-2022-04-16-3d>python calibrate.py
Analyzing all the videos in the directory
[['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session001_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session001_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session001_rightCam-0000.mp4'], ['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session002_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session002_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session002_rightCam-0000.mp4'], ['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session003_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session003_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session003_rightCam-0000.mp4'], ['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session004_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session004_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session004_rightCam-0000.mp4'], ['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session005_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session005_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session005_rightCam-0000.mp4'], ['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session006_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session006_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session006_rightCam-0000.mp4'], ['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session007_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session007_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session007_rightCam-0000.mp4'], ['C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session008_0000_Linea.h5', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session008_leftCam-0000.mp4', 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled\\20211007_VM05_session008_rightCam-0000.mp4']]
Creating 3D video from 20211007_VM05_session001_leftCam-0000.mp4 and 20211007_VM05_session001_rightCam-0000.mp4 using 20211007_VM05_session001_0000_Linea.h5
Looking for filtered predictions...
Found the following filtered data:  C:\Users\madComp\Desktop\chaosdbsdlc3d\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\*20211007_VM05_session001_leftCam-0000DLC_resnet50_COTaskOct18shuffle1_1030000*filtered.h5 C:\Users\madComp\Desktop\chaosdbsdlc3d\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\*20211007_VM05_session001_rightCam-0000DLC_resnet50_COTaskOct18shuffle1_1030000*filtered.h5
  0%|                                                                                        | 0/20438 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "calibrate.py", line 35, in <module>
    deeplabcut.create_labeled_video_3d(config_path3d, [triangulateFolder], videotype=".mp4")
  File "C:\Users\madComp\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 222, in create_labeled_video_3d
    output_folder, num_frames = plot2D(
  File "C:\Users\madComp\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 354, in plot2D
    axes3.set_xlim3d([np.nanmin(df_x), np.nanmax(df_x)])
  File "<__array_function__ internals>", line 5, in nanmin
  File "C:\Users\madComp\anaconda3\envs\DEEPLABCUT\lib\site-packages\numpy\lib\nanfunctions.py", line 319, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmin which has no identity
```

### Anything else?

**calibrate.py** (pls excuse the goofy file name)

```
import deeplabcut
config_path3d = 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2022-04-16-3d/config.yaml'
triangulateFolder = 'C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2021-10-18/videos/unlabeled'
deeplabcut.create_labeled_video_3d(config_path3d, [triangulateFolder], videotype=".mp4")
```

**2D config**
```
 # Project definitions (do not edit)
Task: COTask
scorer: Linea
date: Oct18
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: C:\\Users\\madComp\\Desktop\\chaosdbsdlc3d\\VM05_3d\\COTask-Linea-2021-10-18

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session001_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session002_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session003_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session004_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session005_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session006_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session007_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session008_leftCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session001_rightCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session002_rightCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session003_rightCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session004_rightCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session005_rightCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session006_rightCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session007_rightCam-0000.mp4:
    crop: 0, 720, 0, 540
  C:\Users\madComp\Desktop\dbsdlc\VM05_3d\COTask-Linea-2021-10-18\videos\unlabeled\20211007_VM05_session008_rightCam-0000.mp4:
    crop: 0, 720, 0, 540

bodyparts:
- D2TIP
start: 0
stop: 1
numframes2pick: 25

    # Plotting configuration
skeleton: []
skeleton_color: black
pcutoff: 0.6
dotsize: 3
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true

```

**3D config**
```
# Project definitions (do not edit)
Task: COTask
scorer: Linea
date: Apr16

# Project path (change when moving around)
project_path: C:/Users/madComp/Desktop/chaosdbsdlc3d/VM05_3d/COTask-Linea-2022-04-16-3d

# Plotting configuration
skeleton: []    # Note that the pairs must be defined, as you want them linked!
skeleton_color: black
pcutoff: 0.6
colormap: jet
dotsize: 3
alphaValue: 0.7
markerType: '*'
markerColor: r

# Number of cameras, camera names, path of the config files, shuffle index and trainingsetindex used to analyze videos:
num_cameras: 2
camera_names:
- leftCam
- rightCam

scorername_3d: Linea # Enter the scorer name for the 3D output
trainingsetindex_leftCam: 0
trainingsetindex_rightCam: 0
config_file_leftCam: C:\\Users\\madComp\\Desktop\\chaosdbsdlc3d\\VM05_3d\\COTask-Linea-2021-10-18\\config.yaml
config_file_rightCam: C:\\Users\\madComp\\Desktop\\chaosdbsdlc3d\\VM05_3d\\COTask-Linea-2021-10-18\\config.yaml
shuffle_leftCam: 1
shuffle_rightCam: 1
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello! You edited out relevant information from the issue template; could you tell us what version of DeepLabCut you're running? You can do it with:
```python
import deeplabcut

print(deeplabcut.__version__)
```

**Comment by MMathisLab** [comment]
@mendlen see the 3D config file, where you need to have a skeleton defined for creating 3D videos: 
```
# Plotting configuration
skeleton: []    # Note that the pairs must be defined, as you want them linked!
```

**Comment by jeylau** [comment]
@mendlen, does this also happen when using the unfiltered data?
Try anyway with the latest DeepLabCut version (2.2.1) using `pip install -U deeplabcut`, we had improved the way the limits of the 3D axes are determined: these lines should handle NaNs properly https://github.com/DeepLabCut/DeepLabCut/blob/edae3231ad2e61be6aa782bb6977de5190467cad/deeplabcut/pose_estimation_3d/plotting3D.py#L295-L297

**Comment by NLeeOrmia** [comment]
I currently have this same issue of not being able to generate labelled videos in 3D DLC. Currently using DLC 2.2.3.

I tried the above as suggested by @jeylau:

deeplabcut.triangulate(config_path,video_path, videotype='avi', filterpredictions=False)

But deeplabcut.create_labeled_video_3d seems to require filtered predictions.
