### ISSUE TITLE
extract outlier frame `KeyError: 'leftear_mice2'`

### ISSUE THREAD

**Issue by ZZysh** [DeepLabCut/DeepLabCut#1797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi author, I use the maDLC to anaylsis 2 c57 mice and 4 videos in total i used , and when i use the OPT extract outlier frams, the first two are almost normal, however, i found the last 2 are abnormal. i could not to refine labels, because i cannot see any labels in the GUI.
Meanwhile, there are two individuls i used in the yaml file, however,i can only find i individual label color in the GUI.
could you help me?

### Operating System

win10

### DeepLabCut version

the latest version

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1.in maDLC gui enviroment

2.individuals:
```
- individual1
- individual2
uniquebodyparts: []
multianimalbodyparts:
- leftear_mice1
- rightear_mice1
- snout_mice1
- middlebody_mice1
- leftbody_mice1
- rightbody_mice1
- tailbase_mice1
- leftear_mice2
- rightear_mice2
- snout_mice2
- middlebody_mice2
- leftbody_mice2
- rightbody_mice2
- tailbase_mice2
bodyparts: MULTI!

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 40

    # Plotting configuration
skeleton:
- - leftear_mice1
  - snout_mice1
- - snout_mice1
  - rightear_mice1
- - leftear_mice1
  - leftbody_mice1
- - leftbody_mice1
  - tailbase_mice1
- - rightear_mice1
  - rightbody_mice1
- - rightbody_mice1
  - tailbase_mice1
- - leftear_mice2
  - snout_mice2
- - snout_mice2
  - rightear_mice2
- - leftear_mice2
  - leftbody_mice2
- - leftbody_mice2
  - tailbase_mice2
- - rightear_mice2
  - rightbody_mice2
- - rightbody_mice2
  - tailbase_mice2
skeleton_color: pink
pcutoff: 0.6
dotsize: 3
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
default_track_method: ellipse
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```

3.in the extract outlier frame tab use shuffle = 1, algorithm = jump

### Relevant log output

```shell
Kmeans clustering ... (this might take a while)
Let's select frames indices: [373787, 322227, 282481, 5810, 268626, 5936, 69332, 137683, 157686, 135858, 143631, 28941, 337265, 175529, 162106, 109160, 203276, 274581, 95801, 402628, 53002, 16136, 24523, 316846, 18785, 573, 312593, 183154, 174826, 47253, 387509, 276637, 180338, 213, 288274, 252704, 146107, 87279, 81948, 32081]
New videos were added to the project! Use the function 'extract_frames' to select frames for labeling.
The outlier frames are extracted. They are stored in the subdirectory labeled-data\4.
Once you extracted frames for all videos, use 'refine_labels' to manually correct the labels.
Traceback (most recent call last):
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'leftear_mice2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\deeplabcut\deeplabcut\gui\multiple_individuals_refinement_toolbox.py", line 517, in browseDir
    MainFrame.plot(self, self.img)
  File "D:\software\deeplabcut\deeplabcut\gui\multiple_individuals_refinement_toolbox.py", line 1114, in plot
    self.dr.coords = MainFrame.getLabels(
  File "D:\software\deeplabcut\deeplabcut\gui\multiple_individuals_refinement_toolbox.py", line 903, in getLabels
    self.Dataframe[self.scorer][ind][bp]["x"].values[self.iter],
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\frame.py", line 3504, in __getitem__
    return self._getitem_multilevel(key)
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\frame.py", line 3555, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\indexes\multi.py", line 2869, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\indexes\multi.py", line 3222, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\indexes\multi.py", line 2802, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'leftear_mice2'
Traceback (most recent call last):
  File "D:\software\Annoconda\envs\deeplabcut\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'leftear_mice2'
```

### Anything else?

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
HI @ZZysh this is an issue with your project. For maDLC you should not label body parts per animal, i.e. `leftear_mice2` It should be left ear... the idea is that if you have shared body parts-- named the same, same location-- across animals, it should be just `leftear` 

Unfortunately, the way you have it setup won't work for maDLC efficiently. 

Please see these docs: 

https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#configure-the-project

**Comment by ZZysh** [comment]
thanks a lot



---- 回复的原邮件 ----
| 发件人 | Mackenzie ***@***.***> |
| 日期 | 2022年04月24日 22:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [DeepLabCut/DeepLabCut] extract outlier frame and there may be a bug (Issue #1797) |

HI @ZZysh this is an issue with your project. For maDLC you should not label body parts per animal, i.e. leftear_mice2 It should be left ear... the idea is that if you have shared body parts-- named the same, same location-- across animals, it should be just leftear

Unfortunately, the way you have it setup won't work for maDLC efficiently.

Please see these docs:

https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#configure-the-project
