### ISSUE TITLE
Two Error: FileNotFoundError: No unfiltered data file found,  ValueError: Unrecognized track_method=

### ISSUE THREAD

**Issue by Cadaqoes** [DeepLabCut/DeepLabCut#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi DLC team, 

I encountered the same error as #1626 .
However, it behaves a little differently.

If you analyze_video to the original video used for learning, .csv, .h5, .pickle files will be output.
However, when I try to apply to other videos, only .csv files are output and there are no .h5, .pickle files.
I get <code>FileNotFoundError: No unfiltered data file found</code> and <code>ValueError: Unrecognized track_method=</code>

Also, strangely, you can apply to videos shot with iphone, but you cannot apply to videos shot with GoProb on same config.yaml. 
Only csv files will appear.
Is it still an encoding problem like #1626 
If so, can you tell me a good way to re-encode?

Thank you

### Operating System

Windows10

### DeepLabCut version

deeplabcut==2.2.1

### DeepLabCut mode

single animal

### Device type

GPU - NVIDIA GeForce RTX 3080

### Steps To Reproduce

1. labeling, traning and evaluate network is OK
2. analyze video
    - save csv -> yes
    - save nwb -> yes
    - filter prediction -> no
    - dynamically crop bodyparts -> no
    - plots to pop up -> no
    - plot trajectory -> yes

### Relevant log output

```shell
Starting GUI...
Using snapshot-200000 for model F:\DeepLabCut\20220307\normal\120fpsfullhd-normal-2022-04-04\dlc-models\iteration-0\120fpsfullhdApr4-trainset95shuffle1
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2022-04-26 16:24:50.555117: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2022-04-26 16:24:50.786987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:b1:00.0 name: NVIDIA GeForce RTX 3080 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 68 deviceMemorySize: 10.00GiB deviceMemoryBandwidth: 707.88GiB/s
2022-04-26 16:24:50.787357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties:
pciBusID: 0000:31:00.0 name: NVIDIA T400 computeCapability: 7.5
coreClock: 1.425GHz coreCount: 6 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.52GiB/s
2022-04-26 16:24:50.790822: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2022-04-26 16:24:52.717192: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2022-04-26 16:24:52.717512: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
2022-04-26 16:24:54.176566: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
2022-04-26 16:24:54.411575: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2022-04-26 16:24:55.320201: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2022-04-26 16:24:56.168921: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
2022-04-26 16:24:56.172607: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2022-04-26 16:24:56.172884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1856] Ignoring visible gpu device (device: 1, name: NVIDIA T400, pci bus id: 0000:31:00.0, compute capability: 7.5) with core count: 6. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
2022-04-26 16:24:56.174037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-04-26 16:24:56.175374: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-26 16:24:56.182731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:b1:00.0 name: NVIDIA GeForce RTX 3080 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 68 deviceMemorySize: 10.00GiB deviceMemoryBandwidth: 707.88GiB/s
2022-04-26 16:24:56.183021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-04-26 16:24:56.694803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-04-26 16:24:56.695051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2022-04-26 16:24:56.696284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2022-04-26 16:24:56.697451: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7440 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:b1:00.0, compute capability: 8.6)
Starting to analyze %  F:\DeepLabCut\20220415_movie\normal\GH010123\test.mp4
Loading  F:\DeepLabCut\20220415_movie\normal\GH010123\test.mp4
Duration of video [s]:  4.61 , recorded with  120.0 fps!
Overall # of frames:  553  found with (before cropping) frame dimensions:  1920 1080
Starting to extract posture
  0%|                                                                                         | 0/553 [00:00<?, ?it/s]2022-04-26 16:24:58.537161: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2022-04-26 16:25:00.719822: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8201
2022-04-26 16:25:06.296225: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2022-04-26 16:25:07.785131: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
 99%|██████████████████████████████████████████████████████████████████████████████▌| 550/553 [01:39<00:00,  5.53it/s]
Saving results in F:\DeepLabCut\20220415_movie\normal\GH010123...
Saving csv poses!
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Loading  F:\DeepLabCut\20220415_movie\normal\GH010123\test.mp4 and data.

No unfiltered data file found in F:\DeepLabCut\20220415_movie\normal\GH010123 for video test and scorer DLC_resnet50_120fpsfullhdApr4shuffle1_200000.
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\deeplabcut\utils\plotting.py", line 266, in plot_trajectories
    df, _, _, suffix = auxiliaryfunctions.load_analyzed_data(
  File "C:\Users\user\anaconda3\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 768, in load_analyzed_data
    filepath, scorer, suffix = find_analyzed_data(
  File "C:\Users\user\anaconda3\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 754, in find_analyzed_data
    raise FileNotFoundError(msg)
FileNotFoundError: No unfiltered data file found in F:\DeepLabCut\20220415_movie\normal\GH010123 for video test and scorer DLC_resnet50_120fpsfullhdApr4shuffle1_200000.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 563, in analyze_videos
    deeplabcut.plot_trajectories(
  File "C:\Users\user\anaconda3\lib\site-packages\deeplabcut\utils\plotting.py", line 300, in plot_trajectories
    _ = auxiliaryfunctions.load_detection_data(
  File "C:\Users\user\anaconda3\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 785, in load_detection_data
    raise ValueError(f"Unrecognized track_method={track_method}")
ValueError: Unrecognized track_method=
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by BioWalking** [comment]
HIi
I encountered the same problem. I reduced the batch size in config.yaml and the problem was solved. Try it.

**Comment by jeylau** [comment]
I couldn't reproduce the error @m-yanada. Could you confirm that after video analysis a h5 data file was created F:\DeepLabCut\20220415_movie\normal\GH010123? If the output file is absent, could it be a permission issue when writing data to the F disk?

**Comment by HallaMo** [comment]
In my case,  the cropping parameters were incorrect. Setting them to "false" (or using the correct values) solves the problem.
