### ISSUE TITLE
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After a fresh install of docker for my ubuntu 18.04 system, I successfully pulled the deeplabcut-latest-gui-jupyter image from Dockerhub.  However, when I call 'deeplabcut-docker gui' on my terminal I get the following output:
> "ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2022-04-27T12:14:09-0700]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/carmen:/app -w /app "
Container stopped.

I'm wondering if this has anything to do with the fact that I don't have an NVIDIA GPU, and I haven't been able to install an NVIDIA driver for that reason.  I'm also new to WSL and Ubuntu, so possibly I am just misunderstanding some basic installation concept.  Any help would be greatly appreciated!

### Operating System

Ubuntu 18.04

### DeepLabCut version

N/A

### DeepLabCut mode

single animal

### Device type

Windows Subsystem for Linux (WSL) on Windows 11 Home 64-bit
Intel(R) UHD Graphics

### Steps To Reproduce

In Ubuntu 18.04:

> from https://docs.docker.com/engine/install/ubuntu/:
``` 
 sudo apt-get update
 sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

```
After running `sudo docker run hello-world` I get the correct message printed.

> from 	https://hub.docker.com/r/deeplabcut/deeplabcut/tags:

```
docker pull deeplabcut/deeplabcut:latest-gui-jupyter'
```

> Install DLC helper, finish other setup steps

```pip install deeplabcut-docker
sudo groupadd docker
sudo usermod -aG docker $USER
sudo reboot
deeplabcut-docker gui
```

### Relevant log output

```shell
.--,       .--,
                    ( (  \.---./  ) )
                     '.__/o   o\__.'
                       `{=  ^  =}´
                         >  u  <
 ____________________.""`-------`"".______________________
\   ___                   __         __   _____       __  /
/  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
\ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
//____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
\_________________________________________________________/
                       ___)( )(___ `-.___.
                      (((__) (__)))      ~`

Welcome to DeepLabCut docker!

latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2022-04-27T12:13:50-0700]: Configuring a local container for user carmen (1000) in group carmen (1000)
sha256:c3505814f6c7e18caac54ed5caf450d8d5efed7cd35d3684df4e9c9079b46a09
[2022-04-27T12:13:57-0700]: Build succeeded
[2022-04-27T12:13:57-0700]: Using Linux config
2022-04-27 19:14:00.402948: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 27, in <module>
    from deeplabcut import generate_training_dataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    from .pose_deterministic import DeterministicPoseDataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    from deeplabcut.utils.auxfun_videos import imread, imresize
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2022-04-27T12:14:09-0700]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/carmen:/app -w /app "
Container stopped.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @diegosancarmen this is a duplicate issue; can you try the fixes here? But in short, we recommend and support nvidia GPU, or you need to look into some tips, here: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-install-deeplabcut-for-intel-and-amd-gpus-on-windows

https://github.com/DeepLabCut/DeepLabCut/issues/1618

https://github.com/DeepLabCut/DeepLabCut/issues/1623

**Comment by diegosancarmen** [comment]
Does the DLC Docker container work for only NVIDIA-GPUs?  Can it work with Linux using an Intel GPU?

**Comment by MMathisLab** [comment]
we only support nvidia gpus, that's correct; however there are user-contributed docs on how to use other GPUs: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-install-deeplabcut-for-intel-and-amd-gpus-on-windows
