### ISSUE TITLE
Error when running train_network on supercomputing (Setting environment variables on devices without monitors)

### ISSUE THREAD

**Issue by davidSafeloc** [DeepLabCut/DeepLabCut#185]
Windows 10 

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

I uploaded the data to supercomputing system to run the training steps in there but when the job starts it fails immediately giving the following error:

  File "<string>", line 1, in <module>
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/__init__.py", line 25, in <module>
    from deeplabcut import generate_training_dataset
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 15, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 18, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

The call i do using the bash file is:

deeplabcut.train_network('/icm/hydra/home/plgmirandeitor/upload to ICM/Interaction_Test2/Interaction Test-David-2019-01-24/config.yaml',shuffle=1)

I thought that the wx library is for graphic representation, so i don't know why is being called at this step. Is there any step I'm missing to run things on the server?

**Comment by MMathisLab** [comment]
Yes, please see the user guide pdf, which has the commands you need to run to suppress GUI support beforehand. 

Also, if you created the project on Windows but the server is Ubuntu, you’ll also have to run a function to convert - see DLCUtils

**Comment by AlexEMG** [comment]
Indeed, that error appears because natively everything is imported (for GUI support) when you ```import deeplabcut```.  However, as Mackenzie says (quoting from paper): it is also possible to run the network training steps of DeepLabCut in the supplied Docker, or on cloud computing resources (such as AWS, Google, or on a University cluster). For running DeepLabCut on certain platforms you will need to suppress the GUI support. This can be done by setting an *environment variable* before loading the
toolbox:

Linux: ```export DLClight=True```
Windows: ```set DLClight=True```

If you want to re-engage the GUIs (and have installed wxPython as described above):

Linux: ```unset DLClight```
Windows: ```set DLClight=```

**Comment by davidSafeloc** [comment]
Im running the DLCUtils function on the cluster and i get the following error:

  import deeplabcut
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/__init__.py", line 33, in <module>
    from deeplabcut import pose_estimation_tensorflow
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 17, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet import *
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/__init__.py", line 14, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet.losses import *
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/losses.py", line 5, in <module>
    import tensorflow as tf
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Any idea what to do to solve the problem?

**Comment by MMathisLab** [comment]
(please see response on your other issue on DLCUtils; but in short, seems tensorflow is broken)

**Comment by tleitold** [comment]
> Yes, please see the user guide pdf, which has the commands you need to run to suppress GUI support beforehand.
> 
> Also, if you created the project on Windows but the server is Ubuntu, you’ll also have to run a function to convert - see DLCUtils

Hello, I am also running DeepLabCut on a cluster server. I did the labeling process on Windows and now want to use the cluster server (Ubuntu) for training.
Can you please explain how to run the function to convert? Do I have to put it in the ipython session or something?
