### ISSUE TITLE
An Axiserror occurred when I tried to create a video

### ISSUE THREAD

**Issue by ByeByeChen** [DeepLabCut/DeepLabCut#1904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

An Axiserror occurred when I tried to create a video。

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 718, in proc_video
    _create_labeled_video(
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 793, in _create_labeled_video
    CreateVideo(
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 179, in CreateVideo
    clip.save_frame(image)
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\video_processor.py", line 149, in save_frame
    self.svid.write(np.flip(frame, 2))
  File "<__array_function__ internals>", line 180, in flip
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\numpy\lib\function_base.py", line 338, in flip
    axis = _nx.normalize_axis_tuple(axis, m.ndim)
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\numpy\core\numeric.py", line 1391, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\numpy\core\numeric.py", line 1391, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\create_videos.py", line 359, in create_videos
    deeplabcut.create_labeled_video(
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 577, in create_labeled_video
    pool.map(func, Videos)
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
numpy.AxisError: axis 2 is out of bounds for array of dimension 0

### Operating System

Windows10   anaconda

### DeepLabCut version

dlc version2.2.1.1

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 718, in proc_video
    _create_labeled_video(
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 793, in _create_labeled_video
    CreateVideo(
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 179, in CreateVideo
    clip.save_frame(image)
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\video_processor.py", line 149, in save_frame
    self.svid.write(np.flip(frame, 2))
  File "<__array_function__ internals>", line 180, in flip
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\numpy\lib\function_base.py", line 338, in flip
    axis = _nx.normalize_axis_tuple(axis, m.ndim)
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\numpy\core\numeric.py", line 1391, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\numpy\core\numeric.py", line 1391, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\create_videos.py", line 359, in create_videos
    deeplabcut.create_labeled_video(
  File "G:\Anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 577, in create_labeled_video
    pool.map(func, Videos)
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "G:\Anaconda\envs\DEEPLABCUT\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Duplicates of #1460, #1702

One or more video frames may be corrupted. The solution to reencode your video (as suggested [here](https://forum.image.sc/t/numpy-axiserror-traceback/53022/4)) seems to work for our users. You could also look at this [recipe](https://deeplabcut.github.io/DeepLabCut/docs/recipes/io.html#tips-on-video-re-encoding-and-preprocessing), it may be helpful. 😃
