### ISSUE TITLE
Deepkabcut training automatically stopped at Iteration200000

### ISSUE THREAD

**Issue by NTUMEDREX** [DeepLabCut/DeepLabCut#1915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

My training model automatically stopped at Iteration 200000, which i set it to be at 500000 innitially. However, at the end it still shows that "The network is now trained and ready to evaluate." How can I fix it?
(By the way the loss is just 0.0010, or is this the reason why it stops automatically?) 

### Operating System

Linux Ubuntu

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

multi animal

### Device type

gpu Nvidia 3060

### Steps To Reproduce

1.Click training data sets and wait for several hours.
when it runs to Iteration 200000, it automatically stopped.

### Relevant log output

```shell
iteration: 198000 loss: 0.0010 scmap loss: 0.0009 locref loss: 0.0000 limb loss: 0.0001 lr: 1e-05
iteration: 199000 loss: 0.0010 scmap loss: 0.0009 locref loss: 0.0000 limb loss: 0.0001 lr: 1e-05
iteration: 200000 loss: 0.0010 scmap loss: 0.0009 locref loss: 0.0000 limb loss: 0.0001 lr: 1e-05
2022-07-20 23:22:20.459561: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 83, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1370, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.CancelledError: Graph execution error:

Detected at node 'fifo_queue_enqueue' defined at (most recent call last):
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/__main__.py", line 22, in <module>
      deeplabcut.launch_dlc()
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/wx/core.py", line 2237, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/train_network.py", line 315, in train_network
      deeplabcut.train_network(
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 194, in train_network
      train(
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py", line 66, in train
      batch, enqueue_op, placeholders = setup_preloading(batch_spec)
    File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 69, in setup_preloading
      enqueue_op = q.enqueue(placeholders_list)
Node: 'fifo_queue_enqueue'
Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]

Original stack trace for 'fifo_queue_enqueue':
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/__main__.py", line 22, in <module>
    deeplabcut.launch_dlc()
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/launch_script.py", line 50, in launch_dlc
    app.MainLoop()
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/wx/core.py", line 2237, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/train_network.py", line 315, in train_network
    deeplabcut.train_network(
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 194, in train_network
    train(
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py", line 66, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 69, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/ops/data_flow_ops.py", line 346, in enqueue
    return gen_data_flow_ops.queue_enqueue_v2(
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4063, in queue_enqueue_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3754, in _create_op_internal
    ret = Operation(
  File "/home/n513n514/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
```

### Anything else?

No

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @NTUMEDREX, have a look here #1008. multi-animal training is capped to 200k by default, but this can be changed by editing multi-step in the config.yaml (& maxiters).

**Comment by AlexEMG** [comment]
Keep in mind that the model will train until the minimum of maxiter and the last entry in the learning rate schedule. E.g., in this one the last entry is 103000: https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/pose_cfg.yaml#L156 

I suspect in your case the last entry is _200000,_ which is why it stops even before reaching maxiter. You can just increase this number in the _pose_cfg.yaml_ file of the model you try to train.

**Comment by jeylau** [comment]
It's set to 200k for all multi-animal projects: https://github.com/DeepLabCut/DeepLabCut/blob/5ad1d845046557e4832a83bdf60b06be841cbee0/deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py#L422
