### ISSUE TITLE
Error in Training 

### ISSUE THREAD

**Issue by IamNaQi** [DeepLabCut/DeepLabCut#1919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to train a model but getting unexpected error and training stopped.

### Operating System

windows 10

### DeepLabCut version

dlc version 2.2.1

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['mouth', 'body', 'tail'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_BlackMosueJul24\\BlackMosue_Mouse195shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\Users\\Naqi\\anaconda3\\envs\\dlc\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_BlackMosueJul24\\Documentation_data-BlackMosue_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Naqi\\Desktop\\dll_windows_void_0520\\DLC\\BlackMosue-Mouse1-2022-07-24',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Naqi\\Desktop\\dll_windows_void_0520\\DLC\\BlackMosue-Mouse1-2022-07-24\\dlc-models\\iteration-0\\BlackMosueJul24-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
Loading ImageNet-pretrained resnet_50
2022-07-24 12:42:49.218910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3497 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Max_iters overwritten as 500000
Display_iters overwritten as 1000
Save_iters overwritten as 10000
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\Naqi\\Desktop\\dll_windows_void_0520\\DLC\\BlackMosue-Mouse1-2022-07-24\\dlc-models\\iteration-0\\BlackMosueJul24-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2]], 'all_joints_names': ['mouth', 'body', 'tail'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_BlackMosueJul24\\BlackMosue_Mouse195shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\Users\\Naqi\\anaconda3\\envs\\dlc\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_BlackMosueJul24\\Documentation_data-BlackMosue_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 3, 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\Naqi\\Desktop\\dll_windows_void_0520\\DLC\\BlackMosue-Mouse1-2022-07-24', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2022-07-24 12:42:56.999605: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 81.21MiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py", line 1377, in _do_call
    return fn(*args)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) UNKNOWN: CUDNN failed to allocate the scratch space for the runner or to find a working no-scratch runner.
         [[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D}}]]
         [[sigmoid_cross_entropy_loss/value/_549]]
  (1) UNKNOWN: CUDNN failed to allocate the scratch space for the runner or to find a working no-scratch runner.
         [[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\train_network.py", line 315, in train_network
    deeplabcut.train_network(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    raise e
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 178, in train_network
    train(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 272, in train
    [_, loss_val, summary] = sess.run(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node 'resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D' defined at (most recent call last):
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\__main__.py", line 22, in <module>
      deeplabcut.launch_dlc()
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\wx\core.py", line 2167, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\label_frames.py", line 212, in label_frames
      label_frames(self.config)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\label_frames.py", line 81, in label_frames
      labeling_toolbox.show(config, config3d, sourceCam, imtypes, jump_unlabeled)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 968, in show
      app.MainLoop()
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\wx\core.py", line 2167, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\train_network.py", line 315, in train_network
      deeplabcut.train_network(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 178, in train_network
      train(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 170, in train
      losses = PoseNetFactory.create(cfg).train(batch)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\base.py", line 22, in train
      heads = self.get_net(batch[Batch.inputs])
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 66, in get_net
      net, end_points = self.extract_features(inputs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 39, in extract_features
      net, end_points = net_fun(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 270, in resnet_v1_50
      return resnet_v1(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 212, in resnet_v1
      net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_utils.py", line 215, in stack_blocks_dense
      net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 125, in bottleneck
      residual = layers.conv2d(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\layers\layers.py", line 1171, in convolution2d
      return convolution(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\layers\layers.py", line 1089, in convolution
      outputs = layer.apply(inputs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 1697, in apply
      return self.__call__(inputs, *args, **kwargs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\base.py", line 568, in __call__
      outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 784, in __call__
      outputs = call_fn(cast_inputs, *args, **kwargs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 253, in call
      outputs = self._convolution_op(inputs, self.kernel)
Node: 'resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D'
Detected at node 'resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D' defined at (most recent call last):
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\__main__.py", line 22, in <module>
      deeplabcut.launch_dlc()
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\wx\core.py", line 2167, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\label_frames.py", line 212, in label_frames
      label_frames(self.config)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\label_frames.py", line 81, in label_frames
      labeling_toolbox.show(config, config3d, sourceCam, imtypes, jump_unlabeled)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 968, in show
      app.MainLoop()
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\wx\core.py", line 2167, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\train_network.py", line 315, in train_network
      deeplabcut.train_network(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 178, in train_network
      train(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 170, in train
      losses = PoseNetFactory.create(cfg).train(batch)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\base.py", line 22, in train
      heads = self.get_net(batch[Batch.inputs])
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 66, in get_net
      net, end_points = self.extract_features(inputs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 39, in extract_features
      net, end_points = net_fun(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 270, in resnet_v1_50
      return resnet_v1(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 212, in resnet_v1
      net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_utils.py", line 215, in stack_blocks_dense
      net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 125, in bottleneck
      residual = layers.conv2d(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\layers\layers.py", line 1171, in convolution2d
      return convolution(
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
      return func(*args, **current_args)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\layers\layers.py", line 1089, in convolution
      outputs = layer.apply(inputs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 1697, in apply
      return self.__call__(inputs, *args, **kwargs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\base.py", line 568, in __call__
      outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 784, in __call__
      outputs = call_fn(cast_inputs, *args, **kwargs)
    File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 253, in call
      outputs = self._convolution_op(inputs, self.kernel)
Node: 'resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D'
2 root error(s) found.
  (0) UNKNOWN: CUDNN failed to allocate the scratch space for the runner or to find a working no-scratch runner.
         [[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D}}]]
         [[sigmoid_cross_entropy_loss/value/_549]]
  (1) UNKNOWN: CUDNN failed to allocate the scratch space for the runner or to find a working no-scratch runner.
         [[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D':
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\__main__.py", line 22, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
    app.MainLoop()
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\label_frames.py", line 212, in label_frames
    label_frames(self.config)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\label_frames.py", line 81, in label_frames
    labeling_toolbox.show(config, config3d, sourceCam, imtypes, jump_unlabeled)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 968, in show
    app.MainLoop()
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\train_network.py", line 315, in train_network
    deeplabcut.train_network(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 178, in train_network
    train(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 170, in train
    losses = PoseNetFactory.create(cfg).train(batch)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\base.py", line 22, in train
    heads = self.get_net(batch[Batch.inputs])
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 66, in get_net
    net, end_points = self.extract_features(inputs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 39, in extract_features
    net, end_points = net_fun(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 270, in resnet_v1_50
    return resnet_v1(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 212, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_utils.py", line 215, in stack_blocks_dense
    net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\nets\resnet_v1.py", line 125, in bottleneck
    residual = layers.conv2d(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\layers\layers.py", line 1171, in convolution2d
    return convolution(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tf_slim\layers\layers.py", line 1089, in convolution
    outputs = layer.apply(inputs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 1697, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\base.py", line 568, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 784, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 253, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\util\dispatch.py", line 1082, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1148, in convolution_v2
    return convolution_internal(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1280, in convolution_internal
    return op(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2756, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 968, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 740, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\ops.py", line 3776, in _create_op_internal
    ret = Operation(
  File "C:\Users\Naqi\anaconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\ops.py", line 2175, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by IamNaQi** [comment]
Problem has been solved with downgrade Tensorflow to  2.0.0.
Thank you
