### ISSUE TITLE
Nothing Extracted with Extract Outliers on GUI

### ISSUE THREAD

**Issue by apassagelee** [DeepLabCut/DeepLabCut#1939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Nothing is extracted when extracting outlier frames

### Operating System

Windows 11

### DeepLabCut version

dlc version 2.2.1.1

### DeepLabCut mode

single animal

### Device type

gpu NVIDA GeForce RTX3070

### Steps To Reproduce

Hi!
I am attempting to extract outlier frames using the GUI. I do not understand what the error means.

When I select the option to extract manually:
![error 1](https://user-images.githubusercontent.com/110839511/183858077-7fdfb87d-9d49-43f5-8559-9b0e4215a308.png)
I do not have the video file open.

When I click the option with “fitting”
```
Fitting state-space models with parameters: 3 1
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
Method  fitting  found  200  putative outlier frames.
Do you want to proceed with extracting  100  of those?
If this list is very large, perhaps consider changing the parameters (start, stop, epsilon, ARdegree, MAdegree, alpha, comparisonbodyparts) or use a different method.
yes/noyes
Nothing extracted, please change the parameters and start again...

```

Thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
yes, the error states: `ConvergenceWarning: Maximum Likelihood optimization failed to converge` -- you will need to test different model parameters.

**Comment by apassagelee** [comment]
Can I change the model parameters on the GUI itself?
How about the first kind of error? I restarted the computer, erased the empty folder that my previous attempt created:

Attempting to create a symbolic link of the video ...
The syntax of the command is incorrect.
Symlink creation impossible (exFat architecture?): cutting/pasting the video instead.
Traceback (most recent call last):
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\create_project\add.py", line 87, in add_new_videos
    os.symlink(src, dst)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\Lamylab\\Desktop\\DeepLabCut Mouse Behaviour\\Mouse Behaviour Videos\\180122_3_bnst_stim1.avi' -> 'C:\\Users\\Lamylab\\Desktop\\DeepLabCut Mouse Behaviour\\Mouse Behaviour Analysis-April-2022-07-26\\videos\\180122_3_bnst_stim1.avi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\create_project\add.py", line 93, in add_new_videos
    subprocess.check_call("mklink %s %s" % (dst, src), shell=True)
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mklink C:\Users\Lamylab\Desktop\DeepLabCut Mouse Behaviour\Mouse Behaviour Analysis-April-2022-07-26\videos\180122_3_bnst_stim1.avi C:\Users\Lamylab\Desktop\DeepLabCut Mouse Behaviour\Mouse Behaviour Videos\180122_3_bnst_stim1.avi' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Lamylab\\Desktop\\DeepLabCut Mouse Behaviour\\Mouse Behaviour Videos\\180122_3_bnst_stim1.avi' -> 'C:\\Users\\Lamylab\\Desktop\\DeepLabCut Mouse Behaviour\\Mouse Behaviour Analysis-April-2022-07-26\\videos\\180122_3_bnst_stim1.avi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\extract_outlier_frames.py", line 190, in extract_outlier_frames
    deeplabcut.extract_outlier_frames(
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py", line 412, in extract_outlier_frames
    outlier_frame_extraction_toolbox.show(
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\outlier_frame_extraction_toolbox.py", line 585, in show
    frame = MainFrame(
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\outlier_frame_extraction_toolbox.py", line 267, in __init__
    add.add_new_videos(self.config_path, [self.video_source])
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\create_project\add.py", line 99, in add_new_videos
    shutil.move(os.fspath(src), os.fspath(dst))
  File "C:\Users\Lamylab\anaconda3\envs\deeplabcut\lib\shutil.py", line 812, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Lamylab\\Desktop\\DeepLabCut Mouse Behaviour\\Mouse Behaviour Videos\\180122_3_bnst_stim1.avi'

**Comment by jeylau** [comment]
@apassagelee, I'm not sure about what causes the PermissionError. For outlier frame extraction though, if fitting statistical models to your output data does not reach convergence, I'd rather use the default `jump` detection method. It's fast and nicely captures frames where keypoints moved abnormally.

**Comment by MMathisLab** [comment]
permission error is typically just that when you open the terminal you need to first right click and "open as admin."
