### ISSUE TITLE
Numpy version error: Wxypthon installation for Ubuntu 20.04 forces Numpy version update 

### ISSUE THREAD

**Issue by anpeter1** [DeepLabCut/DeepLabCut#1953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After installing DLC on Ubuntu 20.04 with the [following instructions](https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#troubleshooting-note-if-you-get-a-failed-build-due-to-wxpython-note-this-does-not-happen-on-ubuntu-18-16-etc-i-e), we get a Numpy error when trying to launch the GUI. This is after the installation of Wxpython.

It seems that during the DLC installation numpy==1.21.5, but the wxpython installation forces a numpy upgrade to numpy==1.23.1, which causes an error when trying to initiate deeplabcut. 

We have successfully installed a couple DLC environments on the same computer/login, but they were built a few months prior. We have never been able install DLC without have to run the wxpython troubleshooting steps, but this is the first time those steps have failed.

We were able to install wxpython==4.1.1 and then downgrade numpy to numpy==1.21.5 and successfully launch DLC with the following steps:

conda install -c conda-forge wxpython==4.1.1 
conda install -c conda-forge numpy==1.21.5

However, we have not started using this installation of DLC yet and do not know if this workaround will cause any issues further down the pipeline.

### Operating System

Ubuntu 20.04

### DeepLabCut version

DLC 2.2.1.1

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Open the .yaml file and change deeplabcut[gui] to deeplabcut, save file
Re-create Enviornment (DLC_troubleshoot)

conda env create -n DLC_troubleshoot -f DEEPLABCUT.yaml

Installation is succussful, activate with:

conda activate DLC_troubleshoot

install -c conda-forge wxpython

### Relevant log output

```shell
(DLC_troubleshoot) anpetey@lambda-quad:~/Downloads$ install -c conda-forge wxpython
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/anpetey/anaconda3/envs/DLC_troubleshoot

  added / updated specs:
    - wxpython


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cairo-1.16.0               |    ha61ee94_1012         1.5 MB  conda-forge
    charset-normalizer-2.1.0   |     pyhd8ed1ab_0          35 KB  conda-forge
    cryptography-37.0.4        |   py38h2b5fc30_0         1.5 MB  conda-forge
    harfbuzz-5.1.0             |       hf9f4e7c_0         2.3 MB  conda-forge
    lerc-4.0.0                 |       h27087fc_0         275 KB  conda-forge
    libblas-3.9.0              |16_linux64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_linux64_openblas          13 KB  conda-forge
    libdeflate-1.13            |       h166bdaf_0          79 KB  conda-forge
    liblapack-3.9.0            |16_linux64_openblas          13 KB  conda-forge
    libopenblas-0.3.21         |pthreads_h78a6416_1        10.1 MB  conda-forge
    libtiff-4.4.0              |       h0e0dad5_3         642 KB  conda-forge
    libwebp-base-1.2.4         |       h166bdaf_0         404 KB  conda-forge
    numpy-1.23.2               |   py38h3a7f9d9_0         7.1 MB  conda-forge
    openjpeg-2.5.0             |       h7d73246_1         533 KB  conda-forge
    pango-1.50.9               |       hc4f8a73_0         460 KB  conda-forge
    pillow-9.2.0               |   py38ha3b2c9c_2        45.2 MB  conda-forge
    requests-2.28.1            |     pyhd8ed1ab_0          53 KB  conda-forge
    urllib3-1.26.11            |     pyhd8ed1ab_0         102 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        70.2 MB

The following NEW packages will be INSTALLED:

  atk-1.0            conda-forge/linux-64::atk-1.0-2.36.0-h3371d22_4
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py38h0a891b7_1004
  cairo              conda-forge/linux-64::cairo-1.16.0-ha61ee94_1012
  certifi            conda-forge/linux-64::certifi-2022.6.15-py38h578d9bd_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.1.0-pyhd8ed1ab_0
  cryptography       conda-forge/linux-64::cryptography-37.0.4-py38h2b5fc30_0
  fribidi            conda-forge/linux-64::fribidi-1.0.10-h36c2ea0_0
  gdk-pixbuf         conda-forge/linux-64::gdk-pixbuf-2.42.8-hff1cb4f_0
  graphite2          conda-forge/linux-64::graphite2-1.3.13-h58526e2_1001
  gtk2               conda-forge/linux-64::gtk2-2.24.33-h90689f9_2
  harfbuzz           conda-forge/linux-64::harfbuzz-5.1.0-hf9f4e7c_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  lcms2              conda-forge/linux-64::lcms2-2.12-hddcbb42_0
  lerc               conda-forge/linux-64::lerc-4.0.0-h27087fc_0
  libblas            conda-forge/linux-64::libblas-3.9.0-16_linux64_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-16_linux64_openblas
  libdeflate         conda-forge/linux-64::libdeflate-1.13-h166bdaf_0
  libglu             conda-forge/linux-64::libglu-9.0.0-he1b5a44_1001
  liblapack          conda-forge/linux-64::liblapack-3.9.0-16_linux64_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.21-pthreads_h78a6416_1
  libtiff            conda-forge/linux-64::libtiff-4.4.0-h0e0dad5_3
  libwebp-base       conda-forge/linux-64::libwebp-base-1.2.4-h166bdaf_0
  numpy              conda-forge/linux-64::numpy-1.23.2-py38h3a7f9d9_0
  openjpeg           conda-forge/linux-64::openjpeg-2.5.0-h7d73246_1
  pango              conda-forge/linux-64::pango-1.50.9-hc4f8a73_0
  pathlib2           conda-forge/linux-64::pathlib2-2.3.7.post1-py38h578d9bd_1
  pillow             conda-forge/linux-64::pillow-9.2.0-py38ha3b2c9c_2
  pixman             conda-forge/linux-64::pixman-0.40.0-h36c2ea0_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pypubsub           conda-forge/noarch::pypubsub-4.0.3-py_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py38h578d9bd_5
  requests           conda-forge/noarch::requests-2.28.1-pyhd8ed1ab_0
  urllib3            conda-forge/noarch::urllib3-1.26.11-pyhd8ed1ab_0
  wxpython           conda-forge/linux-64::wxpython-4.1.1-py38hc041153_7
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h7f98852_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-hd9c2040_1000
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h7f98852_1003
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002
  zlib               conda-forge/linux-64::zlib-1.2.12-h166bdaf_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
openjpeg-2.5.0       | 533 KB    | ##################################### | 100% 
lerc-4.0.0           | 275 KB    | ##################################### | 100% 
harfbuzz-5.1.0       | 2.3 MB    | ##################################### | 100% 
pango-1.50.9         | 460 KB    | ##################################### | 100% 
libopenblas-0.3.21   | 10.1 MB   | ##################################### | 100% 
charset-normalizer-2 | 35 KB     | ##################################### | 100% 
libblas-3.9.0        | 13 KB     | ##################################### | 100% 
cryptography-37.0.4  | 1.5 MB    | ##################################### | 100% 
requests-2.28.1      | 53 KB     | ##################################### | 100% 
libdeflate-1.13      | 79 KB     | ##################################### | 100% 
libcblas-3.9.0       | 13 KB     | ##################################### | 100% 
libwebp-base-1.2.4   | 404 KB    | ##################################### | 100% 
liblapack-3.9.0      | 13 KB     | ##################################### | 100% 
pillow-9.2.0         | 45.2 MB   | ##################################### | 100% 
libtiff-4.4.0        | 642 KB    | ##################################### | 100% 
cairo-1.16.0         | 1.5 MB    | ##################################### | 100% 
numpy-1.23.2         | 7.1 MB    | ##################################### | 100% 
urllib3-1.26.11      | 102 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: | 
done


(DLC_troubleshoot) anpetey@lambda-quad:~/Downloads$ python -m deeplabcut
Loading DLC 2.2.1.1...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/deeplabcut/__init__.py", line 39, in <module>
    from deeplabcut.create_project import (
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/deeplabcut/create_project/__init__.py", line 2, in <module>
    from deeplabcut.create_project.demo_data import load_demo_data
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/deeplabcut/create_project/demo_data.py", line 15, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/deeplabcut/utils/__init__.py", line 1, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 24, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 21, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/lib/trackingutils.py", line 18, in <module>
    from numba import jit
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/numba/__init__.py", line 206, in <module>
    _ensure_critical_deps()
  File "/home/anpetey/anaconda3/envs/DLC_troubleshoot/lib/python3.8/site-packages/numba/__init__.py", line 146, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.22 or less")
ImportError: Numba needs NumPy 1.22 or less
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by mfkeles** [comment]
can confirm same issue here. dealt with this by first installing wxpython then deeplabcut (which i think does exactly the same thing and downgrades numpy).

**Comment by MMathisLab** [comment]
this is a new issue as numba requires < 1.22 : `Numba needs NumPy 1.22 or less`.

**Comment by MMathisLab** [comment]
`wxpython==4.1.1` won't work for the standalone GUI, but you can use the napari-deeplabcut labeling GUI (soon to be default) and just install `pip install deeplabcut` without [gui]

**Comment by anpeter1** [comment]
Just to clarify, what about wxpython==4.1.1 should not work? I ask because this is the version we have been using with the stand alone GUI for months now, on other installations on the same computer without wxpython errors.  These installations were installed when I believe numpy <1.22 was the default.

I may be misunderstanding, but isn't `pip install deeplabcut` an installation that does not use an anaconda environment? Would this not be problematic given our standard DLC anaconda environments contain downgraded versions of various packages?  Additionally, we have multiple anaconda DLC installations for testing/debugging and undergrad training purposes, unfortunately we have yet to get docker working properly, so that is not an option. We have had so many Linux package issues (both related and unrelated to DLC), that we are wary of installing DLC outside of anaconda.

We appreciate your feedback, thank you!

**Comment by MMathisLab** [comment]
`pip install deeplabcut` can be used in a conda env, it is just the headless version (no GUI). If 4.1.1 is working for you, that is awesome -- for a long time it fails, so thats great news :)

**Comment by MMathisLab** [comment]
please now try running `pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1` in your env and/or docker. I will close, but please do post back!
