### ISSUE TITLE
Error evaluating single images

### ISSUE THREAD

**Issue by abedghanbari2** [DeepLabCut/DeepLabCut#1956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Trying to get single image evaluation to work

```
cfg = load_config('./testdlc3-abed-2021-12-06/dlc-models/iteration-0/testdlc2Dec6-trainset95shuffle1/test/pose_cfg.yaml')
df = _eval_images(
        image_paths='./dlc_cloudfactory/labeled-data1',
        test_cfg=cfg,
        snapshot_path='./testdlc3-abed-2021-12-06/dlc-models/iteration-0/testdlc2Dec6-trainset95shuffle1/train/snapshot-500.index',
)
```

However it fails to load the weights with following error:
```
NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Graph execution error:

Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "/home/ghanba/.conda/envs/DEEPLABCUT/bin/ipython", line 11, in <module>
      sys.exit(start_ipython())
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/__init__.py", line 124, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/traitlets/config/application.py", line 976, in launch_instance
      app.start()
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 318, in start
      self.shell.mainloop()
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 680, in mainloop
      self.interact()
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 673, in interact
      self.run_cell(code, store_history=True)
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2881, in run_cell
      result = self._run_cell(
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2936, in _run_cell
      return runner(coro)
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3135, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-5-032f348ecd58>", line 2, in <cell line: 2>
      df = _eval_images(
    File "<ipython-input-1-4511ed47cffc>", line 63, in _eval_images
      pose_setup = predict.setup_pose_prediction(test_cfg)
    File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/predict.py", line 51, in setup_pose_prediction
      restorer = tf.compat.v1.train.Saver()
Node: 'save/RestoreV2'
Tensor name "pose/locref_pred/block4/biases" not found in checkpoint files /projects/compsci/ramamg/USERS/ghanba/DLC/testdlc3-abed-2021-12-06/dlc-models/iteration-0/testdlc2Dec6-trainset95shuffle1/train/snapshot-700.index
         [[{{node save/RestoreV2}}]]

Original stack trace for 'save/RestoreV2':
  File "/home/ghanba/.conda/envs/DEEPLABCUT/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 318, in start
    self.shell.mainloop()
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 680, in mainloop
    self.interact()
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 673, in interact
    self.run_cell(code, store_history=True)
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2881, in run_cell
    result = self._run_cell(
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2936, in _run_cell
    return runner(coro)
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3135, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-032f348ecd58>", line 2, in <cell line: 2>
    df = _eval_images(
  File "<ipython-input-1-4511ed47cffc>", line 63, in _eval_images
    pose_setup = predict.setup_pose_prediction(test_cfg)
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/predict.py", line 51, in setup_pose_prediction
    restorer = tf.compat.v1.train.Saver()
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 933, in __init__
    self.build()
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 945, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 973, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 543, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 363, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 611, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1501, in restore_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3754, in _create_op_internal
    ret = Operation(
  File "/home/ghanba/.conda/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

### Operating System

```
CentOS Linux release 7.8.2003 (Core)
Cluster Manager v9.0
slave
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.8.2003 (Core)
CentOS Linux release 7.8.2003 (Core)
```

### DeepLabCut version

DLC 2.2.1.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

Trained the network and trying to use a snapshot to evaluate single frames

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by abedghanbari2** [comment]
The config file looks like this:

```
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
all_joints_names:
- NOSE_INDEX
- LEFT_EAR_INDEX
- RIGHT_EAR_INDEX
- BASE_NECK_INDEX
- LEFT_FRONT_PAW_INDEX
- RIGHT_FRONT_PAW_INDEX
- CENTER_SPINE_INDEX
- LEFT_REAR_PAW_INDEX
- RIGHT_REAR_PAW_INDEX
- BASE_TAIL_INDEX
- MID_TAIL_INDEX
- TIP_TAIL_INDEX
dataset: training-datasets/iteration-0/UnaugmentedDataSet_testdlc2Dec6/testdlc2_Scorer95shuffle1.pickle
dataset_type: multi-animal-imgaug
global_scale: 0.8
init_weights: /projects/compsci/ramamg/USERS/ghanba/DLC/testdlc3-abed-2021-12-06/dlc-models/iteration-0/testdlc2Dec6-trainset95shuffle1/train/checkpoint.ckpt
location_refinement: true
locref_smooth: false
locref_stdev: 7.2801
minconfidence: 0.01
multi_stage: false
net_type: resnet_50
nmsradius: 5.0
num_idchannel: 0
num_joints: 12
num_limbs: 66
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 0
  - 4
- - 0
  - 5
- - 0
  - 6
- - 0
  - 7
- - 0
  - 8
- - 0
  - 9
- - 0
  - 10
- - 0
  - 11
- - 1
  - 2
- - 1
  - 3
- - 1
  - 4
- - 1
  - 5
- - 1
  - 6
- - 1
  - 7
- - 1
  - 8
- - 1
  - 9
- - 1
  - 10
- - 1
  - 11
- - 2
  - 3
- - 2
  - 4
- - 2
  - 5
- - 2
  - 6
- - 2
  - 7
- - 2
  - 8
- - 2
  - 9
- - 2
  - 10
- - 2
  - 11
- - 3
  - 4
- - 3
  - 5
- - 3
  - 6
- - 3
  - 7
- - 3
  - 8
- - 3
  - 9
- - 3
  - 10
- - 3
  - 11
- - 4
  - 5
- - 4
  - 6
- - 4
  - 7
- - 4
  - 8
- - 4
  - 9
- - 4
  - 10
- - 4
  - 11
- - 5
  - 6
- - 5
  - 7
- - 5
  - 8
- - 5
  - 9
- - 5
  - 10
- - 5
  - 11
- - 6
  - 7
- - 6
  - 8
- - 6
  - 9
- - 6
  - 10
- - 6
  - 11
- - 7
  - 8
- - 7
  - 9
- - 7
  - 10
- - 7
  - 11
- - 8
  - 9
- - 8
  - 10
- - 8
  - 11
- - 9
  - 10
- - 9
  - 11
- - 10
  - 11
partaffinityfield_predict: true
scoremap_dir: test
sigma: 1
```

**Comment by abedghanbari2** [comment]
I have the single image evaluation from: https://github.com/DeepLabCut/DeepLabCut/blob/6ffd4441c6564e2513f1ca1ab1ed6d5085024546/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py#L532-L581

**Comment by jeylau** [comment]
Hello @abedghanbari2, `snapshot_path` should be absolute and not include the suffix `.meta` or `.index` (as expected by DeepLabCut in `init_weights`).

**Comment by abedghanbari2** [comment]
Thanks @jeylau! That fixed the problem. However, another error raises here

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 84>()
     82     image_paths[i] = dir + '/' + image_paths[i]
     83 cfg = load_config('/projects/compsci/ramamg/USERS/ghanba/DLC/testdlc3-abed-2021-12-06/dlc-models/iteration-0/testdlc2Dec6-trainset95shuffle1/test/pose_cfg.yaml')
---> 84 df = _eval_images(
     85         image_paths=image_paths,
     86         test_cfg=cfg,
     87         snapshot_path='/projects/compsci/ramamg/USERS/ghanba/DLC/testdlc3-abed-2021-12-06/dlc-models/iteration-0/testdlc2Dec6-trainset95shuffle1/train/snapshot-39400',
     88 )

Input In [2], in _eval_images(image_paths, test_cfg, snapshot_path, aug_pipeline, to_coco)
     65 print("Network evaluation underway...")
     66 for image_path in tqdm(image_paths):
---> 67     preds = _eval_single_image(
     68         image_path, test_cfg, pose_setup, aug_pipeline, to_coco,
     69     )
     70     data["predictions"][image_path] = preds
     71 data["metadata"] = {"keypoints": test_cfg["all_joints_names"]}

Input In [2], in _eval_single_image(image_path, test_cfg, pose_setup, aug_pipeline, to_coco)
     35 if aug_pipeline is not None:
     36     frame = aug_pipeline(images=[frame])[0]
     37 preds = predictma.predict_batched_peaks_and_costs(
     38     test_cfg,
     39     np.expand_dims(frame, axis=0),
---> 40     pose_setup.session,
     41     pose_setup.inputs,
     42     pose_setup.outputs,
     43 )
     44 if not preds:
     45     return {}

AttributeError: 'tuple' object has no attribute 'session'
```

The core problem here is that I do not pass `pose_setup` and it makes it using `predict.setup_pose_prediction(test_cfg)` which return tuple. However looking at `pose_setup.session` it seems to expect an object!

Here is the returned tuple for `pose_setup`:

```
ipdb> pose_setup
(<tensorflow.python.client.session.Session object at 0x2aac422b8790>, <tf.Tensor 'Placeholder:0' shape=(1, None, None, 3) dtype=float32>, [<tf.Tensor 'Sigmoid:0' shape=(1, None, None, 12) dtype=float32>, <tf.Tensor 'pose/locref_pred/block4/BiasAdd:0' shape=(1, None, None, 24) dtype=float32>, <tf.Tensor 'pose/pairwise_pred/block4/BiasAdd:0' shape=(1, None, None, 132) dtype=float32>, <tf.Tensor 'Cast_2:0' shape=(None, 4) dtype=int32>])
```

Looking into https://github.com/DeepLabCut/DeepLabCut/blob/34eb7f6042322d1af98afb487dbfd13b617d276f/deeplabcut/pose_estimation_tensorflow/core/predict.py#L56

It returns session, inputs, and outputs directly so changed the code accordingly

```
    preds = predictma.predict_batched_peaks_and_costs(
        test_cfg,
        np.expand_dims(frame, axis=0),
        pose_setup[0],
        pose_setup[1],
        pose_setup[2],
    )
```

and 

```
    pose_setup[0].close()
```

Resolved my issue

**Comment by jeylau** [comment]
Great to hear @abedghanbari2! In the future though, if you want development code found in pull requests, it's probably easier for you to clone the repo and checkout the relevant branch, so you don't have to copy-paste code around ☺️
