### ISSUE TITLE
Constant crashing when labelling using deeplabcut.label_frames(config_path)

### ISSUE THREAD

**Issue by hihosilvers** [DeepLabCut/DeepLabCut#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When labelling, using: `deeplabcut.label_frames(config_path)`, DLC constantly crashes the Jupyter kernel. Maybe once every 5-10 minutes or so. Either labelling frames or moving from one frame to the next. Usually there is no error other than Jupyter kernel has restarted. Finally saw an error message so I decided I should post here in case anyone else has experienced anything similar:

### Operating System

Windows 10 21H2

### DeepLabCut version

2.2.2

### DeepLabCut mode

multi animal

### Device type

GPU, cuda

### Steps To Reproduce

1. Env
```
packages in environment at C:\ProgramData\Miniconda3\envs\deeplabcut:
#
# Name                    Version                   Build  Channel
absl-py                   1.2.0                    pypi_0    pypi
aiohttp                   3.8.1            py38h2bbff1b_1    anaconda
aiosignal                 1.2.0              pyhd3eb1b0_0    anaconda
aom                       3.4.0                h0e60522_1    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h294d835_2    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.1              pyhd3eb1b0_0    anaconda
attrs                     22.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
bokeh                     2.4.2            py38haa95532_1    anaconda
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15.1          h5b45459_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15.1        pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38hd8c33c5_0    conda-forge
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.0.4            py38haa95532_0    anaconda
cloudpickle               2.0.0              pyhd3eb1b0_0    anaconda
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.1           py38h21b164f_0    anaconda
cycler                    0.11.0                   pypi_0    pypi
cytoolz                   0.11.0           py38he774522_0    anaconda
dask                      2022.5.0         py38haa95532_0    anaconda
dask-core                 2022.5.0         py38haa95532_0    anaconda
debugpy                   1.6.3            py38h885f38d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deeplabcut                2.2.2                    pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2022.5.0         py38haa95532_0    anaconda
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.0.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h39d44d4_0    conda-forge
ffmpeg                    5.1.1           gpl_h7b28927_101    conda-forge
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               2.0.7                    pypi_0    pypi
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.1                   pypi_0    pypi
freetype                  2.12.1               h546665d_0    conda-forge
frozenlist                1.2.0            py38h2bbff1b_0    anaconda
fsspec                    2022.3.0         py38haa95532_0    anaconda
gast                      0.4.0                    pypi_0    pypi
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
google-auth               2.6.0              pyhd3eb1b0_0    anaconda
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.48.1                   pypi_0    pypi
gst-plugins-base          1.20.3               h001b923_1    conda-forge
gstreamer                 1.20.3               h6b5321d_1    conda-forge
h5py                      3.7.0                    pypi_0    pypi
heapdict                  1.0.1              pyhd3eb1b0_0    anaconda
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                      pypi_0    pypi
imageio                   2.21.2                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        4.11.4           py38haa244fe_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.2             pyh025b116_0    conda-forge
ipympl                    0.9.2              pyhd8ed1ab_0    conda-forge
ipython                   8.5.0              pyh08f2357_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd3eb1b0_1    anaconda
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py38haa244fe_7    conda-forge
jupyter_client            7.2.2            py38haa95532_0    anaconda
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py38haa244fe_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               h1176d77_0    conda-forge
libclang                  14.0.6                   pypi_0    pypi
libclang13                14.0.6          default_h77d9078_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_4    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.39.3               hcfcfb64_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libxml2                   2.9.14               hf5bbc77_4    conda-forge
libxslt                   1.1.35               h34f844d_0    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0            py38haa95532_0    anaconda
lxml                      4.9.1            py38h294d835_0    conda-forge
lz4                       3.1.3            py38h2bbff1b_0    anaconda
lz4-c                     1.9.3                h2bbff1b_1    anaconda
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1            py38h294d835_1    conda-forge
matplotlib-base           3.5.3            py38h3268a40_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
msgpack-python            1.0.3            py38h59b6b97_0    anaconda
multidict                 5.1.0            py38h2bbff1b_2    anaconda
nb_conda                  2.2.1                     win_6    conda-forge
nb_conda_kernels          2.3.1            py38haa244fe_1    conda-forge
nbclient                  0.6.8              pyhd8ed1ab_0    conda-forge
nbconvert                 7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.0.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.6                    pypi_0    pypi
notebook                  6.4.12             pyha770c72_0    conda-forge
numba                     0.56.2                   pypi_0    pypi
numexpr                   2.8.3                    pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
oauthlib                  3.2.1                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.3.0                h0e60522_0    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4                    pypi_0    pypi
pandoc                    2.19.2               h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd3eb1b0_1    anaconda
patsy                     0.5.2                    pypi_0    pypi
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
prompt_toolkit            3.0.31               hd8ed1ab_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.2            py38h91455d4_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd3eb1b0_0    anaconda
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py38h75e37d8_0    conda-forge
pyqt5-sip                 12.11.0          py38h885f38d_0    conda-forge
pyrsistent                0.18.1           py38h294d835_1    conda-forge
python                    3.8.13          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.2.1                 pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   303              py38h294d835_0    conda-forge
pywinpty                  2.0.7            py38hd3f51b4_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.1           py38h09162b1_0    conda-forge
qt-main                   5.15.6               hf0cf448_0    conda-forge
qtconsole                 5.3.2              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.2              pyha770c72_0    conda-forge
qtpy                      2.2.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.8.0                   pypi_0    pypi
shapely                   1.8.4                    pypi_0    pypi
sip                       6.6.2            py38h885f38d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd3eb1b0_0    anaconda
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.39.3               hcfcfb64_0    conda-forge
stack_data                0.5.0              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.2                   pypi_0    pypi
svt-av1                   1.2.1                h0e60522_0    conda-forge
tables                    3.7.0                    pypi_0    pypi
tabulate                  0.8.10                   pypi_0    pypi
tblib                     1.7.0              pyhd3eb1b0_0    anaconda
tensorboard               2.10.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.0                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.27.0                   pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.15.0           py38haa244fe_0    conda-forge
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.8.12                pypi_0    pypi
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.2             pyhd3eb1b0_0    anaconda
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.1.1                hd3eb1b0_0    anaconda
typing_extensions         4.1.1              pyh06a4308_0    anaconda
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 hb210afc_7    conda-forge
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.2            py38haa95532_0    anaconda
winpty                    0.4.3                         4    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
wxpython                  4.0.7.post2              pypi_0    pypi
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yarl                      1.6.3            py38h2bbff1b_0    anaconda
zeromq                    4.3.4                h0e60522_1    conda-forge
zict                      2.0.0              pyhd3eb1b0_0    anaconda
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
```
3. Config
```
...
multianimalproject: true
identity: false
...
individuals:
- l01
- l02
- l03
- l04
- l05
- l06
- l07
- l08
- l09
- l10
- l11
- l12
- l13
- l14
- l15
- l16
- l17
- l18
- l19
- l20
- l21
- l22
- l23
- l24
- l25
- l26
- l27
- l28
- l29
- l30
- l31
- l32
- l33
- l34
- l35
- l36
- l37
- l38
- l39
- l40
uniquebodyparts: []
multianimalbodyparts:
- tip
- middle
bodyparts: MULTI!

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 2

    # Plotting configuration
skeleton:
- - bodypart1
  - bodypart2
- - bodypart2
  - bodypart3
- - bodypart1
  - bodypart3
skeleton_color: black
pcutoff: 0.6
dotsize: 4
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
default_track_method: ellipse
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```
5. Run
Run `deeplabcut.label_frames(config_path)`

### Relevant log output

```shell
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\multiple_individuals_labeling_toolbox.py", line 669, in onClick
    self.axes.add_patch(circle[0])
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\axes\_base.py", line 2363, in add_patch
    self._update_patch_limits(p)
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\axes\_base.py", line 2386, in _update_patch_limits
    patch_trf = patch.get_transform()
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\patches.py", line 278, in get_transform
    return self.get_patch_transform() + artist.Artist.get_transform(self)
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\patches.py", line 1546, in get_patch_transform
    self._recompute_transform()
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\patches.py", line 1536, in _recompute_transform
    self._patch_transform = transforms.Affine2D() \
  File "C:\ProgramData\Miniconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\transforms.py", line 2052, in translate
    self._mtx[0, 2] += tx
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
please now try running `pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1` in your env and/or docker. I will close, but please do post back!
