### ISSUE TITLE
WXAgg error in Docker

### ISSUE THREAD

**Issue by junQree** [DeepLabCut/DeepLabCut#2002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description
I've tried both: creating a conda env or using docker to import deeplabcut containers.
In both cases, the installation goes through. But when I run

$ python -m deeplabcut
-or-
$ deeplabcut-docker gui

I get very similar errors involving WXAgg. Not sure how to solve this.
#3 shows you the gpu information.

### Operating System

Ubuntu 20.04.2

### Device type

14 VCPUs and 1 GPU

### Relevant log output

```shell
>#1

(DEEPLABCUT) jkrhee@compute:~/anaconda3/envs$ python -m deeplabcut
2022-10-07 09:41:07.014745: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-07 09:41:07.267372: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-07 09:41:13.538786: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-07 09:41:13.538978: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-07 09:41:13.538999: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.2.2...
Starting GUI...
Traceback (most recent call last):
  File "/nfs/home/jkrhee/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nfs/home/jkrhee/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nfs/home/jkrhee/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/__main__.py", line 22, in <module>
    deeplabcut.launch_dlc()
  File "/nfs/home/jkrhee/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/launch_script.py", line 45, in launch_dlc
    mpl.use("WxAgg")
  File "/nfs/home/jkrhee/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/matplotlib/__init__.py", line 1156, in use
    plt.switch_backend(name)
  File "/nfs/home/jkrhee/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/matplotlib/pyplot.py", line 273, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running


>#2

(scripts_python) jkrhee@compute:~/anaconda3/envs$ deeplabcut-docker gui

                    .--,       .--,
                    ( (  \.---./  ) )
                     '.__/o   o\__.'
                       `{=  ^  =}´
                         >  u  <
 ____________________.""`-------`"".______________________
\   ___                   __         __   _____       __  /
/  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
\ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
//____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
\_________________________________________________________/
                       ___)( )(___ `-.___.
                      (((__) (__)))      ~`

Welcome to DeepLabCut docker!

groups: cannot find name for group ID 5000
latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
id: cannot find name for group ID 5000
[2022-10-07T09:49:35+0000]: Configuring a local container for user jkrhee (10006) in group 5000 (5000)
sha256:ff0a2149602cc8bbea96b063a8ec50e030565bd280b5f399aac517580438fbae
[2022-10-07T09:49:35+0000]: Build succeeded
[2022-10-07T09:49:35+0000]: Using Linux config
2022-10-07 09:49:36.328858: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 27, in <module>
    from deeplabcut import generate_training_dataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    from .pose_deterministic import DeterministicPoseDataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    from deeplabcut.utils.auxfun_videos import imread, imresize
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
[2022-10-07T09:49:39+0000]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /nfs/home/jkrhee/anaconda3/envs:/app -w /app "
Container stopped.


>#3
(scripts_python) nvidia-smi
Fri Oct  7 10:21:50 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   23C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
You can try to install env without the GUI and `conda install -c conda-forge wxpython` or wait a day for the new, non wxPython GUI which is right around the corner - or even install it now from `newGUI` branch.

**Comment by junQree** [comment]
> You can try to install env without the GUI and `conda install -c conda-forge wxpython` or wait a day for the new, non wxPython GUI which is right around the corner - or even install it now from `newGUI` branch.

I successfully installed the env without the GUI, and then installed wxpython, but DLC still doesn't run...
Thanks, I think I'll wait for the new, non wxPython GUI.

I've also tried to import DEEPLABCUT docker containers.
I couldn't get
$ sudo ubuntu-drivers autoinstall
to execute. No command found.

So if I skip that step, and get everything uncompressed from the container, and run
$ deeplabcut-docker GUI
the program runs and then stops with an error:
> ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
> [2022-10-07T09:49:39+0000]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /nfs/home/jkrhee/anaconda3/envs:/app -w /app "
> Container stopped.

**Comment by KonradDanielewski** [comment]
> I've also tried to import DEEPLABCUT docker containers.
> I couldn't get
> $ sudo ubuntu-drivers autoinstall
> to execute. No command found.

`sudo apt-get install ubuntu-drivers-common` should solve this issue. Run it first and then `sudo ubuntu-drivers autoinstall`

As for the other error, it probably again stems from bad wxPython installation, since `deeplabcut-docker GUI` should run GUI but error says it cannot cause it's running a GUI-less version already.

**Comment by junQree** [comment]
>`sudo apt-get install ubuntu-drivers-common` should solve this issue. Run it first and then `sudo ubuntu-drivers autoinstall`

Thank you, I’ll try that as soon as I can.

> As for the other error, it probably again stems from bad wxPython installation, since `deeplabcut-docker GUI` should run GUI but error says it cannot cause it's running a GUI-less version already.

Is it possible I am already running an instance of deeplabcut that is interfering with launching an another one with the GUI? I don’t think that is possible, but is it by any chance possible?

**Comment by KonradDanielewski** [comment]
If it works from a another terminal it should be independent even if run with the same virtual env.

**Comment by MMathisLab** [comment]
hi @junQree - did you try this? https://github.com/DeepLabCut/DeepLabCut/issues/1538

and, as there, could you report the output of:

```
cat /etc/gdm3/custom.conf | grep WaylandEnable
echo $XDG_SESSION_TYPE
echo $DISPLAY
```

thanks!

**Comment by MMathisLab** [comment]
please now try running `pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1` in your env and/or docker

**Comment by vv111y** [comment]
@MMathisLab 

> please now try running `pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1` in your env and/or docker

in the docker container, after some successful installs, it gets to 
```
WARNING: napari x.x.x does not provide the extra 'pyside2'
```
where `x.x.x` loops through a list of version number indefinitely

add: also problem remains when committing whatever was accomplished above

**Comment by vv111y** [comment]
the only thing I got working was the conda env running on CPU only, no GPU, after applying this fix https://github.com/DeepLabCut/DeepLabCut/issues/2118#issuecomment-1381070495

**Comment by MMathisLab** [comment]
We have decided to drop Docker support now since wxPython has been dropped for 1 year within DeepLabCut.
