### ISSUE TITLE
DLC 2.2.1.1 GUI Docker fails to start on Windows 10

### ISSUE THREAD

**Issue by ChrCoello** [DeepLabCut/DeepLabCut#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Running `docker run -it deeplabcut/deeplabcut:2.2.1.1-gui-cuda11.0.3-runtime-ubuntu18.04` fails to start an image with access to the GUI environment (`core` runs fine).

### Operating System

Windows 10

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1. docker pull deeplabcut/deeplabcut:2.2.1.1-gui-cuda11.0.3-runtime-ubuntu18.04
2. docker run deeplabcut/deeplabcut:2.2.1.1-gui-cuda11.0.3-runtime-ubuntu18.04

### Relevant log output

```shell
C:\data\containers>docker run deeplabcut/deeplabcut:2.2.1.1-gui-cuda11.0.3-runtime-ubuntu18.04
2022-10-11 14:42:27.747371: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
/usr/local/lib/python3.8/dist-packages/statsmodels/compat/pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py:81: UserWarning:
        As PyTorch is not installed, unsupervised identity learning will not be available.
        Please run `pip install torch`, or ignore this warning.

  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__main__.py", line 11, in <module>
    import wx
  File "/usr/lib/python3/dist-packages/wx/__init__.py", line 12, in <module>
    __version__ = wx.__version__.VERSION_STRING
AttributeError: partially initialized module 'wx' has no attribute '__version__' (most likely due to a circular import)
Loading DLC 2.2.1.1...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
we don't support docker for windows actually; we only support linux systems.
