### ISSUE TITLE
Getting error while trying to train using a snapshot from a different project as init_weights

### ISSUE THREAD

**Issue by lkatsouri** [DeepLabCut/DeepLabCut#2012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have a big Master network that I have trained with different arenas and light conditions using about 40 videos. I have now decided to add the points of each arena to help with analysis, so I thought the best way of doing it is making a new project, add in the new labels to the already labeled data and train using as init_weight the last snapshot from the previously trained Master project. I couldn’t manage to do it, it throws an error, does anyone have an advice?

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.1.1

### DeepLabCut mode

single animal

### Device type

NVIDIA GPU 2080

### Relevant log output

```shell
deeplabcut.train_network(config, max_snapshots_to_keep=None, saveiters=5000)
Selecting single-animal trainer
Config:
{'all_joints': [[0],
                [1],
                [2],
                [3],
                [4],
                [5],
                [6],
                [7],
                [8],
                [9],
                [10],
                [11],
                [12],
                [13],
                [14],
                [15],
                [16],
                [17],
                [18],
                [19]],
 'all_joints_names': ['snout',
                      'left_ear',
                      'right_ear',
                      'centre',
                      'lateral_left',
                      'lateral_right',
                      'tailbase',
                      'tail_end',
                      'EPM_TopLeftCorner',
                      'EPM_TopRightCorner',
                      'EPM_CentreTopLeftCorner',
                      'EPM_CentreTopRightCorner',
                      'EPM_CentreBottomLeftCorner',
                      'EPM_CentreBottomRightCorner',
                      'EPM_BottomLeftCorner',
                      'EPM_BottomRightCorner',
                      'EPM_LeftTopCorner',
                      'EPM_LeftBottomCorner',
                      'EPM_RightTopCorner',
                      'EPM_RightBottomCorner'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'augmentationprobability': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'covering': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_MouseTopDown_EPMOct11\\MouseTopDown_EPM_Loukia90shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'elastic_transform': True,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'D:\\DlcTrainedNetworks\\MouseTopDown-Loukia-2022-09-13\\dlc-models\\iteration-0\\MouseTopDownSep13-trainset90shuffle1\\train\\snapshot-300000',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_MouseTopDown_EPMOct11\\Documentation_data-MouseTopDown_EPM_90shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'motion_blur': True,
 'multi_stage': False,
 'multi_step': [[0.0001, 7500], ['5e-05', 12000], ['1e-05', 300000]],
 'net_type': 'resnet_50',
 'num_joints': 20,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'D:\\DlcTrainedNetworks\\MouseTopDown_EPM-Loukia-2022-10-11',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 5000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'D:\\DlcTrainedNetworks\\MouseTopDown_EPM-Loukia-2022-10-11\\dlc-models\\iteration-0\\MouseTopDown_EPMOct11-trainset90shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Loading already trained DLC with backbone: resnet_50
2022-10-12 22:15:37.287106: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: NVIDIA GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.71GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.23GiB/s
2022-10-12 22:15:37.288224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-10-12 22:15:37.288765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-10-12 22:15:37.289310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2022-10-12 22:15:37.289646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2022-10-12 22:15:37.290351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5956 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080, pci bus id: 0000:04:00.0, compute capability: 7.5)
Save_iters overwritten as 5000
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'D:\\DlcTrainedNetworks\\MouseTopDown_EPM-Loukia-2022-10-11\\dlc-models\\iteration-0\\MouseTopDown_EPMOct11-trainset90shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19]], 'all_joints_names': ['snout', 'left_ear', 'right_ear', 'centre', 'lateral_left', 'lateral_right', 'tailbase', 'tail_end', 'EPM_TopLeftCorner', 'EPM_TopRightCorner', 'EPM_CentreTopLeftCorner', 'EPM_CentreTopRightCorner', 'EPM_CentreBottomLeftCorner', 'EPM_CentreBottomRightCorner', 'EPM_BottomLeftCorner', 'EPM_BottomRightCorner', 'EPM_LeftTopCorner', 'EPM_LeftBottomCorner', 'EPM_RightTopCorner', 'EPM_RightBottomCorner'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_MouseTopDown_EPMOct11\\MouseTopDown_EPM_Loukia90shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'D:\\DlcTrainedNetworks\\MouseTopDown-Loukia-2022-09-13\\dlc-models\\iteration-0\\MouseTopDownSep13-trainset90shuffle1\\train\\snapshot-300000', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_MouseTopDown_EPMOct11\\Documentation_data-MouseTopDown_EPM_90shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.0001, 7500], ['5e-05', 12000], ['1e-05', 300000]], 'net_type': 'resnet_50', 'num_joints': 20, 'pos_dist_thresh': 17, 'project_path': 'D:\\DlcTrainedNetworks\\MouseTopDown_EPM-Loukia-2022-10-11', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 5000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'augmentationprobability': 0.5, 'elastic_transform': True, 'covering': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2022-10-12 22:15:46.216607: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_grad_input_ops.cc:93 : Invalid argument: Conv2DSlowBackpropInput: input depth must be evenly divisible by filter depth
2022-10-12 22:15:46.217233: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_grad_input_ops.cc:93 : Invalid argument: Conv2DSlowBackpropInput: input depth must be evenly divisible by filter depth
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Conv2DSlowBackpropInput: input depth must be evenly divisible by filter depth
	 [[{{node pose/locref_pred/block4/conv2d_transpose}}]]
	 [[huber_loss/num_present/broadcast_weights/assert_broadcastable/is_valid_shape/else/_24/has_valid_nonscalar_shape/then/_116/has_valid_nonscalar_shape/has_invalid_dims/concat/_609]]
  (1) Invalid argument: Conv2DSlowBackpropInput: input depth must be evenly divisible by filter depth
	 [[{{node pose/locref_pred/block4/conv2d_transpose}}]]
0 successful operations.
0 derived errors ignored.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8d2cb864457b>", line 1, in <cell line: 1>
    deeplabcut.train_network(config, max_snapshots_to_keep=None, saveiters=5000)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 218, in train_network
    raise e
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 207, in train_network
    train(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 272, in train
    [_, loss_val, summary] = sess.run(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Conv2DSlowBackpropInput: input depth must be evenly divisible by filter depth
	 [[node pose/locref_pred/block4/conv2d_transpose (defined at C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\layers\layers.py:1449) ]]
	 [[huber_loss/num_present/broadcast_weights/assert_broadcastable/is_valid_shape/else/_24/has_valid_nonscalar_shape/then/_116/has_valid_nonscalar_shape/has_invalid_dims/concat/_609]]
  (1) Invalid argument: Conv2DSlowBackpropInput: input depth must be evenly divisible by filter depth
	 [[node pose/locref_pred/block4/conv2d_transpose (defined at C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\layers\layers.py:1449) ]]
0 successful operations.
0 derived errors ignored.
Errors may have originated from an input operation.
Input Source operations connected to node pose/locref_pred/block4/conv2d_transpose:
 resnet_v1_50/block4/unit_3/bottleneck_v1/Relu (defined at C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\nets\resnet_v1.py:128)
Input Source operations connected to node pose/locref_pred/block4/conv2d_transpose:
 resnet_v1_50/block4/unit_3/bottleneck_v1/Relu (defined at C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\nets\resnet_v1.py:128)
Original stack trace for 'pose/locref_pred/block4/conv2d_transpose':
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 509, in <module>
    pydevconsole.start_client(host, port)
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 437, in start_client
    process_exec_queue(interpreter)
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 284, in process_exec_queue
    interpreter.add_exec(code_fragment)
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_code_executor.py", line 108, in add_exec
    more, exception_occurred = self.do_add_exec(code_fragment)
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_ipython_console.py", line 36, in do_add_exec
    more, exception_occurred = self.interpreter.add_exec(code_fragment.text)
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_ipython_console_011.py", line 379, in add_exec
    res = self.ipython.run_cell(line, store_history=True)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_cell
    result = self._run_cell(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 2936, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3135, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3338, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8d2cb864457b>", line 1, in <cell line: 1>
    deeplabcut.train_network(config, max_snapshots_to_keep=None, saveiters=5000)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 207, in train_network
    train(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 170, in train
    losses = PoseNetFactory.create(cfg).train(batch)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\base.py", line 22, in train
    heads = self.get_net(batch[Batch.inputs])
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 67, in get_net
    return self.prediction_layers(net, end_points)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 47, in prediction_layers
    out = super(PoseResnet, self).prediction_layers(features, scope, reuse,)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\base.py", line 91, in prediction_layers
    out["locref"] = prediction_layer(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\layers.py", line 29, in prediction_layer
    pred = slim.conv2d_transpose(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\layers\layers.py", line 1449, in convolution2d_transpose
    outputs = layer.apply(inputs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 1695, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\base.py", line 561, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 692, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 336, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 463, in _call_unconverted
    return f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 1315, in call
    outputs = backend.conv2d_transpose(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\backend.py", line 5395, in conv2d_transpose
    x = nn.conv2d_transpose(x, kernel, output_shape, strides,
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2486, in conv2d_transpose
    return conv2d_transpose_v2(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2570, in conv2d_transpose_v2
    return gen_nn_ops.conv2d_backprop_input(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1284, in conv2d_backprop_input
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
You shouldn't start a new project, as the edges of the NN graph won't match and it cannot be used for int weights. If you want to add points, that was always possible and automated. See docs here: https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html?highlight=add%20points#d-label-frames
<img width="682" alt="Screen Shot 2022-10-19 at 10 56 31 AM" src="https://user-images.githubusercontent.com/28102185/196645493-214e851e-aa2c-4c1a-b208-1f8445f50f4b.png">

**Comment by lkatsouri** [comment]
I have multiple arenas that were recorded with different cameras/lenses. What I was aiming was to train a new network for each one using the already labeled animal parts and adding on top the arena points for each of my tasks since the arenas are so different and I need them for the analysis (ie OF is round vs EPM that is a cross). Should I be training from scratch?
