### ISSUE TITLE
maDLC 2.2.0.3 error while refining tracklets

### ISSUE THREAD

**Issue by Zou-Jingyi** [DeepLabCut/DeepLabCut#2017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Can not “refine tracklets” during maDLC.

### Operating System

linux ubuntu

### DeepLabCut version

2.2.0.3

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

In GUI , I completed the 'analyze videos' and got el.pickle, full.pickle, meta.pickle and assembiles.pickle files.  

When I run 'Refine tracklets', error shows and I can not get .h5 file to do the next step.

### Relevant log output

```shell
Processing...  /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/videos/20211209-4-1.mp4
/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py:123: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return mode(self.data[..., 3], axis=None, nan_policy="omit")[0][0]
100%|█████████████████████████████████████| 2211/2211 [00:00<00:00, 4651.21it/s]
Traceback (most recent call last):
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 654, in stitch
    self.paths = self.reconstruct_paths()
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 952, in reconstruct_paths
    path = self.reconstruct_path(node.replace("in", "out"))
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 962, in reconstruct_path
    path.extend(self.reconstruct_path(node.replace("in", "out")))
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 962, in reconstruct_path
    path.extend(self.reconstruct_path(node.replace("in", "out")))
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 962, in reconstruct_path
    path.extend(self.reconstruct_path(node.replace("in", "out")))
  [Previous line repeated 984 more times]
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 958, in reconstruct_path
    for node, flow in self.flow[source].items():
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/refine_tracklets.py", line 317, in create_tracks
    deeplabcut.stitch_tracklets(
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 1103, in stitch_tracklets
    stitcher.stitch()
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 732, in stitch
    raise ValueError(
ValueError: Could not reconstruct 2 tracks from the tracklets given.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @Ivy-ZOU I would update your code to the latest; a  lot of updates to the code since then (see releases). 

But your error "ValueError: Could not reconstruct 2 tracks from the tracklets given" is a real error, if the algorithm cannot find 2 animals from your data. You need to (1) check how good the detections are by doing this: https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#attention
(2) if and only if detections are good, then proceed. The latest versions also have autoTrack=True, so I would use this feature.

**Comment by Zou-Jingyi** [comment]
Thank you very much for your reply! Since I stalled on 2.2.0.3 windows, I switched to Linux. I am using ubuntu, and training with dlc2.2.3 now. 
I use 150 frames from video A for training and I think the model good. I can get the .h5 file of video A after analyze video, but when I analyze video B, I got four .pickle files and two errors.  When I choose the number of animals to be 1, I can get .h5 file, even though there are two animals on the video. 
Both videos were shot in almost the same scene, and both have only two animals(fish). May I ask if this is because I made a mistake in any step? I really don't know why. I've tried everything I know.
This is the output I got. 

Starting GUI...
Gtk-Message: 16:12:49.156: Failed to load module "atk-bridge"
Gtk-Message: 16:12:49.167: Failed to load module "canberra-gtk-module"
DLC network loading and video analysis starting ... 
Using snapshot-50000 for model /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/dlc-models/iteration-0/distanceOct14-trainset95shuffle2
/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Activating extracting of PAFs
2022-10-19 16:14:02.943417: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-19 16:14:04.244889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9402 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5
2022-10-19 16:14:04.283732: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
Starting to analyze %  /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/videos/20211208-3-1.mp4
Video already analyzed! /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/videos/20211208-3-1DLC_dlcrnetms5_distanceOct14shuffle2_50000.h5
Using snapshot-50000 for model /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/dlc-models/iteration-0/distanceOct14-trainset95shuffle2
Processing...  /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/videos/20211208-3-1.mp4
Tracklets already computed /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/videos/20211208-3-1DLC_dlcrnetms5_distanceOct14shuffle2_50000_el.pickle
Set overwrite = True to overwrite.
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  /home/molethol/data/zou/distance-KOfamiliar-2022-10-14/videos/20211208-3-1.mp4
/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py:127: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return mode(self.data[..., 3], axis=None, nan_policy="omit")[0][0]
100%|█████████████████████████████████████| 3505/3505 [00:00<00:00, 6643.65it/s]
Traceback (most recent call last):
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 674, in stitch
    self.paths = self.reconstruct_paths()
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 976, in reconstruct_paths
    path = self.reconstruct_path(node.replace("in", "out"))
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 986, in reconstruct_path
    path.extend(self.reconstruct_path(node.replace("in", "out")))
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 986, in reconstruct_path
    path.extend(self.reconstruct_path(node.replace("in", "out")))
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 986, in reconstruct_path
    path.extend(self.reconstruct_path(node.replace("in", "out")))
  [Previous line repeated 983 more times]
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 982, in reconstruct_path
    for node, flow in self.flow[source].items():
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/analyze_videos.py", line 497, in analyze_videos
    scorername = deeplabcut.analyze_videos(
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 645, in analyze_videos
    stitch_tracklets(
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 1181, in stitch_tracklets
    stitcher.stitch()
  File "/home/molethol/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 752, in stitch
    raise ValueError(
ValueError: Could not reconstruct 2 tracks from the tracklets given.
