### ISSUE TITLE
Why deeplabcut.create_labeled_video() inside Docker, uses the CPU instead of the GPU? to create videos

### ISSUE THREAD

**Issue by rnrpereira** [DeepLabCut/DeepLabCut#202]
Using: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut 2.0.4.1
=> **Why during deeplabcut.create_labeled_video() inside Docker, python is using the CPU instead of the GPU to create videos (... save_frames = True)?** My GPU is 0%; 3 threads of my CPU are 100%.
Obs:. It also says I cannot use save_frame=False for cropped videos! Has it been implemented?

```
In [16]: deeplabcut.create_labeled_video(path_config,['/home/rodrigo/DLC_proj_Joao-Rod-2019-02-04/videos/CTR_R4_WaltDisney_NAOFamiliar_1.avi'],save_fram
    ...: es=True)
Starting %  /home/rodrigo/DLC_proj_Joao-Rod-2019-02-04/videos ['/home/rodrigo/DLC_proj_Joao-Rod-2019-02-04/videos/CTR_R4_WaltDisney_NAOFamiliar_1.avi']
Loading  /home/rodrigo/DLC_proj_Joao-Rod-2019-02-04/videos/CTR_R4_WaltDisney_NAOFamiliar_1.avi and data.
True 255 537 93 446
41230
Duration of video [s]:  1374.33 , recorded with  30.0 fps!
Overall # of frames:  41230 with cropped frame dimensions:  282 353
Generating frames and creating video.
                                                                                                                                                       [mpeg4 @ 0x55133180] slice end not reached but screenspace end (7 left 7E0000, score= -2)
Exception in thread Thread-740:
Traceback (most recent call last):                  
Traceback (most recent call last):                                                                                    | 6/41230 [00:00<46:10, 14.88it/s]
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()                                                                                                       | 42/41230 [00:02<47:46, 14.37it/s]
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "/usr/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

**Comment by rnrpereira** [comment]
Following `RuntimeError: Set changed size during iteration`

```
All labeled frames were created, now generating video...
HALLO, ['file00964.png', 'file03932.png', 'file22860.png', 'file21683.png', 'file25800.png', 'file26000.png', 'file16480.png', 'file12037.png', 'file33168.png', 'file19971.png', 'file00688.png', 'file35950.png', .....]

ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, image2, from 'file%05d.png':
  Duration: 00:22:54.33, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 282x353 [SAR 3937:3937 DAR 282:353], 30 fps, 30 tbr, 30 tbn, 30 tbc
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0x219f680] using SAR=1/1
[libx264 @ 0x219f680] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0x219f680] profile High 4:4:4 Predictive, level 2.1, 4:4:4 8-bit
[libx264 @ 0x219f680] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '../CTR_R4_WaltDisney_NAOFamiliar_1DeepCut_resnet50_DLC_proj_JoaoFeb4shuffle1_650000_labeled.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 282x353 [SAR 1:1 DAR 282:353], q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc56.60.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame=41230 fps=498 q=-1.0 Lsize=   17918kB time=00:22:54.26 bitrate= 106.8kbits/s    
video:17434kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.777942%
[libx264 @ 0x219f680] frame I:171   Avg QP:19.66  size:  5455
[libx264 @ 0x219f680] frame P:11916 Avg QP:23.19  size:   821
[libx264 @ 0x219f680] frame B:29143 Avg QP:25.88  size:   245
[libx264 @ 0x219f680] consecutive B-frames:  0.7% 12.9%  6.6% 79.8%
[libx264 @ 0x219f680] mb I  I16..4: 13.6% 71.3% 15.1%
[libx264 @ 0x219f680] mb P  I16..4:  0.4%  1.4%  0.2%  P16..4: 32.7%  6.3%  5.1%  0.0%  0.0%    skip:53.9%
[libx264 @ 0x219f680] mb B  I16..4:  0.0%  0.1%  0.0%  B16..8: 24.3%  1.1%  0.2%  direct: 0.3%  skip:74.0%  L0:42.8% L1:56.0% BI: 1.2%
[libx264 @ 0x219f680] 8x8 transform intra:72.3% inter:91.7%
[libx264 @ 0x219f680] coded y,u,v intra: 58.9% 5.9% 4.5% inter: 5.3% 0.2% 0.1%
[libx264 @ 0x219f680] i16 v,h,dc,p: 17% 32% 14% 37%
[libx264 @ 0x219f680] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 20% 22%  6%  6%  6%  7%  6%  8%
[libx264 @ 0x219f680] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 27% 13%  5%  8%  6%  7%  4%  6%
[libx264 @ 0x219f680] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x219f680] ref P L0: 57.0%  8.8% 22.3% 11.9%  0.0%
[libx264 @ 0x219f680] ref B L0: 76.5% 18.0%  5.5%
[libx264 @ 0x219f680] ref B L1: 93.4%  6.6%
[libx264 @ 0x219f680] kb/s:103.91

In [17]: 
```

**Comment by AlexEMG** [comment]
The code you are using saves each frame individually and is thus very slow; for quicker processing you can use: ```save_frames = False)```. However cropping is then not supported yet. Would be great if you contribute code for processing the videos on a GPU. Currently, we are busy with many other upgrades.

**Comment by MMathisLab** [comment]
@rnrpereira - cropping is now supported with ``save_frames=False`` (as of #309)
