### ISSUE TITLE
napari load_settings TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dprotter** [DeepLabCut/DeepLabCut#2046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Installed DLC 2.3rc2. Ran the GUI once successfully, then went to open again and DLC crashes when trying to load recent file names. Ive seen this on two different Ubuntu installations now.

### Operating System

Ubuntu 20.04.2 LTS

### DeepLabCut version

 DLC 2.3rc2

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1. install  DLC 2.3rc2 (pip)
2. open gui
3. close gui
4. deactivate conda env
5. activate conda env
6. open gui again

### Relevant log output

```shell
$ python -m deeplabcut
Loading DLC 2.3rc1...
Starting GUI...
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/__main__.py", line 22, in <module>
    launch_dlc()
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/gui/launch_script.py", line 57, in launch_dlc
    window = MainWindow(app)
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/gui/window.py", line 76, in __init__
    self.load_settings()
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/gui/window.py", line 107, in load_settings
    for filename in filenames:
TypeError: 'NoneType' object is not iterable
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @dprotter, I could not reproduce this bug 🧐 Could you maybe try reinstalling DLC? It is loading 2.3rc1 judging from your Terminal output.

**Comment by dprotter** [comment]
oops, youre probably right that I noted the wrong version. I ended up just hackily fixing this by adding a check for NoneTypes in the actual code. However, even after upgrading I get the same error.

After upgrading:

`Loading DLC 2.3rc2...
Starting GUI...
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/__main__.py", line 22, in <module>
    launch_dlc()
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/gui/launch_script.py", line 56, in launch_dlc
    window = MainWindow(app)
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/gui/window.py", line 76, in __init__
    self.load_settings()
  File "/home/dprotter/anaconda3/envs/DLC-GPU-2/lib/python3.8/site-packages/deeplabcut/gui/window.py", line 107, in load_settings
    for filename in filenames:
TypeError: 'NoneType' object is not iterable
`
