### ISSUE TITLE
napari can't open data in labeled-data

### ISSUE THREAD

**Issue by guiwitz** [DeepLabCut/DeepLabCut#2050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have a fresh install of DLC on M1 and I'm trying to go through a basic workflow. I managed to extract frames from the ```m3v1mp4.mp4``` video which creates a series of png in the ```labeled-folder``` in a sub-folder called ```m3v1mp4```. Now I go to the ```Label frames``` tab, click on the ```Label frames``` button and select the ```labeled-folder/m3v1mp4``` as indicated in the docs. Nothing happens and I get an error message ending with 
```
ValueError: Video path "/Users/gw18g940/Desktop/testdlc2-GW-2022-11-16/labeled-data/m3v1mp4" does not point to a file.
```
as it is only possible to select a folder at this step, the error is a bit puzzling.

napari still opens with the plugin on the right side. Now I can drag and drop a folder on napari and there are two cases:
- if I use the napari Deeplabcut reader, I get the same error as above
- if I use the napari builtins reader, I get a long error: 
```
Traceback (most recent call last):
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 830, in _qt_open
    self.viewer.open(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1024, in open
    layers = self._open_or_raise_error(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1146, in _open_or_raise_error
    raise MultipleReaderError(
napari.errors.reader_errors.MultipleReaderError: Multiple plugins found capable of reading /Users/gw18g940/Desktop/testdlc2-GW-2022-11-16/labeled-data/m3v1mp4. Select plugin from {'napari': 'napari builtins', 'napari-deeplabcut': 'napari DeepLabCut'} and pass to reading function e.g. `viewer.open(..., plugin=...)`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 1191, in dropEvent
    self._qt_open(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 848, in _qt_open
    handle_gui_reading(filenames, self, stack, **kwargs)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/_qt/dialogs/qt_reader_dialog.py", line 199, in handle_gui_reading
    open_with_dialog_choices(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/_qt/dialogs/qt_reader_dialog.py", line 292, in open_with_dialog_choices
    qt_viewer.viewer.open(paths, stack=stack, plugin=plugin_name, **kwargs)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1242, in _add_layers_with_plugins
    added.extend(self._add_layer_from_data(*_data))
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1316, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/utils/migrations.py", line 44, in _update_from_dict
    return func(*args, **kwargs)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 819, in add_image
    self.layers.append(layer)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/_collections_abc.py", line 1073, in append
    self.insert(len(self), value)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/layerlist.py", line 166, in insert
    super().insert(index, new_layer)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/utils/events/containers/_selectable_list.py", line 66, in insert
    super().insert(index, value)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/utils/events/containers/_evented_list.py", line 188, in insert
    self.events.inserted(index=index, value=value)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/utils/events/event.py", line 757, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/utils/events/event.py", line 794, in _invoke_callback
    _handle_exception(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/utils/events/event.py", line 781, in _invoke_callback
    cb(event)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari_deeplabcut/_widgets.py", line 397, in on_insert
    "root": layer.metadata["root"],
KeyError: 'root'
```

The images in the folder still get opened, I can also drag and drop the config.yml file and I can annotate the images. The problem is that the annotations can't be saved as no h5 file is saved.

Alternatively, once napari is open, I can also open the movie file directly (here it doesn't ask which plugin I want to use) and I can also add the config.yml file. No error is generated but when I try to save the annotations I get:
```
Traceback (most recent call last):
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari_deeplabcut/_widgets.py", line 207, in <lambda>
    lambda: _save_layers_dialog(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari_deeplabcut/_widgets.py", line 94, in _save_layers_dialog
    self.viewer.layers.save("", selected=True, plugin="napari-deeplabcut")
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/components/layerlist.py", line 476, in save
    return save_layers(path, layers, plugin=plugin, _writer=_writer)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/plugins/io.py", line 229, in save_layers
    _written, writer_name = _write_single_layer_with_plugins(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/plugins/io.py", line 442, in _write_single_layer_with_plugins
    written_paths, writer_name = _npe2.write_layers(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari/plugins/_npe2.py", line 101, in write_layers
    paths, writer = io_utils.write_get_writer(
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/npe2/io_utils.py", line 115, in write_get_writer
    return _write(path, layer_data, plugin_name=plugin_name, return_writer=True)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/npe2/io_utils.py", line 224, in _write
    res = writer.exec(args=args)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/npe2/manifest/utils.py", line 65, in exec
    return self.get_callable(_registry)(*args, **kwargs)
  File "/Users/gw18g940/mambaforge/envs/DLC2_3_M1/lib/python3.9/site-packages/napari_deeplabcut/_writer.py", line 45, in write_hdf
    root = meta["root"]
KeyError: 'root'
```

### Operating System

Mac M1 installed with https://github.com/DeepLabCut/DeepLabCut/blob/master/conda-environments/DLC2_3_M1.yaml

### DeepLabCut version

2.3rc2 

### DeepLabCut mode

single animal

### Device type

M1 GPU

### Steps To Reproduce

1. Install the environment with https://github.com/DeepLabCut/DeepLabCut/blob/master/conda-environments/DLC2_3_M1.yaml
2. Start DLC, create a standard project for ```m3v1mp4.mp4```
3. Extract frames
4. Click and ```Label Frames```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Alright, I just got this one... Because the labeled-data folder ends with one of our supported video extensions, our napari plugin uses the wrong file reader to load the data 😅. I'll push a fix. Thanks @guiwitz for reporting this bug.

**Comment by jeylau** [comment]
This should now be fixed with [ee44e0fb55ee26f824d18d47711259f44a565cd7](https://github.com/DeepLabCut/napari-deeplabcut/commit/ee44e0fb55ee26f824d18d47711259f44a565cd7). You could try it out with `pip install --no-deps --force-reinstall git+https://github.com/DeepLabCut/napari-deeplabcut.git`.

**Comment by guiwitz** [comment]
Yes that works now! I had my fair share of trouble with reader selection in napari, so I sympathise with you here :wink:

**Comment by jeylau** [comment]
Awesome, I'll release a new version of napari-deeplabcut soon.
