### ISSUE TITLE
Videos not analyzing 

### ISSUE THREAD

**Issue by MaureenAscona** [DeepLabCut/DeepLabCut#2095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to analyze videos from a trained network and it does not do anything. I don't get a CSV file and I don't get any graphs

### Operating System

operating system
Windows 10

### DeepLabCut version

dlc version
2.2.1

### DeepLabCut mode

single animal

### Device type

gpu
NVIDIA RTX 2070 SUPER

### Relevant log output

```shell
Using snapshot-400000 for model C:\Users\mca47\Desktop\Machine Learning\WT EAE Project\EAE Project-Maureen-2022-12-12\dlc-models\iteration-0\EAE ProjectDec12-trainset70shuffle4
2022-12-21 13:35:14.221999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 SUPER computeCapability: 7.5
coreClock: 1.785GHz coreCount: 40 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2022-12-21 13:35:14.222170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-12-21 13:35:14.223311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-12-21 13:35:14.223549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2022-12-21 13:35:14.223805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2022-12-21 13:35:14.224184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5973 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
Starting to analyze %  C:\Users\mca47\Desktop\EAE 40dpi 3.12.21\GH010181_1616164640231.MP4
Loading  C:\Users\mca47\Desktop\EAE 40dpi 3.12.21\GH010181_1616164640231.MP4
Duration of video [s]:  121.92 , recorded with  29.97 fps!
Overall # of frames:  3654  found with (before cropping) frame dimensions:  1080 1920
Starting to extract posture
  0%|                                                                                         | 0/3654 [00:00<?, ?it/s]2022-12-21 13:35:15.123547: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2022-12-21 13:35:15.553964: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8201
2022-12-21 13:35:16.322079: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2022-12-21 13:35:16.825572: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
100%|█████████████████████████████████████████████████████████████████████████████▌| 3636/3654 [05:41<00:01, 10.64it/s]
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Loading  C:\Users\mca47\Desktop\EAE 40dpi 3.12.21\GH010181_1616164640231.MP4 and data.
No unfiltered data file found in C:\Users\mca47\Desktop\EAE 40dpi 3.12.21 for video GH010181_1616164640231 and scorer DLC_resnet50_EAE ProjectDec12shuffle4_400000.
Traceback (most recent call last):
  File "C:\Users\mca47\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\plotting.py", line 287, in plot_trajectories
    df, _, _, suffix = auxiliaryfunctions.load_analyzed_data(
  File "C:\Users\mca47\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 771, in load_analyzed_data
    filepath, scorer, suffix = find_analyzed_data(
  File "C:\Users\mca47\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 757, in find_analyzed_data
    raise FileNotFoundError(msg)
FileNotFoundError: No unfiltered data file found in C:\Users\mca47\Desktop\EAE 40dpi 3.12.21 for video GH010181_1616164640231 and scorer DLC_resnet50_EAE ProjectDec12shuffle4_400000.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mca47\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 568, in analyze_videos
    deeplabcut.plot_trajectories(
  File "C:\Users\mca47\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\plotting.py", line 321, in plot_trajectories
    _ = auxiliaryfunctions.load_detection_data(
  File "C:\Users\mca47\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 788, in load_detection_data
    raise ValueError(f"Unrecognized track_method={track_method}")
ValueError: Unrecognized track_method=
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
couple of issues, one did you check the errors?

```
No unfiltered data file found in C:\Users\mca47\Desktop\EAE 40dpi 3.12.21 for video GH010181_1616164640231 and scorer DLC_resnet50_EAE ProjectDec12shuffle4_400000.

FileNotFoundError: No unfiltered data file found in C:\Users\mca47\Desktop\EAE 40dpi 3.12.21 for video GH010181_1616164640231 and scorer DLC_resnet50_EAE ProjectDec12shuffle4_400000.

```

(1) your project has spaces in the name, which are not allowed: "EAE Project-Maureen-2022-12-12" 
(2) your video folder has "." in it, which won't work -- many systems use the . to parse files from the name from the ending type ...

**Comment by jeylau** [comment]
I'd add that video analysis seems to stop prematurely at frame 3636; it looks like an old bug. Updating deeplabcut with `pip install -U deeplabcut` should do the trick.

**Comment by MaureenAscona** [comment]
@MMathisLab I didn't realize we couldn't have spaces in the name, I've worked with this project for a while and I haven't had an issue with the naming scheme. (2) Also, I will change this right away thanks. 

Also, I have another question if you don't mind. I feel like I train and refine my network and everytime I see the created analyzed video, It doesn't fix the training that I did to improve the weird analysis. Do you think this has something to do with the net type that I choose? I train for 500,000 iterations and see no improvements. And i'm making sure all training sets are merged. Do you have any insight?

**Comment by MaureenAscona** [comment]
@jeylau there should only be around 3600 frames so that sounds about right to me. I did run the pip install though, and I have a question as well, everytime I update, nothing works until I uninstall tables 3.7 and reinstall tables 3.6.1. Do you know why this is occurring? I'm running V.2.2.3

**Comment by jeylau** [comment]
@MaureenAscona, your video has 3654 frames, but the analysis does stop before, which is an old bug. If you update, the video analysis should give you the desired output files 😊. As for the `tables` package, I do have v3.7.0, but I'm using macOS. Maybe this is something specific to Windows, though I'm only guessing.

**Comment by jeylau** [comment]
HI @MaureenAscona, do you get it to analyze the video fully?

**Comment by MaureenAscona** [comment]
@jeylau yes thank you! The newest update works much better. It was a bit of an adjustment to learn napari but yes all of the video is being analyzed now. Thanks so much!

**Comment by jeylau** [comment]
Sweet, great to hear! ☺️
