### ISSUE TITLE
df.index.levels[1] list index out of range

### ISSUE THREAD

**Issue by mano2991** [DeepLabCut/DeepLabCut#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

WARNING: QStatusBar::insertPermanentWidget: Index out of range (0), appending widget. 

after labelling the frames I'm getting an error index out of range (0). I tried to continue to the next step as it was a warning message. and started to train my data where I stuck with the trace back error 

### Operating System

operating system Windows 11

### DeepLabCut version

DeepLabCut version GUI 2.2rc3

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

step1: activate the DLC conda environment ` conda activate DLC`
step2: start the DLC GUI  `python -m deeplabcut`
step3: Created a new project and uploaded the video files.
step4: extract the frames.
step4: label the frames.
![image](https://user-images.githubusercontent.com/13638496/209307895-f6ed5c22-e8f4-464b-9558-bc6a25751abd.png)

### Relevant log output

```shell
WARNING: QStatusBar::insertPermanentWidget: Index out of range (0), appending widget
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\gui\tabs\create_training_dataset.py", line 95, in create_training_dataset
    deeplabcut.create_training_dataset(
  File "C:\ProgramData\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 857, in create_training_dataset
    Data = merge_annotateddatasets(
  File "C:\ProgramData\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 479, in merge_annotateddatasets
    conversioncode.guarantee_multiindex_rows(data)
  File "C:\ProgramData\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\utils\conversioncode.py", line 247, in guarantee_multiindex_rows
    df.index = df.index.set_levels(df.index.levels[1].astype(str), level=1)
  File "C:\ProgramData\Miniconda3\envs\DLC\lib\site-packages\pandas\core\indexes\frozen.py", line 73, in __getitem__
    return super().__getitem__(n)
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @mano2991, I updated the title, as the problem you're facing does not relate to the warning, but to your data file instead. 

Check #2072 and this answer specifically https://github.com/DeepLabCut/DeepLabCut/issues/2072#issuecomment-1346102566, it should point you to the solution.
