### ISSUE TITLE
DLC installtion error 

### ISSUE THREAD

**Issue by mano2991** [DeepLabCut/DeepLabCut#2102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to install DeepLabcut . Im using M1 macbook, So i have followed https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html for installing DLC.

```
Traceback (most recent call last):
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/manojkumark/Desktop/Test_DLC/DeepLabCut-2.3rc3/conda-environments/DeepLabCut/deeplabcut/__init__.py", line 16, in <module>
    import tensorflow as tf
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 28, in <module>
    import ctypes
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: <E87F2CF1-C39F-319B-AC95-8B0D23B12C36> /Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
  Reason: tried: '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libffi.8.dylib' (no such file), '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)
```

### Operating System

operating system : MacOS

### DeepLabCut version

dlc version : DeepLabCut-2.3rc3

### DeepLabCut mode

single animal

### Device type

gpu MAC_M1

### Steps To Reproduce

Step 1 : Clone the DLC repo.
`git clone https://github.com/DeepLabCut/DeepLabCut.git`

Step 2 : Change your Director to the conda-environment.
`cd DeepLabCut/conda-environments`

Step 3: download TensorFlow for installation.
`https://drive.google.com/file/d/17pSwfoNuyf3YR8vCaVggHeI-pMQ3xL7l/view?usp=sharing`

Step 4: Create the Conda environment 
`conda env create -f DEEPLABCUT_M1.yaml`

note i have chnage the name of  DEEPLABCUT_M1 to DLC_M1
<img width="689" alt="Screenshot 2022-12-24 at 01 25 21" src="https://user-images.githubusercontent.com/13638496/209400469-2159504e-3c2d-4b2d-a63b-221026f98931.png">

Step 5: activate the DLC conda environment 
```
conda activate DLC_M1
conda env config vars set CONDA_SUBDIR=osx-64
```

Step 6: reactivate the DLC conda environment 
```
conda deactivate
conda activate DLC_M1
conda env update -f DEEPLABCUT_M1.yaml
```

Step 7:  install tensor flow 
`pip install tensorflow-2.4.1-py3-none-any.whl --no-dependencies --force-reinstall`

Step 8: start DLC
`pythonw -m deeplabcut`

<img width="1512" alt="Screenshot 2022-12-24 at 00 46 41" src="https://user-images.githubusercontent.com/13638496/209400841-87c48593-3be1-4946-a99d-6f37161bfb0d.png">

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/manojkumark/Desktop/Test_DLC/DeepLabCut-2.3rc3/conda-environments/DeepLabCut/deeplabcut/__init__.py", line 16, in <module>
    import tensorflow as tf
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 28, in <module>
    import ctypes
  File "/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: <E87F2CF1-C39F-319B-AC95-8B0D23B12C36> /Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
  Reason: tried: '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libffi.8.dylib' (no such file), '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/manojkumark/miniconda/envs/DLC_M1/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by bendichter** [comment]
@mano2991 https://github.com/DeepLabCut/DeepLabCut/issues/2056 might be relevant

**Comment by yanavdsande** [comment]
HI! I also had this issue and tried a couple of things and eventually got it to work: 
My output also stated it could not find certain versions of libffi - so I first figured it had something to do with the path. After further exploration, I found that the path was correct. 
I then focused on the architecture problem since that was a repeated error: have ARM64 need X86_64. I found that this has to do with indeed your anaconda version, but it was a little different than thread #2056 since the minicondaversion installed already said it was the ARM64 version (don't know if that also happened with you after following the steps described in #2056) and I still got that error. I then tried to run both Miniconda arm 64 and Miniconda x86_64 side by side - but that was quite an ugly fix. Especially because it is a hassle, but also because the M1 yaml file does not seem to work on Miniconda x86_64 (which is kind of expected) - it did setting up the Deeplabcut yaml file - but you don't have the benefits of the M1/M2 if you run it like that. 

So here is how I eventually fixed it: 
 I created a new user on my Mac and downloaded Anaconda following the instructions from: https://deeplabcut.github.io/DeepLabCut/docs/installation.html 
Literally just copy-pasted the wget Miniconda commands and then followed their steps in installation guide and it worked. 

Conclusion : you need to follow even the miniconda3 installation steps provided in the installation guide - so either remove your own and reinstall or create a new user (that for me was the best and most "clean" option) to make it work. Hope this helps you!! And saves you a lot of headaches haha :)

**Comment by mano2991** [comment]
@bendichter I have updated the conda enviorment and also installed `tensorflow-deps` still its says x86_64.  also tried of reinstalling my conda env.

**Comment by mano2991** [comment]
@yanavdsande Thanks for the sugesstion it worked.

**Comment by sdli** [comment]
errored on `Step 5` -> `conda env update -f DEEPLABCUT_M1.yaml`

```shell
Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/steven/Documents/t/DeepLabCut-main/setup.py", line 18, in <module>
          setuptools.setup(
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/dist.py", line 488, in __init__
          _Distribution.__init__(
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/dist.py", line 911, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/dist.py", line 910, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/npe2/__init__.py", line 9, in <module>
          from ._dynamic_plugin import DynamicPlugin
        File "/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/npe2/_dynamic_plugin.py", line 17, in <module>
          from pydantic import BaseModel, ValidationError
      ImportError: dlopen(/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so, 0x0002): tried: '/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (no such file), '/Users/steven/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```
