### ISSUE TITLE
DLC crashes after labeling in napari

### ISSUE THREAD

**Issue by OmerBarkai** [DeepLabCut/DeepLabCut#2112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When trying to save labeled (or also unlabeled) frames on napari DLC crashes immediately.

### Operating System

Windows 10

### DeepLabCut version

2.3

### DeepLabCut mode

single animal

### Device type

GPU: NVIDIA GeForce RTX 3060

### Steps To Reproduce

In Windows 10
DLC-GPU GUI configuration, after creating/loading config.yaml file and extracting frames.
When labeling frames in napari, and clicking File>Save All Layers... DLC and napari window close immediately and send an output (see below) to the command prompt. 

### Relevant log output

```shell
Loading DLC 2.3.0...
Starting GUI...
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=120
WARNING: QStatusBar::insertPermanentWidget: Index out of range (0), appending widget
Traceback (most recent call last):
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\label_frames.py", line 55, in label_frames
    _ = launch_napari(folder)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\widgets.py", line 45, in launch_napari
    viewer.open(files, plugin="napari-deeplabcut")
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\io.py", line 77, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\_npe2.py", line 55, in read
    layer_data, reader = io_utils.read_get_reader(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 66, in read_get_reader
    return _read(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 160, in _read
    read_func = rdr.exec(kwargs={"path": paths, "stack": stack})
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\manifest\contributions\_readers.py", line 52, in exec
    callable_ = super().exec(kwargs=kwargs)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\manifest\utils.py", line 65, in exec
    return self.get_callable(_registry)(*args, **kwargs)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_reader.py", line 71, in get_folder_parser
    raise OSError("No supported images were found.")
OSError: No supported images were found.
97it [00:00, 646.72it/s]
646it [00:00, 694.62it/s]
1361it [00:01, 694.74it/s]
WARNING: QStatusBar::insertPermanentWidget: Index out of range (0), appending widget
Traceback (most recent call last):
  File "shibokensupport/signature/mapping.py", line 196, in update
  File "shibokensupport/signature/mapping.py", line 197, in <genexpr>
  File "shibokensupport/signature/mapping.py", line 182, in module_valid
AttributeError: 'CythonDotParallel' object has no attribute '__name__'
Fatal Python error: seterror_argument failed to call update_mapping
Python runtime state: initialized

Thread 0x00004270 (most recent call first):
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\concurrent\futures\thread.py", line 78 in _worker
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 870 in run
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 890 in _bootstrap

Thread 0x00003770 (most recent call first):
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 306 in wait
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 558 in wait
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tqdm\_monitor.py", line 60 in run
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 890 in _bootstrap

Thread 0x0000159c (most recent call first):
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\threading.py", line 302 in wait
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\queue.py", line 170 in get
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\widgets.py", line 206 in run

Current thread 0x00004e64 (most recent call first):
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_viewer.py", line 617 in _save_layers_dialog
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\menus\file_menu.py", line 82 in <lambda>
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py", line 69 in launch_dlc
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__main__.py", line 24 in <module>
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 87 in _run_code
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 194 in _run_module_as_main
*** Received signal 22 ***
*** BEGIN STACK TRACE POINTERS ***
0x00007ffa6107a58f
0x00007ffa6107a777
0x00007ffb06821881
0x00007ffb06822851
0x00007ffab6f348c5
0x00007ffab6f34944
0x00007ffaa9c5ddad
0x00007ffa314061e6
0x00007ffab6e0136e
0x00007ffab6e00256
0x00007ffab6ee9008
0x00007ffab6ee5442
0x00007ffab6ee7c0a
0x00007ffab6e00aaf
0x00007ffab6e03b36
0x00007ffab6e03d4c
0x00007ffab6ee0676
0x00007ffab6ee9008
0x00007ffab6ee5442
0x00007ffab6ee7c0a
0x00007ffab6e00aaf
0x00007ffab6e003a6
0x00007ffaa9c06f6f
0x00007ffaa9c0abcb
0x00007ffa88fddfb1
0x00007ffa8900e186
0x00007ffa890103b4
0x00007ffa88b52701
0x00007ffa30f19779
0x00007ffa30f19614
0x00007ffa30f1f8ea
0x00007ffa31582385
0x00007ffa30dcf8c0
0x00007ffa30f1b000
0x00007ffa315805cb
0x00007ffa30d910ee
0x00007ffa30d8ef45
0x00007ffa31383e98
0x00007ffa88fd31b5
0x00007ffa30d94dff
0x00007ffa30ded426
0x00007ffa30deb5c5
0x00007ffa30d910ee
0x00007ffa30d9008f
0x00007ffa31383e98
0x00007ffa88fd31b5
0x00007ffa88896939
0x00007ffa888e4b48
0x00007ffa8912cf40
0x00007ffa88b20b19
0x00007ffa88fd888f
0x00007ffa88fd0fcd
0x00007ffa31380e15
0x00007ffab6e46f62
0x00007ffab6ee0676
0x00007ffab6ee9008
0x00007ffab6ee53e9
0x00007ffab6e00695
0x00007ffab6e009d8
0x00007ffab6ee0676
0x00007ffab6ee9008
0x00007ffab6ee3078
0x00007ffab6ee7c0a
0x00007ffab6ee1a74
*** END STACK TRACE POINTERS ***

0x00007FFA61109605      tensorflow::CurrentStackTrace
0x00007FFA6107A781      tensorflow::testing::InstallStacktraceHandler
0x00007FFB06821881      raise
0x00007FFB06822851      abort
0x00007FFAB6F348C5      Py_EndInterpreter
0x00007FFAB6F34944      Py_FatalError
0x00007FFAA9C5DDAD      SetError_Argument
0x00007FFA314061E6      (unknown)
0x00007FFAB6E0136E      PyMethodDef_RawFastCallKeywords
0x00007FFAB6E00256      PyObject_MakeTpCall
0x00007FFAB6EE9008      PyEval_GetFuncDesc
0x00007FFAB6EE5442      PyEval_EvalFrameDefault
0x00007FFAB6EE7C0A      PyEval_EvalCodeWithName
0x00007FFAB6E00AAF      PyFunction_Vectorcall
0x00007FFAB6E03B36      PyCell_Set
0x00007FFAB6E03D4C      PyMethod_Self
0x00007FFAB6EE0676      PyOS_URandomNonblock
0x00007FFAB6EE9008      PyEval_GetFuncDesc
0x00007FFAB6EE5442      PyEval_EvalFrameDefault
0x00007FFAB6EE7C0A      PyEval_EvalCodeWithName
0x00007FFAB6E00AAF      PyFunction_Vectorcall
0x00007FFAB6E003A6      PyVectorcall_Call
0x00007FFAA9C06F6F      PySide::SignalManager::callPythonMetaMethod
0x00007FFAA9C0ABCB      PySide::SignalManager::setQmlMetaCallErrorHandler
0x00007FFA88FDDFB1      QMetaObject::metacall
0x00007FFA8900E186      QObject::qt_static_metacall
0x00007FFA890103B4      QMetaObject::activate
0x00007FFA88B52701      QAction::activate
0x00007FFA30F19779      QMenu::actionGeometry
0x00007FFA30F19614      QMenu::actionGeometry
0x00007FFA30F1F8EA      QMenu::mouseReleaseEvent
0x00007FFA31582385      (unknown)
0x00007FFA30DCF8C0      QWidget::event
0x00007FFA30F1B000      QMenu::event
0x00007FFA315805CB      (unknown)
0x00007FFA30D910EE      QApplicationPrivate::notify_helper
0x00007FFA30D8EF45      QApplication::notify
0x00007FFA31383E98      (unknown)
0x00007FFA88FD31B5      QCoreApplication::notifyInternal2
0x00007FFA30D94DFF      QApplicationPrivate::sendMouseEvent
0x00007FFA30DED426      QWidgetPrivate::shouldDiscardSyncRequest
0x00007FFA30DEB5C5      QWidgetPrivate::shouldDiscardSyncRequest
0x00007FFA30D910EE      QApplicationPrivate::notify_helper
0x00007FFA30D9008F      QApplication::notify
0x00007FFA31383E98      (unknown)
0x00007FFA88FD31B5      QCoreApplication::notifyInternal2
0x00007FFA88896939      QGuiApplicationPrivate::processMouseEvent
0x00007FFA888E4B48      QWindowSystemInterface::sendWindowSystemEvents
0x00007FFA8912CF40      QEventDispatcherWin32::processEvents
0x00007FFA88B20B19      QWindowsGuiEventDispatcher::processEvents
0x00007FFA88FD888F      QEventLoop::exec
0x00007FFA88FD0FCD      QCoreApplication::exec
0x00007FFA31380E15      (unknown)
0x00007FFAB6E46F62      PyCFunction_DebugMallocStats
0x00007FFAB6EE0676      PyOS_URandomNonblock
0x00007FFAB6EE9008      PyEval_GetFuncDesc
0x00007FFAB6EE53E9      PyEval_EvalFrameDefault
0x00007FFAB6E00695      PyObject_Call
0x00007FFAB6E009D8      PyFunction_Vectorcall
0x00007FFAB6EE0676      PyOS_URandomNonblock
0x00007FFAB6EE9008      PyEval_GetFuncDesc
0x00007FFAB6EE3078      PyEval_EvalFrameDefault
0x00007FFAB6EE7C0A      PyEval_EvalCodeWithName
0x00007FFAB6EE1A74      PyEval_EvalCode
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi Omar, is there a reason you run "save all layers" vs. just save? Can you confirm how you are launching the dlc-napari gui?

**Comment by jeylau** [comment]
@OmerBarkai, save only the annotations (Points) layer with Ctrl+S or `Save Selected Layer...`. This will writes the h5 data file into the corresponding folder.

**Comment by OmerBarkai** [comment]
That indeed solves it! Really enjoy working with DLC!
Thank you, have a great week
