### ISSUE TITLE
Missing cuda libraries?

### ISSUE THREAD

**Issue by laurelrr** [DeepLabCut/DeepLabCut#2115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I installed DLC using the conda environment provided but received an error when trying to run it about missing tensorflow libraries.

### Operating System

operating system: Debian Buster v10.X.
CPU Count: 64 : "AuthenticAMD AMD EPYC 7513 32-Core Processor 1799.602 MHz (2 chips x 32 cores)"

### DeepLabCut version

dlc version: appears to be trying to load DLC 2.3.0

### DeepLabCut mode

single animal

### Device type

GPU: A40, NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2 

### Steps To Reproduce

I followed the installation instructions for conda on Linux platform as follows:
`git clone https://github.com/DeepLabCut/DeepLabCut.git`
`cd DeepLabCut/conda-environments`
`conda env create -f DEEPLABCUT.yaml`

It appeared to install correctly with no errors.
`conda activate DEEPLABCUT`
but
`python -m deeplabcut` 
gave the error (below)

### Relevant log output

```shell
2023-01-09 14:41:15.353074: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-09 14:41:16.169473: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-09 14:41:21.432570: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:
2023-01-09 14:41:21.433516: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:
2023-01-09 14:41:21.433525: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.0...
Traceback (most recent call last):
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/nadata/snlkt/home/lkeyes/Projects/GIT/DeepLabCut/deeplabcut/__init__.py", line 76, in <module>
    from deeplabcut.pose_tracking_pytorch import transformer_reID
  File "/nadata/snlkt/home/lkeyes/Projects/GIT/DeepLabCut/deeplabcut/pose_tracking_pytorch/__init__.py", line 14, in <module>
    from .train_dlctransreid import train_tracking_transformer
  File "/nadata/snlkt/home/lkeyes/Projects/GIT/DeepLabCut/deeplabcut/pose_tracking_pytorch/train_dlctransreid.py", line 15, in <module>
    import torch
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/lkeyes/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```

### Anything else?

This is the first time I am trying out DeepLabCut.  My apologies in advance if there is an obvious fix for this that I missed. Thanks for the help!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by laurelrr** [comment]
One other comment...
I also tried using without opening the gui by typing in the terminal window `ipython` and `import deeplabcut` but received the same error.

**Comment by MMathisLab** [comment]
@laurelrr you will need to first install CUDA then install DLC, see here: https://deeplabcut.github.io/DeepLabCut/docs/installation.html#gpu-support 

> CRITICAL: If you have a GPU, you should FIRST install the NVIDIA CUDA package and an appropriate driver for your specific GPU, then you can use the supplied conda file. Please follow the instructions found here https://www.tensorflow.org/install/gpu, and more tips below, to install the correct version of CUDA and your graphic card driver. The order of operations matters.
> 
> Here we provide notes on how to install and check your GPU use with TensorFlow (which is used by DeepLabCut and already installed with the Anaconda files above). Thus, you do not need to independently install tensorflow.
> 
> FIRST, install a driver for your GPU. Find DRIVER HERE: https://www.nvidia.com/download/index.aspx
> 
> check which driver is installed by typing this into the terminal: nvidia-smi.
> 
> SECOND, install CUDA (versions up to CUDA11 are supported, together with TF2.5): https://developer.nvidia.com/ (Note that cuDNN, https://developer.nvidia.com/cudnn, is supplied inside the anaconda environment files, so you don’t need to install it again).
> 
> THIRD: Follow the steps above to get the DEEPLABCUT conda file and install it!

**Comment by SimonHubs** [comment]
I have almost the same problem. I first installed gpu driver, then cuda with:

`conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0`

Then tensorflow with:

`pip install tensorflow`

always following exactly the steps descried here: https://www.tensorflow.org/install/pip

Then I installed dlc with:
```
git clone https://github.com/DeepLabCut/DeepLabCut.git
cd DeepLabCut/conda-environments
conda env create -f DEEPLABCUT.yaml
```
 

**operating system:** ubuntu 20.04


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:08:00.0  On |                  N/A |
|  0%   43C    P8    10W / 250W |    339MiB /  8192MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       993      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      1585      G   /usr/lib/xorg/Xorg                 84MiB |
|    0   N/A  N/A      1714      G   /usr/bin/gnome-shell               47MiB |
|    0   N/A  N/A      2359      G   /usr/lib/firefox/firefox          161MiB |
+-----------------------------------------------------------------------------+

-------------------------------------------------------------------------------------
Starting dlc with:
```
conda activate DEEPLABCUT
python3
import deeplabcut
```

gave the following output

**Relevant log output**

2023-01-17 17:19:03.773870: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-17 17:19:03.873895: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-17 17:19:04.264218: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/ralph/miniconda3/envs/DEEPLABCUT/lib/:/home/ralph/miniconda3/envs/DEEPLABCUT/lib/
2023-01-17 17:19:04.264264: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/ralph/miniconda3/envs/DEEPLABCUT/lib/:/home/ralph/miniconda3/envs/DEEPLABCUT/lib/
2023-01-17 17:19:04.264270: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.0...
Traceback (most recent call last):
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/__init__.py", line 76, in <module>
    from deeplabcut.pose_tracking_pytorch import transformer_reID
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/__init__.py", line 14, in <module>
    from .train_dlctransreid import train_tracking_transformer
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/train_dlctransreid.py", line 15, in <module>
    import torch
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ralph/miniconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11

**Comment by noahweber1-debug** [comment]
@SimonHubs did you solve that, have the same issue?

**Comment by SimonHubs** [comment]
No I couldn't solve it in Ubuntu. I switched back to windows 10. There I first installed the GPU driver, then anaconda, then DLC with:

`git clone https://github.com/DeepLabCut/DeepLabCut.git`
`cd C:\Users\YourUserName\Desktop\DeepLabCut\conda-environments`
`conda env create -f DEEPLABCUT.yaml`

then in the DEEPLABCUT environment I installed CUDA and tensorflow with: 

`conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0`
`pip install tensorflow`

This finally worked for me.

**Comment by MMathisLab** [comment]
@SimonHubs please be aware that tensorflow is already installed within the DLC environment; it is a requirement of DLC, and TF stopped supporting native TF in windows after 2.10 so please carefully check your version; it could have performance degredations.

**Comment by SimonHubs** [comment]
@MMathisLab true TF is already installed with DLC, probably didn't do the `pip install tensorflow` step. My TF version is 2.10.1
But I have indeed performance problems, and I assume it has something to do with the ptxas error messages I get:

`2023-01-30 15:27:42.053830: W tensorflow/stream_executo/gpu/redzone_allocator.C:314] INTERNAL: Failed to launch ptxas`
`Relying on driver to perform pt compilation.`
`Modify $PATH to customize ptxas location.`
`This message will be only logged once.`

**Comment by jeylau** [comment]
@SimonHubs, could you try to run `conda install -c nvidia cuda-nvcc`? It may fix the error about ptxas.

**Comment by SimonHubs** [comment]
@jeylau thank you. But won't `conda install -c nvidia cuda-nvcc` upgrade my cudatoolkit and cudnn version. I'm so glad that I finally have the right versions that work together.

**Comment by jeylau** [comment]
I don't think so, it's a different set of drivers. conda will warn you anyway of the potential dependencies about to be installed, so you could always input "n" when you're asked.

**Comment by SimonHubs** [comment]
@jeylau thanks! `conda install -c nvidia cuda-nvcc` fixed the error about ptxas, however, the performance further dropped. While training The GPU Utilization was at 0%; Dedicated GPU memory 5.5/8.0 GB;GPU Memory 5.5/24.0 GB and shared GPU memory  0.2/16.0GB; Cuda is around 24%. 
Any ideas how I could increase performance?

**Comment by MMathisLab** [comment]
can you please explain what you mean by "performance," ie. the key point RMSE is changing?

**Comment by SimonHubs** [comment]
@MMathisLab sorry I'm quite new to this, I meant GPU performance/usage. Training now needs around an hour for 5000 iterations and I think it went a lot faster with my first DLC installation (v2.2)

**Comment by juhuntenburg** [comment]
Hi, 
I am having the same issue on Ubuntu 20.04 Cuda 11.2 CudNN 8.1. I regularly update the libraries in this environment which might be the issue here? 
My tensorflow is at 2.11.0 and torch 1.13.1 (thinking the latter might be the issue due to [this thread](https://stackoverflow.com/questions/74394695/how-does-one-fix-when-torch-cant-find-cuda-error-version-libcublaslt-so-11-no))

Seeing torch in the environment also surprised me, since when is it a dependency and why?

UPDATE: I removed and recreate my virtual environment and get the same issue
```
virtualenv dlcenv --python=python3.8
source dlcenv/bin/activate
pip install deeplabcut[tf]
python -c 'import deeplabcut'
```


Best, 
Julia

**Comment by MMathisLab** [comment]
hi @juhuntenburg we introduced torch with 2.2 and all the prior beta and RC releases; it is for the transformer architecture that is now in DLC, and per our roadmap, we are transitioning away from tensorflow this year, so rather have people start installing it now ;)

**Comment by juhuntenburg** [comment]
Hi @MMathisLab thanks for the reply, good to know!

So I think the issue is indeed that the latest torch (1.13) installs some cuda libraries by itself, which interfer with existing cuda installations (see thread I linked above). What I did to solve this for now:

Remove my cuda 11.2 and cudnn 8.1 installations (that had been messed with, I didn't find a different way to fix this), reinstall both fresh and make sure they are in the LD_LIBRARY_PATH. Then make a fresh environment for DLC, fix the torch version to 1.12 and install deeplabcut

```
virtualenv dlcenv --python=python3.8
source ~/Documents/PYTHON/envs/dlcenv/bin/activate
pip install torch==1.12
pip install deeplabcut[tf]
```

Now the  libcublasLt.so.11 error is gone, but the libnvinfer.so.7 is still there so I'll look into that next. 

I think until this is fixed by torch, it might be recommendable to fix torch to 1.12 ? I am surely not the only one that has cuda set up prior to deeplabcut installation, right?

**Comment by juhuntenburg** [comment]
Thanks @MMathisLab

I still cannot seem to fix the libnvinfer.so.7 warning, that was also in the original post
```
2023-02-20 11:35:53.200200: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/$
2023-02-20 11:35:53.200264: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/$
2023-02-20 11:35:53.200276: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```
 Seeing as it is only a warning, and I believe only relevant for TensorRT I wanted to double check if DLC currently uses TensorRT? Do I even need to fix this?
 
 Thanks again

**Comment by vianmiranda** [comment]
@juhuntenburg For the libnvinfer.so.7 warning, try downgrading TensorFlow from 2.10 to 2.9.2, which solves the issue for me. See: [#57663 for TF](https://github.com/tensorflow/tensorflow/issues/57663)
