### ISSUE TITLE
MemryError during video analysis

### ISSUE THREAD

**Issue by rapacotta** [DeepLabCut/DeepLabCut#2120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After the analysis of 1 video (using GUI), DLC crashes and throws a MemoryError, or a Ran out of input error

### Operating System

operating system Windows 10 Enterprise (version 1809)

### DeepLabCut version

dlc version 2.3.0

### DeepLabCut mode

multi animal

### Device type

gpu NVIDIA RTX 2080 Ti

### Steps To Reproduce

1. activate dlc env
2. launch the GUI
3. start the analysis of the videos 

### Relevant log output

```shell
(DEEPLABCUT) PS C:\Users\biagini> python -m deeplabcut
Loading DLC 2.3.0...
Starting GUI...
C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-01-12 18:50:24.312275: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-12 18:50:25.088444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8060 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:21:00.0, compute capability: 7.5
2023-01-12 18:50:25.148705: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
Traceback (most recent call last):
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\utils.py", line 22, in run
    self.func()
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 626, in analyze_videos
    AnalyzeMultiAnimalVideo(
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 225, in AnalyzeMultiAnimalVideo
    data, metadata = auxfun_multianimal.LoadFullMultiAnimalData(dataname)
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py", line 207, in SaveFullMultiAnimalData
    pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)
MemoryError

(DEEPLABCUT) PS C:\Users\biagini> python -m deeplabcut
Loading DLC 2.3.0...
Starting GUI...
C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-01-12 18:50:24.312275: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-12 18:50:25.088444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8060 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:21:00.0, compute capability: 7.5
2023-01-12 18:50:25.148705: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
Traceback (most recent call last):
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\utils.py", line 22, in run
    self.func()
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 640, in analyze_videos
    convert_detections2tracklets(
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 1744, in convert_detections2tracklets
    data, metadata = auxfun_multianimal.LoadFullMultiAnimalData(dataname)
  File "C:\Users\biagini\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py", line 218, in LoadFullMultiAnimalData
    data = pickle.load(handle)
EOFError: Ran out of input
```

### Anything else?

I get the errors above in two different circumstances:
- the memory error occurs when I try to run a video analysis of 3 different videos of 12 hours each (8.72 GB all together)
- the ran out of input error occurs when I try to run a video analysis of just one of the videos (2.59 GB)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@rapacotta the size (length of the video) does not matter, but the image/frame size does. Your GPU is quite small, so it would not handle large frames, so please check it. There are tools to allow you to downsample videos in DLC, and we also recommend carefully training on images that are a size similar to your final video size (so you might want to re-train)
