### ISSUE TITLE
Not Found Error when trying to analyze videos

### ISSUE THREAD

**Issue by ckKLI** [DeepLabCut/DeepLabCut#2132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I created a new training data set in DeepLabCut, trained the network and then evaluated it. Now when I try to analyze videos I get an error.  
This is the third time I trained the network. It always worked the previous times. 
I'm not familiar with python at all and I don't know what the problem is this time. Can you help me?

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.3

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce GTX 950M

### Relevant log output

```shell
Using snapshot-500000 for model G:\DeepLabCut\Snail3-Carina-2020-03-11\dlc-models\iteration-2\Snail3Mar11-trainset95shuffle1
C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-01-25 10:55:05.995506: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-25 10:55:06.616577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2825 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0
2023-01-25 10:55:06.663547: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2023-01-25 10:55:07.872503: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at save_restore_v2_ops.cc:228 : NOT_FOUND: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1377     try:
-> 1378       return fn(*args)
   1379     except errors.OpError as e:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1361       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1362                                       target_list, run_metadata)
   1363

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1455                                             fetch_list, target_list,
-> 1456                                             run_metadata)
   1457

NotFoundError: 2 root error(s) found.
  (0) NOT_FOUND: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_27]]
  (1) NOT_FOUND: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1415         sess.run(self.saver_def.restore_op_name,
-> 1416                  {self.saver_def.filename_tensor_name: save_path})
   1417     except errors.NotFoundError as err:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    968       result = self._run(None, fetches, feed_dict, options_ptr,
--> 969                          run_metadata_ptr)
    970       if run_metadata:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1191       results = self._do_run(handle, final_targets, final_fetches,
-> 1192                              feed_dict_tensor, options, run_metadata)
   1193     else:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1371       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1372                            run_metadata)
   1373     else:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1396                     'disable_meta_optimizer = True')
-> 1397       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1398

NotFoundError: Graph execution error:

Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "C:\anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
      sys.exit(start_ipython())
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 130, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
      self.shell.mainloop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 566, in mainloop
      self.interact()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 557, in interact
      self.run_cell(code, store_history=True)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2915, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
      return runner(coro)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3186, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
      deeplabcut.launch_dlc()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 550, in analyze_videos
      dynamic=dynamic,
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 597, in analyze_videos
      dlc_cfg, allow_growth=allow_growth
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py", line 225, in setup_GPUpose_prediction
      restorer = tf.compat.v1.train.Saver()
Node: 'save/RestoreV2'
Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "C:\anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
      sys.exit(start_ipython())
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 130, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
      self.shell.mainloop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 566, in mainloop
      self.interact()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 557, in interact
      self.run_cell(code, store_history=True)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2915, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
      return runner(coro)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3186, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
      deeplabcut.launch_dlc()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 550, in analyze_videos
      dynamic=dynamic,
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 597, in analyze_videos
      dlc_cfg, allow_growth=allow_growth
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py", line 225, in setup_GPUpose_prediction
      restorer = tf.compat.v1.train.Saver()
Node: 'save/RestoreV2'
2 root error(s) found.
  (0) NOT_FOUND: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_27]]
  (1) NOT_FOUND: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "C:\anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 130, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 566, in mainloop
    self.interact()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 557, in interact
    self.run_cell(code, store_history=True)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2915, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3186, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
    deeplabcut.launch_dlc()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
    app.MainLoop()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 550, in analyze_videos
    dynamic=dynamic,
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 597, in analyze_videos
    dlc_cfg, allow_growth=allow_growth
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py", line 225, in setup_GPUpose_prediction
    restorer = tf.compat.v1.train.Saver()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 931, in __init__
    self.build()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 943, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 981, in _build
    build_restore=build_restore)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 541, in _build_internal
    restore_sequentially, reshape)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddRestoreOps
    restore_sequentially)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 608, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1519, in restore_v2
    name=name)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 799, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3808, in _create_op_internal
    op_def=op_def)


During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in get_tensor(self, tensor_str)
     66     return CheckpointReader.CheckpointReader_GetTensor(
---> 67         self, compat.as_bytes(tensor_str))
     68   # TODO(b/143319754): Remove the RuntimeError casting logic once we resolve the

RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1425       try:
-> 1426         names_to_keys = object_graph_key_mapping(save_path)
   1427       except errors.NotFoundError:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py in object_graph_key_mapping(checkpoint_path)
   1747   reader = py_checkpoint_reader.NewCheckpointReader(checkpoint_path)
-> 1748   object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
   1749   object_graph_proto = (trackable_object_graph_pb2.TrackableObjectGraph())

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in get_tensor(self, tensor_str)
     70   except RuntimeError as e:
---> 71     error_translator(e)
     72

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in error_translator(e)
     30       'matching files for') in error_message:
---> 31     raise errors_impl.NotFoundError(None, None, error_message)
     32   elif 'Sliced checkpoints are not supported' in error_message or (

NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py in analyze_videos(self, event)
    548                 save_as_csv=save_as_csv,
    549                 cropping=crop,
--> 550                 dynamic=dynamic,
    551             )
    552             if _filter:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, in_random_order, destfolder, batchsize, cropping, TFGPUinference, dynamic, modelprefix, robust_nframes, allow_growth, use_shelve, auto_track, n_tracks, calibrate, identity_only, use_openvino)
    595     elif TFGPUinference:
    596         sess, inputs, outputs = predict.setup_GPUpose_prediction(
--> 597             dlc_cfg, allow_growth=allow_growth
    598         )
    599     else:

C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py in setup_GPUpose_prediction(cfg, allow_growth)
    236
    237     # Restore variables from disk.
--> 238     restorer.restore(sess, cfg["init_weights"])
    239
    240     return sess, inputs, outputs

C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1430         # a helpful message (b/110263146)
   1431         raise _wrap_restore_error_with_msg(
-> 1432             err, "a Variable name or other graph key that is missing")
   1433
   1434       # This is an object-based checkpoint. We'll print a warning and then do

NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Graph execution error:

Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "C:\anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
      sys.exit(start_ipython())
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 130, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
      self.shell.mainloop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 566, in mainloop
      self.interact()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 557, in interact
      self.run_cell(code, store_history=True)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2915, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
      return runner(coro)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3186, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
      deeplabcut.launch_dlc()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 550, in analyze_videos
      dynamic=dynamic,
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 597, in analyze_videos
      dlc_cfg, allow_growth=allow_growth
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py", line 225, in setup_GPUpose_prediction
      restorer = tf.compat.v1.train.Saver()
Node: 'save/RestoreV2'
Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "C:\anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
      sys.exit(start_ipython())
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 130, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
      self.shell.mainloop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 566, in mainloop
      self.interact()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 557, in interact
      self.run_cell(code, store_history=True)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2915, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
      return runner(coro)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3186, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
      deeplabcut.launch_dlc()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 550, in analyze_videos
      dynamic=dynamic,
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 597, in analyze_videos
      dlc_cfg, allow_growth=allow_growth
    File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py", line 225, in setup_GPUpose_prediction
      restorer = tf.compat.v1.train.Saver()
Node: 'save/RestoreV2'
2 root error(s) found.
  (0) NOT_FOUND: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_27]]
  (1) NOT_FOUND: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "C:\anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 130, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 566, in mainloop
    self.interact()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 557, in interact
    self.run_cell(code, store_history=True)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2915, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3186, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
    deeplabcut.launch_dlc()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
    app.MainLoop()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 550, in analyze_videos
    dynamic=dynamic,
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 597, in analyze_videos
    dlc_cfg, allow_growth=allow_growth
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py", line 225, in setup_GPUpose_prediction
    restorer = tf.compat.v1.train.Saver()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 931, in __init__
    self.build()
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 943, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 981, in _build
    build_restore=build_restore)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 541, in _build_internal
    restore_sequentially, reshape)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddRestoreOps
    restore_sequentially)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py", line 608, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1519, in restore_v2
    name=name)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 799, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3808, in _create_op_internal
    op_def=op_def)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @ckKLI, this is strange. It is somehow failing to load your refined network. If you open the main config.yaml file, and change `iteration` to 1 (to attempt to load a network refined anteriorly), does this fail too? If you also have a look at the pose_cfg.yaml file under dlc-models/.../test, is there something looking different between iteration 0 and iteration 2?

**Comment by ckKLI** [comment]
It also fails when I change iteration to 1. I looked at the pose_cfg.yaml files of iteration 0 and 2 and there are differences in init_weights and net_type. Do I have to change the values of iteration 2 to those of iteration 0?

This is written in the file for iteration 0:

all_joints:
- - 0
- - 1
- - 2
- - 3
all_joints_names:
- right tentacle
- right tentacle base
- left tentacle
- left tentacle base
dataset: training-datasets\iteration-0\UnaugmentedDataSet_Snail3Mar11\Snail3_Carina95shuffle1.mat
global_scale: 0.8
init_weights: D:\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mobilenet_v2_1.0_224.ckpt
location_refinement: true
locref_stdev: 7.2801
net_type: mobilenet_v2_1.0
num_joints: 4
scoremap_dir: test


And this is written in the file for iteration 2:

all_joints:
- - 0
- - 1
- - 2
- - 3
all_joints_names:
- right tentacle
- right tentacle base
- left tentacle
- left tentacle base
dataset: training-datasets\iteration-2\UnaugmentedDataSet_Snail3Mar11\Snail3_Carina95shuffle1.mat
global_scale: 0.8
init_weights: C:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
location_refinement: true
locref_stdev: 7.2801
net_type: resnet_50
num_joints: 4
scoremap_dir: test

**Comment by ckKLI** [comment]
I changed init_weights of iteration 0 to that of iteration 2 and now it works. Thank you very much for your help. I'm so glad that it works again :)

**Comment by jeylau** [comment]
I'd rather change the net_type in iteration 2 to be that of 0 (you apparently trained originally a mobilenet); DeepLabCut will then find the latest snapshot weights for you. I'm puzzled though as to why refinement worked once but not twice 🧐
