### ISSUE TITLE
Error with filterpredictions function when analyzing videos

### ISSUE THREAD

**Issue by cdj5044** [DeepLabCut/DeepLabCut#2136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When analyzing videos, with the "Filter predictions" box checked in the GUI, I get the error below, and then no filtered files are created after videos are analyzed.

**TypeError: filterpredictions() got an unexpected keyword argument 'videos'**

### Operating System

Windows 10

### DeepLabCut version

2.3

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 2070

### Steps To Reproduce

1. Activate DEEPLABCUT environment
2. Initiate GUI
3. Load project
4. Use Analyze Videos tab--> "Save results as csv" checked, "Filter predictions" checked
5. Click Analyze videos
6. Videos are analyzed and results saved, however filtered results files are not produced, due to the error

### Relevant log output

```shell
(base) PS C:\Users\SNRC_G7_2> conda activate DEEPLABCUT
(DEEPLABCUT) PS C:\Users\SNRC_G7_2> python -m deeplabcut
Loading DLC 2.3.0...
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\SNRC_G7_2\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\analyze_videos.py", line 332, in analyze_videos
    deeplabcut.filterpredictions(
TypeError: filterpredictions() got an unexpected keyword argument 'videos'
C:\Users\SNRC_G7_2\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-01-30 09:36:51.137178: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-30 09:36:51.671291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5999 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-01-30 09:36:51.713850: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
```

### Anything else?

I've tried updating just in case there was something wrong my install, using: **pip install --upgrade deeplabcut**. However this did not fix the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by cdj5044** [comment]
Sorry to reopen this, but could you please let me know how to update my install correctly for the bug fix? I tried the **pip install --upgrade deeplabcut** command, but I'm still getting the same error.

**Comment by jeylau** [comment]
Sure! You need to install DeepLabCut directly from our code base (as we haven't yet released a new version) with the following command:
`pip install git+https://github.com/DeepLabCut/DeepLabCut.git@main`

**Comment by cdj5044** [comment]
Oh perfect, yes that makes sense. Thank you so much!

**Comment by qqspm** [comment]
I have the same problem. And  "pip install git+https://github.com/DeepLabCut/DeepLabCut.git@main" doesn't help. Still shows the typo issue and no filtered data saved and no plots shows. 

(deeplabcut) C:\>python -m deeplabcut
Loading DLC 2.3.0...
Starting GUI...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tabs\analyze_videos.py", line 332, in analyze_videos
    deeplabcut.filterpredictions(
TypeError: filterpredictions() got an unexpected keyword argument 'videos'
C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-02-09 16:24:23.693934: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-09 16:24:24.225950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8949 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-02-09 16:24:24.263244: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
