### ISSUE TITLE
`Pip subprocess error:   error: subprocess-exited-with-error`

### ISSUE THREAD

**Issue by au183** [DeepLabCut/DeepLabCut#2157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I've tried to install DCL but it fails to do so. I cloned the git repository to a folder on my desktop. When I run conda env create -f DEEPLABCUT.yaml the system crashes. I didn't expect this to happen

### Operating System

Windows 11 Home

### DeepLabCut version

dlc version: N/A

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 3080

### Steps To Reproduce

What I typed in Anaconda and the resulting error:  
(base) C:\Users\joyce>cd C:\Users\joyce\OneDrive\Desktop\DLC\DeepLabCut\conda-environments
(base) C:\Users\joyce\OneDrive\Desktop\DLC\DeepLabCut\conda-environments>conda env create -f DEEPLABCUT.yaml

### Relevant log output

```shell
(base) C:\Users\joyce\OneDrive\Desktop\DLC\DeepLabCut\conda-environments>conda env create -f DEEPLABCUT.yaml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ Enabling nb_conda_kernels...
CONDA_PREFIX: C:\Users\joyce\.conda\envs\DEEPLABCUT
Status: enabled

/ Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Enabling notebook extension nb_conda/main...
      - Validating: ok
Enabling tree extension nb_conda/tree...
      - Validating: ok
Config option `kernel_spec_manager_class` not recognized by `EnableServerExtensionApp`.
Enabling: nb_conda
- Writing config: C:\Users\joyce\.conda\envs\DEEPLABCUT\etc\jupyter
    - Validating...
      nb_conda 2.2.1 ok

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\Users\\joyce\\.conda\\envs\\DEEPLABCUT\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\joyce\\OneDrive\\Desktop\\DLC\\DeepLabCut\\conda-environments\\condaenv.79_7rfz4.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting deeplabcut[gui,tf]
  Using cached deeplabcut-2.3.0-py3-none-any.whl (1.4 MB)
Collecting networkx>=2.6
  Using cached networkx-3.0-py3-none-any.whl (2.0 MB)
Collecting matplotlib>=3.3
  Using cached matplotlib-3.7.0-cp38-cp38-win_amd64.whl (7.7 MB)
Collecting torch
  Using cached torch-1.13.1-cp38-cp38-win_amd64.whl (162.6 MB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting tables>=3.7.0
  Using cached tables-3.8.0-cp38-cp38-win_amd64.whl (3.6 MB)
Collecting filterpy>=1.4.4
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\joyce\AppData\Local\Temp\pip-install-6hf3kcix\filterpy_b65b2f7b9b4b484585bad38c02386a80\setup.py", line 12, in <module>
          setup(
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\dist.py", line 488, in __init__
          _Distribution.__init__(
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\dist.py", line 911, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\dist.py", line 910, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "C:\Users\joyce\.conda\envs\DEEPLABCUT\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 843, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\joyce\AppData\Roaming\Python\Python38\site-packages\npe2\__init__.py", line 9, in <module>
          from ._dynamic_plugin import DynamicPlugin
        File "C:\Users\joyce\AppData\Roaming\Python\Python38\site-packages\npe2\_dynamic_plugin.py", line 19, in <module>
          from ._plugin_manager import PluginManager
        File "C:\Users\joyce\AppData\Roaming\Python\Python38\site-packages\npe2\_plugin_manager.py", line 30, in <module>
          from ._command_registry import CommandRegistry
        File "C:\Users\joyce\AppData\Roaming\Python\Python38\site-packages\npe2\_command_registry.py", line 10, in <module>
          from .manifest import utils
        File "C:\Users\joyce\AppData\Roaming\Python\Python38\site-packages\npe2\manifest\__init__.py", line 2, in <module>
          from .schema import ENTRY_POINT, PluginManifest
        File "C:\Users\joyce\AppData\Roaming\Python\Python38\site-packages\npe2\manifest\schema.py", line 17, in <module>
          from ._bases import ImportExportModel
        File "C:\Users\joyce\AppData\Roaming\Python\Python38\site-packages\npe2\manifest\_bases.py", line 6, in <module>
          import pytomlpp as toml
      ModuleNotFoundError: No module named 'pytomlpp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@au183 seems you have many packages already installed, and it fails with filterpy, not on deeplabcut. 

I would recommend that you create a simple env with a force re-install:

`conda create -n DLC python=3.9`

then, activate it (follow the prompts), and then run:

`pip install --upgrade --force-reinstall 'deeplabcut[gui,tf,modelzoo]'`

**Comment by au183** [comment]
@MMathisLab OK! That seems to get DLC up and running, I need to go through now and make sure my GPU is getting engaged. 
I do have another question, I had previously trained a model, and now when I go to analyze videos through the GUI it says videos are not found or to make sure that the filetype is specified. I have been able to analyze videos in the past I'm not sure what the issue is now. Video files are not corrupted and the filetype specified is correct. Any suggestions?
