### ISSUE TITLE
tracklet_toolbox.py and refine_tracklets.py issues with merging dataset

### ISSUE THREAD

**Issue by KonradDanielewski** [DeepLabCut/DeepLabCut#2161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When trying to merge datasets after refining tracklets and saving I get:
```
Traceback (most recent call last):
  File "C:\Anaconda\anaconda3\envs\dlc_newgui\lib\site-packages\deeplabcut\gui\tabs\refine_tracklets.py", line 221, in merge_dataset
    msg.setWindowIcon(QtWidgets.QMessageBox.Warning)
TypeError: 'PySide6.QtWidgets.QWidget.setWindowIcon' called with wrong argument types:
  PySide6.QtWidgets.QWidget.setWindowIcon(Icon)
Supported signatures:
  PySide6.QtWidgets.QWidget.setWindowIcon(Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap])
```

This can be fixed by just removing `msg.setWindowIcon(QtWidgets.QMessageBox.Warning)` the icon is there anyway when the message box pops up - I'm not sure if it's a `PySide` or `PyQt` version issue or not, I'm on 6.3.0 and 5.15.7 respectively.

After that fix I got an error:
```
Traceback (most recent call last):
  File "C:\Anaconda\anaconda3\envs\dlc_newgui\lib\site-packages\deeplabcut\gui\tabs\refine_tracklets.py", line 224, in merge_dataset
    deeplabcut.merge_datasets(self.config, forceiterate=None)
AttributeError: 'RefineTracklets' object has no attribute 'config'
```

changing `self.config` to `self.root.config` solved this issue.

The saved, refined frames aren't extracted and placed into a folder. There is no error printed. They changes are saved to the video `*_el.h5` and merge seems to run cause it updates the iteration - but the refined data isn't saved in the `labeled-data`.

### Operating System

Windows 10

### DeepLabCut version

2.3.0

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Will be fixed by #2126
