### ISSUE TITLE
Feature Request: Quick start guide for installation via Singularity

### ISSUE THREAD

**Issue by tsievert** [DeepLabCut/DeepLabCut#2180]
**Is your feature request related to a problem? Please describe.**
My local set of clusters only allows Singularity installs for containers instead of Docker, so the quick start guide is unfortunately not very helpful for me, and I'm struggling to get everything to run.

**Describe the solution you'd like**
Would it be possible to provide a quick start guide and helper script for users stuck with Singularity?

**Comment by qiyubio** [comment]
Wanna give this singularity definition file a try? I compose it for our Rocky/8 cluster with multiple flavors of GPUs, and based on CUDA/11.4. 
https://github.com/qiyubio/DLC_singularity/blob/main/DLC.def

**Comment by LinuxPersonEC** [comment]
> Wanna give this singularity definition file a try? I compose it for our Rocky/8 cluster with multiple flavors of GPUs, and based on CUDA/11.4. https://github.com/qiyubio/DLC_singularity/blob/main/DLC.def

Do you have a work around for this known error?

```
Processing triggers for systemd (245.4-4ubuntu3.23) ...
Processing triggers for libc-bin (2.31-0ubuntu9.12) ...
Segmentation fault (core dumped)
Segmentation fault (core dumped)
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 139
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.40.0+dfsg-3ubuntu0.4) ...
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
FATAL:   failed to execute %post proc: exit status 100
FATAL:   While performing build: while running engine: while running /opt/singularity-3.5.3/libexec/singularity/bin/starter: exit status 255
```


Also I did get the container to build via Sylabs Remote Builder but now I get this:
```
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 37, in <module>
    from deeplabcut.create_project import (
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/create_project/__init__.py", line 12, in <module>
    from deeplabcut.create_project.demo_data import load_demo_data
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/create_project/demo_data.py", line 16, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 11, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/auxfun_multianimal.py", line 34, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/auxiliaryfunctions.py", line 31, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/lib/trackingutils.py", line 20, in <module>
    from numba import jit
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 40, in _ensure_critical_deps
    raise ImportError(msg)
ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.
```

**Comment by qiyubio** [comment]
Give this a try? I build it for DLC/2.3.9 for our cluster based on CUDA/11.4. 

https://github.com/qiyubio/DLC_singularity/blob/main/DLC_2.3.9
