### ISSUE TITLE
No such file or directory: failed to save labeled images while evaluating the model

### ISSUE THREAD

**Issue by witeal** [DeepLabCut/DeepLabCut#2206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi everyone, 

I would like to evaluate my trained network. However, when asking to "plot predictions (as in standard DLC projects)" I cannot do it. On my terminal, it is said that there is no such file or directory found with the path of .png. But when I check manually, the folder in which the .png is supposed to be saved does exist. 

I have already searched existing issues and tried to follow the different steps adviced but I didn't work...

Thank you by advance for any help!

### Operating System

Windows 11

### DeepLabCut version

dlc version 2.3.3

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
warnings.warn('`layer.apply` is deprecated and '
480it [01:31,  5.27it/s]
  0%|                                                                                          | 0/480 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\evaluate_network.py", line 184, in evaluate_network
    deeplabcut.evaluate_network(
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py", line 944, in evaluate_network
    Plotting(
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py", line 202, in Plotting
    ax = visualization.plot_and_save_labeled_frame(
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\visualization.py", line 184, in plot_and_save_labeled_frame
    save_labeled_frame(fig, image_path, foldername, ind in trainIndices)
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\visualization.py", line 203, in save_labeled_frame
    fig.savefig(full_path)
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\matplotlib\figure.py", line 3343, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 75, in print_figure
    super().print_figure(*args, **kwargs)
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\matplotlib\backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\matplotlib\backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\matplotlib\image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Users\my_name\.conda\envs\DEEPLABCUT\lib\site-packages\PIL\Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\T:/my_name_deeplabcut/DLC/all-animals-test1-my_name-2022-10-23\\evaluation-results\\iteration-0\\all-animals-test1Oct23-trainset95shuffle1\\LabeledImages_DLC_effnet_b0_all-animals-test1Oct23shuffle1_1044000_snapshot-1044000\\Training-2022-08-03_rat-2022.01-img000136.png'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
There is something odd with the path and the volume name: `'\\\\?\\T:/` looks like it may be causing the issue. Is this intended?

**Comment by witeal** [comment]
> There is something odd with the path and the volume name: `'\\\\?\\T:/` looks like it may be causing the issue. Is this intended?

Hi thanks for your help, 
No it is not intended and I don't understand where it comes from as the real path to the folder should be the following one : 

'T:/my_name_deeplabcut/DLC/all-animals-test1-my_name-2022-10-23\\evaluation-results\\iteration-0\\all-animals-test1Oct23-trainset95shuffle1\\LabeledImages_DLC_effnet_b0_all-animals-test1Oct23shuffle1_1044000_snapshot-1044000\\Training-2022-08-03_rat-2022.01-img000136.png'

**Comment by witeal** [comment]
Hi, 

If I can help anyone facing the same issue. I solved my problem by moving my main folder directly to my local disk T:, it seems that the problem was coming from the length of the path.

**Comment by witeal** [comment]
Hi, 

If I can help anyone facing the same issue. I solved my problem by moving my main folder directly to my local disk T:, it seems that the problem was coming from the length of the path.

**Comment by jeylau** [comment]
Great catch @witeal! Thanks a lot for letting us know how you solved it.
