### ISSUE TITLE
Different M2 Mac Installation Problem

### ISSUE THREAD

**Issue by inwabudike** [DeepLabCut/DeepLabCut#2218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,
I have been unable to update condo environment after setting osx-64 (step 5: conda env update -f DEEPLABCUT_M1.yaml). I've tried re-installing miniconda, setting up a new user on my Mac and following the DLC GitHub instructions there, but nothing is working.  Can you please help me figure out what I'm doing wrong?

Thank you!

### Operating System

MacOS Ventura 13.0.1 (M2)

### DeepLabCut version

DeepLabCut2.3.3r

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. `git clone https://github.com/DeepLabCut/DeepLabCut.git`
2. `cd DeepLabCut/conda-environments`
3. downloaded tensor flow 2.4.1 from link on GitHub
4. `conda env create -f DEEPLABCUT_M1.yaml`
5. `conda activate DEEPLABCUT_M1`
`conda env config vars set CONDA_SUBDIR=osx-64`
`conda deactivate
conda activate DEEPLABCUT_M1`
`conda env update -f DEEPLABCUT_M1.yaml`

### Relevant log output

```shell
conda-environments % conda env update -f DEEPLABCUT_M1.yaml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
openssl-3.1.0        | 2.2 MB    | ##################################### | 100% 
python-3.9.16        | 11.0 MB   | ##################################### | 100% 
python.app-1.4       | 13 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/Users/dlc/miniconda/envs/DEEPLABCUT_M1/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/dlc/DeepLabCut/conda-environments/condaenv.6a3plsr6.requirements.txt']
Pip subprocess output:
Obtaining file:///Users/dlc/DeepLabCut (from -r /Users/dlc/DeepLabCut/conda-environments/condaenv.6a3plsr6.requirements.txt (line 3))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/dlc/DeepLabCut/setup.py", line 18, in <module>
          setuptools.setup(
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/dist.py", line 496, in __init__
          _Distribution.__init__(
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/dist.py", line 934, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/dist.py", line 933, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/npe2/__init__.py", line 9, in <module>
          from ._dynamic_plugin import DynamicPlugin
        File "/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/npe2/_dynamic_plugin.py", line 17, in <module>
          from pydantic import BaseModel, ValidationError
      ImportError: dlopen(/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so, 0x0002): tried: '/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (no such file), '/Users/dlc/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
@inwabudike, you do not need to install tensorflow yourself; this is likely what is causing the issue. Delete your previous environment and recreate a fresh one by simply running `conda env create -f DEEPLABCUT_M1.yaml`: this will install tensorflow-macos and tensorflow-metal (which are the base version of tensorflow and its Apple plugin) for you. You're then all set!

**Comment by inwabudike** [comment]
That fixed the issue. Thank you!
