### ISSUE TITLE
evaluate_network -> IndexError: list index out of range

### ISSUE THREAD

**Issue by aredwine3** [DeepLabCut/DeepLabCut#2228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When attempting to evaluate a recently trained network I encounter an error after the first saved training snapshot is evaluated. I have tried evaluating all saved snapshots and individual snapshots and the error I receive is the same. I previously encountered the same error and traceback with a different shuffle of the same network iteration and deleting the training snapshot the evaluation was failing on resolved the error, however that has not worked with this shuffle. 

### Operating System

macOS Ventura 13.4

### DeepLabCut version

DeepLabCut 2.3.4

### DeepLabCut mode

multi animal

### Device type

M1 Max

### Steps To Reproduce

1. Enter DEEPLABCUT_M1 environment
2. Switch from zshell to ipython
3. Import deeplabcut
4. Set config_path
5. Evaluate network
6. Receive error after first network snapshot is evaluated.

### Relevant log output

```shell
In [1]: import deeplabcut
Loading DLC 2.3.4...

In [2]: config_path = '/Users/adanredwine/Desktop/OpenArena-RedwineAdan-2023-01-05/config.yaml'

In [3]: deeplabcut.evaluate_network(config_path, Shuffles=[0], trainingsetindex='all')
Running  DLC_resnet50_OpenArenaJan5shuffle0_2500  with # of trainingiterations: 2500
Model already evaluated. /Users/adanredwine/Desktop/OpenArena-RedwineAdan-2023-01-05/evaluation-results/iteration-3/OpenArenaJan5-trainset95shuffle0/DLC_resnet50_OpenArenaJan5shuffle0_2500-snapshot-2500.h5
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 deeplabcut.evaluate_network(config_path, Shuffles=[0], trainingsetindex='all')

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate.py:604, in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix)
    601     from .evaluate_multianimal import evaluate_multianimal_full
    603     # TODO: Make this code not so redundant!
--> 604     evaluate_multianimal_full(
    605         config=config,
    606         Shuffles=Shuffles,
    607         trainingsetindex=trainingsetindex,
    608         plotting=plotting,
    609         comparisonbodyparts=comparisonbodyparts,
    610         gputouse=gputouse,
    611         modelprefix=modelprefix,
    612     )
    613 else:
    614     from deeplabcut.utils.auxfun_videos import imread, imresize

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py:585, in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix)
    579     n_graphs = 1
    580     paf_inds = [list(range(n_edges))]
    581 (
    582     results,
    583     paf_scores,
    584     best_assemblies,
--> 585 ) = crossvalutils.cross_validate_paf_graphs(
    586     config,
    587     str(path_test_config).replace("pose_", "inference_"),
    588     data_path,
    589     data_path.replace("_full.", "_meta."),
    590     n_graphs=n_graphs,
    591     paf_inds=paf_inds,
    592     oks_sigma=dlc_cfg.get("oks_sigma", 0.1),
    593     margin=dlc_cfg.get("bbox_margin", 0),
    594     symmetric_kpts=dlc_cfg.get("symmetric_kpts"),
    595 )
    596 if plotting == "individual":
    597     assemblies, assemblies_unique, image_paths = best_assemblies

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py:429, in cross_validate_paf_graphs(config, inference_config, full_data_file, metadata_file, output_name, pcutoff, oks_sigma, margin, greedy, add_discarded, calibrate, overwrite_config, n_graphs, paf_inds, symmetric_kpts)
    426 else:
    427     calibration_file = ""
--> 429 results = _benchmark_paf_graphs(
    430     cfg,
    431     inf_cfg_temp,
    432     data,
    433     paf_inds,
    434     greedy,
    435     add_discarded,
    436     oks_sigma=oks_sigma,
    437     margin=margin,
    438     symmetric_kpts=symmetric_kpts,
    439     calibration_file=calibration_file,
    440     split_inds=[
    441         metadata["data"]["trainIndices"],
    442         metadata["data"]["testIndices"],
    443     ],
    444 )
    445 # Select optimal PAF graph
    446 df = results[1]

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py:198, in _benchmark_paf_graphs(config, inference_cfg, data, paf_inds, greedy, add_discarded, identity_only, calibration_file, oks_sigma, margin, symmetric_kpts, split_inds)
    196 for k, v in data.items():
    197     data_[k] = v["prediction"]
--> 198 ass = Assembler(
    199     data_,
    200     max_n_individuals=inference_cfg["topktoretain"],
    201     n_multibodyparts=n_multi,
    202     greedy=greedy,
    203     pcutoff=inference_cfg.get("pcutoff", 0.1),
    204     min_affinity=inference_cfg.get("pafthreshold", 0.1),
    205     add_discarded=add_discarded,
    206     identity_only=identity_only,
    207 )
    208 if calibration_file:
    209     ass.calibrate(calibration_file)

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py:256, in Assembler.__init__(self, data, max_n_individuals, n_multibodyparts, graph, paf_inds, greedy, pcutoff, min_affinity, min_n_links, max_overlap, identity_only, nan_policy, force_fusion, add_discarded, window_size, method)
    254 self.min_n_links = min_n_links
    255 self.max_overlap = max_overlap
--> 256 self._has_identity = "identity" in self[0]
    257 if identity_only and not self._has_identity:
    258     warnings.warn(
    259         "The network was not trained with identity; setting `identity_only` to False."
    260     )

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py:277, in Assembler.__getitem__(self, item)
    276 def __getitem__(self, item):
--> 277     return self.data[self.metadata["imnames"][item]]

IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hey @aredwine3, to evaluate all snapshots it is `snapshotindex: 'all'` that you must set in the main config.yaml file. `trainingsetindex` has a different use: it must be an integer, and specifies what training split to use (when you created multiple ones).

**Comment by aredwine3** [comment]
Hey @jeylau, thank you for your reply. My `snapshotindex` is set to all in my config.yaml file. Thank you for the clarification on `trainingsetindex`. Unfortunately, I am still encountering the same error when attempting evaluate the network, whether it is through the command line or GUI.

**Command line:**
```{python}
In [5]: deeplabcut.evaluate_network(config_path, Shuffles=[0])
Running  DLC_resnet50_OpenArenaJan5shuffle0_2500  with # of trainingiterations: 2500
Model already evaluated. /Users/adanredwine/Desktop/OpenArena-RedwineAdan-2023-01-05/evaluation-results/iteration-3/OpenArenaJan5-trainset95shuffle0/DLC_resnet50_OpenArenaJan5shuffle0_2500-snapshot-2500.h5
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 deeplabcut.evaluate_network(config_path, Shuffles=[0])

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate.py:604, in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix)
    601     from .evaluate_multianimal import evaluate_multianimal_full
    603     # TODO: Make this code not so redundant!
--> 604     evaluate_multianimal_full(
    605         config=config,
    606         Shuffles=Shuffles,
    607         trainingsetindex=trainingsetindex,
    608         plotting=plotting,
    609         comparisonbodyparts=comparisonbodyparts,
    610         gputouse=gputouse,
    611         modelprefix=modelprefix,
    612     )
    613 else:
    614     from deeplabcut.utils.auxfun_videos import imread, imresize

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py:585, in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix)
    579     n_graphs = 1
    580     paf_inds = [list(range(n_edges))]
    581 (
    582     results,
    583     paf_scores,
    584     best_assemblies,
--> 585 ) = crossvalutils.cross_validate_paf_graphs(
    586     config,
    587     str(path_test_config).replace("pose_", "inference_"),
    588     data_path,
    589     data_path.replace("_full.", "_meta."),
    590     n_graphs=n_graphs,
    591     paf_inds=paf_inds,
    592     oks_sigma=dlc_cfg.get("oks_sigma", 0.1),
    593     margin=dlc_cfg.get("bbox_margin", 0),
    594     symmetric_kpts=dlc_cfg.get("symmetric_kpts"),
    595 )
    596 if plotting == "individual":
    597     assemblies, assemblies_unique, image_paths = best_assemblies

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py:429, in cross_validate_paf_graphs(config, inference_config, full_data_file, metadata_file, output_name, pcutoff, oks_sigma, margin, greedy, add_discarded, calibrate, overwrite_config, n_graphs, paf_inds, symmetric_kpts)
    426 else:
    427     calibration_file = ""
--> 429 results = _benchmark_paf_graphs(
    430     cfg,
    431     inf_cfg_temp,
    432     data,
    433     paf_inds,
    434     greedy,
    435     add_discarded,
    436     oks_sigma=oks_sigma,
    437     margin=margin,
    438     symmetric_kpts=symmetric_kpts,
    439     calibration_file=calibration_file,
    440     split_inds=[
    441         metadata["data"]["trainIndices"],
    442         metadata["data"]["testIndices"],
    443     ],
    444 )
    445 # Select optimal PAF graph
    446 df = results[1]

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py:198, in _benchmark_paf_graphs(config, inference_cfg, data, paf_inds, greedy, add_discarded, identity_only, calibration_file, oks_sigma, margin, symmetric_kpts, split_inds)
    196 for k, v in data.items():
    197     data_[k] = v["prediction"]
--> 198 ass = Assembler(
    199     data_,
    200     max_n_individuals=inference_cfg["topktoretain"],
    201     n_multibodyparts=n_multi,
    202     greedy=greedy,
    203     pcutoff=inference_cfg.get("pcutoff", 0.1),
    204     min_affinity=inference_cfg.get("pafthreshold", 0.1),
    205     add_discarded=add_discarded,
    206     identity_only=identity_only,
    207 )
    208 if calibration_file:
    209     ass.calibrate(calibration_file)

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py:256, in Assembler.__init__(self, data, max_n_individuals, n_multibodyparts, graph, paf_inds, greedy, pcutoff, min_affinity, min_n_links, max_overlap, identity_only, nan_policy, force_fusion, add_discarded, window_size, method)
    254 self.min_n_links = min_n_links
    255 self.max_overlap = max_overlap
--> 256 self._has_identity = "identity" in self[0]
    257 if identity_only and not self._has_identity:
    258     warnings.warn(
    259         "The network was not trained with identity; setting `identity_only` to False."
    260     )

File ~/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py:277, in Assembler.__getitem__(self, item)
    276 def __getitem__(self, item):
--> 277     return self.data[self.metadata["imnames"][item]]

IndexError: list index out of range
```

**GUI:**
```{python}
2023-05-03 11:06:35.219 python3[81337:17029282] +[CATransaction synchronize] called within transaction
Traceback (most recent call last):
  File "/Users/adanredwine/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/gui/tabs/evaluate_network.py", line 184, in evaluate_network
    deeplabcut.evaluate_network(
  File "/Users/adanredwine/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate.py", line 604, in evaluate_network
    evaluate_multianimal_full(
  File "/Users/adanredwine/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py", line 585, in evaluate_multianimal_full
    ) = crossvalutils.cross_validate_paf_graphs(
  File "/Users/adanredwine/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py", line 429, in cross_validate_paf_graphs
    results = _benchmark_paf_graphs(
  File "/Users/adanredwine/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py", line 198, in _benchmark_paf_graphs
    ass = Assembler(
  File "/Users/adanredwine/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 257, in __init__
    if identity_only and not self._has_identity:
  File "/Users/adanredwine/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 280, in __getitem__
    def n_keypoints(self):
IndexError: list index out of range
```

**Comment by jeylau** [comment]
This is odd: it is telling us that `self.metadata["imnames"]` is empty 🤔 What were the train & test RMS errors shown in the terminal during network evaluation?

**Comment by aredwine3** [comment]
They were both "nan", it was only able to evaluate a few of the first saved iterations before returning that error.

**Comment by MMathisLab** [comment]
seems the model is far from being converged; 3500 iterations is about 10X less that what is baseline recommended (we recommend ~batch size 8 for 50-100K iterations).

**Comment by aredwine3** [comment]
The iteration at 2500 is only the first I have saved that is being evaluated when I attempt to evaluate the network, the network is trained to 42.5K iterations. I receive this error and am unable to evaluate any of the saved iterations.
