### ISSUE TITLE
Graph Execution Error when Training Network

### ISSUE THREAD

**Issue by Nike-Nay** [DeepLabCut/DeepLabCut#2248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After successfully labelling the frames and creating the dataset, when attempting to train the network, it runs for around 10 minutes and then returns an 'InvalidArgumentError: Graph Execution Error'. I am not sure where the issue is or how to even approach fixing it without causing more issues.

### Operating System

Microsoft Windows 10

### DeepLabCut version

DLC version: 2.3.4

### DeepLabCut mode

single animal

### Device type

Intel(R) Core(TM) i7 - 10750H CPU @ 2.60GHz

### Steps To Reproduce

1. activate DEEPLABCUT
2. ipython
3. import deeplabcut
4. path_config_file = 'path to config file'
5. deeplabcut.train_network(path_config_file)

### Relevant log output

```shell
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]],
 'all_joints_names': ['mouthpiece',
                      'head',
                      'thoraxtop',
                      'thoraxbottom',
                      'wings',
                      'leg1',
                      'leg2',
                      'leg3',
                      'posterior',
                      'genitalia'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'contrast': {'clahe': True,
              'claheratio': 0.1,
              'histeq': True,
              'histeqratio': 0.1},
 'convolution': {'edge': False,
                 'emboss': {'alpha': [0.0, 1.0], 'strength': [0.5, 1.5]},
                 'embossratio': 0.1,
                 'sharpen': False,
                 'sharpenratio': 0.3},
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Control1May10\\Control1_Nikol95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\asus\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Control1May10\\Documentation_data-Control1_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 10,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\asus\\Desktop\\dlc\\Control1-Nikol-2023-05-10',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\asus\\Desktop\\dlc\\Control1-Nikol-2023-05-10\\dlc-models\\iteration-0\\Control1May10-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-05-14 19:15:15.787574: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading ImageNet-pretrained resnet_50
C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py:227: UserWarning: Switching to Adam, as SGD crashes on Apple Silicon.
  warnings.warn("Switching to Adam, as SGD crashes on Apple Silicon.")
2023-05-14 19:15:17.660226: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:357] MLIR V1 optimization pass is not enabled
2023-05-14 19:15:21.404625: W tensorflow/c/c_api.cc:291] Operation '{name:'Adam/update_resnet_v1_50/conv1/weights/ResourceApplyAdam' id:7177 op device:{requested: '', assigned: ''} def:{{{node Adam/update_resnet_v1_50/conv1/weights/ResourceApplyAdam}} = ResourceApplyAdam[T=DT_FLOAT, _class=["loc:@resnet_v1_50/conv1/weights"], _has_manual_control_dependencies=true, use_locking=false, use_nesterov=false](resnet_v1_50/conv1/weights, resnet_v1_50/conv1/weights/Adam, resnet_v1_50/conv1/weights/Adam_1, Adam/update_resnet_v1_50/conv1/weights/ResourceApplyAdam/ReadVariableOp, Adam/update_resnet_v1_50/conv1/weights/ResourceApplyAdam/ReadVariableOp_1, Placeholder_5, Adam/beta1, Adam/beta2, Adam/epsilon, gradients/resnet_v1_50/conv1/Conv2D_grad/tuple/control_dependency_1)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
2023-05-14 19:15:21.650073: W tensorflow/c/c_api.cc:291] Operation '{name:'resnet_v1_50/block4/unit_2/bottleneck_v1/conv2/BatchNorm/gamma/Adam_1/Assign' id:6960 op device:{requested: '', assigned: ''} def:{{{node resnet_v1_50/block4/unit_2/bottleneck_v1/conv2/BatchNorm/gamma/Adam_1/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](resnet_v1_50/block4/unit_2/bottleneck_v1/conv2/BatchNorm/gamma/Adam_1, resnet_v1_50/block4/unit_2/bottleneck_v1/conv2/BatchNorm/gamma/Adam_1/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
2023-05-14 19:15:21.823221: W tensorflow/c/c_api.cc:291] Operation '{name:'pose/locref_pred/block4/biases/Adam_1/Assign' id:7170 op device:{requested: '', assigned: ''} def:{{{node pose/locref_pred/block4/biases/Adam_1/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](pose/locref_pred/block4/biases/Adam_1, pose/locref_pred/block4/biases/Adam_1/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\asus\\Desktop\\dlc\\Control1-Nikol-2023-05-10\\dlc-models\\iteration-0\\Control1May10-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]], 'all_joints_names': ['mouthpiece', 'head', 'thoraxtop', 'thoraxbottom', 'wings', 'leg1', 'leg2', 'leg3', 'posterior', 'genitalia'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'contrast': {'clahe': True, 'claheratio': 0.1, 'histeq': True, 'histeqratio': 0.1, 'gamma': False, 'sigmoid': False, 'log': False, 'linear': False}, 'convolution': {'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'strength': [0.5, 1.5]}, 'embossratio': 0.1, 'sharpen': False, 'sharpenratio': 0.3}, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Control1May10\\Control1_Nikol95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'init_weights': 'C:\\Users\\asus\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Control1May10\\Documentation_data-Control1_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 10, 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\asus\\Desktop\\dlc\\Control1-Nikol-2023-05-10', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
iteration: 1000 loss: 579878603351063.7500 lr: 0.005
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py:1378, in BaseSession._do_call(self, fn, *args)
   1377 try:
-> 1378   return fn(*args)
   1379 except errors.OpError as e:

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py:1361, in BaseSession._do_run.<locals>._run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1360 self._extend_graph()
-> 1361 return self._call_tf_sessionrun(options, feed_dict, fetch_list,
   1362                                 target_list, run_metadata)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py:1454, in BaseSession._call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1452 def _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list,
   1453                         run_metadata):
-> 1454   return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
   1455                                           fetch_list, target_list,
   1456                                           run_metadata)

InvalidArgumentError: LossTensor is inf or nan : Tensor had NaN values
         [[{{node train_op/CheckNumerics}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
Cell In[10], line 1
----> 1 deeplabcut.train_network(path_config_file)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py:223, in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    212         train(
    213             str(poseconfigfile),
    214             displayiters,
   (...)
    219             allow_growth=allow_growth,
    220         )  # pass on path and file name for pose_cfg.yaml!
    222 except BaseException as e:
--> 223     raise e
    224 finally:
    225     os.chdir(str(start_path))

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py:212, in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    209         from deeplabcut.pose_estimation_tensorflow.core.train import train
    211         print("Selecting single-animal trainer")
--> 212         train(
    213             str(poseconfigfile),
    214             displayiters,
    215             saveiters,
    216             maxiters,
    217             max_to_keep=max_snapshots_to_keep,
    218             keepdeconvweights=keepdeconvweights,
    219             allow_growth=allow_growth,
    220         )  # pass on path and file name for pose_cfg.yaml!
    222 except BaseException as e:
    223     raise e

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py:283, in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep, keepdeconvweights, allow_growth)
    280     current_lr = lr_gen.get_lr(it - start_iter)
    281     lr_dict = {learning_rate: current_lr}
--> 283 [_, loss_val, summary] = sess.run(
    284     [train_op, total_loss, merged_summaries], feed_dict=lr_dict
    285 )
    286 cum_loss += loss_val
    287 train_writer.add_summary(summary, it)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py:968, in BaseSession.run(self, fetches, feed_dict, options, run_metadata)
    965 run_metadata_ptr = tf_session.TF_NewBuffer() if run_metadata else None
    967 try:
--> 968   result = self._run(None, fetches, feed_dict, options_ptr,
    969                      run_metadata_ptr)
    970   if run_metadata:
    971     proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py:1191, in BaseSession._run(self, handle, fetches, feed_dict, options, run_metadata)
   1188 # We only want to really perform the run if fetches or targets are provided,
   1189 # or if the call is a partial run that specifies feeds.
   1190 if final_fetches or final_targets or (handle and feed_dict_tensor):
-> 1191   results = self._do_run(handle, final_targets, final_fetches,
   1192                          feed_dict_tensor, options, run_metadata)
   1193 else:
   1194   results = []

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py:1371, in BaseSession._do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1368   return self._call_tf_sessionprun(handle, feed_dict, fetch_list)
   1370 if handle is None:
-> 1371   return self._do_call(_run_fn, feeds, fetches, targets, options,
   1372                        run_metadata)
   1373 else:
   1374   return self._do_call(_prun_fn, handle, feeds, fetches)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py:1397, in BaseSession._do_call(self, fn, *args)
   1392 if 'only supports NHWC tensor format' in message:
   1393   message += ('\nA possible workaround: Try disabling Grappler optimizer'
   1394               '\nby modifying the config for creating the session eg.'
   1395               '\nsession_config.graph_options.rewrite_options.'
   1396               'disable_meta_optimizer = True')
-> 1397 raise type(e)(node_def, op, message)

InvalidArgumentError: Graph execution error:

Detected at node 'train_op/CheckNumerics' defined at (most recent call last):
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\Scripts\ipython-script.py", line 9, in <module>
      sys.exit(start_ipython())
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\__init__.py", line 124, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
      app.start()
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\terminal\ipapp.py", line 318, in start
      self.shell.mainloop()
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\terminal\interactiveshell.py", line 887, in mainloop
      self.interact()
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\terminal\interactiveshell.py", line 880, in interact
      self.run_cell(code, store_history=True)
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_cell
      result = self._run_cell(
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3016, in _run_cell
      result = runner(coro)
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3221, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3400, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-10-7e3f40db92d4>", line 1, in <module>
      deeplabcut.train_network(path_config_file)
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 212, in train_network
      train(
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 238, in train
      learning_rate, train_op, tstep = get_optimizer(total_loss, cfg)
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 117, in get_optimizer
      train_op = slim.learning.create_train_op(loss_op, optimizer)
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\learning.py", line 436, in create_train_op
      return training.create_train_op(
    File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\training\training.py", line 468, in create_train_op
      total_loss = array_ops.check_numerics(total_loss,
Node: 'train_op/CheckNumerics'
LossTensor is inf or nan : Tensor had NaN values
         [[{{node train_op/CheckNumerics}}]]

Original stack trace for 'train_op/CheckNumerics':
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\Scripts\ipython-script.py", line 9, in <module>
    sys.exit(start_ipython())
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\terminal\ipapp.py", line 318, in start
    self.shell.mainloop()
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\terminal\interactiveshell.py", line 887, in mainloop
    self.interact()
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\terminal\interactiveshell.py", line 880, in interact
    self.run_cell(code, store_history=True)
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_cell
    result = self._run_cell(
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3016, in _run_cell
    result = runner(coro)
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3221, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3400, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-7e3f40db92d4>", line 1, in <module>
    deeplabcut.train_network(path_config_file)
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 212, in train_network
    train(
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 238, in train
    learning_rate, train_op, tstep = get_optimizer(total_loss, cfg)
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 117, in get_optimizer
    train_op = slim.learning.create_train_op(loss_op, optimizer)
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\learning.py", line 436, in create_train_op
    return training.create_train_op(
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\training\training.py", line 468, in create_train_op
    total_loss = array_ops.check_numerics(total_loss,
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1220, in check_numerics
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\asus\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\ops.py", line 3798, in _create_op_internal
    ret = Operation(
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
HI @Nike-Nay - seems an issue with tensorflow optimizer nd possible mismatch with your GPU (sadly something DLC we cannot easily control!); see related issues:
- https://forum.image.sc/t/facing-invalidargumenterror-losstensor-is-inf-of-nan-tensor-had-nan-values/78946/5
- https://github.com/DeepLabCut/DeepLabCut/issues/1017
(please search issues before opening new ones, it helps us link things together!!)
