### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by tzeriver** [DeepLabCut/DeepLabCut#2268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

deeplabcut.analyze_videos() stops with the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fenglab/anaconda3/envs/DLC_2.3.5/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 640, in analyze_videos
    convert_detections2tracklets(
  File "/home/fenglab/anaconda3/envs/DLC_2.3.5/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 1873, in convert_detections2tracklets
    trackingutils.fill_tracklets(
  File "/home/fenglab/anaconda3/envs/DLC_2.3.5/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/lib/trackingutils.py", line 761, in fill_tracklets
    tracklet_id, pred_id = content[-2:].astype(np.int)
  File "/home/fenglab/anaconda3/envs/DLC_2.3.5/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### Operating System

Ubuntu 20.04

### DeepLabCut version

2.3.5

### DeepLabCut mode

multi animal

### Device type

RTX 3080

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @tzeriver can you report the version of numpy you are using?

**Comment by tzeriver** [comment]
'1.24.3'

**Comment by jeylau** [comment]
Hi @tzeriver, this will be fixed with #2270. Meanwhile, you could downgrade numpy using e.g. `pip install numpy<1.24`.
