### ISSUE TITLE
NOT_FOUND: Key resnet_v1_152/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint

### ISSUE THREAD

**Issue by koronfelina** [DeepLabCut/DeepLabCut#2278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I cannot evaluate or analyze the videos. I checked for similar issues but the ones I found were not answered!! Also I'm not professional in understanding the programming terminology so please let me know what I should do in the User interface or in my folders or what I should write/change to be able to evaluate and analyze my videos!! Thank you

### Operating System

windows 11

### DeepLabCut version

dlc version 2.2.0.2

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce
```

(base) C:\Users\81904>conda activate deeplabcut

(deeplabcut) C:\Users\81904>python -m deeplabcut
Starting GUI...
D:\EyeBehaviour_B19N3-LMK-2022-02-10/evaluation-results/  already exists!
D:\EyeBehaviour_B19N3-LMK-2022-02-10\evaluation-results\iteration-0\EyeBehaviour_B19N3Feb10-trainset95shuffle1  already exists!

Running  DLC_resnet152_EyeBehaviour_B19N3Feb10shuffle1_100000  with # of trainingiterations: 100000
C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Traceback (most recent call last):
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\client\session.py", line 1380, in _do_call
    return fn(*args)
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\client\session.py", line 1456, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) NOT_FOUND: Key resnet_v1_152/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_211]]
  (1) NOT_FOUND: Key resnet_v1_152/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\training\saver.py", line 1404, in restore
    sess.run(self.saver_def.restore_op_name,
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\client\session.py", line 970, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\client\session.py", line 1193, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\client\session.py", line 1373, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\client\session.py", line 1399, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) NOT_FOUND: Key resnet_v1_152/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[node save/RestoreV2
 (defined at C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py:44)
]]
         [[save/RestoreV2/_211]]
  (1) NOT_FOUND: Key resnet_v1_152/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[node save/RestoreV2
 (defined at C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\predict.py:44)
]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node save/RestoreV2:
In[0] save/Const:
In[1] save/RestoreV2/tensor_names:
In[2] save/RestoreV2/shape_and_slices:

```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @koronfelina, which version of tensorflow are you using?

Edit: to check the version, you can open the terminal, and type:
```
python

import tensorflow

tensorflow.__version__

```

**Comment by MMathisLab** [comment]
minimally I would strongly recommend updating to a newer DLC version; 2.2.02 is quite old!
