### ISSUE TITLE
FileNotFoundError when trying to extract outlier frames

### ISSUE THREAD

**Issue by ckKLI** [DeepLabCut/DeepLabCut#2279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have analyzed some videos. The labeling was not optimal yet, so I tried to extract outlier frames. This did not work and I got an error message.

### Operating System

Windows 11

### DeepLabCut version

DLC version 2.3.5

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 4050

### Relevant log output

```shell
Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:01:59) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
Loading DLC 2.3.5...

In [2]: config_path = "D:/DeepLabCut/Snail 4 Feb 2023-Carina Kronsteiner-2023-02-08/config.yaml"

In [3]: deeplabcut.extract_outlier_frames(config_path, ["D:/Schnecken Verhalten Videos/2 Mittelalt 2 Jung 1 27.11.-12.1
   ...: 2.19/27.11.19 Mittelalt 2 Jung 1 vor Konditionierung/einzelne Videos/S43.mp4"], outlieralgorithm="manual")
Installed qt6 event loop hook.

Traceback (most recent call last):
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_widgets.py", line 281, in _extrae
    _write_image(frame, str(output_path))
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_writer.py", line 85, in _write_ie
    imsave(
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\skimage\io\_io.py", line 143, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\skimage\io\manage_plugins.py", line 205, in call_pln
    return func(*args, **kwargs)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\v3.py", line 139, in imwrite
    with imopen(
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\core\imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\core\request.py", line 247, in __init__
    self._parse_uri(uri)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\core\request.py", line 412, in _parse_uri
    raise FileNotFoundError("The directory %r does not exist" % dn)
FileNotFoundError: The directory 'D:\\Schnecken Verhalten Videos\\2 Mittelalt 2 Jung 1 27.11.-12.12.19\\27.11.19 Mittelt

If you suspect this is an IPython 8.12.2 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @ckKLI, could you try the following:
- use a raw string (by just adding an 'r' in front of the string) for your video path: `[r"D:/Schnecken Verh... "`
- use backslashes instead of forward slashes: `[r"D:\Schnecken Verh... "`

Let me know if that fixes it for you

**Comment by ckKLI** [comment]
Thanks for your suggestion. I added an r in front of the string and replaced / with \. After that, as before, napari opens and as soon as I click on the "extract frame" button, I get an error message again. 
```
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
Loading DLC 2.3.5...

In [2]: config_path = "D:\DeepLabCut\Snail 4 Feb 2023-Carina Kronsteiner-2023-02-08\config.yaml"

In [3]: deeplabcut.extract_outlier_frames(config_path, [r"D:\Schnecken Verhalten Videos\2 Mittelalt 2 Jung 1 27.11.-12.
   ...: 12.19\27.11.19 Mittelalt 2 Jung 1 vor Konditionierung\einzelne Videos\S43.mp4"], outlieralgorithm="manual")
Installed qt6 event loop hook.

Traceback (most recent call last):
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_widgets.py", line 281, in _extrae    _write_image(frame, str(output_path))
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_writer.py", line 85, in _write_ie    imsave(
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\skimage\io\_io.py", line 143, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\skimage\io\manage_plugins.py", line 205, in call_pln    return func(*args, **kwargs)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\v3.py", line 139, in imwrite
    with imopen(
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\core\imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\core\request.py", line 247, in __init__
    self._parse_uri(uri)
  File "C:\Users\Carina\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\core\request.py", line 412, in _parse_uri
    raise FileNotFoundError("The directory %r does not exist" % dn)
FileNotFoundError: The directory 'D:\\Schnecken Verhalten Videos\\2 Mittelalt 2 Jung 1 27.11.-12.12.19\\27.11.19 Mittelt
If you suspect this is an IPython 8.12.2 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by ckKLI** [comment]
I also tried to extract outlier frames using the GUI with each of the 4 algorithms available (jump, fitting, uncertain, manual), but it doesn't work either. I don't get any error messages when using the GUI, but there are no files created in the DLC labeled data folder. No .h5 file and no pictures.

**Comment by n-poulsen** [comment]
Could you check if the video can be found by python using the following snippet:

```
from pathlib import Path
print(Path("D:/Schnecken Verhalten Videos/2 Mittelalt 2 Jung 1 27.11.-12.12.19/27.11.19 Mittelalt 2 Jung 1 vor Konditionierung/einzelne Videos/S43.mp4").exists())
```

**Comment by ckKLI** [comment]
I checked it and I get the following:

In [3]: from pathlib import Path
   ...: print(Path("D:/Schnecken Verhalten Videos/2 Mittelalt 2 Jung 1 27.11.-12.12.19/27.11.19 Mittelalt 2 Jung 1 vor
   ...: Konditionierung/einzelne Videos/S43.mp4").exists())
True

**Comment by n-poulsen** [comment]
I was able to replicate your issue, thanks! If you run

```python
import deeplabcut
config_path = "D:\DeepLabCut\Snail 4 Feb 2023-Carina Kronsteiner-2023-02-08\config.yaml"
videos = ["D:/Schnecken Verhalten Videos/2 Mittelalt 2 Jung 1 27.11.-12.12.19/27.11.19 Mittelalt 2 Jung 1 vor Konditionierung/einzelne Videos/S43.mp4"]
deeplabcut.extract_outlier_frames(config_path, videos)
``` 

Does it run correctly? You won't be able to choose the frames extracted from the video, but this might be a temporary solution while we work on a fix for the manual outlier extraction.

**Comment by ckKLI** [comment]
Yes, that works. Thank you. I will use this method until there is a fix for the manual outlier extraction.
Would be happy to hear about it when you found a solution for it.
