### ISSUE TITLE
Unable to open frames for labeling

### ISSUE THREAD

**Issue by blogeman** [DeepLabCut/DeepLabCut#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using the DLC GUI I click on the 'Label Frames' tab and then on the 'Label Frames' button. I select which folder I would like to open and a blank napari window opens without any images and the terminal returns the following error message. 

I've been trying to debug this myself but am now stuck. 

### Operating System

operating system: Windows 10

### DeepLabCut version

dlc version: 2.3.5

### DeepLabCut mode

multi animal

### Device type

gpu: NA

### Relevant log output

```shell
Starting GUI...
C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\pims\api.py:205: UserWarning: <class 'pims.image_reader.ImageReader'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
  warn(message)
C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\pims\api.py:205: UserWarning: <class 'pims.image_reader.ImageReaderND'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
  warn(message)
C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\pims\api.py:205: UserWarning: <class 'pims.imageio_reader.ImageIOReader'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
  warn(message)
Traceback (most recent call last):
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\deeplabcut\gui\tabs\label_frames.py", line 55, in label_frames
    _ = launch_napari(folder)
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\deeplabcut\gui\widgets.py", line 45, in launch_napari
    viewer.open(files, plugin="napari-deeplabcut")
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\napari\components\viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\napari\components\viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\napari\plugins\io.py", line 77, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\napari\plugins\_npe2.py", line 55, in read
    layer_data, reader = io_utils.read_get_reader(
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\npe2\io_utils.py", line 66, in read_get_reader
    return _read(
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\npe2\io_utils.py", line 160, in _read
    read_func = rdr.exec(
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\npe2\manifest\contributions\_readers.py", line 52, in exec
    callable_ = super().exec(kwargs=kwargs)
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\npe2\manifest\utils.py", line 63, in exec
    return self.get_callable(reg)(*args, **kwargs)
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\napari_deeplabcut\_reader.py", line 74, in get_folder_parser
    layers.extend(read_images(images))
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\napari_deeplabcut\_reader.py", line 102, in read_images
    return [(imread(path), params, "image")]
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\dask_image\imread\__init__.py", line 48, in imread
    with pims.open(sfname) as imgs:
  File "C:\Users\blogeman\anaconda3\envs\DLC\lib\site-packages\pims\api.py", line 207, in open
    raise UnknownFormatError("All handlers returned exceptions:\n" + exceptions)
pims.api.UnknownFormatError: All handlers returned exceptions:
<class 'pims.image_reader.ImageReader'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
<class 'pims.image_reader.ImageReaderND'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
<class 'pims.imageio_reader.ImageIOReader'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
```

### Anything else?

My assumption is that the error is in the way the filepath is being input to pims. However, since I haven't found any other users reporting this error and have no idea what is unique to my setup, I suspect it must be something else. For example, running the following seems to work just fine.

import pims
pims.open('E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\img15288.png')

E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\img15288.png
<Frames>
Length: 1 frames
Frame Shape: 720 x 1280
Pixel Datatype: uint8

However, using the asterisk operator returns the same error as when using the DLC GUI

import pims
pims.open('E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png')

E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png
---------------------------------------------------------------------------
UnknownFormatError                        Traceback (most recent call last)
Cell In[4], line 1
----> 1 pims.open('E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png')

File ~\anaconda3\envs\DLC\lib\site-packages\pims\api.py:207, in open(sequence, **kwargs)
    205         warn(message)
    206         exceptions += message + '\n'
--> 207 raise UnknownFormatError("All handlers returned exceptions:\n" + exceptions)

UnknownFormatError: All handlers returned exceptions:
<class 'pims.image_reader.ImageReader'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
<class 'pims.image_reader.ImageReaderND'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'
<class 'pims.imageio_reader.ImageIOReader'> errored: No such file: 'E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png'

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @blogeman! I was not able to replicate your issue. Could you let me know which package versions you're using? The output of `conda list` in your DeepLabCut anaconda environment would be useful.

And is this a folder where there are only images, or have you already labeled some data (and have an `.h5` or some other data files present)?

**Comment by blogeman** [comment]
Thanks for the help @n-poulsen. Below is the output of conda list:

(DLC) C:\Windows\system32>conda list
# packages in environment at C:\Users\blogeman\anaconda3\envs\DLC:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h63175ca_0    conda-forge
app-model                 0.1.4                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h91455d4_3    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc2                    2.0.0                    pypi_0    pypi
build                     0.10.0                   pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
cachey                    0.2.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1           py38h57701bc_3    conda-forge
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.34                  pypi_0    pypi
dask                      2023.5.0                 pypi_0    pypi
dask-image                2023.3.0                 pypi_0    pypi
dav1d                     1.2.0                hcfcfb64_0    conda-forge
debugpy                   1.6.7            py38hd3f51b4_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deeplabcut                2.3.5                    pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dlclibrary                0.0.3                    pypi_0    pypi
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
ffmpeg                    5.1.2           gpl_h5037a79_109    conda-forge
filelock                  3.12.0                   pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               23.5.9                   pypi_0    pypi
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.4                   pypi_0    pypi
freetype                  2.12.1               h546665d_1    conda-forge
freetype-py               2.4.0                    pypi_0    pypi
fsspec                    2023.5.0                 pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.76.2               h12be248_0    conda-forge
glib-tools                2.76.2               h12be248_0    conda-forge
google-auth               2.18.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
gst-plugins-base          1.22.0               h001b923_2    conda-forge
gstreamer                 1.22.0               h6b5321d_2    conda-forge
h5py                      3.8.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
huggingface-hub           0.14.1                   pypi_0    pypi
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imageio                   2.28.1                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
in-n-out                  0.1.7                    pypi_0    pypi
ipykernel                 6.23.1             pyh025b116_0    conda-forge
ipython                   8.12.2             pyh08f2357_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py38haa244fe_8    conda-forge
jupyter_client            8.2.0              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py38haa244fe_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.7              pyhd8ed1ab_0    conda-forge
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.20.1               heb0366b_0    conda-forge
lazy-loader               0.2                      pypi_0    pypi
libclang                  16.0.0                   pypi_0    pypi
libclang13                16.0.3          default_h45d3cf4_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.76.2               he8f3873_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.41.2               hcfcfb64_1    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.40.0                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
magicgui                  0.7.2                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2            py38h91455d4_0    conda-forge
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2                    pypi_0    pypi
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
msgpack                   1.0.5                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
napari                    0.4.17                   pypi_0    pypi
napari-console            0.0.8                    pypi_0    pypi
napari-deeplabcut         0.1.2                    pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
natsort                   8.3.1                    pypi_0    pypi
nb_conda                  2.2.1                     win_6    conda-forge
nb_conda_kernels          2.3.1            py38haa244fe_2    conda-forge
nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
nbclient                  0.7.4              pyhd8ed1ab_0    conda-forge
nbconvert                 7.4.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.4.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.4.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  3.1                      pypi_0    pypi
notebook                  6.5.4              pyha770c72_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
npe2                      0.7.0                    pypi_0    pypi
numba                     0.57.0                   pypi_0    pypi
numexpr                   2.8.4                    pypi_0    pypi
numpy                     1.21.1                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openh264                  2.3.1                h63175ca_2    conda-forge
openssl                   3.1.0                hcfcfb64_3    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.1                    pypi_0    pypi
pandoc                    2.19.2               h57928b3_2    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.0                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pcre2                     10.40                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.5.0                    pypi_0    pypi
pims                      0.6.1                    pypi_0    pypi
pint                      0.21                     pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.5            py38h91455d4_0    conda-forge
psygnal                   0.9.0                    pypi_0    pypi
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-cpuinfo                9.0.0                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.7                   pypi_0    pypi
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.6                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyproject-hooks           1.0.0                    pypi_0    pypi
pyqt                      5.15.7           py38hd6c051e_3    conda-forge
pyqt5-sip                 12.11.0          py38hd3f51b4_3    conda-forge
pyrsistent                0.19.3           py38h91455d4_0    conda-forge
pyside6                   6.3.1                    pypi_0    pypi
pyside6-addons            6.3.1                    pypi_0    pypi
pyside6-essentials        6.3.1                    pypi_0    pypi
python                    3.8.16          h4de0772_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytomlpp                  1.0.13                   pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   304              py38hd3f51b4_2    conda-forge
pywinpty                  2.0.10           py38hd3f51b4_0    conda-forge
pyyaml                    6.0              py38h91455d4_5    conda-forge
pyzmq                     25.0.2           py38ha85f68a_0    conda-forge
qdarkstyle                3.1                      pypi_0    pypi
qt-main                   5.15.8              h2c8576c_11    conda-forge
qtconsole                 5.4.3              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.3              pyha770c72_0    conda-forge
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
requests                  2.30.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.3.5                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.17.26                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
send2trash                1.8.2              pyh08f2357_0    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1                    pypi_0    pypi
shiboken6                 6.3.1                    pypi_0    pypi
sip                       6.7.9            py38hd3f51b4_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slicerator                1.1.0                    pypi_0    pypi
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0                   pypi_0    pypi
superqt                   0.4.1                    pypi_0    pypi
svt-av1                   1.4.1                h63175ca_0    conda-forge
tables                    3.8.0                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.0                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
terminado                 0.17.0             pyh08f2357_0    conda-forge
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
torch                     1.12.0                   pypi_0    pypi
tornado                   6.3.2            py38h91455d4_0    conda-forge
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typer                     0.9.0                    pypi_0    pypi
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.15                  pypi_0    pypi
vc                        14.3                hb25d44b_16    conda-forge
vc14_runtime              14.34.31931         h5081d32_16    conda-forge
vispy                     0.11.0                   pypi_0    pypi
vs2015_runtime            14.34.31931         hed1258a_16    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.7              pyhd8ed1ab_0    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.15.0                   pypi_0    pypi
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge

**Comment by blogeman** [comment]
When running the following code, nothing is returned and 'files' is an empty list. 
```
import glob

files = glob.glob("E:\Manipulation_Videos\Adults-BL-2023-06-25\labeled-data\Father_01_Ar-floxed\*.png")
for f in files:
    print(f)
```
However, when specifying that the variable is a raw string the following output is generated, as expected:

E:\Manipulation_Videos\Adult-BL-2023-06-25\labeled-data\01_Father_Ar-floxed\img15288.png

This behavior is consistent when there is either 1 or 2 .png file in the directory as well as when the directory contains only .png files or there are other non-.png files present.

**Comment by n-poulsen** [comment]
This issue is stumping us a bit... Our best guess is that there's an issue with your `conda` environment.

Can you label images in other projects, and only this one has issues (or can you not label images for any project)? If it's an issue with all projects, could you try the following
- Force-reinstall python in your environment (`conda install --force-reinstall python=3.8`)
- If that doesn't work, recreate the DeepLabCut environment from scratch

If other projects work correctly, could you try copying the data to another disk/folder and try labeling images there?

**Comment by blogeman** [comment]
I can confirm that in a separate DLC project I am able to label images from the other project. Additionally, I can copy the images from the problematic project and after transferring to the second project they are able to be labeled. So it seems that both the conda environment and the image files themselves are not the problem.

However, I might have found something regarding a problem with the filename. None of the previous DLC projects I have used utilize a number in the filename. When I run this code: 

`import glob

test = "C:\Users\blogeman\Desktop\Adult-BL-2023-06-25\labeled-data\01_Father_Ar-floxed\img15288.png"
file = glob.glob(test)
print(file)`

...I get this error:

 `Cell In[1], line 3
    test = "C:\Users\blogeman\Desktop\Adult-BL-2023-06-25\labeled-data\01_Father_Ar-floxed\img15288.png"
           ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape`

However, when I use a raw string:

`import glob

test = r"C:\Users\blogeman\Desktop\Adult-BL-2023-06-25\labeled-data\01_Father_Ar-floxed\img15288.png"
file = glob.glob(test)
print(file)`

...I get the expected output:

`['C:\\Users\\blogeman\\Desktop\\Adult-BL-2023-06-25\\labeled-data\\01_Father_Ar-floxed\\img15288.png']`

Could the escape character be getting recognized here when it shouldn't be?

**Comment by n-poulsen** [comment]
Hi @blogeman! We were finally able to replicate the issue, and it seems to be coming from the fact that there is only one image in the video folder (this comes from a package we depend on, so might be a bit tricky to fix). Some notes:

- no matter what, you need to use raw strings to define the video path (to escape the backslashes)
- the numbers in the filename should not be an issue

While we're working on a fix, could you try adding a 2nd `.png` image to the folder to see if you can label frames in that case?
