### ISSUE TITLE
Can't generate cnfig.yaml due to a FileExistsError

### ISSUE THREAD

**Issue by asukaRyouji** [DeepLabCut/DeepLabCut#2293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hey,
When I was trying to create a new project with a script in VS code, the following error (FileExistsError) poped out, which made the function couldn't generate config.yaml and there was a mess in video folder under the project path.

```
2023-06-28 22:41:00.168151: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 22:41:00.714094: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2023-06-28 22:41:00.714138: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2023-06-28 22:41:00.714145: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.2.3...
/home/cwang/miniconda3/envs/dlc_2.2.3/lib/python3.8/site-packages/deeplabcut/__init__.py:81: UserWarning: 
        As PyTorch is not installed, unsupervised identity learning will not be available.
        Please run `pip install torch`, or ignore this warning.
        
  warnings.warn(
(dlc_2.2.3) cwang@navu:~/Research/dlc_flytracker$ /home/cwang/miniconda3/envs/dlc_2.2.3/bin/python /home/cwang/Research/dlc_flytracker/preprocess_dlc.py
2023-06-28 22:41:09.636760: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 22:41:10.189950: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2023-06-28 22:41:10.190000: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2023-06-28 22:41:10.190007: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.2.3...
/home/cwang/miniconda3/envs/dlc_2.2.3/lib/python3.8/site-packages/deeplabcut/__init__.py:81: UserWarning: 
        As PyTorch is not installed, unsupervised identity learning will not be available.
        Please run `pip install torch`, or ignore this warning.
        
  warnings.warn(
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos"
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/labeled-data"
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/training-datasets"
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/dlc-models"
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
22  videos from the directory . were added to the project.
Attempting to create a symbolic link of the video ...
Created the symlink of /run to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/run
Created the symlink of /sys to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/sys
Created the symlink of /swapfile to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/swapfile
Created the symlink of /lib64 to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lib64
Created the symlink of /mnt to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/mnt
Created the symlink of /proc to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/proc
Created the symlink of /data to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/data
Created the symlink of /libx32 to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/libx32
Created the symlink of /opt to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/opt
Created the symlink of /backups to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/backups
Created the symlink of /srv to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/srv
Created the symlink of /root to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/root
Created the symlink of /lost+found to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lost+found
Created the symlink of /snap to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/snap
Created the symlink of /media to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/media
Created the symlink of /storage to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/storage
Created the symlink of /dev to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/dev
Created the symlink of /sbin to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/sbin
Created the symlink of /etc to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/etc
Created the symlink of /boot to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/boot
Created the symlink of /bin to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/bin
Created the symlink of /home to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/home
Created the symlink of /lib32 to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lib32
Created the symlink of /tmp to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/tmp
Created the symlink of /cdrom to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/cdrom
Created the symlink of /var to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/var
Created the symlink of /usr to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/usr
Created the symlink of /lib to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lib
Traceback (most recent call last):
  File "/home/cwang/Research/dlc_flytracker/preprocess_dlc.py", line 28, in <module>
    deeplabcut.create_new_project(Name_project, Name_experimenter, Path_video, Path_directory, copy_videos=False, multianimal=False)
  File "/home/cwang/miniconda3/envs/dlc_2.2.3/lib/python3.8/site-packages/deeplabcut/create_project/new.py", line 186, in create_new_project
    raise FileExistsError("Video {} exists already!".format(dst))
FileExistsError: Video /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/run exists already!
(dlc_2.2.3) cwang@navu:~/Research/dlc_flytracker$ /home/cwang/miniconda3/envs/dlc_2.2.3/bin/python /home/cwang/Research/dlc_flytracker/preprocess_dlc.py
2023-06-28 22:48:01.392589: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 22:48:01.944827: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2023-06-28 22:48:01.944874: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2023-06-28 22:48:01.944881: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.2.3...
/home/cwang/miniconda3/envs/dlc_2.2.3/lib/python3.8/site-packages/deeplabcut/__init__.py:81: UserWarning: 
        As PyTorch is not installed, unsupervised identity learning will not be available.
        Please run `pip install torch`, or ignore this warning.
        
  warnings.warn(
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos"
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/labeled-data"
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/training-datasets"
Created "/data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/dlc-models"
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
28  videos from the directory / were added to the project.
22  videos from the directory . were added to the project.
Attempting to create a symbolic link of the video ...
Created the symlink of /run to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/run
Created the symlink of /sys to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/sys
Created the symlink of /swapfile to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/swapfile
Created the symlink of /lib64 to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lib64
Created the symlink of /mnt to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/mnt
Created the symlink of /proc to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/proc
Created the symlink of /data to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/data
Created the symlink of /libx32 to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/libx32
Created the symlink of /opt to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/opt
Created the symlink of /backups to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/backups
Created the symlink of /srv to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/srv
Created the symlink of /root to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/root
Created the symlink of /lost+found to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lost+found
Created the symlink of /snap to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/snap
Created the symlink of /media to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/media
Created the symlink of /storage to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/storage
Created the symlink of /dev to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/dev
Created the symlink of /sbin to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/sbin
Created the symlink of /etc to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/etc
Created the symlink of /boot to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/boot
Created the symlink of /bin to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/bin
Created the symlink of /home to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/home
Created the symlink of /lib32 to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lib32
Created the symlink of /tmp to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/tmp
Created the symlink of /cdrom to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/cdrom
Created the symlink of /var to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/var
Created the symlink of /usr to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/usr
Created the symlink of /lib to /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/lib
Traceback (most recent call last):
  File "/home/cwang/Research/dlc_flytracker/preprocess_dlc.py", line 28, in <module>
    deeplabcut.create_new_project(Name_project, Name_experimenter, Path_video, Path_directory, copy_videos=False, multianimal=False)
  File "/home/cwang/miniconda3/envs/dlc_2.2.3/lib/python3.8/site-packages/deeplabcut/create_project/new.py", line 186, in create_new_project
    raise FileExistsError("Video {} exists already!".format(dst))
FileExistsError: Video /data/bumblebee/Vincent/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/videos/run exists already!
```

### Operating System

Ubuntu 22.04

### DeepLabCut version

2.2.3

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Under standard DLC conda env
2. Config file couldn't be generated

### Anything else?

<img width="955" alt="image" src="https://github.com/DeepLabCut/DeepLabCut/assets/80082006/67250e43-5c2b-4bdc-a117-d50aa064e2e9">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @asukaRyouji, which commands exactly did you run to get this output? Did you use the GUI or did you create it using python: `deeplabcut.create_new_project(...)`?

As lots of videos seem to have been added to the project folder, maybe the wrong video parameters were given to DeepLabCut. Could you share which command you ran that created this output?

**Comment by asukaRyouji** [comment]
Hoi @n-poulsen , I have been using the python script as follow.

```python
import deeplabcut
import os

os.environ["CUDA_VISIBLE_DEVICES"]="1"

Name_project = '1810_fast_seq4_cam3'
Name_experimenter = 'Asuka'

Path_video = '/home/cwang/Desktop/externalDisk/Result/18102021/Moving_fast/seq4/seq4_cam3/18102021_camera3_moving_fast_seq4_S0001.avi'

Path_directory = '/home/cwang/Desktop/externalDisk/Result/18102021/Moving_fast/seq4/seq4_cam3'

Path_config = '/home/cwang/Desktop/externalDisk/Result/18102021/Moving_fast/seq4/seq4_cam3/1810_fast_seq4_cam3-Asuka-2023-06-28/config.yaml'

Project_new          = 0
Project_labelled     = 1
Project_createTD     = 1
Project_trained      = 1
Project_evaluated    = 1
Video_analyzed       = 1
Project_refined      = 1
Refined_merged       = 1
Refined_created      = 1
Refined_retrained    = 1
Video_reanalyzed     = 1

if Project_new == 0:
    deeplabcut.create_new_project(Name_project, Name_experimenter, Path_video, Path_directory, copy_videos=False, multianimal=False)
```

Under the path of video, only one video file exists. And I was also wondering why the video file has been changed to 28 folders.

**Comment by n-poulsen** [comment]
Hi @asukaRyouji, as you can add multiple videos to the project, the method expects to receive a list of videos (as you can see in the [API docs](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#api-docs)). Currently, you give it a string. I believe this is what was causing the issue.

Try running:
```python
deeplabcut.create_new_project(Name_project, Name_experimenter, [Path_video], Path_directory, copy_videos=False, multianimal=False)
```

Let me know if that fixes your issue.

**Comment by asukaRyouji** [comment]
Hi @n-poulsen , thanks for your help and that works!

Sorry that I forgot that input should be a list instead of a string.

Thanks again and wish you a great day!
