### ISSUE TITLE
Cannot load GUI or import Deeplabcut in anaconda after updating to 2.3.5

### ISSUE THREAD

**Issue by koronfelina** [DeepLabCut/DeepLabCut#2296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I updated from dlc 2..2.1 to dlc 2.3.5 and now I cannot open GUI or import deeplabcut in python using anaconda. I get AssertionError for both trials to run Deeplabcut. I have searched in conda list and also active environments and deeplabcut is there, so it has been installed! Please see the code below

### Operating System

Windows 11

### DeepLabCut version

2.3.5 (just installed)

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 2080 Ti

### Steps To Reproduce

```
(base) C:\Users\81904>conda activate deeplabcut

(deeplabcut) C:\Users\81904>python -m deeplabcut
%Errors here (see below)
%
%
(deeplabcut) C:\Users\81904>ipython
In [1]: import deeplabcut
%Errors here (see below)
%
%
```

### Relevant log output

```shell
(base) C:\Users\81904>conda activate deeplabcut

(deeplabcut) C:\Users\81904>python -m deeplabcut
Loading DLC 2.3.5...
Traceback (most recent call last):
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\__init__.py", line 25, in <module>
    from deeplabcut.gui.tracklet_toolbox import refine_tracklets
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\__init__.py", line 15, in <module>
    import qtpy  # Necessary unused import to properly store the env variable
  File "C:\Users\81904\anaconda3\envs\deeplabcut\lib\site-packages\qtpy\__init__.py", line 112, in <module>
    assert API in (PYQT5_API + PYQT4_API + PYSIDE_API + PYSIDE2_API)
AssertionError

(deeplabcut) C:\Users\81904>ipython
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
Loading DLC 2.3.5...
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

~\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\__init__.py in <module>
     23
     24 try:
---> 25     from deeplabcut.gui.tracklet_toolbox import refine_tracklets
     26     from deeplabcut.gui.launch_script import launch_dlc
     27     from deeplabcut.gui.tabs.label_frames import (

~\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\__init__.py in <module>
     13
     14 os.environ["QT_API"] = "pyside6"
---> 15 import qtpy  # Necessary unused import to properly store the env variable
     16
     17 BASE_DIR = os.path.dirname(__file__)

~\anaconda3\envs\deeplabcut\lib\site-packages\qtpy\__init__.py in <module>
    110 API = os.environ[QT_API].lower()
    111 initial_api = API
--> 112 assert API in (PYQT5_API + PYQT4_API + PYSIDE_API + PYSIDE2_API)
    113
    114 is_old_pyqt = is_pyqt46 = False

AssertionError:
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by koronfelina** [comment]
Update: I downgraded to 2.2.3 and GUI is working as well as running dlc in the terminal. I think the issue applies to versions 2.3.0 and higher...I would still like to upgrade to the latest version though.

**Comment by n-poulsen** [comment]
Hi @koronfelina, it seems that the some of the libraries installed have incompatible versions. Could you detail which versions are installed on your machine?

You can do this by providing the output of `conda list` in your conda deeplabcut environment.

**Comment by n-poulsen** [comment]
Closing as stale
