### ISSUE TITLE
Failed opening with napari-deeplabcut

### ISSUE THREAD

**Issue by Temp2Spec** [DeepLabCut/DeepLabCut#2303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Using the command line I successfully trained, evaluated and extracted outliers from the pool of videos used for the initial training. Now the folders in master-folder "label-data" contain 20+20 frames each as well as 2 csv files and 2 h5 with xy coordinates of 20 manually labelled frames (CollectedData.csv), and xy coordinate predictions for the remaining frames (machinelabels.csv).

When I try to refine labels using deeplabcut.refine_labels("pathtoconfig.yaml") napari opens and when I choose a folder with the frames throws a warning "tried opening with napari-deeplabcut but failed.
I can open with napari builtins but the layers are weird: there is a copy of the CollectedData layer named CollectedData_MyName [1] that contains the initially manually labelled frames but the machinelabels layer is empty. I open the csv and I can see the xy coordinates there. 

Weirdly, when I try to label the machinelabels from scratch, the software only lets me add the label for the last bodypart of interest in the config file list. Any ideas??

### Operating System

Win11
GeForce RTX 4090
Python 3.8.17
IPython 8.12.2

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Temp2Spec** [comment]
I have uninstalled and had a clean DLC environment (napari-deeplabcut version 0.1.2). The problem persists.

**Comment by n-poulsen** [comment]
Hi @Temp2Spec, we're working on fixing the issue that's preventing napari-deeplabcut from opening when refining labels.

When it comes to the machine labels not being visible, did you try to toggle the visibility of the `machinelabels` layer? By right-clicking on the layer, you should be able to "toggle visibility" to show or hide the keypoints.
![Screenshot 2023-07-17 at 12 09 52](https://github.com/DeepLabCut/DeepLabCut/assets/45132115/31032a2a-248a-4f43-87de-8c98b564a4f8)

If the keypoints are indeed in the `machinelabels` file and simply aren't shown, then you will not be able to add them to the image (as they already exist). In that case, you need to use the "select points" tool (you can use the shortcut <3> to use it or click on it in the layer controls) to move the machine labels to the correct position.
![Screenshot 2023-07-17 at 12 12 21](https://github.com/DeepLabCut/DeepLabCut/assets/45132115/0387eb8e-4915-4ad1-aae0-dcddb3e19742)

**Comment by jeylau** [comment]
Hi @Temp2Spec, that has now been fixed with `napari-deeplabcut` newest release, which you can get with `pip install napari-deeplabcut==0.2.0`!

**Comment by Temp2Spec** [comment]
Thank you @n-poulsen and @jeylau and apologies for the radio silence! 
I have updated napari as suggested. While I am now able to open the frames with napari deeplabcut in the popup when I choose to open folders, nothing appears in the window.

On my console I get this:|

Traceback (most recent call last):
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_viewer.py", line 953, in _qt_open
    self.viewer.open(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1102, in opn
    layers = self._open_or_raise_error(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1222, in _or
    raise MultipleReaderError(
napari.errors.reader_errors.MultipleReaderError: Multiple plugins found capable of reading C:/Users/ashmi/Desktop/Pupil.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_viewer.py", line 915, in _open_folder_g
    self._qt_open([folder], stack=False, choose_plugin=choose_plugin)
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_viewer.py", line 971, in _qt_open
    handle_gui_reading(filenames, self, stack, **kwargs)
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\dialogs\qt_reader_dialog.py", line 201, ig
    open_with_dialog_choices(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\dialogs\qt_reader_dialog.py", line 294, is
    qt_viewer.viewer.open(paths, stack=stack, plugin=plugin_name, **kwargs)
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1092, in opn
    self._add_layers_with_plugins(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1292, in _as
    layer_data, hookimpl = read_data_with_plugins(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\io.py", line 77, in read_data_with_pls
    res = _npe2.read(paths, plugin, stack=stack)
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\_npe2.py", line 63, in read
    layer_data, reader = io_utils.read_get_reader(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 66, in read_get_reader
    return _read(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 160, in _read
    read_func = rdr.exec(
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\manifest\contributions\_readers.py", line 52, ic
    callable_ = super().exec(kwargs=kwargs)
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\manifest\utils.py", line 63, in exec
    return self.get_callable(reg)(*args, **kwargs)
  File "C:\Users\ashmi\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_reader.py", line 72, in get_folder
    raise OSError("No supported images were found.")
OSError: No supported images were found.

If you suspect this is an IPython 8.12.2 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Any thoughts?

Thank you very much for your time. 
Antonis
