### ISSUE TITLE
ModelZoo Index Error: list index out of range

### ISSUE THREAD

**Issue by lxspedeza** [DeepLabCut/DeepLabCut#2314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,

I'm trying to use ModelZoo's pretrained networks on some of our videos. I'm using Win10 Enterprise and the GUI. First, I encountered the same issue as @mightbeamouse in issue [#2193](https://github.com/DeepLabCut/DeepLabCut/issues/2193). I followed @yeshaokai's intructions, manually downloaded the weights and copied the screenshots into the following folder:
C:\Users\mpc\anaconda3\envs\DEEPLABCUT\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights

This seemed to solve the issue, however now I'm receiving the following error message:

> C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
>   warnings.warn('`layer.apply` is deprecated and '
> 2023-07-18 11:04:07.742644: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-07-18 11:04:08.241589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21348 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
> 2023-07-18 11:04:08.262057: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
> Traceback (most recent call last):
>   File "C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tabs\modelzoo.py", line 112, in run_video_adaptation
>     deeplabcut.video_inference_superanimal(
>   File "C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 106, in video_inference_superanimal
>     adapter.before_adapt_inference(make_video=False)
>   File "C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 119, in before_adapt_inference
>     _plot_trajectories(datafiles[0])
> IndexError: list index out of range

I was thinking, since I use Windows 10, the problem might be with the long path names, so I followed issue #2224 and enabled long path names in the Local Group Policy Editor, then restarted the PC but I still receive the same error message. 

I'm not sure how to proceed from here. Thank you for your help in advance!

### Operating System

Windows 10 Enterprise 64x

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 4090

### Steps To Reproduce

1. Win10 Enterprise with Anaconda Prompt run as Administrator
2. Opening DLC GUI
3. Click ModelZoo
4. Select mp4 video (1)
5. Supermodel settings: superanimal_topviewmouse, scale list left empty
6. Run
7. See Error Above

### Relevant log output

```shell
(deeplabcut) C:\Users\mpc>python -m deeplabcut
Loading DLC 2.3.5...
Starting GUI...
C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-07-18 11:04:07.742644: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 11:04:08.241589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21348 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
2023-07-18 11:04:08.262057: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
Traceback (most recent call last):
  File "C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tabs\modelzoo.py", line 112, in run_video_adaptation
    deeplabcut.video_inference_superanimal(
  File "C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 106, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "C:\Users\mpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 119, in before_adapt_inference
    _plot_trajectories(datafiles[0])
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by lxspedeza** [comment]
I have a solution: The coding of the mp4 produced by our camera somehow was not correct, I ran all videos through ffmpeg and removed the audios. This solved my issue.

**Comment by outlace** [comment]
I am getting this same error with a cropped and gray-scaled AVI

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\deeplabcut\gui\tabs\modelzoo.py", line 112, in run_video_adaptation
    deeplabcut.video_inference_superanimal(
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 106, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 111, in before_adapt_inference
    self.init_weights, datafiles = superanimal_inference.video_inference(
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\deeplabcut\modelzoo\api\superanimal_inference.py", line 314, in video_inference
    init_weights = os.path.abspath(snapshots[0]).replace(".index", "")
IndexError: list index out of range
```

**Comment by lxspedeza** [comment]
> 
Hi! For me what solved the issue is removing the audio track from the videos using ffmpeg. I followed this guide:

https://json2video.com/how-to/ffmpeg-course/ffmpeg-remove-audio.html

Also check if the codec is fine, it's not missing Metadata... These are my best quesses.
