### ISSUE TITLE
Deeplabcut 2.3.5 GUI napari - ValueError: cannot reindex on an axis with duplicate labels

### ISSUE THREAD

**Issue by Nathan-Matharu** [DeepLabCut/DeepLabCut#2321]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug description

Extracting outlier frames with two different shuffles prevents napari from opening machinelabels.

### Operating System

Windows 11

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Train two different models as different shuffles
2. Extract outlier frames for a video with one shuffle
3. Extract outlier frames for the same video with a second shuffle
4. Try to label frames from DLC gui
5. napari window opens but remains empty (the error)

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\label_frames.py", line 55, in label_frames
    _ = launch_napari(folder)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\widgets.py", line 45, in launch_napari
    viewer.open(files, plugin="napari-deeplabcut")
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\io.py", line 77, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\_npe2.py", line 61, in read
    raise e from e
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\_npe2.py", line 55, in read
    layer_data, reader = io_utils.read_get_reader(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 66, in read_get_reader
    return _read(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 160, in _read
    read_func = rdr.exec(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\manifest\contributions\_readers.py", line 52, in exec
    callable_ = super().exec(kwargs=kwargs)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\manifest\utils.py", line 63, in exec
    return self.get_callable(reg)(*args, **kwargs)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_reader.py", line 80, in get_folder_parser
    layers.extend(read_hdf(datafile))
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_reader.py", line 194, in read_hdf
    temp.stack(["individuals", "bodyparts"])
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py", line 8914, in stack
    result = stack_multiple(self, level, dropna=dropna)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\reshape\reshape.py", line 623, in stack_multiple
    result = stack(result, lev, dropna=dropna)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\reshape\reshape.py", line 565, in stack
    return _stack_multi_columns(frame, level_num=level_num, dropna=dropna)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\reshape\reshape.py", line 755, in _stack_multi_columns
    value_slice = chunk.reindex(columns=level_vals_used).values
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\util\_decorators.py", line 347, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py", line 5205, in reindex
    return super().reindex(**kwargs)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\generic.py", line 5289, in reindex
    return self._reindex_axes(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py", line 4998, in _reindex_axes
    frame = frame._reindex_columns(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py", line 5043, in _reindex_columns
    return self._reindex_with_indexers(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\generic.py", line 5355, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\internals\managers.py", line 737, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "C:\Users\natha\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\indexes\base.py", line 4316, in _validate_can_reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @Nathan-Matharu! I could not reproduce the bug. Could you tell me how you extracted the outlier frames? Was it done automatically or manually? It'd be great too if you could load the `machinelabels.h5` and show us the first couple of lines with: 
```python
import pandas as pd

df = pd.read_hdf(path_to_machinelabels_file)
print(df.head())
```
This may help me see something unusual with the dataframe header.

**Comment by jeylau** [comment]
@Nathan-Matharu, never mind, I could reproduce it. I'm looking at it and will push a fix soon!
