### ISSUE TITLE
got error in using 'creat training dataset'

### ISSUE THREAD

**Issue by Fusenheizi** [DeepLabCut/DeepLabCut#2328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Everytime I click  **'training dataset'** in the GUI, an 'IncompleteRead' error occurs each time, and always show **'Downloading a lmageNet-pretrained model from http:/download.tensorflow.org/models/resnet v1_50_2016_08_28.tar.gz...'**. And I also didn't get the file 'training_model_comparison.log'.

### Operating System

Win 11

### DeepLabCut version

latest

### DeepLabCut mode

single animal

### Device type

GPU

### Relevant log output

```shell
Traceback (most recent call last):
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tabs\create_training_dataset.py", line 105, in create_training_dataset
    deeplabcut.create_training_dataset(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 913, in create_training_dataset
    model_path, num_shuffles = auxfun_models.check_for_weights(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxfun_models.py", line 70, in check_for_weights
    download_weights(modeltype, model_path)
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxfun_models.py", line 95, in download_weights
    with tarfile.open(fileobj=BytesIO(response.read()), mode="r:gz") as tar:
  File "E:\anaconda3\envs\deeplabcut\lib\http\client.py", line 472, in read
    s = self._safe_read(self.length)
  File "E:\anaconda3\envs\deeplabcut\lib\http\client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(77684544 bytes read, 17388715 more expected)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Be sure you open the program "terminal" by right clicking and "open as admin" -- likely just a permission issue. I will close now, but please feel free to report back :)
