### ISSUE TITLE
IndexError: list index out of range when running extract_outlier_frames

### ISSUE THREAD

**Issue by NSGregory** [DeepLabCut/DeepLabCut#2337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to extract outlier frames; however, there is an error finding the snapshot.  Additionally, trying to evaluate the network or generate labeled videos produces the same error.  I have tried this with two projects on two computers and gotten the same error.  The common factor seems to be that the networks were originally trained on google colab and the moved off of colab.

### Operating System

I have tried it both on my personal computer (MacOs Ventura 13) and the HPC cluster (CentOS 7).

### DeepLabCut version

dlc version: I tried with both 2.3.2 and 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu: AMD radeon 6600 XT vis tensorflow-metal and NVIDIA Tesla V100

### Steps To Reproduce

I have tried this step on two computers (laptop and HPC cluster).  The initial network was extracted and labeled on my laptop and the moved to google Colab to train the network.  Colab successfully trained the network and generated labeled videos.  I then downloaded the whole project from Colab and made a copy on the HPC cluster.

For the HPC Cluster:
Installed 2.3.2 docker via singularity
Run the .sif via 
`singularity shell --nv {filename.sif}`
Upgraded DLC to 2.3.5 via 
`pip3 install deeplabcut==2.3.5`
`python3`
`import deeplabcut as dlc`
`>>> dlc.extract_outlier_frames('config.yaml', vid_list, videotype='mp4')`

For the laptop:
I used the GUI from 2.3.5, added files using the Extract Outliers tab, and clicked the extract outliers button.  Same error output was generated in the terminal window.

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/outlier_frames.py", line 370, in extract_outlier_frames
    DLCscorer, DLCscorerlegacy = auxiliaryfunctions.get_scorer_name(
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 594, in get_scorer_name
    increasing_indices = np.argsort([int(m.split("-")[1]) for m in Snapshots])
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 594, in <listcomp>
    increasing_indices = np.argsort([int(m.split("-")[1]) for m in Snapshots])
IndexError: list index out of range

>>> dlc.version.VERSION
'2.3.5'
>>> dlc.auxiliaryfunctions.read_config('config.yaml')
{'Task': 'TST_single_cropped', 'scorer': 'Nick', 'date': 'Jul5', 'multianimalproject': False, 'identity': None, 'project_path': '', 'video_sets': {'/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/Grp1_m1_baseline.mp4': {'crop': '0, 267, 0, 404'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/Grp1_m2_baseline.mp4': {'crop': '0, 273, 0, 388'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/Grp1_m3_baseline.mp4': {'crop': '0, 247, 0, 417'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/Grp1_m4_baseline.mp4': {'crop': '0, 288, 0, 442'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/Grp1_m5_baseline.mp4': {'crop': '0, 280, 0, 415'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp6_m1.mp4': {'crop': '0, 242, 0, 482'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp6_m2.mp4': {'crop': '0, 186, 0, 490'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp6_m3.mp4': {'crop': '0, 236, 0, 486'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp6_m4.mp4': {'crop': '0, 250, 0, 494'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp6_m5.mp4': {'crop': '0, 296, 0, 500'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp7_m1.mp4': {'crop': '0, 264, 0, 560'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp7_m2.mp4': {'crop': '0, 226, 0, 564'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp7_m3.mp4': {'crop': '0, 250, 0, 428'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp7_m5.mp4': {'crop': '0, 240, 0, 407'}, '/Volumes/NeuralNet/TST_single_cropped-Nick-2023-07-05/videos/pre_Grp7_m4.mp4': {'crop': '0, 259, 0, 397'}}, 'bodyparts': ['snout', 'center-head', 'right_ear', 'left_ear', 'spine1', 'spine2', 'spine3', 'tail_base', 'tail1', 'tail2', 'tail-tape', 'tape-anchor', 'rf_paw', 'rf_limb', 'rh_paw', 'rh_limb', 'lf_paw', 'lf_limb', 'lh_paw', 'lh_limb', 'ventral-surface'], 'start': 0, 'stop': 1, 'numframes2pick': 20, 'skeleton': [['bodypart1', 'bodypart2'], ['objectA', 'bodypart3']], 'skeleton_color': 'black', 'pcutoff': 0.6, 'dotsize': 4, 'alphavalue': 0.7, 'colormap': 'rainbow', 'TrainingFraction': [0.95], 'iteration': 0, 'default_net_type': 'resnet_50', 'default_augmenter': 'default', 'snapshotindex': -1, 'batch_size': 8, 'cropping': False, 'x1': 0, 'x2': 640, 'y1': 277, 'y2': 624, 'corner2move2': [50, 50], 'move2corner': True}

/home/groups/bheifets/TST_single_animal_cropped_scaled/dlc-models/iteration-0/TST_single_croppedJul5-trainset95shuffle1/train]$ ls
checkpoint          pose_cfg.yaml                       snapshot-75000.data-00000-of-00001  snapshot-80000.index                snapshot-85000.meta
learning_stats.csv  snapshot-70000.data-00000-of-00001  snapshot-75000.index                snapshot-80000.meta                 snapshot-90000.data-00000-of-00001
log                 snapshot-70000.index                snapshot-75000.meta                 snapshot-85000.data-00000-of-00001  snapshot-90000.index
log.txt             snapshot-70000.meta                 snapshot-80000.data-00000-of-00001  snapshot-85000.index                snapshot-90000.meta
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by NSGregory** [comment]
After some additional trial and error, I think this may be related to not using the full filepath for 'config.yaml' due to laziness with typing.

**Comment by n-poulsen** [comment]
Hi @NSGregory! Yes this issue comes must come from the fact that your "project_path" value in the `config.yaml` file is not set correctly (that's what is used to try and find the snapshots).

In your config, you have 'project_path': '' when it should be set to the full path of the project (e.g., `/home/groups/bheifets/TST_single_animal_cropped_scaled`).
