### ISSUE TITLE
m2 mac installation - `tables-3.8.0` fails to build

### ISSUE THREAD

**Issue by ceciliachen0321** [DeepLabCut/DeepLabCut#2342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

According this answer [https://github.com/DeepLabCut/DeepLabCut/issues/2322#issuecomment-1649884924](url),
I have already added the line "- notebook<7.0.0" to " conda-environments/DEEPLABCUT_M1.yaml", but it turned out to be a failure to create the environment.
I don't know how to fix it, because I have very limited knowledge of python. It would be a huge help if anyone can answer it.

### Operating System

macos ventura m2

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

(base) ceciliachen@CeciliaMacBook-Pro ~ % git clone https://github.com/DeepLabCut/DeepLabCut.git
Cloning into 'DeepLabCut'...
remote: Enumerating objects: 15248, done.
remote: Counting objects: 100% (1567/1567), done.
remote: Compressing objects: 100% (586/586), done.
remote: Total 15248 (delta 888), reused 1410 (delta 795), pack-reused 13681
Receiving objects: 100% (15248/15248), 164.44 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (10296/10296), done.
(base) ceciliachen@CeciliaMacBook-Pro ~ % cd /Users/ceciliachen/DeepLabCut/conda-environments
(base) ceciliachen@CeciliaMacBook-Pro conda-environments % conda env create -f DEEPLABCUT_M1.yaml

### Relevant log output

```shell
Downloading and Extracting Packages
                                                                                
Preparing transaction: done                                                     
Verifying transaction: done                                                     
Executing transaction: \ /Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/nb_conda_kernels/install.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html                                                                     
  from pkg_resources import iter_entry_points                                   
Enabling nb_conda_kernels...                                                    
CONDA_PREFIX: /Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1                  
Status: enabled                                                                 
                                                                                
\ Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.                                                                           
Enabling notebook extension nb_conda/main...                                    
      - Validating: OK                                                          
Enabling tree extension nb_conda/tree...                                        
      - Validating: OK                                                          
Config option `kernel_spec_manager_class` not recognized by `EnableServerExtensionApp`.                                                                         
Enabling: nb_conda                                                              
- Writing config: /Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/etc/jupyter  
    - Validating...                                                             
      nb_conda 2.2.1 OK

done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt', '--exists-action=b']
Pip subprocess output:
Obtaining file:///Users/ceciliachen/DeepLabCut (from -r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting dlclibrary (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Obtaining dependency information for dlclibrary from https://files.pythonhosted.org/packages/7f/e0/4b394a8782f56404202ae2999849f5738c7379de18878985a40fcfbf76fb/dlclibrary-0.0.4-py3-none-any.whl.metadata
  Using cached dlclibrary-0.0.4-py3-none-any.whl.metadata (2.3 kB)
Collecting filterpy>=1.4.4 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting ruamel.yaml>=0.15.0 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Obtaining dependency information for ruamel.yaml>=0.15.0 from https://files.pythonhosted.org/packages/d9/0e/2a05efa11ea33513fbdf4a2e2576fe94fd8fa5ad226dbb9c660886390974/ruamel.yaml-0.17.32-py3-none-any.whl.metadata
  Using cached ruamel.yaml-0.17.32-py3-none-any.whl.metadata (17 kB)
Collecting imgaug>=0.4.0 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Using cached imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
Collecting imageio-ffmpeg (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Using cached imageio-ffmpeg-0.4.8.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numba>=0.54 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Obtaining dependency information for numba>=0.54 from https://files.pythonhosted.org/packages/23/21/644a5fb3f74ee8e63e59a8acc78f08ec281f5e11d07551209b02614aa6a2/numba-0.57.1-cp39-cp39-macosx_11_0_arm64.whl.metadata
  Using cached numba-0.57.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting matplotlib>=3.3 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Obtaining dependency information for matplotlib>=3.3 from https://files.pythonhosted.org/packages/a3/e5/c9cdc737ea2256285dc1b28e8ecbf649c716cfc7b1ee12a8be6d4cf1feb7/matplotlib-3.7.2-cp39-cp39-macosx_11_0_arm64.whl.metadata
  Using cached matplotlib-3.7.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting networkx>=2.6 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Requirement already satisfied: numpy>=1.18.5 in /Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1)) (1.23.2)
Collecting pandas!=1.5.0,>=1.0.1 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Obtaining dependency information for pandas!=1.5.0,>=1.0.1 from https://files.pythonhosted.org/packages/6c/1c/689c9d99bc4e5d366a5fd871f0bcdee98a6581e240f96b78d2d08f103774/pandas-2.0.3-cp39-cp39-macosx_11_0_arm64.whl.metadata
  Using cached pandas-2.0.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting scikit-image>=0.17 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Obtaining dependency information for scikit-image>=0.17 from https://files.pythonhosted.org/packages/c4/09/0b465a48f9bc7e848538f82e62811978932132b1edd50da758a9243cef5a/scikit_image-0.21.0-cp39-cp39-macosx_12_0_arm64.whl.metadata
  Using cached scikit_image-0.21.0-cp39-cp39-macosx_12_0_arm64.whl.metadata (14 kB)
Collecting scikit-learn>=1.0 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Obtaining dependency information for scikit-learn>=1.0 from https://files.pythonhosted.org/packages/63/87/6cd5450f0385966bf2a5b865a2043cf68c2a41676193afdbccb40f8719dc/scikit_learn-1.3.0-cp39-cp39-macosx_12_0_arm64.whl.metadata
  Using cached scikit_learn-1.3.0-cp39-cp39-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting scipy<1.11.0,>=1.4 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Using cached scipy-1.10.1-cp39-cp39-macosx_12_0_arm64.whl (28.9 MB)
Collecting statsmodels>=0.11 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Using cached statsmodels-0.14.0-cp39-cp39-macosx_11_0_arm64.whl (9.4 MB)
Collecting tables>=3.7.0 (from deeplabcut==2.3.5->-r /Users/ceciliachen/DeepLabCut/conda-environments/condaenv.he0zi2yh.requirements.txt (line 1))
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library not found for -llzo2
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -llzo
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -lblosc
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      def _dump_h5_backtrace():
          cdef object bt = []
      
          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------
      
      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)
      * Found cython 3.0.0
      * USE_PKGCONFIG: False
      * Found conda env: ``/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1``
      * Found HDF5 headers at ``/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/include``, library at ``/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/lib``.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Found bzip2 headers at ``/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/include``, library at ``/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/lib``.
      * Could not find blosc headers and library; using internal sources.
      * Found blosc2 headers at ``/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/include``, library at ``/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib``.
        * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ceciliachen/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed

(base) ceciliachen@CeciliaMacBook-Pro conda-environments % >....                                                                
          return hook(config_settings)
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel            
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())                
        File "<string>", line 928, in <module>           
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/4l/v49q_94s0qxbgcb554z_kj100000gn/T/pip-build-env-hs09a63w/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)                        
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]
                                                                                      
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1           
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed
```

### Anything else?

[https://github.com/DeepLabCut/DeepLabCut/issues/2322#issuecomment-1649884924](url)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by traveler130** [comment]
Same issue here on M2

**Comment by xt0x1c** [comment]
same here on M2

**Comment by sbgbash** [comment]
Same issue here on M1

**Comment by n-poulsen** [comment]
This issue is linked to the comments written in issue #2330. This [particular solution](https://github.com/DeepLabCut/DeepLabCut/issues/2330#issuecomment-1653742637) )(installing a specific version of PyTables using pip first) seems to have worked for some people, could you try it out?

**Comment by traveler130** [comment]
Unfortunately didn't work either. I'm getting a Cython compiler error when trying to install PyTables 3.7:

Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx

**Comment by sbgbash** [comment]
This is what worked for me: 
system: MacOs M1 Ventura 13.4.1
installed miniconda3
`conda create -n dlc_m1 python=3.9`
`conda activate dlc_m1`

before using pip make sure to run:
`which python` and `which pip` inside your conda env
Make sure both print a path into your conda env something like:  Users/user/miniconda3/envs/dlc_m1/bin/pip
I was having an issue in which when I used pip inside my conda envirionment it was referencing the pip in my /homebrew which was somehow linked to my system version of python which was 3.11. Fixing this mismatch helped resolve my issue. 
You may have to change you .bash_profile config file to make sure the conda pip path is prioritized. Once the correct pip and python are aligned inside your conda env then install the below inside your conda env
`pip install "notebook<7.0.0" "tensorflow-macos<2.13.0" "tensorflow-metal" `
`pip install "deeplabcut[gui]"`

I had to also:
 `conda install hdf5`
`conda install numpy=1.24`
I was geting a conflict between Numba and NumPy. Specifically, Numba is expecting a version of NumPy that is 1.24 or lower.

After all this I was able to load dlc with:
`python -m deeplabcut`

**Comment by stickzh** [comment]
Followed the  recipe of @sbgbash above, but still same issue with tables

```
Collecting tables>=3.7.0 (from deeplabcut[gui])
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
```

**Comment by ceciliachen0321** [comment]
> This issue is linked to the comments written in issue #2330. This [particular solution](https://github.com/DeepLabCut/DeepLabCut/issues/2330#issuecomment-1653742637) )(installing a specific version of PyTables using pip first) seems to have worked for some people, could you try it out?

Following the suggestion in this comment.
```
pip uninstall tables
conda install pytables
```
I uninstalled tables, and then reinstalled it, it turned out to work successfully. Then, I was able to run `python -m deeplabcut` following the instructions of @sbgbash step by step.

Thank you very much! Your advices have been tremendously helpful!

**Comment by ceciliachen0321** [comment]
> This is what worked for me: system: MacOs M1 Ventura 13.4.1 installed miniconda3 `conda create -n dlc_m1 python=3.9` `conda activate dlc_m1`
> 
> before using pip make sure to run: `which python` and `which pip` inside your conda env Make sure both print a path into your conda env something like: Users/user/miniconda3/envs/dlc_m1/bin/pip I was having an issue in which when I used pip inside my conda envirionment it was referencing the pip in my /homebrew which was somehow linked to my system version of python which was 3.11. Fixing this mismatch helped resolve my issue. You may have to change you .bash_profile config file to make sure the conda pip path is prioritized. Once the correct pip and python are aligned inside your conda env then install the below inside your conda env `pip install "notebook<7.0.0" "tensorflow-macos<2.13.0" "tensorflow-metal" ` `pip install "deeplabcut[gui]"`
> 
> I had to also: `conda install hdf5` `conda install numpy=1.24` I was geting a conflict between Numba and NumPy. Specifically, Numba is expecting a version of NumPy that is 1.24 or lower.
> 
> After all this I was able to load dlc with: `python -m deeplabcut`

Thank you very much! I am now able to load DLC as well.

**Comment by stickzh** [comment]
I confirm. When we uninstalled tables and reinstalled 3.7.0 we can also run the gui on m2. Now we just need dlc to be able to use the gpu on m1/m2!
