### ISSUE TITLE
Mac M2 - Training the network is too slow and low CPU usage

### ISSUE THREAD

**Issue by liangsen0908** [DeepLabCut/DeepLabCut#2355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

My computer is an Apple M2 chip, every time I execute "train_network", the training is very slow, but the CPU usage is very low in the activity monitor, I think it's a problem with "tensorflow", I've been working on it for a week, but it's still not solved!

### Operating System

macos

### DeepLabCut version

DLC 2.3.5...

### DeepLabCut mode

single animal

### Device type

macbook M2

### Steps To Reproduce

```bash
conda env create -f DEEPLABCUT_M1.yaml
conda activate DEEPLABCUT_M1
```

```python
import deeplabcut as dlc
dlc.create_new_project('demo','sls',['/Users/senxiaopang/Ai_project/deeplabcut/laoshu_test.mp4'],copy_videos=True)
config_path='/Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16/config.yaml'
dlc.extract_frames(config_path)
dlc.check_labels(config_path)
dlc.create_training_dataset(config_path,net_type='resnet_50',augmenter_type='imgaug')
dlc.train_network(config_path)
```

pose_cfg.yaml:
```yaml
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
all_joints_names:
- pelvis
- hip
- knee
- right_ankle
- left_ankle
- right_toe
- left_toe
alpha_r: 0.02
apply_prob: 0.5
batch_size: 8
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/demo_sls80shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 10
global_scale: 0.8
init_weights: /Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/Documentation_data-demo_80shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.02
  - 20000
net_type: resnet_50
num_joints: 7
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16
rotation: 25
rotratio: 0.4
save_iters: 1000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
```

version:
```bash
tensorflow-deps           2.10.0                        0    apple
tensorflow-estimator      2.12.0                   pypi_0    pypi
tensorflow-macos          2.12.0                   pypi_0    pypi
tensorflow-metal          1.0.1                    pypi_0    pypi
```

### Relevant log output

```shell
/Users/senxiaopang/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/senxiaopang/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/senxiaopang/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/core/train.py", line 83, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 406, in next_batch
    ) = self.get_batch()
  File "/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 297, in get_batch
    img_idx = np.random.choice(self.num_images, size=self.batch_size, replace=True)
  File "mtrand.pyx", line 909, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
Loading ImageNet-pretrained resnet_50
/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/core/train.py:227: UserWarning: Switching to Adam, as SGD crashes on Apple Silicon.
  warnings.warn("Switching to Adam, as SGD crashes on Apple Silicon.")
2023-08-16 22:42:23.620963: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16/dlc-models/iteration-0/demoAug16-trainset80shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6]], 'all_joints_names': ['pelvis', 'hip', 'knee', 'right_ankle', 'left_ankle', 'right_toe', 'left_toe'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'contrast': {'clahe': True, 'claheratio': 0.1, 'histeq': True, 'histeqratio': 0.1}, 'convolution': {'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'strength': [0.5, 1.5]}, 'embossratio': 0.1, 'sharpen': False, 'sharpenratio': 0.3}, 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/demo_sls80shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'init_weights': '/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/Documentation_data-demo_80shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 7, 'pos_dist_thresh': 17, 'project_path': '/Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @liangsen0908, did you label any data (how many labeled frames do you have)?

And could you try setting `batch_size: 1` and `display_iters: 1` in your configuration file and report how many iterations per second you have?

**Comment by liangsen0908** [comment]
I marked 80 frames, I set the parameters: batch_size: 1 and display_iters: 10, I tried to get him to train 10,000 times for 7-8 hours with no end in sight, and the LOSS value is still very high, and it won't come down. But the same parameters and code for runs in Google's Colab for about 15 minutes and ends, and I don't know what causes it.

**Comment by n-poulsen** [comment]
But are you getting prints showing iterations, such as:
```
iteration: 1 loss: 1.0963 lr: 0.0005
iteration: 2 loss: 1.0656 lr: 0.0005
iteration: 3 loss: 0.2745 lr: 0.0005
iteration: 4 loss: 0.1031 lr: 0.0005
iteration: 5 loss: 0.0968 lr: 0.0005
```

Training on a Mac is much slower as on Colab, and 10'000 iterations is going to take a lot of time (see [this issue](https://github.com/DeepLabCut/DeepLabCut/issues/2240)).

**Comment by liangsen0908** [comment]
/I appreciate the reply, I know there is a speed difference between Colab and mac, but the difference is so large that it feels as if it's my installation!  I just deleted the environment and re-installed it with DEEPLABCUT_M1.yaml, at this time its version is: tensorflow_macos==2.12.0 with tensorflow_metal==1.0.1 with parameters: 'display_iters': 1, batch_size: 1 . The training is very slow, it doesn't show once in more than 10 minutes: iteration: xxxx loss: xxxxx lr: xxxxx. looked at the activity monitor, python3.9 basically doesn't take up any CPU or GPU, then changed the tensorflow_metal version to 0.8.0, it's still the same.

output result：
```
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6]],
 'all_joints_names': ['pelvis',
                      'hip',
                      'knee',
                      'right_ankle',
                      'left_ankle',
                      'right_toe',
                      'left_toe'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'contrast': {'clahe': True,
              'claheratio': 0.1,
              'histeq': True,
              'histeqratio': 0.1},
 'convolution': {'edge': False,
                 'emboss': {'alpha': [0.0, 1.0], 'strength': [0.5, 1.5]},
                 'embossratio': 0.1,
                 'sharpen': False,
                 'sharpenratio': 0.3},
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/demo_sls80shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/Documentation_data-demo_80shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000]],
 'net_type': 'resnet_50',
 'num_joints': 7,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': '/Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 1000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16/dlc-models/iteration-0/demoAug16-trainset80shuffle1/train/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Selecting single-animal trainer
Batch Size is 1
[/Users/senxiaopang/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694](https://file+.vscode-resource.vscode-cdn.net/Users/senxiaopang/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694): UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Users/senxiaopang/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/senxiaopang/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/core/train.py", line 83, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 406, in next_batch
    ) = self.get_batch()
  File "/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py", line 297, in get_batch
    img_idx = np.random.choice(self.num_images, size=self.batch_size, replace=True)
  File "mtrand.pyx", line 909, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
Metal device set to: Apple M2

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Loading ImageNet-pretrained resnet_50
[/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/core/train.py:227](https://file+.vscode-resource.vscode-cdn.net/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/core/train.py:227): UserWarning: Switching to Adam, as SGD crashes on Apple Silicon.
  warnings.warn("Switching to Adam, as SGD crashes on Apple Silicon.")
2023-08-17 16:46:07.627936: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16/dlc-models/iteration-0/demoAug16-trainset80shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6]], 'all_joints_names': ['pelvis', 'hip', 'knee', 'right_ankle', 'left_ankle', 'right_toe', 'left_toe'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'contrast': {'clahe': True, 'claheratio': 0.1, 'histeq': True, 'histeqratio': 0.1}, 'convolution': {'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'strength': [0.5, 1.5]}, 'embossratio': 0.1, 'sharpen': False, 'sharpenratio': 0.3}, 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/demo_sls80shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1, 'init_weights': '/Users/senxiaopang/Desktop/DeepLabCut-main/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_demoAug16/Documentation_data-demo_80shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000]], 'net_type': 'resnet_50', 'num_joints': 7, 'pos_dist_thresh': 17, 'project_path': '/Users/senxiaopang/Ai_project/deeplabcut/demo-sls-2023-08-16', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 1000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
```

**Comment by liangsen0908** [comment]
@yarikoptic    Hi！bothering you guys, I would like to know what to do in my case, because I'm waiting for this problem to be solved before I can take the next step.

**Comment by yarikoptic** [comment]
As I am a "new commer" to this issue, I would need more information from you @liangsen0908 on how I could facilitate a solution here.  I don't even use any of the aluminum cases, M1 or M2 or any other kind.

**Comment by liangsen0908** [comment]
Thank you for your reply, today I used my friend's mac computer and tried to train, but the same result, even if I set display_iters: 1, it appears "Starting training ....". Even if I set display_iters: 1, the message "Starting training" doesn't show "iteration: xxx loss: xxx lr: xxx", I don't know how to solve it!

**Comment by liangsen0908** [comment]
[MMMathisLab](https://github.com/MMathisLab)   Hello！ sorry to bother you, can you help me with my problem?

**Comment by MMathisLab** [comment]
You can try dropping the learning rate a lot if the loss is not dropping. This is a known issue we have hit on some datasets that have few images labeled (like 80) on M1/M2 tensorflow-metal.

But yes -- training on a M1 or M2 is slow. We only ``officially" support NVIDIA GPUs with > 8 GB of memory, see installation guide for suggestions (a reminder no warranty or guarantees, this is a free open source software project ;). I recommend only using your M1/M2 for inference and training on google colab if you don't have a local GPU.
