### ISSUE TITLE
Type Error running testscript.py: `unexpected keyword argument 'per_keypoint_evaluation'`

### ISSUE THREAD

**Issue by efin396** [DeepLabCut/DeepLabCut#2367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to run the testscript to ensure gpu setup is correct, however I am getting an error of " TypeError: evaluate_network() got an unexpected keyword argument 'per_keypoint_evaluation' " after running testscript.

 I have tried several solutions but no luck. 

**Versions Used:**
DLC = 2.3.0
Tensorflow = 2.12.0
CUDA = 11.8
cuDNN = 8.6.0

### Operating System

Windows 10 Enterprise

### DeepLabCut version

2.3.0

### DeepLabCut mode

single animal

### Device type

CPU = 4th Gen Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
GPU = NVIDIA GeForce GTX 1660 SUPER

### Steps To Reproduce

1. Activate DeepLabCut environment
2. cd to examples
3. run test script
4. error after running testscript

### Relevant log output

```shell
`python testscript.py
Loading DLC 2.3.0...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Created "C:\Users\efinlayson3\DeepLabCut\examples\TEST-Alex-2023-08-31\videos"
Created "C:\Users\efinlayson3\DeepLabCut\examples\TEST-Alex-2023-08-31\labeled-data"
Created "C:\Users\efinlayson3\DeepLabCut\examples\TEST-Alex-2023-08-31\training-datasets"
Created "C:\Users\efinlayson3\DeepLabCut\examples\TEST-Alex-2023-08-31\dlc-models"
Copying the videos
C:\Users\efinlayson3\DeepLabCut\examples\TEST-Alex-2023-08-31\videos\reachingvideo1.avi
Generated "C:\Users\efinlayson3\DeepLabCut\examples\TEST-Alex-2023-08-31\config.yaml"

A new project with name TEST-Alex-2023-08-31 is created at C:\Users\efinlayson3\DeepLabCut\examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:01, 163.84it/s]
Kmeans clustering ... (this might take a while)
C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1930: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=3)
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.36it/s]
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
CREATING TRAININGSET
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
CHANGING training parameters to end quickly!
TRAIN
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'contrast': {'clahe': True,
              'claheratio': 0.1,
              'histeq': True,
              'histeqratio': 0.1},
 'convolution': {'edge': False,
                 'emboss': {'alpha': [0.0, 1.0], 'strength': [0.5, 1.5]},
                 'embossratio': 0.1,
                 'sharpen': False,
                 'sharpenratio': 0.3},
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTAug31\\TEST_Alex80shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 2,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\efinlayson3\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTAug31\\Documentation_data-TEST_80shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.001, 5]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\efinlayson3\\DeepLabCut\\examples\\TEST-Alex-2023-08-31',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 5,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\efinlayson3\\DeepLabCut\\examples\\TEST-Alex-2023-08-31\\dlc-models\\iteration-0\\TESTAug31-trainset80shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Loading ImageNet-pretrained resnet_50
C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py:227: UserWarning: Switching to Adam, as SGD crashes on Apple Silicon.
  warnings.warn("Switching to Adam, as SGD crashes on Apple Silicon.")
2023-08-31 13:27:39.868472: W tensorflow/c/c_api.cc:300] Operation '{name:'pose/locref_pred/block4/biases/Adam_1/Assign' id:7170 op device:{requested: '', assigned: ''} def:{{{node pose/locref_pred/block4/biases/Adam_1/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](pose/locref_pred/block4/biases/Adam_1, pose/locref_pred/block4/biases/Adam_1/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\efinlayson3\\DeepLabCut\\examples\\TEST-Alex-2023-08-31\\dlc-models\\iteration-0\\TESTAug31-trainset80shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'contrast': {'clahe': True, 'claheratio': 0.1, 'histeq': True, 'histeqratio': 0.1, 'gamma': False, 'sigmoid': False, 'log': False, 'linear': False}, 'convolution': {'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'strength': [0.5, 1.5]}, 'embossratio': 0.1, 'sharpen': False, 'sharpenratio': 0.3}, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTAug31\\TEST_Alex80shuffle1.mat', 'decay_steps': 30000, 'display_iters': 2, 'init_weights': 'C:\\Users\\efinlayson3\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TESTAug31\\Documentation_data-TEST_80shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.001, 5]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\efinlayson3\\DeepLabCut\\examples\\TEST-Alex-2023-08-31', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 5, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
iteration: 2 loss: 0.6641 lr: 0.001
iteration: 4 loss: 0.0906 lr: 0.001
2023-08-31 13:27:55.846956: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-4 (load_and_enqueue):
Traceback (most recent call last):
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\client\session.py", line 1378, in _do_call
    return fn(*args)
           ^^^^^^^^^
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\client\session.py", line 1361, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\client\session.py", line 1454, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 85, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    results = self._do_run(handle, final_targets, final_fetches,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\client\session.py", line 1371, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\client\session.py", line 1397, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.CancelledError: Graph execution error:

Detected at node 'fifo_queue_enqueue' defined at (most recent call last):
    File "C:\Users\efinlayson3\DeepLabCut\examples\testscript.py", line 177, in <module>
      deeplabcut.train_network(path_config_file)
    File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 212, in train_network
      train(
    File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 171, in train
      batch, enqueue_op, placeholders = setup_preloading(batch_spec)
    File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 71, in setup_preloading
      enqueue_op = q.enqueue(placeholders_list)
Node: 'fifo_queue_enqueue'
Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

Original stack trace for 'fifo_queue_enqueue':
  File "C:\Users\efinlayson3\DeepLabCut\examples\testscript.py", line 177, in <module>
    deeplabcut.train_network(path_config_file)
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 212, in train_network
    train(
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 171, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 71, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 346, in enqueue
    return gen_data_flow_ops.queue_enqueue_v2(
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4471, in queue_enqueue_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\framework\op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\efinlayson3\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\framework\ops.py", line 3814, in _create_op_internal
    ret = Operation(

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
EVALUATE
Traceback (most recent call last):
  File "C:\Users\efinlayson3\DeepLabCut\examples\testscript.py", line 180, in <module>
    deeplabcut.evaluate_network(
TypeError: evaluate_network() got an unexpected keyword argument 'per_keypoint_evaluation'`
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Tetra-quark** [comment]
For a simple fix, removing the `per_keypoint_evaluation` parameter from `evaluate_network` should work. (I did the same last week). 

I suspect you have a cloned a recent version of the DLC repository but are using an environment with a older version of DLC installed. The error is because the `per_keypoint_evaluation` is a new feature (from the last two months) that I don't believe is in any official DLC release yet.

**Comment by MMathisLab** [comment]
agree -- @AlexEMG lets prioritise a pypi release this week!

**Comment by MMathisLab** [comment]
before we release 2.3.6 you can just pip install from source: `pip install git+https://github.com/DeepLabCut/DeepLabCut.git` but it should be out this week.
