### ISSUE TITLE
ValueError: key must be provided when HDF5 file contains multiple datasets.

### ISSUE THREAD

**Issue by akshatsingh22** [DeepLabCut/DeepLabCut#2377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Converted single animal labels for maDLC following the link - https://github.com/DeepLabCut/DeepLabCut/blob/821d3d9b10713963fc25b0e363fe93e3d3a29de3/docs/convert_maDLC.md

### Operating System

operating system: windows 11

### DeepLabCut version

dlc version: 2.3.5

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

Convert single animal project to maDLC

### Relevant log output

```shell
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=120
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 2400x1251-1+26 (frame: 2418x1298-10-12) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1924x1055-1+26 (frame: 1942x1102-10-12) margins: 9, 38, 9, 9 minimum size: 379x575 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=492, y=766)))
Traceback (most recent call last):
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\deeplabcut\gui\tabs\label_frames.py", line 55, in label_frames
    _ = launch_napari(folder)
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\deeplabcut\gui\widgets.py", line 45, in launch_napari
    viewer.open(files, plugin="napari-deeplabcut")
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\napari\components\viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\napari\components\viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\napari\plugins\io.py", line 77, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\napari\plugins\_npe2.py", line 61, in read
    raise e from e
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\napari\plugins\_npe2.py", line 55, in read
    layer_data, reader = io_utils.read_get_reader(
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\npe2\io_utils.py", line 66, in read_get_reader
    return _read(
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\npe2\io_utils.py", line 160, in _read
    read_func = rdr.exec(
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\npe2\manifest\contributions\_readers.py", line 52, in exec
    callable_ = super().exec(kwargs=kwargs)
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\npe2\manifest\utils.py", line 63, in exec
    return self.get_callable(reg)(*args, **kwargs)
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\napari_deeplabcut\_reader.py", line 81, in get_folder_parser
    layers.extend(read_hdf(datafile))
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\napari_deeplabcut\_reader.py", line 178, in read_hdf
    temp = pd.read_hdf(filename)
  File "C:\Users\singh\Anaconda3\envs\deepGUI\lib\site-packages\pandas\io\pytables.py", line 441, in read_hdf
    raise ValueError(
ValueError: key must be provided when HDF5 file contains multiple datasets.
```

### Anything else?

The csv file looks good to me but when I load the project in the GUI and the go to label frames and open one of the folder in labelled-data it shows nothing and then when I check the terminal it shows the above error.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by akshatsingh22** [comment]
Looks like the function for creating the h5 file was not updated for long.

To fix the above issue:
Step-1 follow the steps in https://github.com/DeepLabCut/DeepLabCut/blob/821d3d9b10713963fc25b0e363fe93e3d3a29de3/docs/convert_maDLC.md

Step-2 The csv file is updated by now but the h5 file is corrupted. Therefore you need to keep CollectedData_Scorer.csv and delete rest 3 files.

Step-3 Take the below code snippet and run over labelled-data directory:

import os
from glob import glob

import pandas as pd

labeled_data_dir = glob(os.path.join(r"path to\labeled-data", "*" ))

for folder in labeled_data_dir:
    filepath = os.path.join(folder, 'CollectedData_Scorer.csv')
    df = pd.read_csv(filepath, index_col=[0,1,2], header=[0,1,2,3])
    savepath = os.path.join(folder, 'CollectedData_Scorer.h5')
    df.to_hdf(savepath, key="df")
    
CREDIT FOR THE SOLUTION: https://forum.image.sc/t/convert-single-animal-project-to-madlc/86241
