### ISSUE TITLE
Index Error: List index out of range

### ISSUE THREAD

**Issue by klgrove** [DeepLabCut/DeepLabCut#2400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Using the GUI and an mp4 video, I tried to use the superanimal quadruped analysis. It runs through a few lines and then gives me an Index error. I tried a few of the fixes shown here, but nothing has changed the error.

### Operating System

Windows 10 Enterprise 

### DeepLabCut version

dlc version 2.3.6

### DeepLabCut mode

multi animal

### Device type

11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   1.80 GHz

### Steps To Reproduce

in the DeepLabCut Conda Environment
run GUI using python -m deeplabcut

in GUI, attempt to run Model Zoo
Add mp4 video
Click Run

### Relevant log output

```shell
Loading DLC 2.3.6...
Starting GUI...
D_Lib: debug printing for files [.*] and level [100] is turned on
D_Lib: debug printing for files [.*] and level [200] is turned on
D_Lib: debug printing for files [.*] and level [300] is turned on
13212:vf_shex.cpp(89): INFO: DllCanUnloadNow returned S_OK.
Traceback (most recent call last):
  File "C:\Users\klgrove\AppData\Local\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tabs\modelzoo.py", line 112, in run_video_adaptation
    deeplabcut.video_inference_superanimal(
  File "C:\Users\klgrove\AppData\Local\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 106, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "C:\Users\klgrove\AppData\Local\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 114, in before_adapt_inference
    self.init_weights, datafiles = superanimal_inference.video_inference(
  File "C:\Users\klgrove\AppData\Local\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\modelzoo\api\superanimal_inference.py", line 314, in video_inference
    init_weights = os.path.abspath(snapshots[0]).replace(".index", "")
IndexError: list index out of range
```

### Anything else?

I already tried all the fixes in issue #2193 and was unable to get anything to work for me. I removed the weights folder, put it back, manually downloaded the weight files and unzipped them into the weights folder. I looked in the huggingface_hub.file_download as the last suggestion in the #2193 thread suggested, and I could not find where the create_relative_symlink() even exists in this version of the file. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@jeylau is this an issue with the weight hash?

**Comment by jeylau** [comment]
@MMathisLab, all URLs work, I tested them earlier.
@klgrove, do you have permissions to download files on your machine (i.e., do you run the terminal as administrator)? Can you also confirm that the version of the `dlclibrary` package installed is 0.0.4?

**Comment by klgrove** [comment]
I only get temporary admin permission for an hour at a time, but I did get those and run it as an admin when I ran into this problem. Do I need permanent admin permissions in order to get this to run properly?

**Comment by MMathisLab** [comment]
can you plesae check which version of dlclibrary you have; please open the terminal, 
```
python

import dlclibrary

dlclibrary.__version__
```

**Comment by klgrove** [comment]
(deeplabcut) PS C:\WINDOWS\system32> python
Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:01:59) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlclibrary
>>> dlclibrary.__version__
'0.0.4'

**Comment by klgrove** [comment]
It looks like it was a version issue with tensorflow. I re-installed everything in the correct order, and now I have two different issues: 
-The GUI doesn't have the option for using the pre-trained superanimal or topviewmouse models. The only option is 'Manage Project', which allows me to create my own training dataset, but not use the pre-trained ones. 
-The GPU times out around 2500 iterations every single time. I realize this is probably an issue with my system, not DLC, but is there anything I can do about it besides getting a new computer/GPU? Also, if I set it to save every 500 iterations, and it goes up to 2500, if I run it again, will it be re-running the same information? As in, if I get it to run to 2500 iterations 200 times, will it train the program? Or am I just having it re-do the same thing every time I re-run it? 

This is the error: 
iteration: 2100 loss: 0.0176 lr: 0.005
iteration: 2200 loss: 0.0182 lr: 0.005
iteration: 2300 loss: 0.0164 lr: 0.005
iteration: 2400 loss: 0.0150 lr: 0.005
2023-10-11 12:16:38.055147: E tensorflow/core/kernels/dml_ops_common.cc:185] The DirectML device has encountered an unrecoverable error (DXGI_ERROR_DEVICE_REMOVED). This is most often caused by a timeout occurring on the GPU. Please visit https://aka.ms/tfdmltimeout for more information and troubleshooting steps.
2023-10-11 12:16:38.057229: F tensorflow/core/kernels/dml_ops_common.cc:185] HRESULT failed with 0x887a0005: dml_device->CompileOperator(op.Get(), execution_flags, IID_PPV_ARGS(&compiled_op))

**Comment by MMathisLab** [comment]
> -The GUI doesn't have the option for using the pre-trained superanimal or topviewmouse models. The only option is 'Manage Project', which allows me to create my own training dataset, but not use the pre-trained ones.

The GUI does have the model zoo in it. If you don't see it, you must be using an old version; can you be sure to run: `pip install -U 'deeplabcut[gui,tf]'`

**Comment by klgrove** [comment]
When I run that command, it does this: 
 Installing collected packages: deeplabcut
  Attempting uninstall: deeplabcut
    Found existing installation: deeplabcut 2.3.6
    Uninstalling deeplabcut-2.3.6:
      Successfully uninstalled deeplabcut-2.3.6
Successfully installed deeplabcut-2.2.3

The GUI still does not have the model zoo. I tried just updating deeplabcut, and it gives me an error about running in light version and unable to run the GUI, and the GUI won't even launch.

**Comment by jeylau** [comment]
I'm not aware of a case where using the -U flag (upgrade) would install a version lower than the current one; could you please retry by specifying the latest DLC version explicitly with:
`pip install deeplabcut[gui,tf]==2.3.7`?

**Comment by klgrove** [comment]
That gives me this error: 

om deeplabcut[gui,tf]==2.3.7) (0.0.4)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (1.0.2)
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12; 1.9.2 Requires-Python >=3.8; 1.9.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement scipy>=1.9 (from deeplabcut[gui,tf]) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3)
ERROR: No matching distribution found for scipy>=1.9
(dlc_dml) PS C:\WINDOWS\system32>

**Comment by MMathisLab** [comment]
Seems your running Python 3.8 which has hit security patches only, so scipy and major packages have dropped support. https://devguide.python.org/versions/

I'd recommend updating; the latest version is 3.13.

**Comment by klgrove** [comment]
My computer has the most recent version of python installed. But my different conda environments seem to be running on different versions of python. Any idea how to fix this? 
(dlc_dml) PS C:\WINDOWS\system32> python -V
Python 3.7.16
(dlc_dml) PS C:\WINDOWS\system32> conda deactivate dlc_dml
(base) PS C:\WINDOWS\system32> python -V
Python 3.11.4
(base) PS C:\WINDOWS\system32> conda activate deeplabcut
(deeplabcut) PS C:\WINDOWS\system32> python -V
Python 3.8.17

**Comment by klgrove** [comment]
I updated python in the conda environment, and I'm getting the same error: 

```
(base) PS C:\> conda activate dlc_dml
(dlc_dml) PS C:\> python -V
Python 3.7.16
(dlc_dml) PS C:\> conda update python
Collecting package metadata (current_repodata.json): - DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
\ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
| DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/noarch/current_repodata.json HTTP/1.1" 304 0
done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\klgrove\AppData\Local\anaconda3\envs\dlc_dml

  added / updated specs:
    - python


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       he774522_0         113 KB
    certifi-2023.7.22          |  py312haa95532_1         155 KB
    expat-2.5.0                |       hd77b12b_0         225 KB
    libffi-3.4.4               |       hd77b12b_0         113 KB
    pip-23.2.1                 |  py312haa95532_0         3.4 MB
    python-3.12.0              |       h1d929f7_0        16.2 MB
    setuptools-68.0.0          |  py312haa95532_0         1.2 MB
    tk-8.6.12                  |       h2bbff1b_0         3.1 MB
    xz-5.4.2                   |       h8cc25b3_0         592 KB
    zlib-1.2.13                |       h8cc25b3_0         113 KB
    ------------------------------------------------------------
                                           Total:        25.1 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0
  expat              pkgs/main/win-64::expat-2.5.0-hd77b12b_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0
  tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  xz                 pkgs/main/win-64::xz-5.4.2-h8cc25b3_0
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0

The following packages will be REMOVED:

  wincertstore-0.2-py37haa95532_2

The following packages will be UPDATED:

  certifi                          2022.12.7-py37haa95532_0 --> 2023.7.22-py312haa95532_1
  openssl                                 1.1.1w-h2bbff1b_0 --> 3.0.11-h2bbff1b_2
  pip                                 22.3.1-py37haa95532_0 --> 23.2.1-py312haa95532_0
  python                                  3.7.16-h6244533_0 --> 3.12.0-h1d929f7_0
  setuptools                          65.6.3-py37haa95532_0 --> 68.0.0-py312haa95532_0

The following packages will be SUPERSEDED by a higher-priority channel:

  wheel              pkgs/main/win-64::wheel-0.38.4-py37ha~ --> pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
setuptools-68.0.0    | 1.2 MB    |                                                                              |   0%
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443                                  DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443                            |   0%
tk-8.6.12            | 3.1 MB    |                                                                              |   0% DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443

python-3.12.0        | 16.2 MB   |                                                                              |   0%
certifi-2023.7.22    | 155 KB    |                                                                              |   0%
                                                                                                                       DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/setuptools-68.0.0-py312haa95532_0.conda HTTP/1.1" 200 1248954 113 KB    |                                                                              |   0%
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/python-3.12.0-h1d929f7_0.conda HTTP/1.1" 200 16944376      | 225 KB    |                                                                              |   0%
setuptools-68.0.0    | 1.2 MB    | ##############9                                                              |  20% DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/libffi-3.4.4-hd77b12b_0.conda HTTP/1.1" 200 115307
bzip2-1.0.8          | 113 KB    |                                                                              |   0% DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/tk-8.6.12-h2bbff1b_0.conda HTTP/1.1" 200 3229518
python-3.12.0        | 16.2 MB   | #1                                                                           |   1% DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/zlib-1.2.13-h8cc25b3_0.conda HTTP/1.1" 200 116215           | 3.1 MB    | 3                                                                            |   1%



                                                                                                                       DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/expat-2.5.0-hd77b12b_0.conda HTTP/1.1" 200 2304553          | 113 KB    | ##########7                                                                  |  14% D
python-3.12.0        | 16.2 MB   | ##########################3                                                  |  35% DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/xz-5.4.2-h8cc25b3_0.conda HTTP/1.1" 200 60643312            | 3.1 MB    | ###########################################################3                 |  78%
                                                                                                                       DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/bzip2-1.0.8-he774522_0.conda HTTP/1.1" 200 115376
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/pip-23.2.1-py312haa95532_0.conda HTTP/1.1" 200 3601719

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(dlc_dml) PS C:\> pip install deeplabcut[gui,tf]==2.3.7
Collecting deeplabcut[gui,tf]==2.3.7
  Obtaining dependency information for deeplabcut[gui,tf]==2.3.7 from https://files.pythonhosted.org/packages/b2/a8/505cdc8e1d14efd21bcd19702e0121f5519d077376ac330e7f90754406fd/deeplabcut-2.3.7-py3-none-any.whl.metadata
  Downloading deeplabcut-2.3.7-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: dlclibrary in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.0.4)
Requirement already satisfied: filterpy>=1.4.4 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (1.4.5)
Requirement already satisfied: ruamel.yaml>=0.15.0 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.17.35)
Requirement already satisfied: imgaug>=0.4.0 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.4.0)
Requirement already satisfied: imageio-ffmpeg in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.4.9)
Requirement already satisfied: numba>=0.54 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.56.4)
Requirement already satisfied: matplotlib>=3.3 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (3.5.3)
Requirement already satisfied: networkx>=2.6 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (2.6.3)
Requirement already satisfied: numpy>=1.18.5 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (1.21.6)
Requirement already satisfied: pandas!=1.5.0,>=1.0.1 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (1.3.5)
Requirement already satisfied: scikit-image>=0.17 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.18.1)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (1.0.2)
Collecting scipy>=1.9 (from deeplabcut[gui,tf]==2.3.7)
  Obtaining dependency information for scipy>=1.9 from https://files.pythonhosted.org/packages/f4/ce/be0b376ba6069f3f8ba240aa532a374733447453c93582d4c474effdde21/scipy-1.11.3-cp312-cp312-win_amd64.whl.metadata
  Downloading scipy-1.11.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 60.4/60.4 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: statsmodels>=0.11 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.13.5)
Requirement already satisfied: tables>=3.7.0 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (3.7.0)
Requirement already satisfied: torch<=1.12 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (1.12.0)
Requirement already satisfied: tensorpack>=0.11 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (0.11)
Requirement already satisfied: tf-slim>=1.1.0 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (1.1.0)
Requirement already satisfied: tqdm in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (4.66.1)
Requirement already satisfied: pyyaml in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (6.0.1)
Requirement already satisfied: Pillow>=7.1 in c:\users\klgrove\appdata\local\anaconda3\envs\dlc_dml\lib\site-packages (from deeplabcut[gui,tf]==2.3.7) (9.5.0)
INFO: pip is looking at multiple versions of deeplabcut[gui,tf] to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12; 6.3.0 Requires-Python <3.11,>=3.6; 6.3.1 Requires-Python <3.11,>=3.6; 6.3.2 Requires-Python <3.11,>=3.6; 6.4.0 Requires-Python <3.11,>=3.6; 6.4.0.1 Requires-Python <3.12,>=3.7; 6.4.1 Requires-Python <3.12,>=3.7; 6.4.2 Requires-Python <3.12,>=3.7; 6.4.3 Requires-Python <3.12,>=3.7; 6.5.0 Requires-Python <3.12,>=3.7; 6.5.1 Requires-Python <3.12,>=3.7; 6.5.1.1 Requires-Python <3.12,>=3.7; 6.5.2 Requires-Python <3.12,>=3.7; 6.5.3 Requires-Python <3.12,>=3.7
ERROR: Could not find a version that satisfies the requirement pyside6<6.3.2; extra == "gui" (from deeplabcut[gui,tf]) (from versions: none)
ERROR: No matching distribution found for pyside6<6.3.2; extra == "gui"
(dlc_dml) PS C:\> python -V
Python 3.12.0
```

**Comment by jeylau** [comment]
@klgrove, I have just tried to reproduce this issue on windows, in a fresh environment (python 3.9, `conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0` as explained [here](https://www.tensorflow.org/install/pip#windows-native), and `pip install "deeplabcut[gui,tf]`), and all worked fine. Whether running the terminal as admin or not, weights were successfully downloaded and found either locally in the git cloned DLC code base, or (as you report) under site-packages/deeplabcut.

The simplest programmatic solution would be to run:
```python
from deeplabcut.utils import auxiliaryfunctions
from dlclibrary.dlcmodelzoo.modelzoo_download import download_huggingface_model
from pathlib import Path

superanimal_name = "superanimal_topviewmouse"
dlc_root_path = auxiliaryfunctions.get_deeplabcut_path()
weight_folder = str(
      Path(dlc_root_path)
      / "pose_estimation_tensorflow"
      / "models"
      / "pretrained"
      / (superanimal_name + "_weights")
  )
download_huggingface_model(superanimal_name, weight_folder) 
```

This is nothing more than what the code does, but reduced to its bare minimum, so maybe that'd allow us to spot what and where it goes wrong.
