### ISSUE TITLE
Training running on CPU instead of GPU

### ISSUE THREAD

**Issue by ssfrz** [DeepLabCut/DeepLabCut#2455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to train a multianimal model, but I get warnings when importing deeplabcut and training is happening on the CPU instead of the GPU. 

### Operating System

Linux

### DeepLabCut version

2.3.8

### DeepLabCut mode

multi animal

### Device type

NVIDIA GeForce RTX 2080 Ti (through cluster)

### Steps To Reproduce

(in new conda environment)
1. pip install deeplabcut[tf]
2. conda install -c conda-forge cudnn
3. conda install -c conda-forge cudatoolkit-dev
4. ipython
5. import deeplabcut

### Relevant log output

```shell
2023-11-22 14:59:00.782734: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-22 14:59:00.921876: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-22 14:59:00.921911: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-11-22 14:59:00.953191: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-22 14:59:02.484976: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-22 14:59:02.485084: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-22 14:59:02.485119: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.8...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
```

### Anything else?

This is on a cluster, so the labeling was done locally (where a gui can be used). Also, since it's on a cluster, I do not have sudo privileges. 

I can create a training dataset in this environment, but when I run it, it uses the CPU instead of the GPU including similar errors to above.

I tried creating a new environment and entering "conda install -c conda-forge cudnn"  and "conda install -c conda-forge cudatoolkit-dev" before installing DeepLabCut, but that resulted in the following:

```
Collecting deeplabcut[tf]
  Using cached deeplabcut-2.3.8-py3-none-any.whl.metadata (29 kB)
Collecting dlclibrary (from deeplabcut[tf])
  Using cached dlclibrary-0.0.4-py3-none-any.whl.metadata (2.3 kB)
Collecting filterpy>=1.4.4 (from deeplabcut[tf])
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py) ... done
Collecting ruamel.yaml>=0.15.0 (from deeplabcut[tf])
  Using cached ruamel.yaml-0.18.5-py3-none-any.whl.metadata (23 kB)
Collecting imgaug>=0.4.0 (from deeplabcut[tf])
  Using cached imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
Collecting imageio-ffmpeg (from deeplabcut[tf])
  Using cached imageio_ffmpeg-0.4.9-py3-none-manylinux2010_x86_64.whl.metadata (1.7 kB)
Collecting numba>=0.54 (from deeplabcut[tf])
  Using cached numba-0.58.1.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-pv3qt9wu/numba_dc1687978ea3492988a6f33a9b663df1/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-pv3qt9wu/numba_dc1687978ea3492988a6f33a9b663df1/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
> RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.

Create an environment with `python < 3.12`.

Check your `tensorflow` version `2.12.0` for Linux and MacOS `2.10.0` for Windows. Install `conda install -c conda-forge cudnn==8.4.1.50` and `conda install -c conda-forge cudatoolkit==11.7`

It should work with those versions.

**Comment by ssfrz** [comment]
> Check your `tensorflow` version `2.12.0` for Linux

I created a new conda environment with `python = 3.10` and installed `conda install -c conda-forge cudnn==8.4.1.50` and `conda install -c conda-forge cudatoolkit==11.7`. It seems that tensorflow is getting downgraded to `2.10.0` after deeplabcut is installed. After updating tensorflow with `pip install tensorflow[and-cuda]==2.12.0`, I received the following error after entering `import deeplabcut` in `ipython`:

```
2023-11-27 14:43:16.444927: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-27 14:43:16.490879: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-27 14:43:16.491536: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-27 14:43:17.972019: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading DLC 2.3.8...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
```

When I enter `nvidia-smi`, the information for the GPU shows up with `CUDA Version: 12.2`, so I think it could be a compatibility issue since I am now using older versions of `python`, `tensorflow`, `cudnn`, and `cudatoolkit`. However, since it's on a cluster, I don't have admin privileges and don't think I can downgrade it. If this is the issue, is there a way to still use the GPU with deeplabcut?

**Comment by MMathisLab** [comment]
DeepLabCut only supports up to TensorFlow 2.10; so you cannot override this with positive results. 

Note that 'nvidia-smi' does not show the actual version installed, only the highest that could be, given gpu drivers. 

https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html

**Comment by ssfrz** [comment]
> DeepLabCut only supports up to TensorFlow 2.10; so you cannot override this with positive results.

Got it. I misunderstood the previous response to mean that I needed to have 2.12 since I'm using Linux. 

I'm now getting the same output as I did originally:
```
2023-11-27 16:11:27.936686: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-27 16:11:28.067944: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:11:28.067970: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-11-27 16:11:28.098059: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-27 16:11:29.492936: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:11:29.493074: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:11:29.493088: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.8...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
```
I installed `tensorrt` using `pip` since it did not originally seem to be installed, but that did not resolve the issue. 
I get this similar output as part of the output when I try to train a model:
```
/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-11-27 16:05:51.848310: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gr/st/home/frz/.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.848484: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.848694: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.848888: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.849090: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.849285: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.849472: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.849671: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.local/lib/python3.9/site-packages/cv2/../../lib64:/misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2023-11-27 16:05:51.849691: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-11-27 16:05:51.850674: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading ImageNet-pretrained resnet_50
2023-11-27 16:05:52.363085: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-11-27 16:05:54.056812: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] ML IR V1 optimization pass is not enabled
```

**Comment by MMathisLab** [comment]
May I ask if you followed the Ubuntu specific instructions? I would also truly recommend docker - much easier to use on Ubuntu, consistent env, and easy gpu support :)

**Comment by ssfrz** [comment]
I didn't install with the Ubuntu-specific instructions listed in the Installation Tips in the link above since this is on a cluster for which I don't have sudo privileges. Unfortunately, the cluster also does not support docker.
