### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29’ not found

### ISSUE THREAD

**Issue by khadija-ch** [DeepLabCut/DeepLabCut#2456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I’m currently trying to launch the train_network step using a command line. I installed the conda environment and followed all the steps to load DLC 2.3.8 but I am facing errors towards the end. I have the python3 version installed and I wrote the code in a py file to run it in CMD but when I do it, it shows me an error “ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29’ not found (required by /crnldata/eduwell/Cognilearnlab/BODYS2/Deeplabcut/lib/python3.9/site-packages/zmq/backend/cython/…/…/…/…/…/libzmq.so.5)”. 
How can I fix this to proceed with training the dataset and next steps?

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.3.8

### DeepLabCut mode

single animal

### Device type

the processor "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @khadija-ch!

This issue seems to comes from one of the packages that DeepLabCut relies on (likely `tensorflow`). Which commands exactly did you run to install DeepLabCut?

And could you provide the entire error that's printed to the screen?

**Comment by khadija-ch** [comment]
Hello again,

I used the command "conda env create DEEPLABCUT.yaml" to install it.

and here is the entire error:

2023-12-05 12:15:19.149889: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-05 12:15:20.538661: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-12-05 12:15:20.538695: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-12-05 12:15:20.697700: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-05 12:15:23.415003: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-12-05 12:15:23.415423: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-12-05 12:15:23.415439: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.8...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "/crnldata/eduwell/Cognilearnlab/BODYS/lauch_training.py", line 3, in <module>
    import deeplabcut
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/__init__.py", line 37, in <module>
    from deeplabcut.create_project import (
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/__init__.py", line 12, in <module>
    from deeplabcut.create_project.demo_data import load_demo_data
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/demo_data.py", line 16, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/utils/__init__.py", line 11, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 34, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 31, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 17, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 16, in <module>
    from .pose_tensorpack import TensorpackPoseDataset
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py", line 45, in <module>
    from tensorpack.dataflow.parallel import MultiProcessRunnerZMQ, MultiProcessRunner
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/__init__.py", line 8, in <module>
    from tensorpack.dataflow import *
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/dataflow/__init__.py", line 50, in <module>
    _global_import(module_name)
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/dataflow/__init__.py", line 30, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/dataflow/parallel.py", line 15, in <module>
    import zmq
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/__init__.py", line 31, in <module>
    raise original_error from None
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/alice.gomez/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)

**Comment by MMathisLab** [comment]
Do you have CUDA installed?

**Comment by jeylau** [comment]
@khadija-ch, this line in the traceback `Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0` indeed indicates that CUDA is not (properly) installed. I'd install the 2 conda packages mentioned in https://github.com/DeepLabCut/DeepLabCut/issues/2455#issuecomment-1824167985:
`conda install -c conda-forge cudnn==8.4.1.50  cudatoolkit==11.7`. I hope this helps.

**Comment by luvres** [comment]
### This trick worked for me for GLIBCXX_3.4.29
```
mv /lib64/libstdc++.so.6{,.ORIG}
ln -s /opt/miniconda/envs/DEEPLABCUT/lib/libstdc++.so.6 /lib64/
```

**Comment by EmiliosIsaias** [comment]
I am using DLC in an [HPC](https://wiki.bwhpc.de/e/Helix). Cuda and cudnn are preinstalled packages and I can only use cuda 11.6.1 and cudnn 8.5.0. I loaded these modules and also executed the command suggested by @jeylau, `conda install -c conda-forge cudnn==8.4.1.50 cudatoolkit==11.7`. The error however persisted.
I searched further about this error and found an [Amazon resource](https://docs.aws.amazon.com/simspaceweaver/1.15/userguide/working-with_local-development_1-15-3.html) where they mention the exact error for they-know-what package. The proposed solution is to upgrade/update the `libstdc++` compiler to 'include the required GLIBCXX version'. 
I loaded the GNU compiler suite version 12.1.0 and that fixed my problem. I don't know if it was the combination of these two solutions or one of them. 
I hope you can solve your issue soon @khadija-ch!
