### ISSUE TITLE
AttributeError When Trying to Swap Identities

### ISSUE THREAD

**Issue by tom221085** [DeepLabCut/DeepLabCut#2457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello!
I am currently trying to refine my analyzed videos and I am running into two issues:

1) The identities of two mice, even though I labelled them correctly in the training's data set and they are in two separate chambers are swapped for the whole video.

Here is a screen shot: 
![refineTrackletScreenshot](https://github.com/DeepLabCut/DeepLabCut/assets/11939642/b286aea9-5a82-492e-9c6d-7750225795d2)
mouseMiniscope and mouseOppositeChamber should actually be swapped!

2) When I then try to use refine tracklets with the lasso function after I flagged frame 1 and the last frame I get the following error message: "AttributeError: 'ArtistList' object has no attribute 'clear'". The swapping then does not happen.

I found a few similar closed issues about this but none provided any solutions.

Thank you,
Thomas

### Operating System

![Operating System](https://github.com/DeepLabCut/DeepLabCut/assets/11939642/499bd487-60d5-46f3-a2aa-705f04474bf6)

### DeepLabCut version

DLC 2.3.3

### DeepLabCut mode

multi animal

### Device type

NVIDIA Gforce RTX 3090

### Relevant log output

```shell
(base) PS C:\WINDOWS\system32> conda activate deeplabcut
(deeplabcut) PS C:\WINDOWS\system32> python -m deeplabcut
Loading DLC 2.3.3...
Starting GUI...
QCoreApplication::exec: The event loop is already running
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\cbook\__init__.py", line 304, in process
    func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 684, in on_pick
    self.ax_slider.lines.clear()
AttributeError: 'ArtistList' object has no attribute 'clear'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by tom221085** [comment]
I updated to version DLC version 2.3.8 and that solved the problems.
