### ISSUE TITLE
train_network() -FileNotFoundError: No such file: '....png' while using Google Colab

### ISSUE THREAD

**Issue by SciRay** [DeepLabCut/DeepLabCut#2459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running the function - deeplabcut.train_network() in Google Colab training goes normal to the certain point, usually to 57000-73000 iterations or 4.5-5.5hrs of running cell with this function (I've trained different models during many days, so I write min-max interval I've faced). After that appears the following error: check log output below. The cell can't be stopped normally, only by deleting runtime. Checkpoints are saved and can be used for next training.

### Operating System

**For all steps till creating training dataset:**
Windows 10 Pro
Version: 22H2
**For creating training dataset and training:**
Google Colab free version

### DeepLabCut version

DLC 2.3.7 for labeling and training
Also used 2.3.5 with same error

### DeepLabCut mode

multi animal

### Device type

Google Colab T4 GPU

### Steps To Reproduce

1. Create on Windows 10, using DLC GUI, new multianimal project, add videos, extract frames automatically and then manually. 
2. Label all frames.
3. Load full folder to Google Drive and correct project path in config to match new folder location in Drive.
4. Select T4 GPU, pip install deeplabcut[tf]==2.3.7, mount drive, import dlc
5. deeplabcut.create_multianimaltraining_dataset(path_config_file, windows2linux=True)
6. deeplabcut.train_network(path_config_file, displayiters=1000, saveiters=5000, maxiters=300000, allow_growth=True) (but I don't think those numbers play any role in this error, I tried different)

### Relevant log output

```shell
Starting multi-animal training....
iteration: 51000 loss: 0.0056 scmap loss: 0.0054 locref loss: 0.0001 limb loss: 0.0001 lr: 0.0001
iteration: 52000 loss: 0.0056 scmap loss: 0.0054 locref loss: 0.0001 limb loss: 0.0001 lr: 0.0001
iteration: 53000 loss: 0.0057 scmap loss: 0.0055 locref loss: 0.0001 limb loss: 0.0001 lr: 0.0001
iteration: 54000 loss: 0.0056 scmap loss: 0.0054 locref loss: 0.0001 limb loss: 0.0001 lr: 0.0001
iteration: 55000 loss: 0.0055 scmap loss: 0.0053 locref loss: 0.0001 limb loss: 0.0001 lr: 0.0001
iteration: 56000 loss: 0.0055 scmap loss: 0.0053 locref loss: 0.0001 limb loss: 0.0001 lr: 0.0001
iteration: 57000 loss: 0.0055 scmap loss: 0.0053 locref loss: 0.0001 limb loss: 0.0001 lr: 0.0001
iteration: 58000 loss: 0.0052 scmap loss: 0.0050 locref loss: 0.0001 limb loss: 0.0001 lr: 5e-05
iteration: 59000 loss: 0.0048 scmap loss: 0.0046 locref loss: 0.0001 limb loss: 0.0001 lr: 5e-05
iteration: 60000 loss: 0.0047 scmap loss: 0.0045 locref loss: 0.0001 limb loss: 0.0001 lr: 5e-05
iteration: 61000 loss: 0.0047 scmap loss: 0.0045 locref loss: 0.0001 limb loss: 0.0001 lr: 5e-05
iteration: 62000 loss: 0.0046 scmap loss: 0.0044 locref loss: 0.0001 limb loss: 0.0001 lr: 5e-05
iteration: 63000 loss: 0.0043 scmap loss: 0.0042 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 64000 loss: 0.0043 scmap loss: 0.0041 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 65000 loss: 0.0043 scmap loss: 0.0041 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 66000 loss: 0.0042 scmap loss: 0.0041 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 67000 loss: 0.0042 scmap loss: 0.0040 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 68000 loss: 0.0042 scmap loss: 0.0040 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 69000 loss: 0.0042 scmap loss: 0.0040 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 70000 loss: 0.0041 scmap loss: 0.0040 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 71000 loss: 0.0041 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 72000 loss: 0.0041 scmap loss: 0.0040 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 73000 loss: 0.0041 scmap loss: 0.0040 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 74000 loss: 0.0041 scmap loss: 0.0040 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 75000 loss: 0.0041 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 76000 loss: 0.0040 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 77000 loss: 0.0040 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 78000 loss: 0.0041 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 79000 loss: 0.0040 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 80000 loss: 0.0040 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 81000 loss: 0.0040 scmap loss: 0.0039 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 82000 loss: 0.0040 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 83000 loss: 0.0039 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 84000 loss: 0.0039 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 85000 loss: 0.0040 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 86000 loss: 0.0040 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 87000 loss: 0.0039 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 88000 loss: 0.0040 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 89000 loss: 0.0039 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 90000 loss: 0.0039 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 91000 loss: 0.0039 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 92000 loss: 0.0039 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 93000 loss: 0.0039 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 94000 loss: 0.0039 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 95000 loss: 0.0039 scmap loss: 0.0038 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 96000 loss: 0.0038 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 97000 loss: 0.0038 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 98000 loss: 0.0039 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 99000 loss: 0.0038 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 100000 loss: 0.0038 scmap loss: 0.0036 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 101000 loss: 0.0037 scmap loss: 0.0036 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 102000 loss: 0.0037 scmap loss: 0.0036 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 103000 loss: 0.0038 scmap loss: 0.0037 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 104000 loss: 0.0037 scmap loss: 0.0035 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 105000 loss: 0.0037 scmap loss: 0.0035 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 106000 loss: 0.0036 scmap loss: 0.0035 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 107000 loss: 0.0036 scmap loss: 0.0035 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
iteration: 108000 loss: 0.0037 scmap loss: 0.0035 locref loss: 0.0001 limb loss: 0.0001 lr: 1e-05
Exception in thread Thread-11 (load_and_enqueue):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 83, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py", line 511, in next_batch
    ) = self.get_batch()
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py", line 407, in get_batch
    image = imread(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/utils/auxfun_videos.py", line 371, in imread
    image = io.imread(image_path)
  File "/usr/local/lib/python3.10/dist-packages/skimage/io/_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python3.10/dist-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/skimage/io/_plugins/imageio_plugin.py", line 15, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/usr/local/lib/python3.10/dist-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "/usr/local/lib/python3.10/dist-packages/imageio/core/request.py", line 247, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.10/dist-packages/imageio/core/request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/content/drive/My Drive/Mouse_interaction_main2-We-2023-10-16/labeled-data/Test 5/img4938.png'
```

### Anything else?

I'm pretty new in programming and this is my first bug post, so I didn't gather all possibly useful data, but I'll try to give here some more info. 

- My first training dataset has ~700 frames and I didn't face this bug (possibly, cuz google took away his GPU earlier), DLC version 2.3.5
- Then I added more frames to 1540 and found this error (it appeared >65000 iterations), DLC version 2.3.5
- Previously trainings were interrupted by Google (ended time for using GPU), but from that moment it was always interrupted by this error and difference in time between error and Google can be >10000 iterations
- I started to use dlc.create_multianimaltraining_dataset(windows2linux=True), but it doesn't help
- Picture that can't be found is always different, from different videos and is always actually present (following path named in error) and isn't corrupted
- Then I added more frames to ~2500 and error was still there, in same iteration (or time) interval, DLC version 2.3.7
- Then I added more lables (originally were 4 for each mouse, and then became 10) to project with 1540 frames. After that error appeared after 57000 iterations (I don't think any dependance exists here), DLC version 2.3.7
- This error doesn't impede me dramatically, but it exists and I'm afraid that next time it won't allow me to go 40k iterations or fewer...

Thank you for your work!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @SciRay this happened to me once, I verified the image was there (you can even click on the link), so I believe it's a colab connection to the GFDrive issue -- I unfortunately cannot solve it, and it's not deterministic, and only happens rarely, but I agree this is good to document !
