### ISSUE TITLE
cant copypaste labels

### ISSUE THREAD

**Issue by delaroob** [DeepLabCut/DeepLabCut#2474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

So I have some frames that I would like to label, where the positions of the subject is very similar, so I thought that I could save myself a lot of trouble and time if instead of labeling all frames from scratch, I would label the first and then copy that data to the other frames and adjust from there. 
So I selected all the labels on the freshly labeled frame, ctrl c, next frame, ctrl v and nothing happened (got terminal output). 
If I select only one label, ctrl c, next frame, ctrl v, it works. And after that, if I delete this one pasted label and try to copypaste all of the labels from previous frame, it will only paste that single label. Any ideas?
Thank you so much in advance for any help!

### Operating System

windows 10

### DeepLabCut version

2.3.8

### DeepLabCut mode

single animal

### Device type

cpu

### Steps To Reproduce

anaconda prompt: 
- conda activate deeplabcut
- python -m deeplabcut
dlc:
- load project (select config file)
- label frames tab, label frames
- select folder in labeled-data (-> napari window opens)
- label a frame (with all 27 labels that stand in the config file)
- select labels (select points (3) tool)
- ctrl+c
- go to next frame (without labels)
- ctrl+v

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\vispy\app\backends\_qt.py", line 561, in keyPressEvent
    self._keyEvent(self._vispy_canvas.events.key_press, ev)
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\vispy\app\backends\_qt.py", line 622, in _keyEvent
    func(native=ev, key=key, text=str(ev.text()), modifiers=mod)
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\napari\utils\key_bindings.py", line 545, in on_key_press
    self.press_key(combo)
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\napari\utils\key_bindings.py", line 470, in press_key
    generator_or_callback = func()
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\napari\layers\points\_points_key_bindings.py", line 64, in copy
    layer._copy_data()
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\napari\layers\points\points.py", line 1976, in _copy_data
    'text': self.text._copy(index),
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\napari\layers\utils\text_manager.py", line 215, in _copy
    'color': _get_style_values(self.color, indices),
  File "C:\mentes\conda\envs\deeplabcut\lib\site-packages\napari\layers\utils\style_encoding.py", line 289, in _get_style_values
    return values if values.ndim == value_ndim else values[indices]
IndexError: index 4 is out of bounds for axis 0 with size 4
```

### Anything else?

note: when loading DLC (gui), I usually get this geometry error. I dont think that it as anything to do with my copypaste issue, but I'll paste it just in case
`QWindowsWindow::setGeometry: Unable to set geometry 1920x1049+0+35 (frame: 1942x1105-11-10) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x986+0+34 (frame: 1942x1042-11-11) margins: 11, 45, 11, 11 minimum size: 1078x699 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=1639, y=1105)))
WARNING: DirectWrite: CreateFontFaceFromHDC() failed for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=144`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by delaroob** [comment]
update: tried with the same dlc version (2.3.8) on mac (version 12.3.1) and it works (but still nothing on windows)

**Comment by jeylau** [comment]
Hi @delaroob, could you make sure you use the latest version of our labeling plugin, by running `pip install -U napari-deeplabcut`? I tried the copy/paste functionality and did not run into trouble.

**Comment by delaroob** [comment]
yep, solved the issue:)
