### ISSUE TITLE
DLC dropping underscore in file path

### ISSUE THREAD

**Issue by tsievert** [DeepLabCut/DeepLabCut#2482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

DLC seems to drop an underscore in the file path while creating symlinks.
See last line in the log output: `/gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test videos/cluster_test_vid.mp4` instead of `/2023-09-15_test_videos/`.
But it was clearly correct before `Created the symlink of /gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test_videos/temp/cluster_test_vid.mp4`

### Operating System

Operating System: Red Hat Enterprise Linux 8.6 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-372.26.1.el8_6.x86_64

### DeepLabCut version

2.3.8 (pulled from GitHub, so including fixes up to #2475, but also occurs in a standard 2.3.8 install) 

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. `sbatch --output=res_DLC_extract_testvid.txt DLC_batch_add_and_extract.sh /gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test_videos/temp`
2. Content of `DLC_batch_add_and_extract.sh`
```bash
#!/bin/bash
#
#SBATCH --job-name=DLC_extract_test
#SBATCH --output=res_DLC_add_extract.txt
#SBATCH --account=behavior
#
#SBATCH --partition=debug-gpu
#SBATCH --time=1:00:00
#SBATCH --gpus=1
#SBATCH --gres=gpu:1
#
#

module load devel/python/Anaconda3-2022.05
conda activate DLC_dev
module load CUDA/11.7.0 TensorFlow/2.11.0-foss-2022a-CUDA-11.7.0

cd /gpfs/projects/acad/behavior/softs/DLC_scripts

python DLC_add_videos.py $1
python DLC_extract_frames.py $1
```
3. Content of `DLC_add_videos.py`
```python
import deeplabcut
import os,sys,glob

"""to execute the script, do: python extract.py path_to_folder_with_videos"""
config_file_path = '/gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/config.yaml'

my_path = sys.argv[1]

video_file_path = glob.glob(os.path.join(my_path, "*.mp4"))

VideoType = 'mp4'

deeplabcut.add_new_videos(
    config_file_path,
    video_file_path,
    copy_videos=False,
    coords=None,
    extract_frames=False,
)
```
4. Content of `DLC_extract_frames.py`
```python
import deeplabcut
import os,sys,glob

"""to execute the script, do: python extract.py path_to_folder_with_videos"""
config_file_path = '/gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/config.yaml'

my_path = sys.argv[1]

#video_file_path = ["/gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/cohort6/2023-11-06_ID064_POm.mp4"]
video_file_path = glob.glob(os.path.join(my_path, "*.mp4"))

VideoType = 'mp4'

deeplabcut.extract_frames(
    config_file_path, 
    mode='automatic', 
    algo='kmeans', 
    userfeedback=False, 
    crop=False,
    cluster_step=50,
    videos_list=video_file_path)
```

### Relevant log output

```shell
Loading DLC 2.3.8...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Attempting to create a symbolic link of the video ...
Created the symlink of /gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test_videos/temp/cluster_test_vid.mp4 to /gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/videos/cluster_test_vid.mp4
New videos were added to the project! Use the function 'extract_frames' to select frames for labeling.
Loading DLC 2.3.8...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Attempting to create a symbolic link of the video ...
Video /gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/videos/cluster_test_vid.mp4 already exists. Skipping...
Traceback (most recent call last):
  File "/gpfs/projects/acad/behavior/softs/DLC_scripts/DLC_extract_frames.py", line 9, in <module>
    deeplabcut.add_new_videos(
  File "/gpfs/home/acad/ulg-neurosci/tsievert/.local/lib/python3.10/site-packages/deeplabcut/create_project/add.py", line 119, in add_new_videos
    vid = VideoReader(video_path)
  File "/gpfs/home/acad/ulg-neurosci/tsievert/.local/lib/python3.10/site-packages/deeplabcut/utils/auxfun_videos.py", line 40, in __init__
    raise ValueError(f'Video path "{video_path}" does not point to a file.')
ValueError: Video path "/gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test videos/cluster_test_vid.mp4" does not point to a file.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @tsievert! It seems to me that the symlink is not actually being created here. From the logs, we can see:

```
Attempting to create a symbolic link of the video ...
Video /gpfs/...main-model-2023-09-14/videos/cluster_test_vid.mp4 already exists. Skipping...
```

So the program exits [here](https://github.com/DeepLabCut/DeepLabCut/blob/a2c9b038b4192de8fe49be0ef5021370ad6c69b5/deeplabcut/create_project/add.py#L91) and thus does not create a new symlink. It then crashes when trying to read the video, as the existing symlink is incorrect.

Could you try deleting the symlink `LassanceLab-main-model-2023-09-14/videos/cluster_test_vid.mp4`, re-running the code and seeing if the problem persists?

**Comment by n-poulsen** [comment]
Closing as stale

**Comment by tsievert** [comment]
Sorry for the late reply!

I tried deleting the problematic symlink, but the issue remains.

The script etc are the same as before.

```bash
This run started on: Thu Mar 14 13:59:00 CET 2024
Loading DLC 2.3.9...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Attempting to create a symbolic link of the video ...
Created the symlink of /gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test_videos/temp/cluster_test_vid.mp4 to /gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/videos/cluster_test_vid.mp4
New videos were added to the project! Use the function 'extract_frames' to select frames for labeling.
Loading DLC 2.3.9...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Attempting to create a symbolic link of the video ...
Video /gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/videos/cluster_test_vid.mp4 already exists. Skipping...
Traceback (most recent call last):
  File "/gpfs/projects/acad/behavior/softs/DLC_scripts/DLC_extract_frames.py", line 9, in <module>
    deeplabcut.add_new_videos(
  File "/gpfs/home/acad/ulg-neurosci/tsievert/.local/lib/python3.10/site-packages/deeplabcut/create_project/add.py", line 123, in add_new_videos
    vid = VideoReader(video_path)
  File "/gpfs/home/acad/ulg-neurosci/tsievert/.local/lib/python3.10/site-packages/deeplabcut/utils/auxfun_videos.py", line 40, in __init__
    raise ValueError(f'Video path "{video_path}" does not point to a file.')
ValueError: Video path "/gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test videos/cluster_test_vid.mp4" does not point to a file.
This run completed on: Thu Mar 14 13:59:10 CET 2024
```

Since `dlc.extract_frames()` also tries to create the symlink, I skipped the `dlc.add_new_videos()` step, but the result is the same:

```bash
This run started on: Thu Mar 14 14:18:33 CET 2024
Loading DLC 2.3.9...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Attempting to create a symbolic link of the video ...
Created the symlink of /gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test videos/cluster_test_vid.mp4 to /gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/videos/cluster_test_vid.mp4
Traceback (most recent call last):
  File "/gpfs/projects/acad/behavior/softs/DLC_scripts/DLC_extract_frames.py", line 9, in <module>
    deeplabcut.add_new_videos(
  File "/gpfs/home/acad/ulg-neurosci/tsievert/.local/lib/python3.10/site-packages/deeplabcut/create_project/add.py", line 123, in add_new_videos
    vid = VideoReader(video_path)
  File "/gpfs/home/acad/ulg-neurosci/tsievert/.local/lib/python3.10/site-packages/deeplabcut/utils/auxfun_videos.py", line 40, in __init__
    raise ValueError(f'Video path "{video_path}" does not point to a file.')
ValueError: Video path "/gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test videos/cluster_test_vid.mp4" does not point to a file.
This run completed on: Thu Mar 14 14:18:44 CET 2024
```

**Comment by tsievert** [comment]
Sorry to ping you @n-poulsen, but I guess you didn't see my late answer.

**Comment by n-poulsen** [comment]
Hi @tsievert! I'm a little perplexed then, I really don't know where this issue is coming from... Could you try renaming the problematic path from an underscore to a dash (from `2023-09-15_test videos/cluster_test_vid.mp4` to `2023-09-15-test-videos/cluster-test-vid.mp4`) and see if the issue persists?

That's likely the easiest way to fix the issue

**Comment by tsievert** [comment]
Hey @n-poulsen!
I feel very foolish. I went again over all of my code with a fine comb and discovered that I must have uploaded a wrong version to the cluster.
Turns out the faulty file path was hard-coded into one of my scripts.
I'm really sorry for all the time wasted for this!

**Comment by tsievert** [comment]
Close as user error
