### ISSUE TITLE
Connection reset by peer when trying to download pretrained models other than ResNets

### ISSUE THREAD

**Issue by programerkotik** [DeepLabCut/DeepLabCut#2497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Receive `ConnectionResetError: [Errno 104] Connection reset by peer` when trying to download pretrained models during creation of the training set. 

### Operating System

Ubuntu 20.04.6 LTS

### DeepLabCut version

deeplabcut=2.3.8

### DeepLabCut mode

multi animal

### Device type

GPU

### Steps To Reproduce

Create dataset with network architecture to anything other than ResNets.

### Relevant log output

```shell
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/site-packages/deeplabcut/gui/tabs/create_training_dataset.py", line 100, in create_training_dataset
    deeplabcut.create_multianimaltraining_dataset(
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/site-packages/deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py", line 275, in create_multianimaltraining_dataset
    model_path = auxfun_models.check_for_weights(
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/site-packages/deeplabcut/utils/auxfun_models.py", line 69, in check_for_weights
    download_weights(modeltype, model_path.parent)
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/site-packages/deeplabcut/utils/auxfun_models.py", line 95, in download_weights
    response = urllib.request.urlopen(url)
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/home/aagafono/miniconda3/envs/DLC39/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @programerkotik, are you running this on a "regular" internet connection? I've tried to replicate your issue but was able to successfully download other pretrained models on my computer (e.g., EfficientNet or MobileNet)

I'm thinking it could be something similar to #2361, where a proxy blocks you from downloading the files.

**Comment by n-poulsen** [comment]
Closing due to inactivity
