### ISSUE TITLE
ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub' 

### ISSUE THREAD

**Issue by stefanolatini** [DeepLabCut/DeepLabCut#2530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello everyone, and thanks for the attention.
When I try to launch `import deeplabcut`  from anaconda python console I have the following error:

`Loading DLC 2.3.9...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/__init__.py", line 37, in <module>
    from deeplabcut.create_project import (
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/__init__.py", line 13, in <module>
    from deeplabcut.create_project.modelzoo import (
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/modelzoo.py", line 19, in <module>
    from dlclibrary.dlcmodelzoo.modelzoo_download import (
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/dlclibrary/dlcmodelzoo/modelzoo_download.py", line 18, in <module>
    from huggingface_hub import hf_hub_download
ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub' (/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/huggingface_hub/__init__.py)
`

DLC version: 2.3.9
Environment: Conda 23.1.0
OS: Mac OSX Sonoma 14.0 (23A344)
CPU: Intel

[This](https://github.com/DeepLabCut/DeepLabCut/blob/main/conda-environments/DEEPLABCUT.yaml) is my env file

### Operating System

operating system

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

cpu

### Steps To Reproduce

1. activate the anaconda env
2. open python console from anaconda
3. launch `import deeplabcut`

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/__init__.py", line 37, in <module>
    from deeplabcut.create_project import (
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/__init__.py", line 13, in <module>
    from deeplabcut.create_project.modelzoo import (
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/modelzoo.py", line 19, in <module>
    from dlclibrary.dlcmodelzoo.modelzoo_download import (
  File "/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/dlclibrary/dlcmodelzoo/modelzoo_download.py", line 18, in <module>
    from huggingface_hub import hf_hub_download
ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub' (/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/huggingface_hub/__init__.py)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by stefanolatini** [comment]
can anyone helm me? I'm stucked everytime I do 
`> import deeplabcut`

or 

`$ python -m deeplabcut`

**Comment by n-poulsen** [comment]
Hi @stefanolatini, could you specify which package versions are installed? You can get that by running `pip list` in anaconda

**Comment by stefanolatini** [comment]
```
Package                       Version
----------------------------- ---------------
absl-py                       2.1.0
alabaster                     0.7.16
anyio                         4.3.0
app-model                     0.2.4
appdirs                       1.4.4
appnope                       0.1.4
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
astunparse                    1.6.3
attrs                         23.2.0
Babel                         2.14.0
beautifulsoup4                4.12.3
bleach                        6.1.0
blosc2                        2.5.1
build                         1.1.1
cached-property               1.5.2
cachetools                    5.3.3
cachey                        0.2.1
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
comm                          0.2.1
contourpy                     1.2.0
cycler                        0.12.1
dask                          2024.2.1
dask-image                    2023.8.1
debugpy                       1.8.1
decorator                     5.1.1
deeplabcut                    2.3.9
defusedxml                    0.7.1
dlclibrary                    0.0.6
docstring-parser              0.15
docutils                      0.17.1
entrypoints                   0.4
exceptiongroup                1.2.0
executing                     2.0.1
fastjsonschema                2.19.1
filelock                      3.13.1
filterpy                      1.4.5
flatbuffers                   23.5.26
fonttools                     4.49.0
fqdn                          1.5.1
freetype-py                   2.4.0
fsspec                        2024.2.0
gast                          0.4.0
google-auth                   2.28.1
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.62.0
h5py                          3.10.0
HeapDict                      1.0.1
hsluv                         5.0.4
huggingface-hub               0.21.3
idna                          3.6
imageio                       2.34.0
imageio-ffmpeg                0.4.9
imagesize                     1.4.1
imgaug                        0.4.0
importlib-metadata            7.0.1
importlib_resources           6.1.2
in-n-out                      0.1.9
ipykernel                     6.29.3
ipython                       8.18.1
ipython-genutils              0.2.0
ipywidgets                    8.1.2
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.3
joblib                        1.3.2
jsonpointer                   2.4
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
jupyter                       1.0.0
jupyter_client                7.4.9
jupyter-console               6.6.3
jupyter_core                  5.7.1
jupyter-events                0.9.0
jupyter_server                2.12.5
jupyter_server_terminals      0.5.2
jupyterlab_pygments           0.3.0
jupyterlab_widgets            3.0.10
keras                         2.10.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.5
lazy_loader                   0.3
libclang                      16.0.6
llvmlite                      0.42.0
locket                        1.0.0
magicgui                      0.8.1
Markdown                      3.5.2
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.8.3
matplotlib-inline             0.1.6
mdurl                         0.1.2
mistune                       3.0.2
msgpack                       1.0.8
msgpack-numpy                 0.4.8
mypy-extensions               1.0.0
napari                        0.4.18
napari-console                0.0.9
napari-deeplabcut             0.2.1.3
napari-plugin-engine          0.2.0
napari-svg                    0.1.10
natsort                       8.4.0
nb_conda                      2.2.1
nb_conda_kernels              2.3.1
nbclassic                     1.0.0
nbclient                      0.8.0
nbconvert                     7.16.1
nbformat                      5.9.2
ndindex                       1.8
nest_asyncio                  1.6.0
networkx                      3.2.1
notebook                      6.5.6
notebook_shim                 0.2.4
npe2                          0.7.4
numba                         0.59.0
numexpr                       2.9.0
numpy                         1.26.4
numpydoc                      1.5.0
oauthlib                      3.2.2
opencv-python                 4.9.0.80
opencv-python-headless        4.9.0.80
opt-einsum                    3.3.0
overrides                     7.7.0
packaging                     23.2
pandas                        2.2.1
pandocfilters                 1.5.0
parso                         0.8.3
partd                         1.4.1
patsy                         0.5.6
pexpect                       4.9.0
pickleshare                   0.7.5
pillow                        10.2.0
PIMS                          0.6.1
Pint                          0.23
pip                           24.0
pkgutil_resolve_name          1.3.10
platformdirs                  4.2.0
pooch                         1.8.1
prometheus_client             0.20.0
prompt-toolkit                3.0.42
protobuf                      3.19.6
psutil                        5.9.8
psygnal                       0.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pyconify                      0.1.6
pycparser                     2.21
pydantic                      1.10.14
pydantic-compat               0.1.2
Pygments                      2.17.2
pyobjc-core                   10.1
pyobjc-framework-Cocoa        10.1
PyOpenGL                      3.1.7
pyparsing                     3.1.1
pyproject_hooks               1.0.0
PySide6                       6.3.1
PySide6-Addons                6.3.1
PySide6-Essentials            6.3.1
python-dateutil               2.9.0
python-json-logger            2.0.7
pytz                          2024.1
PyYAML                        6.0.1
pyzmq                         24.0.1
QDarkStyle                    3.1
qtconsole                     5.5.1
QtPy                          2.4.1
referencing                   0.33.0
requests                      2.31.0
requests-oauthlib             1.3.1
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.1
rpds-py                       0.18.0
rsa                           4.9
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.8
scikit-image                  0.22.0
scikit-learn                  1.4.1.post1
scipy                         1.12.0
Send2Trash                    1.8.2
setuptools                    69.1.1
shapely                       2.0.3
shiboken6                     6.3.1
six                           1.16.0
slicerator                    1.1.0
sniffio                       1.3.1
snowballstemmer               2.2.0
soupsieve                     2.5
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
stack-data                    0.6.2
statsmodels                   0.14.1
superqt                       0.6.1
tables                        3.9.2
tabulate                      0.9.0
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.36.0
tensorpack                    0.11
termcolor                     2.4.0
terminado                     0.18.0
tf-slim                       1.1.0
threadpoolctl                 3.3.0
tifffile                      2024.2.12
tinycss2                      1.2.1
tomli                         2.0.1
tomli_w                       1.0.0
toolz                         0.12.1
torch                         1.12.0
tornado                       6.4
tqdm                          4.66.2
traitlets                     5.14.1
typer                         0.9.0
types-python-dateutil         2.8.19.20240106
typing_extensions             4.10.0
typing-utils                  0.1.0
tzdata                        2024.1
uri-template                  1.3.0
urllib3                       2.2.1
vispy                         0.12.2
wcwidth                       0.2.13
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.7.0
Werkzeug                      3.0.1
wheel                         0.42.0
widgetsnbextension            4.0.10
wrapt                         1.16.0
zipp                          3.17.0

```

**Comment by stefanolatini** [comment]
i tried to uninstall and reinstall anaconda, launch `conda  clean --all` but the problem persists

**Comment by n-poulsen** [comment]
Could you try running `pip install "huggingface-hub==0.16.4"` in your conda environment and checking if the issue persists?

I've tried replicating the issue with macOS on my end but couldn't reproduce it. 

Could you also try running:

```python
import huggingface_hub
from huggingface_hub import hf_hub_download
```

in your conda environment?

**Comment by stefanolatini** [comment]
the installation goes well but the problem persists
```

(DEEPLABCUT) stefanolatini@macbook ~ % pip install "huggingface-hub==0.16.4"
Collecting huggingface-hub==0.16.4
  Downloading huggingface_hub-0.16.4-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: filelock in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from huggingface-hub==0.16.4) (3.13.1)
Requirement already satisfied: fsspec in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from huggingface-hub==0.16.4) (2024.2.0)
Requirement already satisfied: requests in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from huggingface-hub==0.16.4) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from huggingface-hub==0.16.4) (4.66.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from huggingface-hub==0.16.4) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from huggingface-hub==0.16.4) (4.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from huggingface-hub==0.16.4) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from requests->huggingface-hub==0.16.4) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from requests->huggingface-hub==0.16.4) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from requests->huggingface-hub==0.16.4) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages (from requests->huggingface-hub==0.16.4) (2024.2.2)
Downloading huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 3.6 MB/s eta 0:00:00
Installing collected packages: huggingface-hub
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.21.3
    Uninstalling huggingface-hub-0.21.3:
      Successfully uninstalled huggingface-hub-0.21.3
Successfully installed huggingface-hub-0.16.4
(DEEPLABCUT) stefanolatini@macbook ~ % python
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:36:46) 
[Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import huggingface_hub
>>> from huggingface_hub import hf_hub_download
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub' (/usr/local/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/huggingface_hub/__init__.py)
>>> 

```

**Comment by n-poulsen** [comment]
This doesn't seem to be an issue with DeepLabCut... could you try creating a "clean" environment with only `huggingface-hub` installed and see if the issue persists? You can do so by running the following in your terminal:

```bash
conda create -n TEST_ENV python=3.9
conda activate TEST_ENV
pip install huggingface-hub
python
```

and then try to import in the python shell with

```python
import huggingface_hub
from huggingface_hub import hf_hub_download
```

**Comment by stefanolatini** [comment]
same problem:
as usual the `import huggingface_hub` command goes well, the `from huggingface_hub import hf_hub_download` crashes

**Comment by stefanolatini** [comment]
anyway 
thanks so much for the attention payed

**Comment by tokioshima** [comment]
I got the exact same configuration and problem as @stefanolatini (except that I use Windows 8).
If anyone have a idea
Thanks in advance

**Comment by johnmbarrett** [comment]
Ran into the same error today, for me running `conda install chardet` fixed the issue.

Suspect my case was a different but related issue as a) I was using Anipose, not importing DLC directly, b) no matter what I did I could not reproduce the issue in a clean conda environment, and c) while `anipose analyze` gave the same error as OP was getting from `import deeplabcut`, for me `from huggingface_hub import hf_hub_download` in a fresh Python REPL session gave 

`ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/home/lsps/anaconda3/envs/anipose/lib/python3.7/site-packages/charset_normalizer/constant.py)`

hence why installing `chardet` fixed it. So not sure my solution will work for OP, but commenting here in case anyone else stumbles across this issue in their Googling like I did.

**Comment by SvrCvs** [comment]
Did you try to update hugging face_hub? I had the same issue and it fixed it.

pip install --upgrade huggingface_hub

**Comment by saurabh-kataria** [comment]
@johnmbarrett your solution strangely worked for me! thanks.

**Comment by ewayboy** [comment]
conda install chardet

**Comment by gtimk6** [comment]
> conda install chardet

solved it. thanks.
