### ISSUE TITLE
yaml.constructor.ConstructorError: 

### ISSUE THREAD

**Issue by AthiemoneZero** [DeepLabCut/DeepLabCut#2548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

after training a network, I tried using GUI or API (dlc.evaluate_network) to evaluate this new-trained network. It got such error report:

` 
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/app
ly:pathlib.WindowsPath'
`

### Operating System

Windows10

### DeepLabCut version

dlc version 2.3.8

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. create a new training dataset (resnet-50);
2. change batch_size into 4 in pose_cfg.yaml file;
3. training  (I ever got error after changing it, but sometime it won't happend);
4.  evaluate new network

### Relevant log output

```shell
Loading DLC 2.3.8...
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\deeplabcut\gui\tabs\evaluate_network.py", line 181, in ev
aluate_network
    deeplabcut.evaluate_network(
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py", 
line 760, in evaluate_network
    dlc_cfg = load_config(str(path_test_config))
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\config.py", line 71
, in load_config
    return cfg_from_file(filename)
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\config.py", line 50
, in cfg_from_file
    yaml_cfg = yaml.load(f, Loader=yaml.SafeLoader)
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\constructor.py", line 51, in get_single_data        
    return self.construct_document(node)
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\constructor.py", line 60, in construct_document     
    for dummy in generator:
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\constructor.py", line 413, in construct_yaml_map    
    value = self.construct_mapping(node)
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\constructor.py", line 218, in construct_mapping     
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\constructor.py", line 143, in construct_mapping     
    value = self.construct_object(value_node, deep=deep)
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\constructor.py", line 100, in construct_object      
    data = constructor(self, node)
  File "C:\Users\Admin\anaconda3\envs\DLC\lib\site-packages\yaml\constructor.py", line 427, in construct_undefined   
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/app
ly:pathlib.WindowsPath'
  in "C:\Users\Admin\Desktop\CXC\DLC_projects\TreDet\TreDet-WC-2024-02-29\dlc-models\iteration-3\TreDetFeb29-trainset
95shuffle1\test\pose_cfg.yaml", line 11, column 15
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AthiemoneZero** [comment]
I am stupid, is just a small detail I miss to notice. my bad
