### ISSUE TITLE
DLClight on HPC with issue "AttributeError: module 'deeplabcut' has no attribute 'create_training_dataset'"

### ISSUE THREAD

**Issue by M3K33L** [DeepLabCut/DeepLabCut#2549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have been attempting to use DLC on a cluster. I was able to get a sbatch job to begin running a python script that calls DLC functions, but I get this output log from that script:

```
no change     /home/dlazega/miniconda/bin/deactivate
no change     /home/dlazega/miniconda/etc/profile.d/conda.sh
no change     /home/dlazega/miniconda/etc/fish/conf.d/conda.fish
no change     /home/dlazega/miniconda/shell/condabin/Conda.psm1
no change     /home/dlazega/miniconda/shell/condabin/conda-hook.ps1
no change     /home/dlazega/miniconda/lib/python3.12/site-packages/xontrib/cond>
no change     /home/dlazega/miniconda/etc/profile.d/conda.csh
no change     /home/dlazega/.bashrc
No action taken.
CondaError: Run 'conda init' before 'conda activate'
2024-03-22 14:15:40.068601: I tensorflow/core/platform/cpu_feature_guard.cc:210>
To enable the following instructions: AVX2 FMA, in other operations, rebuild Te>
2024-03-22 14:15:42.302754: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc>
Traceback (most recent call last):
  File "/isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2->
    dlc.create_training_dataset(config_path, Shuffles=[1])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'deeplabcut' has no attribute 'create_training_dataset'
```

I've seen on this forum that usually this error is resolved by checking the paths. However, I've checked my paths on the cluster, the python script, the batch script, and the config.yaml:

**Python:**
```python
import tensorflow as tf
import os
import sys
sys.path.append('/home/dlazega/miniconda/envs/DEEPLABCUT/lib/')
sys.path.append('/home/dlazega/miniconda/envs/DEEPLABCUT/lib')
sys.path.append('/home/dlazega/miniconda/envs/DEEPLABCUT/')
sys.path.append('/home/dlazega/miniconda')
os.environ["DLClight"] = "True"
import deeplabcut as dlc
os.chdir('/home/dlazega/miniconda/envs/DEEPLABCUT/lib/')
config_path = "/isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2-Gaby_Danny-2024-03-22/config.yaml"
dlc.create_training_dataset(config_path, Shuffles=[1])
```

**Batch:**
```
#!/bin/bash
#SBATCH -t 08:00
#SBATCH --job-name=MaierDLC
#SBATCH -n 1
#SBATCH -p gpu
#SBATCH --gpus 1
#SBATCH --mem 16384M
export THIS_LIB=/home/dlazega/miniconda/envs/DEEPLABCUT/lib
export PRJ_PATH=/isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2-Gaby_Danny-2024-03-22
cd $THIS_LIB
module purge
module load cuda-toolkit/12.2.2
conda init
conda activate DEEPLABCUT
yes | python $PRJ_PATH/ClusterTest.py
```

**Config.yaml:**

```yaml
    # Project path (change when moving around)
project_path: 
  /isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2-Gaby_Danny-2024-03-22
video_sets:
  /isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2-Gaby_Danny-2024-03-22/videos/[REDACTED].mp4:
    crop: 0, 1280, 0, 720
......
```

**Cluster:**
```
(base) [dlazega@demon-ln1 Test_2-Gaby_Danny-2024-03-22]$ pwd
/isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2-Gaby_Danny-2024-03-22
(base) [dlazega@demon-ln1 lib]$ pwd
/home/dlazega/miniconda/envs/DEEPLABCUT/lib
```

I must be missing something, but I have no idea what. My install is up to date - I deleted everything in the DEEPLABCUT env folder and the DeepLabCut-main folder that I downloaded via git; then restarted and did a completely fresh install. I was having issues with GLIBCXX4.30 not being available as well, but that was fixed by calling DLC from the DEEPLABCUT/lib folder.

### Operating System

RHEL9 Linux

### DeepLabCut version

2.9.3

### DeepLabCut mode

single animal

### Device type

Nvidia A100

### Steps To Reproduce

sbatch MaierDLC.slurm
(See bug description to read the .slurm file)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by M3K33L** [comment]
I just added
#!/home/dlazega/miniconda/envs/DEEPLABCUT/lib python3.9
to the top of my ClusterTest.py file to try and have the interpreter use the python that I want.

It did not change the output log.

**Comment by M3K33L** [comment]
I tried updating DLC again via pip install --upgrade deeplabcut, which found a package that was not installed correctly. Then, I did the following within the environment:

```
cd ./Test_2...
module load cuda-toolkit/12.2.2
python
>>> import tensorflow as tf
>>> import os
>>> os.environ["DLClight"] = "True"
>>> import deeplabcut as dlc (SUCCESS!!!!!)
>>> config_path = "/isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2-Gaby_Danny-2024-03-22/config.yaml"
>>> dlc.create_training_dataset(config_path, Shuffles=[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 893, in create_training_dataset
    Data = merge_annotateddatasets(
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 521, in merge_annotateddatasets
    AnnotationData.to_hdf(filename + ".h5", key="df_with_missing", mode="w")
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/pandas/core/generic.py", line 2682, in to_hdf
    pytables.to_hdf(
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/pandas/io/pytables.py", line 302, in to_hdf
    with HDFStore(
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/pandas/io/pytables.py", line 579, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/pandas/io/pytables.py", line 731, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/tables/file.py", line 300, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/tables/file.py", line 750, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 366, in tables.hdf5extension.File._g_new
  File "/home/dlazega/miniconda/envs/DEEPLABCUT/lib/python3.9/site-packages/tables/utils.py", line 161, in check_file_access
    raise PermissionError(
PermissionError: directory ``/isilon/datalake/maier_lab/Cluster/Test_2-Gaby_Danny-2024-03-22/Test_2-Gaby_Danny-2024-03-22/training-datasets/iteration-0/UnaugmentedDataSet_Test_2Mar22`` exists but it can not be written
```

I can only think that this is an error on the cluster administration side rather than mine. Also, I am still unsure of whether all of this will run within a batch script.

**Comment by n-poulsen** [comment]
Hi @M3K33L, this is indeed an issue on the cluster administration side rather than on DeepLabCut's. 

Just one note - from your logs, it seems that you're running CUDA 12.2 (`module load cuda-toolkit/12.2.2`) - this version of CUDA is not compatible with `tensorflow<2.13`, which is required for DeepLabCut (see [this issue](https://github.com/DeepLabCut/DeepLabCut/issues/2465#issuecomment-1861875446) with COLAB and [this issue](https://github.com/DeepLabCut/DeepLabCut/issues/2546) on windows). 

If you end up running into the same issue where the GPU isn't used by `tensorflow`, you can try changing the `cudatoolkit` version you're using with `conda`:

```bash
conda install -c conda-forge cudnn==8.4.1.50 cudatoolkit==11.7.0
```

I'll close this issue, and you can reopen it if the issue came from DeepLabCut rather than the cluster administration.
