### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by Shubhranshu2411** [DeepLabCut/DeepLabCut#2551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to test SuperAnimal-TopViewMouse pre-train model on my video with DLC-GUI. Have gone to to model zoo page directly and loaded my video, selected SuperAnimal-TopViewMouse model from drop down and clicked on run. My terminal gives this error...

```
Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\utils.py", line 22, in run
    self.func()
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 102, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 114, in before_adapt_inference
    self.init_weights, datafiles = superanimal_inference.video_inference(
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\modelzoo\api\superanimal_inference.py", line 302, in video_inference
    download_huggingface_model(superanimal_name, weight_folder)
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\dlclibrary\dlcmodelzoo\modelzoo_download.py", line 122, in download_huggingface_model
    hf_hub_download(repo_id, targzfn, cache_dir=str(target_dir))
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\huggingface_hub\file_download.py", line 1419, in hf_hub_download
    os.makedirs(os.path.dirname(pointer_path), exist_ok=True)
  File "C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\shubh\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\superanimal_topviewmouse_weights\\models--mwmathis--DeepLabCutModelZoo-SuperAnimal-TopViewMouse\\snapshots\\ca3245fa86115dd2b717d0fa33fbf2b0986b3bf6'
```

### Operating System

Windows 10

### DeepLabCut version

DLC 2.3.9

### DeepLabCut mode

single animal

### Device type

CPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Shubhranshu2411, could you try running the following in an `ipython`shell (you can start one by simply running `ipython` in your `conda` prompt)

```python
from pathlib import Path

p = Path(r"C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights")
print(p.exists())
```

And could you also please provide the package versions you're using (you can just provide the output of `pip list` in your conda shell)?

**Comment by jeylau** [comment]
@Shubhranshu2411, in addition to the above, could you run `pip install -U dlclibrary`? We had recently updated this library, which makes the download of model zoo weights insensitive to a particular commit tag (which seems to be the error you report).

**Comment by plant1987** [comment]
> Hi @Shubhranshu2411, could you try running the following in an `ipython`shell (you can start one by simply running `ipython` in your `conda` prompt)
> 
> ```python
> from pathlib import Path
> 
> p = Path(r"C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights")
> print(p.exists())
> ```
> 
> And could you also please provide the package versions you're using (you can just provide the output of `pip list` in your conda shell)?

@n-poulsen  I come acrross the same error when using the superaninal model. I followed the steps you suggested. And I get 'False' as the output.

And I checked the folder in root envs, there is no folder named 'superanimal_topviewmouse_weights'

![屏幕截图 2024-04-05 171009](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/4379054c-a335-4585-b343-91176360635c)

**Comment by plant1987** [comment]
> > Hi @Shubhranshu2411, could you try running the following in an `ipython`shell (you can start one by simply running `ipython` in your `conda` prompt)
> > ```python
> > from pathlib import Path
> > 
> > p = Path(r"C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights")
> > print(p.exists())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And could you also please provide the package versions you're using (you can just provide the output of `pip list` in your conda shell)?
> 
> @n-poulsen I come acrross the same error when using the superaninal model. I followed the steps you suggested. And I get 'False' as the output.
> 
> And I checked the folder in root envs, there is no folder named 'superanimal_topviewmouse_weights'
> 
> ![屏幕截图 2024-04-05 171009](https://private-user-images.githubusercontent.com/71976453/320049878-4379054c-a335-4585-b343-91176360635c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzAyNjcsIm5iZiI6MTcxMjMyOTk2NywicGF0aCI6Ii83MTk3NjQ1My8zMjAwNDk4NzgtNDM3OTA1NGMtYTMzNS00NTg1LWIzNDMtOTExNzYzNjA2MzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE1MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxOTM0YmEyYjZiODg3M2EzYzE4OWEwODk2NDQwYjk4ZmZhZDdiZDliODZkYjAxMWIyMGI3OTJmNzM2ZTkxODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1t3bmGylVCXa9qr2T_7cGIgmm64W9dxwpaT5wyLejg)

![屏幕截图 2024-04-05 170015](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/c61e0c86-a091-404d-8dcf-04c7f9bcc486)


![屏幕截图 2024-04-05 170057](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/fcc679e1-6921-4c61-8847-b2902a091743)


![屏幕截图 2024-04-05 170117](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/15ed8fff-3839-45a9-a20a-06b0770bdf54)

**Comment by Shubhranshu2411** [comment]
> Hi @Shubhranshu2411, could you try running the following in an `ipython`shell (you can start one by simply running `ipython` in your `conda` prompt)
> 
> ```python
> from pathlib import Path
> 
> p = Path(r"C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights")
> print(p.exists())
> ```
> 
> And could you also please provide the package versions you're using (you can just provide the output of `pip list` in your conda shell)?

Here is the output in my environment

```
(DEEPLABCUT) C:\Users\shubh>ipython
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:38:46) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pathlib import Path
   ...:
   ...: p = Path(r"C:\Users\shubh\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\mod
   ...: els\pretrained\superanimal_topviewmouse_weights")
   ...: print(p.exists())
True

In [2]:

```

**Comment by Shubhranshu2411** [comment]
> pip list

Here is the output for pip list

```
(DEEPLABCUT) C:\Users\shubh>pip list
Package                       Version
----------------------------- --------------
absl-py                       2.1.0
alabaster                     0.7.16
anyio                         4.3.0
app-model                     0.2.5
appdirs                       1.4.4
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
astunparse                    1.6.3
attrs                         23.2.0
Babel                         2.14.0
beautifulsoup4                4.12.3
bleach                        6.1.0
blosc2                        2.5.1
build                         1.1.1
cached-property               1.5.2
cachetools                    5.3.3
cachey                        0.2.1
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.2.0
cycler                        0.12.1
dask                          2024.3.1
dask-expr                     1.0.5
dask-image                    2023.8.1
debugpy                       1.8.1
decorator                     5.1.1
deeplabcut                    2.3.9
defusedxml                    0.7.1
dlclibrary                    0.0.6
docstring_parser              0.16
docutils                      0.17.1
entrypoints                   0.4
exceptiongroup                1.2.0
executing                     2.0.1
fastjsonschema                2.19.1
ffmpeg-python                 0.2.0
filelock                      3.13.1
filterpy                      1.4.5
flatbuffers                   24.3.7
fonttools                     4.50.0
fqdn                          1.5.1
freetype-py                   2.4.0
fsspec                        2024.3.1
future                        1.0.0
gast                          0.4.0
google-auth                   2.29.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.62.1
h5py                          3.10.0
HeapDict                      1.0.1
hsluv                         5.0.4
huggingface-hub               0.22.2
idna                          3.6
imageio                       2.34.0
imageio-ffmpeg                0.4.9
imagesize                     1.4.1
imgaug                        0.4.0
importlib_metadata            7.1.0
importlib_resources           6.4.0
in-n-out                      0.2.0
ipykernel                     6.29.3
ipython                       8.18.1
ipython-genutils              0.2.0
ipywidgets                    8.1.2
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.3
joblib                        1.3.2
jsonpointer                   2.4
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
jupyter                       1.0.0
jupyter_client                7.4.9
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter_server                2.13.0
jupyter_server_terminals      0.5.3
jupyterlab_pygments           0.3.0
jupyterlab_widgets            3.0.10
keras                         2.10.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.5
lazy_loader                   0.3
libclang                      18.1.1
llvmlite                      0.42.0
locket                        1.0.0
magicgui                      0.8.2
Markdown                      3.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.8.3
matplotlib-inline             0.1.6
mdurl                         0.1.2
mistune                       3.0.2
msgpack                       1.0.8
msgpack-numpy                 0.4.8
napari                        0.4.18
napari-console                0.0.9
napari-deeplabcut             0.2.1.5
napari-plugin-engine          0.2.0
napari-svg                    0.1.10
natsort                       8.4.0
nb_conda                      2.2.1
nb_conda_kernels              2.3.1
nbclassic                     1.0.0
nbclient                      0.10.0
nbconvert                     7.16.3
nbformat                      5.10.3
ndindex                       1.8
nest_asyncio                  1.6.0
networkx                      3.2.1
notebook                      6.5.6
notebook_shim                 0.2.4
npe2                          0.7.5
numba                         0.59.1
numexpr                       2.9.0
numpy                         1.26.4
numpydoc                      1.5.0
oauthlib                      3.2.2
opencv-python                 4.9.0.80
opencv-python-headless        4.9.0.80
opt-einsum                    3.3.0
overrides                     7.7.0
packaging                     24.0
pandas                        2.2.1
pandocfilters                 1.5.0
parso                         0.8.3
partd                         1.4.1
patsy                         0.5.6
pickleshare                   0.7.5
pillow                        10.2.0
PIMS                          0.6.1
Pint                          0.23
pip                           24.0
pkgutil_resolve_name          1.3.10
platformdirs                  4.2.0
pooch                         1.8.1
prometheus_client             0.20.0
prompt-toolkit                3.0.42
protobuf                      3.19.6
psutil                        5.9.8
psygnal                       0.10.2
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       15.0.2
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pyconify                      0.1.6
pycparser                     2.21
pydantic                      1.10.14
pydantic-compat               0.1.2
Pygments                      2.17.2
PyOpenGL                      3.1.7
pyparsing                     3.1.2
pyproject_hooks               1.0.0
PySide6                       6.3.1
PySide6-Addons                6.3.1
PySide6-Essentials            6.3.1
python-dateutil               2.9.0
python-json-logger            2.0.7
pytz                          2024.1
pywin32                       306
pywinpty                      2.0.13
PyYAML                        6.0.1
pyzmq                         24.0.1
QDarkStyle                    3.1
qtconsole                     5.5.1
QtPy                          2.4.1
referencing                   0.34.0
requests                      2.31.0
requests-oauthlib             2.0.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.1
rpds-py                       0.18.0
rsa                           4.9
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.8
scikit-image                  0.22.0
scikit-learn                  1.4.1.post1
scipy                         1.12.0
Send2Trash                    1.8.2
setuptools                    69.2.0
shapely                       2.0.3
shiboken6                     6.3.1
six                           1.16.0
slicerator                    1.1.0
sniffio                       1.3.1
snowballstemmer               2.2.0
soupsieve                     2.5
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
stack-data                    0.6.2
statsmodels                   0.14.1
superqt                       0.6.2
tables                        3.9.2
tabulate                      0.9.0
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.31.0
tensorpack                    0.11
termcolor                     2.4.0
terminado                     0.18.1
tf-slim                       1.1.0
threadpoolctl                 3.4.0
tifffile                      2024.2.12
tinycss2                      1.2.1
tomli                         2.0.1
tomli_w                       1.0.0
toolz                         0.12.1
torch                         1.12.0
tornado                       6.4
tqdm                          4.66.2
traitlets                     5.14.2
typer                         0.10.0
types-python-dateutil         2.9.0.20240316
typing_extensions             4.10.0
typing-utils                  0.1.0
tzdata                        2024.1
uri-template                  1.3.0
urllib3                       2.2.1
vispy                         0.12.2
wcwidth                       0.2.13
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.7.0
Werkzeug                      3.0.1
wheel                         0.43.0
widgetsnbextension            4.0.10
wrapt                         1.16.0
zipp                          3.17.0
```

**Comment by Shubhranshu2411** [comment]
> @Shubhranshu2411, in addition to the above, could you run `pip install -U dlclibrary`? We had recently updated this library, which makes the download of model zoo weights insensitive to a particular commit tag (which seems to be the error you report).

I tried with `pip install -U dlclibrary`
Shows all Requirement already satisfied and still the error persists. I checked the directory pretrained\superanimal_topviewmouse_weights there a directory name "models--mwmathis--DeepLabCutModelZoo-SuperAnimal-TopViewMouse" is present and inside snapshots directory but nothing inside snapshots.

```
(DEEPLABCUT) C:\Users\shubh>pip install -U dlclibrary
Requirement already satisfied: dlclibrary in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (0.0.6)
Requirement already satisfied: huggingface-hub in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from dlclibrary) (0.22.2)
Requirement already satisfied: ruamel.yaml>=0.15.0 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from dlclibrary) (0.18.6)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from ruamel.yaml>=0.15.0->dlclibrary) (0.2.8)
Requirement already satisfied: filelock in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from huggingface-hub->dlclibrary) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from huggingface-hub->dlclibrary) (2024.3.1)
Requirement already satisfied: packaging>=20.9 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from huggingface-hub->dlclibrary) (24.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from huggingface-hub->dlclibrary) (6.0.1)
Requirement already satisfied: requests in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from huggingface-hub->dlclibrary) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from huggingface-hub->dlclibrary) (4.66.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from huggingface-hub->dlclibrary) (4.10.0)
Requirement already satisfied: colorama in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->dlclibrary) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from requests->huggingface-hub->dlclibrary) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from requests->huggingface-hub->dlclibrary) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from requests->huggingface-hub->dlclibrary) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shubh\anaconda3\envs\deeplabcut\lib\site-packages (from requests->huggingface-hub->dlclibrary) (2024.2.2)
```

**Comment by FelixZhan** [comment]
I am also having this issue. Has a solution been found yet?

**Comment by plant1987** [comment]
> I am also having this issue. Has a solution been found yet?
yes, solved, just using the GUI instead of ipyhton or jupyter

**Comment by heathlarsson** [comment]
I am having the exact same issue, but is also persisting in GUI

`from pathlib import Path

p = Path(...\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights")
print(p.exists())`

is true for me.

 I also updated my dlclibrary.

**Comment by MMathisLab** [comment]
Did you open the terminal program "as admin" before you launched the GUI?

**Comment by heathlarsson** [comment]
Yes, I am running my terminal as "admin,".

**Comment by GabrielOcana** [comment]
Hey, I was struggling with this same issue for a couple days. In my case the location path was nested in so many folders that the path length was too long D: Apparently the windows shell has a 260 character limit. For windows users, this solution worked for me: 

- Open the Group Policy Editor (press Win+R, type gpedit.msc, and press Enter).
- Navigate to: Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem
- Find and Enable the policy “Enable Win32 long paths”.
