### ISSUE TITLE
"RuntimeError: Attempted to use a closed Session." Error, warning

### ISSUE THREAD

**Issue by Seda145** [DeepLabCut/DeepLabCut#2561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Running the "Model Zoo" with a video. Just installed the package through conda, 

Error:
"RuntimeError: Attempted to use a closed Session." on the console while running the "Model Zoo" with a video.

Warning:
Starting a Matplotlib GUI outside of the main thread will likely fail.

After the error and warning the process seems to restart, processing the video on the GPU again before moving on to plotting. 
In the media folder I do see plots, snapshots, a labeled video file. I suppose that it's finalized then?

### Operating System

Windows

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Run the GUI, click Model Zoo, load an mp4 video, use the superanimal_quadruped model, run. watch the console.

### Relevant log output

```shell
2024-04-21 05:45:24.198241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6601 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1
2024-04-21 05:45:24.686030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6601 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1
Exception in thread Thread-6:
Traceback (most recent call last):
  File "****************\envs\DEEPLABCUT\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "****************\DEEPLABCUT\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "****************\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 86, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "****************\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "****************\DEEPLABCUT\lib\site-packages\tensorflow\python\client\session.py", line 1116, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.
2024-04-21 05:47:36.331384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6601 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1
100%|██████████████████████████████████████████████████| 1582/1582 [07:12<00:00,  3.66it/s]
****************\DEEPLABCUT\lib\site-packages\deeplabcut\utils\plotting.py:67: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig1 = plt.figure(figsize=(8, 6))
****************\DEEPLABCUT\lib\site-packages\deeplabcut\utils\plotting.py:74: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig2 = plt.figure(figsize=(10, 3))
****************\DEEPLABCUT\lib\site-packages\deeplabcut\utils\plotting.py:80: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig3 = plt.figure(figsize=(10, 3))
****************\DEEPLABCUT\lib\site-packages\deeplabcut\utils\plotting.py:86: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig4 = plt.figure()
100%|██████████████████████████████████████████████████| 1582/1582 [00:17<00:00, 90.50it/s]
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Seda145! Yes these are just warnings and can be ignored!
