### ISSUE TITLE
Can't see labelled data and check labels doesn't engage

### ISSUE THREAD

**Issue by Kpraetori** [DeepLabCut/DeepLabCut#2571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

This issue has been seen on a M1 mac and Windows. I have two things that I can't figure out but I think they're related so posting both.

Context: I have a single animal project. I extracted frames from multiple videos and then distributed copies of these folders to three different people to do the labeling. They all have my same project folder and same config file (except for the project path). The completed folders are sent to me for label review and to move on to training. 

The issue happens when I try to label or check labels from these folders as well as at least one labeller now not being able to see their labels either. When in the GUI, if I try to label data and open a folder sent from another person, none of their labels show up. When I check the CSV, all the co-ordinates are there and the layout is the same as my own labeled file. I can open data that I've labelled myself and that has never moved from the labeled data folder and it looks just fine. 

I've added the Terminal output with the traceback error. I can get that it's reading a blank/empty output somewhere but I've no idea what to do about it.

I thought it was just my version, but when I asked the person who labeled the data to show me the labels on their device, their own file wouldn't load for them either. They got a similar error I did when loading and they are on a windows. They said it worked last friday when they reviewed it before sending it to me. The file location change and adding initials to the filename were the only adjustments. We both moved the folder to our labeled-data folder within the project and still got the error.

I tested on a labeled file from someone else that did not have a name change to their file and I couldn't see their labels either. I have tested files from all three raters now and none have viewable or checkable labels. Two of these labelers have Win and one has a M1 mac like mine, so I don't think it's an OS problem (and that wouldn't explain why one person can't see their labels anymore).

We have checked the point size and transparency within the GUI.

2. I think it's a related issue of not recognizing data but, when I click check labels in the GUI, nothing happens. There is no activity in the terminal, as if the button doesn't go anywhere. None of the three other people working on my project can get their check labels button to work, either.

I am happy to provide more information, I'm not sure what else I can provide to help troubleshoot. Is there something I missing from this process that keeps it from reading or recognizing the landmark data? Your help is much appreciated.

### Operating System

M1 Mac, Sonoma 14.2.1. Another person on a M1 mac, and two people on Windows (not sure which version).

### DeepLabCut version

I am using DLC version 2.3.9
They are all using updated versions and did the updates (or first time installs) within the last three weeks.
All users have an updated version of Anaconda or Miniconda updated within the last three weeks.

### DeepLabCut mode

single animal

### Device type

gpu and cpu

### Steps To Reproduce

1. open an existing DLC project
2. get a folder of labelled data from a different folder/user, or one that was moved to your project's labeled data folder. 2 MAY UPDATE: it definitely has to do with moving the folder. Labels that were showing no longer appear after moving the folder out and back in again.
3. try to Check Labels or Label Frames
4. There are no labels present in the GUI. Check Labels is unresponsive.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/gui/tabs/label_frames.py", line 59, in label_frames
    _ = launch_napari(folder)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/gui/widgets.py", line 45, in launch_napari
    viewer.open(files, plugin="napari-deeplabcut")
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1092, in open
    self._add_layers_with_plugins(
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1318, in _add_layers_with_plugins
    added.extend(self._add_layer_from_data(*_data))
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1392, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/components/viewer_model.py", line 5, in add_points
    import os
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/_collections_abc.py", line 1073, in append
    self.insert(len(self), value)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/components/layerlist.py", line 167, in insert
    super().insert(index, new_layer)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/utils/events/containers/_selectable_list.py", line 66, in insert
    super().insert(index, value)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/utils/events/containers/_evented_list.py", line 195, in insert
    self.events.inserted(index=index, value=value)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/utils/events/event.py", line 768, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/utils/events/event.py", line 806, in _invoke_callback
    _handle_exception(
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/utils/events/event.py", line 793, in _invoke_callback
    cb(event)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari_deeplabcut/_widgets.py", line 1046, in on_insert
    self._remap_frame_indices(layer_)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari_deeplabcut/_widgets.py", line 927, in _remap_frame_indices
    data[:, 0] = np.vectorize(temp.get)(data[:, 0])
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2328, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2406, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/Users/yggdrasil/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2362, in _get_ufunc_and_otypes
    raise ValueError('cannot call `vectorize` on size 0 inputs '
ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Kpraetori** [comment]
Just as an update, I've tried creating a new project and pasting in the folders into the correct location, and manually adding the filepath into the config.yaml file. I've also tried a project where I added the original video via GUI, then copy and pasted the extracted frames into the respective folder in the labeled-data folder.

I've also tried doing check labels and label frames from Terminal rather than the GUI with no luck.

One labeller sent a screenshot of the error they get when they move their own folder out of and back into their project folder. It has different content from mine but not sure if that's a Win thing.
![DLC_Win_Error](https://github.com/DeepLabCut/DeepLabCut/assets/49706292/d5e043a1-3f54-47b1-be3f-0d06c0c7d941)

**Comment by jeylau** [comment]
Hi @Kpraetori! The second issue indicates that the "video_sets" key is missing from the config.yaml file, which is abnormal as there should be at least one video in the list (this is written automatically by DeepLabCut when adding a video to a project). Even on another machine, these paths should not be removed as they govern what image folders DeepLabCut looks for. A quick solution is to add paths back manually (note that only the video name matters); i.e., if the folder of annotated images you have on another machine is called "mynicevideo", you could add the following (dummy) path: "/Users/me/myproject/mynicevideo.mp4".

As for the first error you reported, could you let me know what version of the annotation GUI you're running? (with `pip show napari-deeplabcut`)

**Comment by Kpraetori** [comment]
Hi @jeylau 
Thanks for checking in and helping me troubleshoot. I am using Version: 0.2.1.6

As for the videos, it still produces an error with the paths as they were when established in the GUI, unless there's something I'm not understanding. 
So for example:
I created a project and imported the videos with the GUI. The full videos are in the videos folder and the config.yaml file, which I have not added or removed from the video path section. If I then move a folder or contents of a folder from a copy project, with the exact same video, landmarks, names, etc., it gives the traceback. I can't see where any of the names or paths are different.
I made a new project today to see if maybe I had messed with a name path by accident and it is doing the same thing. All the paths were added by the GUI and I only copied the contents (frames, h5 and csv) from one labeled video to the same video folder in the new project. Any advice for this?

**Comment by advaitjawaji** [comment]
Did you ever find a fix for this? Thanks.

**Comment by Kpraetori** [comment]
> Did you ever find a fix for this? Thanks.

For some things, yes. So inside the h5 file was a filepath I didn't know about. So there is a helper function to create new h5 files from the csv. So I opened the CSV, made sure the filepaths were correct to the folder, then used the helper function. That worked for me. 
deeplabcut.convertcsv2h5 see https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/HelperFunctions.md

That helped for getting access for processing. I still can't open and modify any landmarks that other people made for some reason. (That said, I still can't get a model to run so not 100% sure everything is okay.)
