### ISSUE TITLE
Cannot build wheels for wxpython during installation

### ISSUE THREAD

**Issue by Abynetio** [DeepLabCut/DeepLabCut#2582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I tried to install DeepLabCut with command `pip install 'deeplabcut[gui,tf]'` and encountered this error reporting could not build wheels for wxpython. I then installed wxpython 4.2.1 and the error is not resolved. I noticed DLC seem to only support wxpython <4.1 which is not supported by my python 3.11, and I believe this might be the problem.

### Operating System

windows 11

### DeepLabCut version

deeplabcut[gui,tf]

### DeepLabCut mode

single animal

### Device type

RTX 3050

### Steps To Reproduce

1. a windows computer 
2. python 3.9 or higher installed
3. run `pip install 'deeplabcut[gui,tf]'`
4. ERROR: Failed building wheel for wxpython

### Relevant log output

```shell
Building wheels for collected packages: wxpython
  Building wheel for wxpython (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py:476: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.

              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py:678: DistDeprecationWarning: use_2to3 is ignored.
        ep.load()(self, ep.name, value)
      running bdist_wheel
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\Users\admin\AppData\Local\Programs\Python\Python311\python.exe" -u build.py build
      C:\Users\admin\AppData\Local\Temp\pip-install-ymvx500w\wxpython_4e1681f12bbd492e9ea7438ec550bb84\build.py:41: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
        from distutils.dep_util import newer, newer_group
      Will build using: "C:\Users\admin\AppData\Local\Programs\Python\Python311\python.exe"
      3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.0.7.post2

      Running command: build
      Running command: build_wx
      Command '"C:\Users\admin\AppData\Local\Programs\Python\Python311\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
      Traceback (most recent call last):

        File "<string>", line 1, in <module>

        File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 400, in initialize

          vc_env = query_vcvarsall(VERSION, plat_spec)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 280, in query_vcvarsall

          raise DistutilsPlatformError("Unable to find vcvarsall.bat")

      distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
      Finished command: build_wx (0.321s)
      Finished command: build (0.321s)
      Command '"C:\Users\admin\AppData\Local\Programs\Python\Python311\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxpython
  Running setup.py clean for wxpython
Failed to build wxpython
ERROR: Could not build wheels for wxpython, which is required to install pyproject.toml-based projects
```

### Anything else?

While it's not a problem with DLC itself, I think it would be very helpful if DLC can support higher versions of wxpython.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Abynetio!

We don't use `wxpython` anymore, so your package manager is trying to install an older version of DeepLabCut (which did). As you said, this is because we currently don't support python 3.11 (as explained in #2511)

You can use the [environment file supplied in the repo](https://github.com/DeepLabCut/DeepLabCut/blob/main/conda-environments/DEEPLABCUT.yaml) to create the environment (with `conda env create -f DEEPLABCUT.yaml`), or you can just install with conda commands. On Windows, the commands to install DeepLabCut would be:

```bash
conda create -n DEEPLABCUT python=3.10
conda activate DEEPLABCUT
conda install -c conda-forge "notebook<7.0.0" nb_conda jupyter ipython ffmpeg pytables
pip install "deeplabcut[gui,tf]"
```
