### ISSUE TITLE
GUI not opening, TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by shawnoh8** [DeepLabCut/DeepLabCut#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

(1) Trying to open GUI with "python -m deeplabcut"
(2) Deeplabcut banner shows up for split of a second and disappears
(3) TypeError in the command prompt

### Operating System

operating system: Windows 10 edu

### DeepLabCut version

dlc version: 2.3.9

### DeepLabCut mode

single animal

### Device type

gpu: gtx 3060Ti

### Relevant log output

```shell
(DEEPLABCUT) C:\Windows\system32>python -m deeplabcut
2024-06-03 23:39:49.404633: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-06-03 23:39:49.404770: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Loading DLC 2.3.9...
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__main__.py", line 24, in <module>
    launch_dlc()
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py", line 63, in launch_dlc
    from deeplabcut.gui.window import MainWindow
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\window.py", line 25, in <module>
    from napari_deeplabcut import misc
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\__init__.py", line 12, in <module>
    from ._reader import (
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_reader.py", line 12, in <module>
    from dask_image.imread import imread
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\dask_image\imread\__init__.py", line 8, in <module>
    import pims
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\pims\__init__.py", line 1, in <module>
    from pims.api import *
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\pims\api.py", line 49, in <module>
    import pims.imageio_reader
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\pims\imageio_reader.py", line 11, in <module>
    imageio_ffmpeg.get_ffmpeg_exe()
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio_ffmpeg\_utils.py", line 28, in get_ffmpeg_exe
    exe = _get_ffmpeg_exe()
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio_ffmpeg\_utils.py", line 44, in _get_ffmpeg_exe
    exe = os.path.join(_get_bin_dir(), FNAME_PER_PLATFORM.get(plat, ""))
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio_ffmpeg\_utils.py", line 69, in _get_bin_dir
    ref = importlib.resources.files("imageio_ffmpeg.binaries") / "__init__.py"
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\importlib\resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\importlib\_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\importlib\_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\shawn\anaconda3\envs\DEEPLABCUT\lib\pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Anything else?

1. I've encountered same problem on my Samsung laptop windows 11 pro.
2. Thinking maybe because the laptop language is set to Korean, some path containing Korean letters are making this problem
3. Thank you for your time in advance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
this is solved in the latest GUI, and consider using the very latest, see notes and installation here: https://github.com/DeepLabCut/DeepLabCut/issues/2616
