### ISSUE TITLE
DLC 2.3.10 does not start - "SyntaxError: invalid or missing encoding declaration for [...] pywintypes39.dll

### ISSUE THREAD

**Issue by Mijar007** [DeepLabCut/DeepLabCut#2608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I tried to install DLC 2.3.10. 
I uninstalled the old environment (DLC 2.3.9) and created it new with the 2.3.10 DEEPLABCUT.yaml.
Afterwards I tried to start it and got an error (last line): SyntaxError: invalid or missing encoding declaration for 'C:\\ProgramData\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\pywin32_system32\\pywintypes39.dll'
The full message is below.
I reinstalled DLC 2.3.9. This version works fine.
Is there some compatibility issue with one of the necessary packages?

### Operating System

Win 11

### DeepLabCut version

dlc version 2.3.10

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Open as adiministrator a Anaconda prompt and navigate to the directory containing the "DEEPLABCUT.yaml"
Enter "conda env create -f DEEPLABCUT.yaml"
Wait for installation
Enter "conda activate DEEPLABCUT"
Enter: python -m deeplabcut

### Relevant log output

```shell
(DEEPLABCUT) C:\Users\[...]\Downloads\DeepLabCut-2.9.10\DeepLabCut-2.9.10\conda-environments>python -m deeplabcut
Loading DLC 2.3.10...
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py", line 25, in <module>
    from deeplabcut.gui.tracklet_toolbox import refine_tracklets
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 18, in <module>
    from deeplabcut.refine_training_dataset.tracklets import TrackletManager
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\refine_training_dataset\__init__.py", line 13, in <module>
    from deeplabcut.refine_training_dataset.tracklets import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py", line 15, in <module>
    from deeplabcut.post_processing import columnwise_spline_interp
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\post_processing\__init__.py", line 21, in <module>
    from deeplabcut.post_processing.analyze_skeleton import analyzeskeleton
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\post_processing\analyze_skeleton.py", line 24, in <module>
    from deeplabcut.utils import auxiliaryfunctions, auxfun_multianimal
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\__init__.py", line 11, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py", line 34, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 31, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 25, in <module>
    from deeplabcut.pose_estimation_tensorflow.predict_videos import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 36, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib import inferenceutils, trackingutils
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\trackingutils.py", line 20, in <module>
    from numba import jit
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\__init__.py", line 89, in <module>
    from numba.core.decorators import (cfunc, jit, njit, stencil,
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\stencils\stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\registry.py", line 6, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\dispatcher.py", line 22, in <module>
    from numba.core.caching import NullCache, FunctionCache
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\caching.py", line 19, in <module>
    from numba.misc.appdirs import AppDirs
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\misc\appdirs.py", line 507, in <module>
    import win32com.shell
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\win32com\__init__.py", line 8, in <module>
    import pythoncom
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 831, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\ProgramData\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\pywin32_system32\\pywintypes39.dll'
```

### Anything else?

Conda version is 23.7.4

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
very strange; can you try in the env to set: `set PYTHONIOENCODING=utf-8` as it works for us here, but maybe something specific to windows

**Comment by Mijar007** [comment]
Thank you for your answer.
I tried it again and entered ` set PYTHONIOENCODING=utf-8` after I created and activated the env.
I still got the error. Below the steps I did in the Anaconda prompt:

```
(base) C:\Users\[...]>cd C:\Users\[...]\DeepLabCut-2.9.10\conda-environments

(base) C:\Users\[...]\DeepLabCut-2.9.10\conda-environments>conda env create -f DEEPLABCUT.yaml

[installation]

(base) C:\Users\[...]\DeepLabCut-2.9.10\conda-environments>conda activate DEEPLABCUT

(DEEPLABCUT) C:\Users\[...]DeepLabCut-2.9.10\conda-environments>set PYTHONIOENCODING=utf-8

(DEEPLABCUT) C:\Users\[...]\DeepLabCut-2.9.10\conda-environments>python -m deeplabcut
Loading DLC 2.3.10...
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py", line 25, in <module>
    from deeplabcut.gui.tracklet_toolbox import refine_tracklets
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 18, in <module>
    from deeplabcut.refine_training_dataset.tracklets import TrackletManager
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\refine_training_dataset\__init__.py", line 13, in <module>
    from deeplabcut.refine_training_dataset.tracklets import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py", line 15, in <module>
    from deeplabcut.post_processing import columnwise_spline_interp
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\post_processing\__init__.py", line 21, in <module>
    from deeplabcut.post_processing.analyze_skeleton import analyzeskeleton
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\post_processing\analyze_skeleton.py", line 24, in <module>
    from deeplabcut.utils import auxiliaryfunctions, auxfun_multianimal
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\__init__.py", line 11, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py", line 34, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 31, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 25, in <module>
    from deeplabcut.pose_estimation_tensorflow.predict_videos import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 36, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib import inferenceutils, trackingutils
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\trackingutils.py", line 20, in <module>
    from numba import jit
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\__init__.py", line 89, in <module>
    from numba.core.decorators import (cfunc, jit, njit, stencil,
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\stencils\stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\registry.py", line 6, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\dispatcher.py", line 22, in <module>
    from numba.core.caching import NullCache, FunctionCache
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\caching.py", line 19, in <module>
    from numba.misc.appdirs import AppDirs
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\misc\appdirs.py", line 507, in <module>
    import win32com.shell
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\win32com\__init__.py", line 8, in <module>
    import pythoncom
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 831, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\ProgramData\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\pywin32_system32\\pywintypes39.dll'
```

**Comment by MMathisLab** [comment]
which version of python are you using?

**Comment by Mijar007** [comment]
Python 3.9.19

**Comment by MMathisLab** [comment]
thanks! any issue trying python 3.10? 

can you also, after installing the via yaml, run `pip install --upgrade napari-deeplabcut, deeplabcut[gui]`

**Comment by hummuscience** [comment]
Had the same issue. Changing the python version to 3.10 (in the .yaml file) and re-creating the environment resolved the issue.

**Comment by MMathisLab** [comment]
okay great, thanks so much! I will update ... 3.9 is years behind anyhow, and the latest python works ✅

**Comment by Mijar007** [comment]
Thank you. It works with Python 3.10.14.
 More for your information, I also tried to install it with Python 3.11, but it failed.
```
Running setup.py clean for wxpython
Successfully built filterpy
Failed to build wxpython

Pip subprocess error:
WARNING: deeplabcut 2.2.3 does not provide the extra 'tf'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      C:\ProgramData\anaconda3\envs\DEEPLABCUT\Lib\site-packages\setuptools\dist.py:476: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!


              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.

              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\ProgramData\anaconda3\envs\DEEPLABCUT\Lib\site-packages\setuptools\dist.py:679: DistDeprecationWarning: use_2to3 is ignored.
        ep.load()(self, ep.name, value)
      running bdist_wheel
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\ProgramData\anaconda3\envs\DEEPLABCUT\python.exe" -u build.py build
      C:\Users\[...]\AppData\Local\Temp\pip-install-61smq7y_\wxpython_e189b8ee6b5740dab9ff21a9785f25a9\build.py:41: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
        from distutils.dep_util import newer, newer_group
      Will build using: "C:\ProgramData\anaconda3\envs\DEEPLABCUT\python.exe"
      3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC v.1938 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.0.7.post2

      Running command: build
      Running command: build_wx
      Command '"C:\ProgramData\anaconda3\envs\DEEPLABCUT\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
      Traceback (most recent call last):

        File "<string>", line 1, in <module>

        File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 400, in initialize

          vc_env = query_vcvarsall(VERSION, plat_spec)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 280, in query_vcvarsall

          raise DistutilsPlatformError("Unable to find vcvarsall.bat")

      distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
      Finished command: build_wx (0.234s)
      Finished command: build (0.234s)
      Command '"C:\ProgramData\anaconda3\envs\DEEPLABCUT\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxpython
ERROR: Could not build wheels for wxpython, which is required to install pyproject.toml-based projects

failed

CondaEnvException: Pip failed
```

**Comment by MMathisLab** [comment]
deeplabcut 2.2.3 is ~ 2 years old: 

" deeplabcut 2.2.3" >> see your trace back :)

**Comment by Mijar007** [comment]
Thank you for your Answer. If I understand it right, parts of DLC are to old for Python 3.11 and that caused the installation error.

**Comment by MMathisLab** [comment]
correct, right now 3.10 is supported; I made a new PR to fix this https://github.com/DeepLabCut/DeepLabCut/pull/2609
