### ISSUE TITLE
'Create video' not possible in GUI; looking for filtered data only

### ISSUE THREAD

**Issue by Mijar007** [DeepLabCut/DeepLabCut#2610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After analyzing the videos, I went to the 'Create videos' step. I tried it like in DLC 2.3.9 but got an error message in the information bar at the bottom of the GUI:
'Plots could not be created for [all selected Videos]'
It doesn't make a difference if the 'Plot all bodyparts' option is checked.
The selected videos are the same as the last analyzed ones.
I don't get an error message in the Anaconda prompt.
![image](https://github.com/DeepLabCut/DeepLabCut/assets/67411312/5bd61130-e00b-4d0e-95b8-02e13e0f2592)

### Operating System

WIN 11

### DeepLabCut version

dlc version 2.3.10

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

Python 3.10.14
conda 24.1.2

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @Mijar007 please update the gui and DLC with `pip install --update napari-deeplabcut` and then `pip install --update deeplabcut[gui]`

**Comment by Mijar007** [comment]
Thank you for your answer.
I activated the DLC env and tried your suggestion.
Since `--update` was not a valid command I used `--upgrade instead`.
In the command prompt all entries were labelled as "Requirement already satisfied:".
Afterwards I tested the video creation again. It didn't work.

**Comment by MMathisLab** [comment]
What is printed in the terminal? I can confirm it's working for me, that is is why it's hard to debug without more information:)

**Comment by Mijar007** [comment]
In the Anaconda prompt, nothing is listed (see below). If there is not another log,  I can't really provide you more information.
I loaded the same config.yaml with DLC 2.3.9 (Python 3.9.19) and selected the same videos and settings. In that DLC version the video creation worked.

![image](https://github.com/DeepLabCut/DeepLabCut/assets/67411312/138200f5-c3cf-4480-a142-0dfbba42448b)

**Comment by n-poulsen** [comment]
@Mijar007 could you please run `pip list` and `napari --info` in your DLC environment and report the output?

**Comment by Mijar007** [comment]
Sure:
```
(DEEPLABCUT) C:\Users\[...]>pip list
Package                       Version
----------------------------- --------------
absl-py                       2.1.0
alabaster                     0.7.16
anyio                         4.4.0
app-model                     0.2.7
appdirs                       1.4.4
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
astunparse                    1.6.3
attrs                         23.2.0
Babel                         2.15.0
beautifulsoup4                4.12.3
bleach                        6.1.0
blosc2                        2.0.0
Brotli                        1.1.0
build                         1.2.1
cached-property               1.5.2
cachetools                    5.3.3
cachey                        0.2.1
certifi                       2024.6.2
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.2.1
cycler                        0.12.1
Cython                        3.0.10
dask                          2024.5.2
dask-expr                     1.1.2
dask-image                    2024.5.3
debugpy                       1.8.1
decorator                     5.1.1
deeplabcut                    2.3.10
defusedxml                    0.7.1
dlclibrary                    0.0.6
docstring_parser              0.16
docutils                      0.17.1
entrypoints                   0.4
exceptiongroup                1.2.0
executing                     2.0.1
fastjsonschema                2.19.1
filelock                      3.15.1
filterpy                      1.4.5
flatbuffers                   24.3.25
flexcache                     0.3
flexparser                    0.3.1
fonttools                     4.53.0
fqdn                          1.5.1
freetype-py                   2.4.0
fsspec                        2024.6.0
gast                          0.4.0
google-auth                   2.30.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.64.1
h5py                          3.11.0
HeapDict                      1.0.1
hsluv                         5.0.4
huggingface-hub               0.23.3
idna                          3.7
imageio                       2.34.1
imageio-ffmpeg                0.5.1
imagesize                     1.4.1
imgaug                        0.4.0
importlib_metadata            7.1.0
importlib_resources           6.4.0
in-n-out                      0.2.1
intel-openmp                  2021.4.0
ipykernel                     6.29.4
ipython                       8.25.0
ipython_genutils              0.2.0
ipywidgets                    8.1.3
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.4
joblib                        1.4.2
jsonpointer                   2.4
jsonschema                    4.22.0
jsonschema-specifications     2023.12.1
jupyter                       1.0.0
jupyter_client                7.4.9
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter_server                2.14.1
jupyter_server_terminals      0.5.3
jupyterlab_pygments           0.3.0
jupyterlab_widgets            3.0.11
keras                         2.10.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.5
lazy_loader                   0.4
libclang                      18.1.1
llvmlite                      0.42.0
locket                        1.0.0
magicgui                      0.8.3
Markdown                      3.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.8.4
matplotlib-inline             0.1.7
mdurl                         0.1.2
mistune                       3.0.2
mkl                           2021.4.0
mpmath                        1.3.0
msgpack                       1.0.8
msgpack-numpy                 0.4.8
napari                        0.4.18
napari-console                0.0.9
napari-deeplabcut             0.2.1.7
napari-plugin-engine          0.2.0
napari-svg                    0.1.10
natsort                       8.4.0
nb_conda                      2.2.1
nb_conda_kernels              2.5.1
nbclassic                     1.1.0
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest_asyncio                  1.6.0
networkx                      3.3
notebook                      6.5.7
notebook_shim                 0.2.4
npe2                          0.7.5
numba                         0.59.1
numexpr                       2.10.0
numpy                         1.26.4
numpydoc                      1.5.0
oauthlib                      3.2.2
opencv-python                 4.10.0.82
opencv-python-headless        4.10.0.82
opt-einsum                    3.3.0
overrides                     7.7.0
packaging                     24.1
pandas                        2.2.2
pandocfilters                 1.5.0
parso                         0.8.4
partd                         1.4.2
patsy                         0.5.6
pickleshare                   0.7.5
pillow                        10.3.0
PIMS                          0.7
Pint                          0.24
pip                           24.0
pkgutil_resolve_name          1.3.10
platformdirs                  4.2.2
pooch                         1.8.2
prometheus_client             0.20.0
prompt_toolkit                3.0.47
protobuf                      3.19.6
psutil                        5.9.8
psygnal                       0.11.1
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       16.1.0
pyasn1                        0.6.0
pyasn1_modules                0.4.0
pyconify                      0.1.6
pycparser                     2.22
pydantic                      1.10.16
pydantic-compat               0.1.2
Pygments                      2.18.0
PyOpenGL                      3.1.7
pyparsing                     3.1.2
pyproject_hooks               1.1.0
PySide6                       6.4.2
PySide6-Addons                6.4.2
PySide6-Essentials            6.4.2
PySocks                       1.7.1
python-dateutil               2.9.0
python-json-logger            2.0.7
pytz                          2024.1
pywin32                       306
pywinpty                      2.0.13
PyYAML                        6.0.1
pyzmq                         26.0.3
QDarkStyle                    3.1
qtconsole                     5.5.2
QtPy                          2.4.1
referencing                   0.35.1
requests                      2.32.3
requests-oauthlib             2.0.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.1
rpds-py                       0.18.1
rsa                           4.9
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.8
scikit-image                  0.23.2
scikit-learn                  1.5.0
scipy                         1.13.1
Send2Trash                    1.8.3
setuptools                    70.0.0
shapely                       2.0.4
shellingham                   1.5.4
shiboken6                     6.4.2
six                           1.16.0
slicerator                    1.1.0
sniffio                       1.3.1
snowballstemmer               2.2.0
soupsieve                     2.5
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
stack-data                    0.6.2
statsmodels                   0.14.2
superqt                       0.6.7
sympy                         1.12.1
tables                        3.8.0
tabulate                      0.9.0
tbb                           2021.12.0
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.31.0
tensorpack                    0.11
termcolor                     2.4.0
terminado                     0.18.1
tf-slim                       1.1.0
threadpoolctl                 3.5.0
tifffile                      2024.5.22
tinycss2                      1.3.0
tomli                         2.0.1
tomli_w                       1.0.0
toolz                         0.12.1
torch                         2.3.1
tornado                       6.4.1
tqdm                          4.66.4
traitlets                     5.14.3
typer                         0.12.3
types-python-dateutil         2.9.0.20240316
typing_extensions             4.12.2
typing-utils                  0.1.0
tzdata                        2024.1
uri-template                  1.3.0
urllib3                       2.2.1
vispy                         0.12.2
wcwidth                       0.2.13
webcolors                     24.6.0
webencodings                  0.5.1
websocket-client              1.8.0
Werkzeug                      3.0.3
wheel                         0.43.0
widgetsnbextension            4.0.11
win-inet-pton                 1.1.0
wrapt                         1.16.0
zipp                          3.19.2
```

```
(DEEPLABCUT) C:\Users\[...]>napari --info
napari: 0.4.18
Platform: Windows-10-10.0.22631-SP0
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Qt: 6.4.2
PySide6:
NumPy: 1.26.4
SciPy: 1.13.1
Dask: 2024.5.2
VisPy: 0.12.2
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.7
npe2: 0.7.5

OpenGL:
  - GL version:  4.6.0 NVIDIA 551.61
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 3440x1440, scale 1.0

Settings path:
  - C:\Users\[...]\AppData\Local\napari\DEEPLABCUT_f28114985eab6f0639c12958f68f0cbc858df2a1\settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-deeplabcut: 0.2.1.7 (16 contributions)
  - napari-svg: 0.1.10 (2 contributions)
```

**Comment by Mijar007** [comment]
Maybe this helps you. I deactivated the Try-Except part in the plot_trajectories function in plotting.py and received the following error as I tried to generate the videos:

```
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\create_videos.py", line 277, in create_videos
    deeplabcut.plot_trajectories(
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\plotting.py", line 298, in plot_trajectories
    df, filepath, _, suffix = auxiliaryfunctions.load_analyzed_data(
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 784, in load_analyzed_data
    filepath, scorer, suffix = find_analyzed_data(
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 770, in find_analyzed_data
    raise FileNotFoundError(msg)
FileNotFoundError: No filtered data file found in C:\Users\[...]\Desktop\WiggleTest2-MR-2024-06-11\videos for video GOPR0629 and scorer DLC_resnet50_WiggleTest2Jun11shuffle1_10000.
```

**Comment by MMathisLab** [comment]
Ah it's looking for filtered data; we can fix (or you can run filter = true and it would work now). Thanks for bug report!

**Comment by n-poulsen** [comment]
There's indeed a bug with the checkboxes in the GUI, I was able to replicate the issue! Thanks for spotting this, I'll work on a fix!

**Comment by Mijar007** [comment]
Thank you.
Regarding not proper working check boxes: In the 'Evaluate network' tab the 'Compare all bodyparts' checkbox doesn't work and the bodyparts list is always possible.

**Comment by MMathisLab** [comment]
this is solved here, and other very nice upgrades worth considering: https://github.com/DeepLabCut/DeepLabCut/issues/2616
