### ISSUE TITLE
Unicode error on GUI startup: `SyntaxError: invalid or missing encoding declaration for 'C:\\ProgramData\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\pywin32_system32\\pywintypes39.dll'`

### ISSUE THREAD

**Issue by rraghavkaushik** [DeepLabCut/DeepLabCut#2612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

![error_dlc](https://github.com/DeepLabCut/DeepLabCut/assets/136466980/37ed2469-b5bb-4bad-aa23-1885812376d2)

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.3,10

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
(base) C:\Users\BarikLab>conda activate DEEPLABCUT

(DEEPLABCUT) C:\Users\BarikLab>python -m deeplabcut
Loading DLC 2.3.10...
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py", line 25, in <module>
    from deeplabcut.gui.tracklet_toolbox import refine_tracklets
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 18, in <module>
    from deeplabcut.refine_training_dataset.tracklets import TrackletManager
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\refine_training_dataset\__init__.py", line 13, in <module>
    from deeplabcut.refine_training_dataset.tracklets import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py", line 15, in <module>
    from deeplabcut.post_processing import columnwise_spline_interp
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\post_processing\__init__.py", line 21, in <module>
    from deeplabcut.post_processing.analyze_skeleton import analyzeskeleton
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\post_processing\analyze_skeleton.py", line 24, in <module>
    from deeplabcut.utils import auxiliaryfunctions, auxfun_multianimal
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\__init__.py", line 11, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py", line 34, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 31, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 25, in <module>
    from deeplabcut.pose_estimation_tensorflow.predict_videos import *
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 36, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib import inferenceutils, trackingutils
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\trackingutils.py", line 20, in <module>
    from numba import jit
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\__init__.py", line 89, in <module>
    from numba.core.decorators import (cfunc, jit, njit, stencil,
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\stencils\stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\registry.py", line 6, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\dispatcher.py", line 22, in <module>
    from numba.core.caching import NullCache, FunctionCache
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\core\caching.py", line 19, in <module>
    from numba.misc.appdirs import AppDirs
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\numba\misc\appdirs.py", line 507, in <module>
    import win32com.shell
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\win32com\__init__.py", line 8, in <module>
    import pythoncom
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\inspect.py", line 831, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\ProgramData\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\pywin32_system32\\pywintypes39.dll'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
we no longer support 3.9 python, so you will beed to update your python version. Note, 3.9 was sunset for bugs only for some time. 

To upgrade:

`conda install python=3.10`

**Comment by MMathisLab** [comment]
I will close, but please do post back if this does not fix your issue!

**Comment by rraghavkaushik** [comment]
Thank you for taking the time to reply. I will get back to you on Monday.
