### ISSUE TITLE
error with pip: `Collecting tables==3.8.0 (from deeplabcut[apple_mchips,gui]`

### ISSUE THREAD

**Issue by albiangela** [DeepLabCut/DeepLabCut#2615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I was previously successful at creating the environment but now I tested re-installation and ran into a new issue. I installed the latest miniconda, cloned the repo and ran the command to create the DLC environment but I get this error

```bash
Using cached pillow-10.3.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting tables==3.8.0 (from deeplabcut[apple_mchips,gui]->-r /Users/ang/DeepLabCut/conda-environments/condaenv.m4qj1a23.requirements.txt (line 1))
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

Pip subprocess error:
WARNING: deeplabcut 2.3.10 does not provide the extra 'apple-mchips'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library 'lzo2' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library 'lzo' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      performance hint: tables/utilsextension.pxd:20:26: No exception value declared for 'get_native_type' in pxd file.
      Users cimporting this function and calling it without the gil will always require an exception check.
      Suggest adding an explicit exception value.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      def _dump_h5_backtrace():
          cdef object bt = []
      
          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------
      
      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t' (alias of 'herr_t (*)(unsigned int, H5E_error_t *, void *) noexcept nogil'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'e_walk_cb'.
      * Using Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:51:49) [Clang 16.0.6 ]
      * Found cython 3.0.10
      * USE_PKGCONFIG: True
      * Found conda env: ``/opt/miniconda3/envs/DEEPLABCUT_M1``
      * pkg-config header dirs for HDF5: /opt/homebrew/Cellar/hdf5/1.14.3_1/include
      * pkg-config library dirs for HDF5: /opt/homebrew/Cellar/hdf5/1.14.3_1/lib
      * Found HDF5 headers at ``/opt/homebrew/Cellar/hdf5/1.14.3_1/include``, library at ``/opt/homebrew/Cellar/hdf5/1.14.3_1/lib``.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Found bzip2 headers at ``/opt/miniconda3/envs/DEEPLABCUT_M1/include``, library at ``/opt/miniconda3/envs/DEEPLABCUT_M1/lib``.
      * pkg-config header dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.5/include
      * pkg-config library dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.5/lib
      * Found blosc headers at ``/opt/homebrew/Cellar/c-blosc/1.21.5/include``, library at ``/opt/homebrew/Cellar/c-blosc/1.21.5/lib``.
      .. WARNING:: Could not find the blosc runtime.
         The blosc shared library was *not* found in the default library
         paths. In case of runtime problems, please remember to install it.
      * Found blosc2 headers at ``/private/var/folders/j7/1x66rnzj3jz1kqdzrbh167t80000gn/T/pip-build-env-51bmfjh2/overlay/include``, library at ``/private/var/folders/j7/1x66rnzj3jz1kqdzrbh167t80000gn/T/pip-build-env-51bmfjh2/overlay/lib``.
        * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/DEEPLABCUT_M1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/miniconda3/envs/DEEPLABCUT_M1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/miniconda3/envs/DEEPLABCUT_M1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/j7/1x66rnzj3jz1kqdzrbh167t80000gn/T/pip-build-env-51bmfjh2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/j7/1x66rnzj3jz1kqdzrbh167t80000gn/T/pip-build-env-51bmfjh2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/j7/1x66rnzj3jz1kqdzrbh167t80000gn/T/pip-build-env-51bmfjh2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/j7/1x66rnzj3jz1kqdzrbh167t80000gn/T/pip-build-env-51bmfjh2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/j7/1x66rnzj3jz1kqdzrbh167t80000gn/T/pip-build-env-51bmfjh2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed
```

I tried installing another version of pytables (3.7) but still didn't work.

### Operating System

macOS Sonoma 14.5

### DeepLabCut version

DLC 2.3.9

### DeepLabCut mode

multi animal

### Device type

CPU

### Steps To Reproduce

```bash
mkdir -p ~/miniconda3
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init zsh

git clone https://github.com/DeepLabCut/DeepLabCut.git
cd DeepLabCut/conda-environments                      
conda env create -f DEEPLABCUT_M1.yaml
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by watarungurunnn** [comment]
Same here

**Comment by MMathisLab** [comment]
sadly an upstream package issue, right now, you can run:

```bash
conda install -c conda-forge pytables==3.8.0
pip install "deeplabcut[gui,modelzoo,apple_mchips]"
```
