### ISSUE TITLE
`numpy 2.0` causes installation issues

### ISSUE THREAD

**Issue by Mijar007** [DeepLabCut/DeepLabCut#2624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Since the last patch, I can't install DLC 2.3.10 anymore.
The first lines of the message in the prompt are:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
```
Below is the full response.

From my point of view more an information, since I decided to wait for a DLC 3 release.

### Operating System

Win 11

### DeepLabCut version

dlc version 2.3.10

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Modify the last line in DEEPLABCUT.yaml to "deeplabcut[gui,tf]==2.3.10" (Downloaded on the 10th June)
2. Created the environment with anaconda
3. Activated the env and started DLC

### Relevant log output

```shell
>conda list deeplabcut
# packages in environment at C:\ProgramData\anaconda3\envs\DEEPLABCUT:
#
# Name                    Version                   Build  Channel
deeplabcut                2.3.10                   pypi_0    pypi
napari-deeplabcut         0.2.1.7                  pypi_0    pypi

>python -m deeplabcut
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py", line 16, in <module>
    import tensorflow as tf
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py", line 16, in <module>
    import tensorflow as tf
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 24, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\util\structure.py", line 23, in <module>
    from tensorflow.python.data.util import nest
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\util\nest.py", line 36, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\eager\execute.py", line 23, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\dtypes.py", line 29, in <module>
    from tensorflow.python.lib.core import _pywrap_bfloat16
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py", line 16, in <module>
    import tensorflow as tf
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 24, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\util\structure.py", line 23, in <module>
    from tensorflow.python.data.util import nest
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\data\util\nest.py", line 36, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\eager\execute.py", line 23, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\ProgramData\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\framework\dtypes.py", line 34, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by yuanlong-o** [comment]
manually downgrading numpy can help, using `pip install numpy=1.26.4` works for me.

**Comment by n-poulsen** [comment]
Thanks @yuanlong-o! Indeed this seems to be an issue with the newest `numpy` release (it was [released on the 16th of June](https://pypi.org/project/numpy/#history)) - you should be able to run things by just downgrading `numpy`(as @yuanlong-o said, you can simply do so by running `pip install "numpy<2"`).

Let me know if that fixes your issue.

**Comment by Mijar007** [comment]
Thank you for the solution. I added it to the DEEPLABCUT.yaml and DLC 2.3.10 started properly after installation.

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78641150/a-module-that-was-compiled-using-numpy-1-x-cannot-be-run-in-numpy-2-0-0

**Comment by Handique-lab** [comment]
Install your required package without dependency
For me, the command below worked as I am working with OpenCV
**pip install opencv-python --no-deps**

replace with **opencv-python** with the package of your requirement.
Installing packages without dependencies will not install a second copy of Numpy so it might help...

Above all, install an older version of Anaconda, or create a new environment in the same Anaconda version, and try...

**Comment by Ericva** [comment]
> manually downgrading numpy can help, using `pip install numpy=1.26.4` works for me.

thanks a lot~  it helps me~
