### ISSUE TITLE
Cannot update DeepLabCut using miniconda on M1 Mac

### ISSUE THREAD

**Issue by mikeumo** [DeepLabCut/DeepLabCut#2626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I try to update DeepLabCut using miniconda on M1 Mac the process fails. It seems that option [apple_mchips] is absent in the deeplabcut update

### Operating System

macOS Sonoma 14.5

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

 conda env update -f ./conda-environments/DEEPLABCUT_M1.yaml

### Relevant log output

```shell
Pip subprocess error:
WARNING: deeplabcut 2.3.10 does not provide the extra 'apple-mchips'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library 'lzo2' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library 'lzo' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library 'blosc' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      performance hint: tables/utilsextension.pxd:20:26: No exception value declared for 'get_native_type' in pxd file.
      Users cimporting this function and calling it without the gil will always require an exception check.
      Suggest adding an explicit exception value.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      def _dump_h5_backtrace():
          cdef object bt = []
      
          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------
      
      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t' (alias of 'herr_t (*)(unsigned int, H5E_error_t *, void *) noexcept nogil'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'e_walk_cb'.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:55:20)
      * Found cython 3.0.10
      * USE_PKGCONFIG: True
      * Found conda env: ``/opt/miniconda3/envs/DEEPLABCUT_M1``
      * Found HDF5 headers at ``/opt/miniconda3/envs/DEEPLABCUT_M1/include``, library at ``/opt/miniconda3/envs/DEEPLABCUT_M1/lib``.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Found bzip2 headers at ``/opt/miniconda3/envs/DEEPLABCUT_M1/include``, library at ``/opt/miniconda3/envs/DEEPLABCUT_M1/lib``.
      * Could not find blosc headers and library; using internal sources.
      * Found blosc2 headers at ``/private/var/folders/6r/5hnkwsgj0j72z_9v8wnvz4bm0000gq/T/pip-build-env-t2z2a5ys/overlay/include``, library at ``/private/var/folders/6r/5hnkwsgj0j72z_9v8wnvz4bm0000gq/T/pip-build-env-t2z2a5ys/overlay/lib``.
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/miniconda3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/6r/5hnkwsgj0j72z_9v8wnvz4bm0000gq/T/pip-build-env-t2z2a5ys/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/6r/5hnkwsgj0j72z_9v8wnvz4bm0000gq/T/pip-build-env-t2z2a5ys/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/6r/5hnkwsgj0j72z_9v8wnvz4bm0000gq/T/pip-build-env-t2z2a5ys/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/6r/5hnkwsgj0j72z_9v8wnvz4bm0000gq/T/pip-build-env-t2z2a5ys/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/6r/5hnkwsgj0j72z_9v8wnvz4bm0000gq/T/pip-build-env-t2z2a5ys/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed

``


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
It is the same as other issues with the package "tables"; https://github.com/DeepLabCut/DeepLabCut/issues/2615

 we strongly recommend moving to #2613  where this all goes away 🚀

Otherwise, see https://deeplabcut.github.io/DeepLabCut/docs/beginner-guides/beginners-guide.html#let-s-learn-a-bit-and-create-a-deeplabcut-env

Where you use: conda install -c conda-forge pytables==3.8.0

**Comment by mikeumo** [comment]
Yes, sorry for replicate posting

**Comment by MMathisLab** [comment]
Not a worry
