### ISSUE TITLE
An error is reported when the DLC3.0 is started, and the GUI becomes unresponsive for a short time

### ISSUE THREAD

**Issue by Niklaus-v** [DeepLabCut/DeepLabCut#2671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After starting deeplabcut it gets an error and the GUI becomes unresponsive for a few minutes before I can start using it.

### Operating System

win11 64bit

### DeepLabCut version

3.0.0rc2

### DeepLabCut mode

single animal

### Device type

gpu：3080ti

### Steps To Reproduce

After starting deeplabcut it gets an error

### Relevant log output

```shell
QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\http\client.py", line 1448, in connect
    super().connect()
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\http\client.py", line 942, in connect
    self.sock = self._create_connection(
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] The connection attempt failed because the connecting party did not reply correctly after some time or the connected host did not respond.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\window.py", line 359, in <lambda>
    QTimer.singleShot(1000, lambda: _check_for_updates(silent=True))
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\window.py", line 43, in _check_for_updates
    is_latest, latest_version = utils.is_latest_deeplabcut_version()
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\utils.py", line 47, in is_latest_deeplabcut_version
    contents = urllib.request.urlopen(url).read()
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\qhm52\.conda\envs\DEEPLABCUT\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] The connection attempt failed because the connecting party did not reply correctly after some time or the connected host did not respond.>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @Niklaus-v, were you lacking internet connection at the time it happened?

**Comment by Niklaus-v** [comment]
> 嗨，事情发生时您是否缺少互联网连接？

There may be a problem with the network settings. I have solved it now. Thank you.

**Comment by jeylau** [comment]
No worries, thanks for letting us know. I've pushed a fix anyway 😊
