### ISSUE TITLE
DLS3.0-pytorch multi animal mode OS Error: Tracklets are empty for tracklets stitching after video analyzing and tracklets generation

### ISSUE THREAD

**Issue by chz31** [DeepLabCut/DeepLabCut#2698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Dear all, this is a follow-up question for this closed issue: [](https://github.com/DeepLabCut/DeepLabCut/issues/2684)

Under Multi Animal Mode, I ran video analyzing with `scorername = deeplabcut.analyze_videos(config_path, video_paths, videotype='.mp4', auto_track=True)`. I also tried set up `auto_track=False` and used `convert_detections2tracklets` followed by `stitch_tracklets`. Both gave me `OSError: Tracklets are empty `in `~\.conda\envs\deeplabcut3_2\Lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:480`,

Initially, I got the zero division error during video analyzing using DLC3.0 Pytorch from `def calc_similarity_with()` in `trackingutils.py.`. I manually set up `max_dist = 1 ` followed the suggestion [here](https://github.com/DeepLabCut/DeepLabCut/issues/2684) in `def calc_similarity_with()`. The zero division error disappears, but I got an `OSError: Tracklets are empty in stitch.py`. I wonder if 'max_dist' meant something for tracklets creation and refine?

The original thread has been closed, that's why I repost it. Let me know if you need a sample data!

### Operating System

Windows 11

### DeepLabCut version

DLC3.0 pytorch

### DeepLabCut mode

Multi animal

### Device type

Geforce 1070 Max-Q

### Steps To Reproduce

Run deeplabcut.analyze_videos for multi-animal mode in DLC3.0 Pytorch
`scorername = deeplabcut.analyze_videos(config_path, video_paths, videotype='.mp4', auto_track=True)
`
Or:
```
scorername = deeplabcut.analyze_videos(config_path, video_paths, videotype='.mp4', auto_track=False)
deeplabcut.convert_detections2tracklets(config_path, video_paths, overwrite=True)
deeplabcut.stitch_tracklets(config_path, video_paths, videotype='.mp4', shuffle=1, trainingsetindex=0)
```

### Relevant log output

```shell
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  C:\Users\charl\Downloads\dlc_multi2\test_multi-chi-2024-07-23\videos\test_multi.mp4
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[5], line 1
----> 1 scorername = deeplabcut.analyze_videos(config_path, videofile_path, videotype='.mp4')

File ~\.conda\envs\deeplabcut3_2\Lib\site-packages\deeplabcut\compat.py:856, in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, in_random_order, destfolder, batchsize, cropping, TFGPUinference, dynamic, modelprefix, robust_nframes, allow_growth, use_shelve, auto_track, n_tracks, calibrate, identity_only, use_openvino, engine, **torch_kwargs)
    851     if use_shelve:
    852         raise NotImplementedError(
    853             f"The 'use_shelve' option is not yet implemented with {engine}"
    854         )
--> 856     return analyze_videos(
    857         config,
    858         videos=videos,
    859         videotype=videotype,
    860         shuffle=shuffle,
    861         trainingsetindex=trainingsetindex,
    862         save_as_csv=save_as_csv,
    863         destfolder=destfolder,
    864         batchsize=batchsize,
    865         modelprefix=modelprefix,
    866         auto_track=auto_track,
    867         identity_only=identity_only,
    868         overwrite=False,
    869         **torch_kwargs,
    870     )
    872 raise NotImplementedError(f"This function is not implemented for {engine}")

File ~\.conda\envs\deeplabcut3_2\Lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\analyze_videos.py:385, in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, save_as_csv, snapshot_index, detector_snapshot_index, device, destfolder, batchsize, modelprefix, transform, auto_track, identity_only, overwrite)
    374             if auto_track:
    375                 convert_detections2tracklets(
    376                     config=config,
    377                     videos=str(video),
   (...)
    383                     destfolder=str(output_path),
    384                 )
--> 385                 stitch_tracklets(
    386                     config,
    387                     [str(video)],
    388                     videotype,
    389                     shuffle,
    390                     trainingsetindex,
    391                     destfolder=str(output_path),
    392                 )
    394 print(
    395     "The videos are analyzed. Now your research can truly start!\n"
    396     "You can create labeled videos with 'create_labeled_video'.\n"
   (...)
    399     "few representative outlier frames.\n"
    400 )
    402 return dlc_scorer

File ~\.conda\envs\deeplabcut3_2\Lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:1197, in stitch_tracklets(config_path, videos, videotype, shuffle, trainingsetindex, n_tracks, min_length, split_tracklets, prestitch_residuals, max_gap, weight_func, destfolder, modelprefix, track_method, output_name, transformer_checkpoint, save_as_csv)
   1195 pickle_file = dataname.split(".h5")[0] + f"{method}.pickle"
   1196 try:
-> 1197     stitcher = TrackletStitcher.from_pickle(
   1198         pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals
   1199     )
   1200     with_id = any(tracklet.identity != -1 for tracklet in stitcher)
   1201     if with_id and weight_func is None:
   1202         # Add in identity weighing before building the graph

File ~\.conda\envs\deeplabcut3_2\Lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:527, in TrackletStitcher.from_pickle(cls, pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals)
    525 with open(pickle_file, "rb") as file:
    526     tracklets = pickle.load(file)
--> 527 class_ = cls.from_dict_of_dict(
    528     tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
    529 )
    530 class_.filename = pickle_file
    531 return class_

File ~\.conda\envs\deeplabcut3_2\Lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:562, in TrackletStitcher.from_dict_of_dict(cls, dict_of_dict, n_tracks, min_length, split_tracklets, prestitch_residuals)
    560     else:
    561         tracklets.append(Tracklet(data, inds))
--> 562 class_ = cls(
    563     tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
    564 )
    565 class_.header = header
    566 class_.single = single

File ~\.conda\envs\deeplabcut3_2\Lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:480, in TrackletStitcher.__init__(self, tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals)
    477             self.residuals.append(t)
    479 if not len(self.tracklets):
--> 480     raise IOError("Tracklets are empty.")
    482 if prestitch_residuals:
    483     self._prestitch_residuals(5)  # Hard-coded but found to work very well

OSError: Tracklets are empty.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by chz31** [comment]
Just to follow-up, I also tested the `auto_track = False option `for analyze_videos: scorername = deeplabcut.analyze_videos(config_path, video_paths, videotype='.mp4', auto_track=False)

Then manually generate and stitching tracklets using:
deeplabcut.convert_detections2tracklets(config_path, video_paths, overwrite=True)
deeplabcut.stitch_tracklets(config_path, video_paths, videotype='.mp4', shuffle=1, trainingsetindex=0)
It reported the same error: `OSError: Tracklets are empty` even though `convert_detections2tracklets` showed tracklets were created.

**Comment by n-poulsen** [comment]
Hi @chz31! Usually the `OSError: Tracklets are empty.` occurs when the model isn't trained well enough and does not make enough predictions.

Could you run `deeplabcut.create_video_with_all_detections` before tracking (as explained [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#evaluating-your-network-on-videos)) and let me know if the model predictions look good there?

**Comment by chz31** [comment]
@n-poulsen Thank you for your response! 
The `deeplabcut.create_video_with_all_detections` stops at the first video in the folder. It did output a video with labeled body parts and it looked OK by just visually examining it, but it reported `error: db file doesn't exist; use 'c' or 'n' flag to create a new db`. 

I can ask my colleague if I can share the videos I used with you, if you have time to have a quick look at it. Thanks!

```
Creating labeled video for  test_multi
100%|███████████████████████████████████████████████████████████████████████████| 24434/24434 [01:43<00:00, 236.89it/s]
Creating labeled video for  test_multi2
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File ~\.conda\envs\deeplabcut3\Lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:217, in LoadFullMultiAnimalData(dataname)
    216 try:
--> 217     with open(data_file, "rb") as handle:
    218         data = pickle.load(handle)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/charl/Downloads/dlc_multi2/test_multi_vid-cz-2024-08-01/videos/test_multi2DLC_Resnet50_test_multi_vidAug1shuffle1_detector_200_snapshot_200_full.pickle'

During handling of the above exception, another exception occurred:

error                                     Traceback (most recent call last)
Cell In[5], line 1
----> 1 deeplabcut.create_video_with_all_detections(config_path, video_paths, videotype='.mp4')

File ~\.conda\envs\deeplabcut3\Lib\site-packages\deeplabcut\utils\make_labeled_video.py:1106, in create_video_with_all_detections(config, videos, videotype, shuffle, trainingsetindex, displayedbodyparts, cropping, destfolder, modelprefix, confidence_to_alpha)
   1104 print("Creating labeled video for ", video_name)
   1105 h5file = full_pickle.replace("_full.pickle", ".h5")
-> 1106 data, metadata = auxfun_multianimal.LoadFullMultiAnimalData(h5file)
   1107 data = dict(
   1108     data
   1109 )  # Cast to dict (making a copy) so items can safely be popped
   1111 x1, y1 = 0, 0

File ~\.conda\envs\deeplabcut3\Lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:220, in LoadFullMultiAnimalData(dataname)
    218         data = pickle.load(handle)
    219 except (pickle.UnpicklingError, FileNotFoundError):
--> 220     data = shelve.open(data_file, flag="r")
    221 with open(data_file.replace("_full.", "_meta."), "rb") as handle:
    222     metadata = pickle.load(handle)

File ~\.conda\envs\deeplabcut3\Lib\shelve.py:243, in open(filename, flag, protocol, writeback)
    230 def open(filename, flag='c', protocol=None, writeback=False):
    231     """Open a persistent dictionary for reading and writing.
    232
    233     The filename parameter is the base filename for the underlying
   (...)
    240     See the module's __doc__ string for an overview of the interface.
    241     """
--> 243     return DbfilenameShelf(filename, flag, protocol, writeback)

File ~\.conda\envs\deeplabcut3\Lib\shelve.py:227, in DbfilenameShelf.__init__(self, filename, flag, protocol, writeback)
    225 def __init__(self, filename, flag='c', protocol=None, writeback=False):
    226     import dbm
--> 227     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)

File ~\.conda\envs\deeplabcut3\Lib\dbm\__init__.py:85, in open(file, flag, mode)
     83         mod = _defaultmod
     84     else:
---> 85         raise error[0]("db file doesn't exist; "
     86                        "use 'c' or 'n' flag to create a new db")
     87 elif result == "":
     88     # db type cannot be determined
     89     raise error[0]("db type could not be determined")

error: db file doesn't exist; use 'c' or 'n' flag to create a new db
```

**Comment by n-poulsen** [comment]
The error actually comes from higher up: `FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/charl/Downloads/dlc_multi2/test_multi_vid-cz-2024-08-01/videos/test_multi2DLC_Resnet50_test_multi_vidAug1shuffle1_detector_200_snapshot_200_full.pickle'` - so it looks like the file containing model predictions isn't there.

Could you check if you have any other files in that folder?

**Comment by chz31** [comment]
> The error actually comes from higher up: `FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/charl/Downloads/dlc_multi2/test_multi_vid-cz-2024-08-01/videos/test_multi2DLC_Resnet50_test_multi_vidAug1shuffle1_detector_200_snapshot_200_full.pickle'` - so it looks like the file containing model predictions isn't there.
> 
> Could you check if you have any other files in that folder?

Sorry for the late response. I used analyzed three videos "test_multi.mp4", "test_multi2.mp4", "test)multi3.mp4". Analyzing videos and creating videos with detections all stopped after generating a labeled video and pickle files for the first video "test_multi.mp4". The above file name has "test_multi2" in it, thus it is for the second video. 

However, if I just analyzed the first video, the same error was still reported.

**Comment by chz31** [comment]
> The error actually comes from higher up: `FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/charl/Downloads/dlc_multi2/test_multi_vid-cz-2024-08-01/videos/test_multi2DLC_Resnet50_test_multi_vidAug1shuffle1_detector_200_snapshot_200_full.pickle'` - so it looks like the file containing model predictions isn't there.
> 
> Could you check if you have any other files in that folder?

Also here is the [project folder](https://drive.google.com/file/d/1KO5NWnoQKhYOyK8n1oT78F_OU7cK7x2l/view?usp=sharing). Could you please have a look at it if you have time? Thanks!

**Comment by Chap5732** [comment]
hi，I just had the same error as you did. 

```
(dlc-oppa) [oppa@n09 code]$ python analyze_videos.py 
Loading DLC 3.0.0rc2...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Analyzing single video file: /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/videos/mixvideos.mp4 with shuffle: 7
Analyzing videos with /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle7/train/snapshot-200.pt
  -> Using detector /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle7/train/snapshot-detector-250.pt
Starting to analyze /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/videos/mixvideos.mp4
Video metadata: 
  Overall # of frames:    6595
  Duration of video [s]:  219.83
  fps:                    30.0
  resolution:             w=3840, h=2160

Running Detector
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6595/6595 [13:53<00:00,  7.91it/s]
Running Pose Prediction
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6595/6595 [17:08<00:00,  6.41it/s]
Saving results in /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/videos/mixvideosDLC_TopDownResnet50_oppamousetrackerAug23shuffle7_detector_250_snapshot_200.h5 and /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/videos/mixvideosDLC_TopDownResnet50_oppamousetrackerAug23shuffle7_detector_250_snapshot_200_full.pickle
Processing...  /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/videos/mixvideos.mp4
Loading From None/mixvideosDLC_TopDownResnet50_oppamousetrackerAug23shuffle7_detector_250_snapshot_200.h5
Traceback (most recent call last):
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 217, in LoadFullMultiAnimalData
    with open(data_file, "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'None/mixvideosDLC_TopDownResnet50_oppamousetrackerAug23shuffle7_detector_250_snapshot_200_full.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 39, in <module>
    main()
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 36, in main
    analyze_videos_in_folder_or_file(config_path, input_path, shuffle)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 23, in analyze_videos_in_folder_or_file
    deeplabcut.analyze_videos(config_path, video_files, save_as_csv=True, batchsize=64, shuffle=shuffle)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 851, in analyze_videos
    return analyze_videos(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py", line 375, in analyze_videos
    convert_detections2tracklets(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py", line 123, in convert_detections2tracklets
    data, metadata = auxfun_multianimal.LoadFullMultiAnimalData(str(data_filename))
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 220, in LoadFullMultiAnimalData
    data = shelve.open(data_file, flag="r")
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/dbm/__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db
```

Did you yet solve the problem?

**Comment by n-poulsen** [comment]
@Chap5732 in your case, the issue comes from 

```
FileNotFoundError: [Errno 2] No such file or directory: 'None/mixvideosDLC_TopDownResnet50_oppamousetrackerAug23shuffle7_detector_250_snapshot_200_full.pickle'
```

So it seems the path to the video is messed up somehow (there should not be a None there)
