### ISSUE TITLE
Missing dependency `fbgemm.dll`

### ISSUE THREAD

**Issue by huxiaoyi520** [DeepLabCut/DeepLabCut#2711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

python -m deeplabcut
Loading DLC 3.0.0rc4...
Traceback (most recent call last):
  File "D:\anaconda\envs\DEEPLABCUT\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\anaconda\envs\DEEPLABCUT\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\anaconda\envs\DEEPLABCUT\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py", line 61, in <module>
    from deeplabcut.modelzoo.video_inference import video_inference_superanimal
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\modelzoo\video_inference.py", line 23, in <module>
    from deeplabcut.pose_estimation_pytorch.modelzoo.train_from_coco import adaptation_train
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\__init__.py", line 11, in <module>
    from deeplabcut.pose_estimation_pytorch.apis import (
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_pytorch.apis.analyze_images import (
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\analyze_images.py", line 27, in <module>
    from deeplabcut.pose_estimation_pytorch.apis.utils import (
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\utils.py", line 23, in <module>
    from deeplabcut.pose_estimation_pytorch.data.dataset import PoseDatasetParameters
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\data\__init__.py", line 11, in <module>
    from deeplabcut.pose_estimation_pytorch.data.base import Loader
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\data\base.py", line 20, in <module>
    from deeplabcut.pose_estimation_pytorch.data.dataset import (
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\data\dataset.py", line 18, in <module>
    from torch.utils.data import Dataset
  File "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\anaconda\envs\DEEPLABCUT\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### Operating System

operating system   window

### DeepLabCut version

dlc version DLC 3.0.0rc4...

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by huxiaoyi520** [comment]
https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/15这个网址中的回答可以解决这个问题。

in case if you dont want to download visual studio. [https://www.dllme.com/dll/files/libomp140_x86_64?sort=upload&arch=0x8664 1.7k](https://www.dllme.com/dll/files/libomp140_x86_64?sort=upload&arch=0x8664) you can just download this dll and place it in windows/system32 directory. it works as well too

我是下载了这个并且复制到windows/system32文件夹中，然后解决了这个问题

**Comment by ludo67100** [comment]
see this comment to solve the issue

https://github.com/DeepLabCut/DeepLabCut/issues/2704#issuecomment-2271653025

**Comment by AlexEMG** [comment]
Thanks @ludo67100!

**Comment by Kevin-spark** [comment]
I tried this method, and it works. https://stackoverflow.com/a/78838829/27040928

**Comment by austin2118ace** [comment]
Sorry to reopen this, but here is a direct solution from the PyTorch developers as well.
Located in this thread https://github.com/pytorch/pytorch/issues/131662 they provide a link to manually install a release candidate for PyTorch 2.4.1
However, they estimated that this RC will be released on the 4th. So, for anyone like me trying to install DLC today, here is the install commands for the RC version of PyTorch.

First uninstall pytorch `pip uninstall torch torchvision torchaudio`

Then (direct from above thread):

```
CPU:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cpu

CUDA:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu118
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu121
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu124
```
