### ISSUE TITLE
Issues with Inconsistent Number of Predicted and Ground Truth Individuals During Evaluation in Multi-Animal Setup

### ISSUE THREAD

**Issue by Chap5732** [DeepLabCut/DeepLabCut#2727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using DeepLabCut for multi-animal (multi-mouse) training , the following error was encountered: ValueError: Must have the same number of GT and predicted individuals, found pred_kpts=(0, 6, 5) and gt_kpts=(10, 6, 3)

### Operating System

operating system

Linux

### DeepLabCut version

dlc version

3.0.0.rc2

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

My training dataset consists of 338 images with 1 to 10 mice, 6 bodyparts were annotated. I successfully created the training shuffle and then run the train_network function :

`    deeplabcut.train_network(config_path,
                             shuffle=shuffle,
                             device="cuda",
                             net_type=net_type,
                             detector_batch_size=8,
                             batch_size=8,
                             freeze_bn_stats=False)`
    net_type = "hrnet_w18"
    shuffle = 4
Then I encoutered error as ValueError: Must have the same number of GT and predicted individuals, found pred_kpts=(0, 6, 5) and gt_kpts=(10, 6, 3) indicating the number of mice predicted was not alligned with the ground truth number of mice I suppose?  

### Relevant log output

```shell
Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using custom collate function: {'type': 'ResizeFromDataSizeCollate', 'min_scale': 0.4, 'max_scale': 1.0, 'min_short_side': 128, 'max_short_side': 1152, 'multiple_of': 32, 'to_square': False}
Using 338 images and 38 for testing

Starting pose model training...
--------------------------------------------------
Loading DLC 3.0.0rc2...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Training network...
Training for epoch 1 done, starting evaluation
Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/training.py", line 22, in <module>
    train_network(project_name, net_type, shuffle)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/training.py", line 9, in train_network
    deeplabcut.train_network(config_path,
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 245, in train_network
    return train_network(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 336, in train_network
    train(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 189, in train
    runner.fit(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 181, in fit
    valid_loss = self._epoch(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 236, in _epoch
    perf_metrics = self._compute_epoch_metrics()
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 365, in _compute_epoch_metrics
    poses = pair_predicted_individuals_with_gt(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/metrics/scoring.py", line 391, in pair_predicted_individuals_with_gt
    match_individuals = rmse_match_prediction_to_gt(pose, ground_truth[image])
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/post_processing/match_predictions_to_gt.py", line 52, in rmse_match_prediction_to_gt
    raise ValueError(
ValueError: Must have the same number of GT and predicted individuals, found pred_kpts=(0, 6, 5) and gt_kpts=(10, 6, 3)
```

### Anything else?

Here is my pytorch_config information:

data:
  colormode: RGB
  inference:
    normalize_images: true
    auto_padding:
      pad_width_divisor: 32
      pad_height_divisor: 32
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling:
      - 1.0
      - 1.0
      translation: 0
    collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1152
      multiple_of: 32
      to_square: false
    covering: false
    gaussian_noise: 12.75
    hist_eq: false
    motion_blur: false
    normalize_images: true
device: auto
metadata:
  project_path: /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23
  pose_config_path: 
    /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle4/train/pose_cfg.yaml
  bodyparts:
  - nose
  - left_ear
  - right_ear
  - mid_back
  - mouse_center
  - tail1
  unique_bodyparts: []
  individuals:
  - individual1
  - individual2
  - individual3
  - individual4
  - individual5
  - individual6
  - individual7
  - individual8
  - individual9
  - individual10
  with_identity: false
method: bu
model:
  backbone:
    type: HRNet
    model_name: hrnet_w18
    freeze_bn_stats: false
    freeze_bn_weights: false
    interpolate_branches: false
    increased_channel_count: false
  backbone_output_channels: 18
  heads:
    bodypart:
      type: DLCRNetHead
      weight_init: normal
      predictor:
        type: PartAffinityFieldPredictor
        num_animals: 10
        num_multibodyparts: 6
        num_uniquebodyparts: 0
        nms_radius: 5
        sigma: 1.0
        locref_stdev: 7.2801
        min_affinity: 0.05
        graph: &id001
        - - 0
          - 1
        - - 0
          - 2
        - - 0
          - 3
        - - 0
          - 4
        - - 0
          - 5
        - - 1
          - 2
        - - 1
          - 3
        - - 1
          - 4
        - - 1
          - 5
        - - 2
          - 3
        - - 2
          - 4
        - - 2
          - 5
        - - 3
          - 4
        - - 3
          - 5
        - - 4
          - 5
        edges_to_keep:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        apply_sigmoid: false
        clip_scores: true
      target_generator:
        type: SequentialGenerator
        generators:
        - type: HeatmapGaussianGenerator
          num_heatmaps: 6
          pos_dist_thresh: 17
          heatmap_mode: KEYPOINT
          generate_locref: true
          locref_std: 7.2801
        - type: PartAffinityFieldGenerator
          graph: *id001
          width: 20
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
        paf:
          type: WeightedHuberCriterion
          weight: 0.1
      heatmap_config:
        channels:
        - 18
        - 6
        kernel_size:
        - 3
        strides:
        - 2
      locref_config:
        channels:
        - 18
        - 12
        kernel_size:
        - 3
        strides:
        - 2
      paf_config:
        channels:
        - 18
        - 30
        kernel_size:
        - 3
        strides:
        - 2
      num_stages: 5
net_type: hrnet_w18
runner:
  type: PoseTrainingRunner
  gpus:
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 1
  optimizer:
    type: AdamW
    params:
      lr: 0.0001
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 1e-05
      - - 1e-06
      milestones:
      - 160
      - 190
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: false
train_settings:
  batch_size: 8
  dataloader_workers: 8
  dataloader_pin_memory: true
  display_iters: 500
  epochs: 200
  seed: 42
freeze_bn_stats: false

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Chap5732** [comment]
ps: I succesfully trained a top_down_resnet_50 and top_down_resnet_101 model on my data. But it didnt work in the case of hrnetw18 hrnetw32 and resnet50 that I for now have tried to train on. Is it the issue with bu model?

When I try resnet50 I got error as follows:
```
Training network...
Training for epoch 1 done, starting evaluation
/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/post_processing/match_predictions_to_gt.py:73: RuntimeWarning: overflow encountered in square
  d = (gt_idv[mask, :2] - pred_idv[mask, :2]) ** 2
Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/training.py", line 22, in <module>
    train_network(project_name, net_type, shuffle)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/training.py", line 9, in train_network
    deeplabcut.train_network(config_path,
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 245, in train_network
    return train_network(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 336, in train_network
    train(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 189, in train
    runner.fit(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 181, in fit
    valid_loss = self._epoch(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 236, in _epoch
    perf_metrics = self._compute_epoch_metrics()
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 365, in _compute_epoch_metrics
    poses = pair_predicted_individuals_with_gt(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/metrics/scoring.py", line 391, in pair_predicted_individuals_with_gt
    match_individuals = rmse_match_prediction_to_gt(pose, ground_truth[image])
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/post_processing/match_predictions_to_gt.py", line 76, in rmse_match_prediction_to_gt
    _, col_ind = linear_sum_assignment(distance_matrix)  # len == len(valid_gt_indices)
ValueError: cost matrix is infeasible
```

**Comment by n-poulsen** [comment]
Hi @Chap5732 - this should have already been fixed - could you please update your version of DeepLabCut in your conda environment with:

```
pip install --upgrade "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc"
```

and let me know if the issue persists?

**Comment by Chap5732** [comment]
The error's gone after the upgrade. Thank you @n-poulsen !
