### ISSUE TITLE
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db

### ISSUE THREAD

**Issue by Chap5732** [DeepLabCut/DeepLabCut#2730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I want to analyze my videos with the model I trained and I encountered such error:
```
Loading DLC 3.0.0rc2...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Analyzing all videos in folder: /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped with shuffle: 11
Analyzing videos with /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle11/train/snapshot-200.pt
  -> Using detector /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle11/train/snapshot-detector-250.pt
Starting to analyze /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO1cropped.mp4
Video metadata: 
  Overall # of frames:    138
  Duration of video [s]:  4.60
  fps:                    30.0
  resolution:             w=1742, h=1672

Running Detector
100%|████████████████████████████████████████████████████████████████████| 138/138 [00:08<00:00, 16.32it/s]
Running Pose Prediction
100%|████████████████████████████████████████████████████████████████████| 138/138 [00:53<00:00,  2.57it/s]
Saving results in /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO1croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200.h5 and /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO1croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200_full.pickle
Processing...  /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO1cropped.mp4
Loading From None/DEMO1croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200.h5
Traceback (most recent call last):
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 217, in LoadFullMultiAnimalData
    with open(data_file, "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'None/DEMO1croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200_full.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 39, in <module>
    main()
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 36, in main
    analyze_videos_in_folder_or_file(config_path, input_path, shuffle)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 23, in analyze_videos_in_folder_or_file
    deeplabcut.analyze_videos(config_path, video_files, save_as_csv=True, batchsize=64, shuffle=shuffle)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 851, in analyze_videos
    return analyze_videos(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py", line 375, in analyze_videos
    convert_detections2tracklets(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py", line 123, in convert_detections2tracklets
    data, metadata = auxfun_multianimal.LoadFullMultiAnimalData(str(data_filename))
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 220, in LoadFullMultiAnimalData
    data = shelve.open(data_file, flag="r")
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/dbm/__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db
```

It seems that it neglect the .h5 file that was output in the videos folder and automatically genearate an empty folder "None" in my code folder and try to seek the .h5 file in it.

### Operating System

operating system

Centos Linux

### DeepLabCut version

dlc version

3.0.0.rc2

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Chap5732** [comment]
hi, just a quick update. I try to update deeplabcut to 3.0.0.rc3 and try the same analysis code for the same shuffle and the error that was output changed.
```
Loading DLC 3.0.0rc3...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Analyzing all videos in folder: /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped with shuffle: 11
Analyzing videos with /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle11/train/snapshot-200.pt
  -> Using detector /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle11/train/snapshot-detector-250.pt
Video /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO1cropped.mp4 already analyzed at /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO1croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200_full.pickle!
Starting to analyze /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO3cropped.mp4
Video metadata: 
  Overall # of frames:    335
  Duration of video [s]:  11.17
  fps:                    30.0
  resolution:             w=1718, h=1718

Running Detector
100%|████████████████████████████████████████████████████████████████████| 335/335 [00:21<00:00, 15.74it/s]
Running Pose Prediction
100%|████████████████████████████████████████████████████████████████████| 335/335 [02:09<00:00,  2.58it/s]
Saving results in /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO3croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200.h5 and /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO3croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200_full.pickle
Processing...  /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO3cropped.mp4
Loading From /ssd01/user_acc_data/oppa/deeplabcut/videos/20240902/MouseBehaviorDEMO/Approach/cropped/DEMO3croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200.h5
147it [00:03, 37.14it/s]
Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 39, in <module>
    main()
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 36, in main
    analyze_videos_in_folder_or_file(config_path, input_path, shuffle)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 23, in analyze_videos_in_folder_or_file
    deeplabcut.analyze_videos(config_path, video_files, save_as_csv=True, batchsize=64, shuffle=shuffle)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 856, in analyze_videos
    return analyze_videos(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py", line 375, in analyze_videos
    convert_detections2tracklets(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py", line 233, in convert_detections2tracklets
    trackers = mot_tracker.track(xy)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/core/trackingutils.py", line 460, in track
    cost = el.calc_similarity_with(el_track)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/core/trackingutils.py", line 118, in calc_similarity_with
    cost1 = 1 - min(dist / max_dist, 1)
ZeroDivisionError: float division by zero
```

**Comment by n-poulsen** [comment]
@Chap5732 in the first message you posted, the error actually occurs higher up:

```
FileNotFoundError: [Errno 2] No such file or directory: 'None/DEMO1croppedDLC_TopDownHrnetW48_oppamousetrackerAug23shuffle11_detector_250_snapshot_200_full.pickle'
```

As this was fixed, your video was likely correctly analyzed, and the prediction data saved. For the second error, it was also recently fixed and you should also be able to solve it by installing the most recent version, as mentioned in #2727. Let me know if upgrading fixes your issue.

**Comment by Chap5732** [comment]
Yes! The upgrade solved the problem.
