### ISSUE TITLE
 I save the labled frames,but  .h5  file can't  be generated.

### ISSUE THREAD

**Issue by LiuXin-Chern** [DeepLabCut/DeepLabCut#275]
Using:Windows10,with PyCharm Env,and DeepLabCut2.0.5.1

Frames were selected.
You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\io\pytables.py", line 445, in __init__
    import tables  # noqa
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\tables\__init__.py", line 131, in <module>
    from .file import File, open_file, copy_file
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\tables\file.py", line 35, in <module>
    from . import hdf5extension
ImportError: DLL load failed: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 567, in saveDataSet
    self.dataFrame.to_hdf(os.path.join(self.dir,"CollectedData_" + self.scorer + '.h5'),'df_with_missing',format='table', mode='w')
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\core\generic.py", line 1471, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\io\pytables.py", line 280, in to_hdf
    complib=complib) as store:
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\io\pytables.py", line 448, in __init__
    'importing'.format(ex=str(ex)))
ImportError: HDFStore requires PyTables, "DLL load failed: 找不到指定的程序。" problem importing
You can now check the labels, using 'check_labels' before proceeding. Then, you can use the function 'create_training_dataset' to create the training dataset.
Creating images with labels by LX.
Attention: D:\Deeplabcut\xingong-LX-2019-05-03\labeled-data\mouse does not appear to have labeled data!
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
Traceback (most recent call last):
  File "D:/Deeplabcut/dlc.py", line 10, in <module>
    deeplabcut.create_training_dataset(path_config_file)
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 439, in create_training_dataset
    Data = merge_annotateddatasets(cfg,project_path,Path(os.path.join(project_path,trainingsetfolder)),windows2linux)
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 392, in merge_annotateddatasets
    AnnotationData.to_hdf(filename+'.h5', key='df_with_missing', mode='w')
AttributeError: 'NoneType' object has no attribute 'to_hdf'
D:\Deeplabcut\xingong-LX-2019-05-03\training-datasets\iteration-0\UnaugmentedDataSet_xingongMay3  already exists!
D:\Deeplabcut\xingong-LX-2019-05-03\labeled-data\mouse/CollectedData_LX.h5  not found (perhaps not annotated)
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['mouse']
D:\Deeplabcut\xingong-LX-2019-05-03\labeled-data\mouse\CollectedData_LX.h5  not found (perhaps not annotated)
No data was found!

This is my code:
import deeplabcut
task='run'
experimenter='Lei'
video='D:\Deeplabcut\mousedemo\\video\\mouse.avi'
path_config_file=deeplabcut.create_new_project(task,experimenter,video, working_directory='D:\\Deeplabcut',copy_videos=True)
deeplabcut.extract_frames(path_config_file,'automatic','uniform',crop=True)
deeplabcut.label_frames(path_config_file)
deeplabcut.check_labels(path_config_file)
deeplabcut.create_training_dataset(path_config_file)
deeplabcut.train_network(path_config_file)
deeplabcut.evaluate_network(path_config_file)
videofile_path ='D:\Deeplabcut\\video\mouse.avi'
deeplabcut.analyze_videos(path_config_file,videofile_path)
deeplabcut.create_labeled_video(path_config_file,videofile_path)
deeplabcut.plot_trajectories(path_config_file,videofile_path)

Look forward to your assistance.

**Comment by MMathisLab** [comment]
Hello, seems related to issues #255 and #210 (and here: https://forum.image.sc/t/how-can-i-solve-this-problem-importerror-hdfstore-requires-pytables/22555) Namely, seems your installation of pytables is not correct. I recommend using our provided environments here: https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by LiuXin-Chern** [comment]
Thanks for the quick reply!
**Question 1**
when I create a new project:
path_config_file=deeplabcut.create_new_project(task,experimenter,video, working_directory='D:\Deeplabcut',copy_videos=True)
the variable "path_config_file"={NoneType}none, but the config.file will be generated.If I run the code again,the error is:
"D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\python.exe" G:/untitled3/dlc.py
Project "D:\Deeplabcut\xg-Lx-2019-05-04" already exists!
Traceback (most recent call last):
  File "G:/untitled3/dlc.py", line 7, in <module>
    deeplabcut.extract_frames(path_config_file,'automatic','uniform',crop=True)
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py", line 98, in extract_frames
    config_file = Path(config).resolve()
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\pathlib.py", line 979, in __new__
    self = cls._from_parts(args, init=False)
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\pathlib.py", line 654, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\pathlib.py", line 638, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
I add a line code:path_config_file='D:\Deeplabcut\……\config.file',then I can go on.
Why config.file can't be assigned to path_config_file? Can code be run multiple times?
**Question2**
when I use spyder to run the code,it will appear an error :
An error ocurred while starting the kernel
Traceback (most recent call last):
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\ipykernel\kernelapp.py", line 15, in 
from tornado import ioloop
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\tornado\ioloop.py", line 53, in 
from tornado.util import Configurable, TimeoutError, import_object
ImportError: cannot import name 'TimeoutError'
Traceback (most recent call last):
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\ipykernel\kernelapp.py", line 15, in 
from tornado import ioloop
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\tornado\ioloop.py", line 53, in 
from tornado.util import Configurable, TimeoutError, import_object
ImportError: cannot import name 'TimeoutError'
Traceback (most recent call last):
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\ipykernel\kernelapp.py", line 15, in 
from tornado import ioloop
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\tornado\ioloop.py", line 53, in 
from tornado.util import Configurable, TimeoutError, import_object
ImportError: cannot import name 'TimeoutError'
Traceback (most recent call last):
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\ipykernel\kernelapp.py", line 15, in 
from tornado import ioloop
File "D:\Program Files\Anaconda3\envs\lei\lib\site‑packages\tornado\ioloop.py", line 53, in 
from tornado.util import Configurable, TimeoutError, import_object
ImportError: cannot import name 'TimeoutError'
**Question3**
I have reinstalled tables==3.5.1,but I also can't generate .h5 file.The error is:
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\io\pytables.py", line 445, in __init__
    import tables  # noqa
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\tables\__init__.py", line 131, in <module>
    from .file import File, open_file, copy_file
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\tables\file.py", line 35, in <module>
    from . import hdf5extension
ImportError: DLL load failed: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 567, in saveDataSet
    self.dataFrame.to_hdf(os.path.join(self.dir,"CollectedData_" + self.scorer + '.h5'),'df_with_missing',format='table', mode='w')
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\core\generic.py", line 1471, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\io\pytables.py", line 280, in to_hdf
    complib=complib) as store:
  File "D:\Program Files\Anaconda3\envs\lei\envs\py36-pytorch\lib\site-packages\pandas\io\pytables.py", line 448, in __init__
    'importing'.format(ex=str(ex)))
ImportError: HDFStore requires PyTables, "DLL load failed: 找不到指定的程序。" problem importing
Is it because I did not use anconda environment ?

**Comment by MMathisLab** [comment]
**Question 1:** correct, you cannot run the same code again as it is trying to create a new project again. If you want to set a variable, just simply type: 
```
config_path = r'D:\Deeplabcut\xg-Lx-2019-05-04\config.yaml' 
```
--> please follow the formatting guide here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#configure-the-project

**Question2:** seems your kernel died, but doesn't seem related to DLC? I would recommend just using the supplied env and use ipython to run the code. 

**Question3:** Yes, you need to use conda to install pytables, not pip. The easiest is to just use our anaconda environment, not your pytorch environment (py36-pytorch): https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by LiuXin-Chern** [comment]
I want to make a 3D reconstruction which is demonstratede in the README.md(the cheeath),but I don't find the code in the demo-code.How can I realize 3d reconstruction?
Thank you very much and look forward to your reply.

**Comment by MMathisLab** [comment]
We will be releasing integrated code when the paper comes out in a few weeks, but otherwise check out: https://github.com/MMathisLab/3D-DeepLabCut-Cheetah/blob/master/README.md
