### ISSUE TITLE
Changing batch size causes an error: `KeypointAwareCrop`

### ISSUE THREAD

**Issue by vonaviv** [DeepLabCut/DeepLabCut#2769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I use DLC with PyTorch engine and when I set the batch size for training in `pytorch_config.yaml` to anything except of 1 I get the following error message:

```
Loading DLC 3.0.0rc5...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "/user/vladyslav.ivanov01/u11170/dlc/ExR_18cam-smg-2024-10-25/scripts/train.py", line 13, in <module>
    deeplabcut.train_network(config_path, max_snapshots_to_keep=20, shuffle=shuffle)
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/compat.py", line 245, in train_network
    return train_network(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 338, in train_network
    train(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 186, in train
    runner.fit(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 166, in fit
    train_loss = self._epoch(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 216, in _epoch
    for i, batch in enumerate(loader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/data/dataset.py", line 156, in __getitem__
    transformed = self.apply_transform_all_keypoints(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/data/dataset.py", line 334, in apply_transform_all_keypoints
    transformed = apply_transform(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/data/utils.py", line 492, in apply_transform
    transformed = _apply_transform(
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/data/utils.py", line 546, in _apply_transform
    transformed = transform(
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 222, in __call__
    data = t(**data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/transforms_interface.py", line 114, in __call__
    params_dependent_on_targets = self.get_params_dependent_on_targets(targets_as_params)
  File "/usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_pytorch/data/transforms.py", line 289, in get_params_dependent_on_targets
    kpts = kpts[~np.isnan(kpts).all(axis=1)]
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py", line 64, in _all
    return umr_all(a, axis, dtype, out, keepdims)
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1

```

### Operating System

Rocky Linux 8.8

### DeepLabCut version

3.0.0rc5

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @vonaviv! Could you please let me know which package versions you have installed (you can just report the output of `pip list`), as well as the `pytorch_config.yaml` file that you use?

**Comment by vonaviv** [comment]
> Hi @vonaviv! Could you please let me know which package versions you have installed (you can just report the output of `pip list`), as well as the `pytorch_config.yaml` file that you use?

# Pip list
```
Package                  Version
------------------------ ------------
albumentations           1.4.3
blosc2                   2.0.0
certifi                  2024.8.30
charset-normalizer       3.4.0
click                    8.1.7
contourpy                1.3.0
cycler                   0.12.1
Cython                   3.0.11
deeplabcut               3.0.0rc5
dlclibrary               0.0.7
docker-pycreds           0.4.0
einops                   0.8.0
filelock                 3.13.1
filterpy                 1.4.5
fonttools                4.54.1
fsspec                   2024.2.0
gitdb                    4.0.11
GitPython                3.1.43
huggingface-hub          0.26.1
idna                     3.10
imageio                  2.36.0
imageio-ffmpeg           0.5.1
imgaug                   0.4.0
Jinja2                   3.1.3
joblib                   1.4.2
kiwisolver               1.4.7
lazy_loader              0.4
llvmlite                 0.43.0
MarkupSafe               2.1.5
matplotlib               3.8.4
mpmath                   1.3.0
msgpack                  1.1.0
networkx                 3.2.1
numba                    0.60.0
numexpr                  2.10.1
numpy                    1.26.3
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.1.105
nvidia-nvtx-cu12         12.1.105
opencv-python            4.10.0.84
opencv-python-headless   4.10.0.84
packaging                24.1
pandas                   2.2.3
patsy                    0.5.6
pillow                   10.2.0
pip                      22.0.2
platformdirs             4.3.6
protobuf                 5.28.3
psutil                   6.1.0
py-cpuinfo               9.0.0
pycocotools              2.0.8
pyparsing                3.2.0
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
requests                 2.32.3
ruamel.yaml              0.18.6
ruamel.yaml.clib         0.2.12
safetensors              0.4.5
scikit-image             0.24.0
scikit-learn             1.5.2
scipy                    1.10.1
sentry-sdk               2.17.0
setproctitle             1.3.3
setuptools               59.6.0
shapely                  2.0.6
six                      1.16.0
smmap                    5.0.1
statsmodels              0.14.4
sympy                    1.13.1
tables                   3.8.0
threadpoolctl            3.5.0
tifffile                 2024.9.20
timm                     1.0.11
torch                    2.5.0+cu121
torchaudio               2.5.0+cu121
torchvision              0.20.0+cu121
tqdm                     4.66.5
triton                   3.1.0
typing_extensions        4.9.0
tzdata                   2024.2
urllib3                  2.2.3
wandb                    0.18.5
wheel                    0.37.1
```

# pytorch_config.yaml
```
data:
  colormode: RGB
  inference:
    normalize_images: true
    auto_padding:
      pad_width_divisor: 32
      pad_height_divisor: 32
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling:
      - 1.0
      - 1.0
      translation: 0
    collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1152
      multiple_of: 32
      to_square: false
    covering: false
    gaussian_noise: 12.75
    hist_eq: false
    motion_blur: false
    normalize_images: true
device: cuda
metadata:
  project_path: /user/.../ExR_18cam-smg-2024-10-25
  pose_config_path: 
    /user/.../pytorch_config.yaml
  bodyparts:
  - nose
  - neck
  - S_tail
  - E_tail
  - L_eye
  - R_eye
  - L_ear
  - R_ear
  - L_shoulder
  - R_shoulder
  - L_elbow
  - R_elbow
  - L_wrist
  - R_wrist
  - L_hip
  - R_hip
  - L_knee
  - R_knee
  - L_ankle
  - R_ankle
  unique_bodyparts: []
  individuals:
  - animal
  with_identity:
method: bu
model:
  backbone:
    type: HRNet
    model_name: hrnet_w48
    freeze_bn_stats: false
    freeze_bn_weights: false
    interpolate_branches: true
    increased_channel_count: false
  backbone_output_channels: 720
  heads:
    bodypart:
      type: DEKRHead
      weight_init: dekr
      target_generator:
        type: DEKRGenerator
        num_joints: 20
        pos_dist_thresh: 17
        bg_weight: 0.1
      criterion:
        heatmap:
          type: DEKRHeatmapLoss
          weight: 1
        offset:
          type: DEKROffsetLoss
          weight: 0.03
      predictor:
        type: DEKRPredictor
        apply_sigmoid: false
        use_heatmap: false
        clip_scores: true
        num_animals: 1
        keypoint_score_type: combined
        max_absorb_distance: 75
      heatmap_config:
        channels:
        - 720
        - 64
        - 21
        num_blocks: 1
        dilation_rate: 1
        final_conv_kernel: 1
      offset_config:
        channels:
        - 720
        - 300
        - 20
        num_offset_per_kpt: 15
        num_blocks: 2
        dilation_rate: 1
        final_conv_kernel: 1
net_type: dekr_w48
runner:
  type: PoseTrainingRunner
  gpus:
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 0.0001
      - - 1e-05
      milestones:
      - 90
      - 120
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: false
train_settings:
  batch_size: 1
  dataloader_workers: 0
  dataloader_pin_memory: true
  display_iters: 1000
  epochs: 200
  seed: 42
with_center_keypoints: true
```

**Comment by n-poulsen** [comment]
Thanks @vonaviv - the issue seems to be coming from the `KeypointAwareCrop` augmentation, which is added with the `crop_sampling` parameter. I'll work on replicating the issue.

Meanwhile can you run the code without `crop_sampling`?

**Comment by n-poulsen** [comment]
@vonaviv I've not been able to replicate your issue. Could it be possible that you have corrupt data in your training dataset?

**Edit**: I was able to replicate the issue. When all keypoints labeled in an image are augmented outside of the image (e.g. they are close to the edge and a rotation is applied), no keypoints are left. Then, density-based sampling of the crop center fails as there are no keypoints to sample from.
