### ISSUE TITLE
FileNotFoundError: [Errno 2]  No such file or directory: '<pathToDLCProject>/training-datasets/UnaugmentedDataSet_myDLC_modelZooDec3'

### ISSUE THREAD

**Issue by siddypot** [DeepLabCut/DeepLabCut#2802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I ran a script using deeplabcut.create_pretrained_project() 

```
import os
import deeplabcut
project_name = 'myDLC_modelZoo'
your_name = 'teamDLC'
model2use='superanimal_topviewmouse'
video_path='<myVideoPath>'
videotype = os.path.splitext(video_path)[-1].lstrip('.') #or MOV, or avi, whatever you uploaded!
config_path, train_config_path = deeplabcut.create_pretrained_project(
    project_name,
    your_name,
    [video_path],
    videotype=videotype,
    model=model2use,
    analyzevideo=True,
    createlabeledvideo=True,
    copy_videos=True, #must leave copy_videos=True
)
```

### Operating System

Ubuntu 22.0.4

### DeepLabCut version

dlc version 3.0.0r6

### DeepLabCut mode

single animal

### Device type

CPU: 13th Gen Intel® Core™ i9-13900K × 32
GPU: NVIDIA GeForce RTX 4090

### Steps To Reproduce

1. install DLC env
2. create python script as shown above
3. run the python script

### Relevant log output

```shell
Loading DLC 3.0.0rc6...
Project "/home/USERNAME/dlc/testing/myDLC_modelZoo-teamDLC-2024-12-03" already exists!
Downloading weights...
Loading.... superanimal_topviewmouse
(…)k_resnet_50_iteration-0_shuffle-1.tar.gz: 100%|███████████████████████████████████████████████████████████████████████████| 235M/235M [00:02<00:00, 115MB/s]
/home/USERNAME/dlc/testing/myDLC_modelZoo-teamDLC-2024-12-03/dlc-models/iteration-0/myDLC_modelZooDec3-trainset95shuffle1/train/pose_cfg.yaml
Analyzing video...
Traceback (most recent call last):
  File "/home/USERNAME/dlc/testing/test.py", line 8, in <module>
    config_path, train_config_path = deeplabcut.create_pretrained_project(
  File "/home/USERNAME/anaconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/create_project/modelzoo.py", line 306, in create_pretrained_project
    deeplabcut.analyze_videos(cfg, [video_dir], videotype, save_as_csv=True)
  File "/home/USERNAME/anaconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/compat.py", line 809, in analyze_videos
    engine = get_shuffle_engine(
  File "/home/USERNAME/anaconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/generate_training_dataset/metadata.py", line 406, in get_shuffle_engine
    metadata = TrainingDatasetMetadata.create(cfg)
  File "/home/USERNAME/anaconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/generate_training_dataset/metadata.py", line 293, in create
    shuffle_docs = [
  File "/home/USERNAME/anaconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/generate_training_dataset/metadata.py", line 293, in <listcomp>
    shuffle_docs = [
  File "/home/USERNAME/anaconda3/envs/DEEPLABCUT/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/USERNAME/dlc/testing/myDLC_modelZoo-teamDLC-2024-12-03/training-datasets/iteration-0/UnaugmentedDataSet_myDLC_modelZooDec3'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @siddypot! The `deeplabcut.create_pretrained_project` method is not yet implemented for PyTorch SuperAnimal models. As a feature request is already open for this (see #2732), I'll close this issue
