### ISSUE TITLE
DLC 3.0rc5 - use_shelve option for pytorch engine for video analysis

### ISSUE THREAD

**Issue by Andrianarivelo** [DeepLabCut/DeepLabCut#2803]
**Is your feature request related to a problem? Please describe.**
Hello ! 
I'm using DLC 3.0rc5 with pytorch engine on windows 11 with 128Gb of memory and RTX 3060 12Gb. I trained a multianimal network and performed analysis on my videos. I noticed huge memory leaks during the analysis that eventually results in crash of the script (see log bellow).

This was a known issue of previous version that was solved by `use_shelve=True ` but the `use_shelve `option is not supported for the pytorch engine.

Or if you have a solution for memory management for inference ? 

Thanks

```
Starting to analyze D:\BEHAVIOR\ethovision\01-11-2024-cerebellum-NPX\Media Files\converted\converted_Trial     6.mp4
Video metadata:
  Overall # of frames:    54038
  Duration of video [s]:  900.63
  fps:                    60.0
  resolution:             w=800, h=600

Running pose prediction with batch size 1
  2%|█▏                                                                            | 832/54038 [00:38<40:15, 22.03it/s]C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\pose_estimation_pytorch\data\postprocessor.py:433: RuntimeWarning: invalid value encountered in cast
  heatmap_indices = np.rint(individual_keypoints).astype(int)
 71%|█████████████████████████████████████████████████████▋                      | 38203/54038 [29:49<12:21, 21.35it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\compat.py", line 865, in analyze_videos
    return analyze_videos(
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\analyze_videos.py", line 339, in analyze_videos
    predictions = video_inference(
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\analyze_videos.py", line 130, in video_inference
    predictions = pose_runner.inference(images=tqdm(video))
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\pose_estimation_pytorch\runners\inference.py", line 108, in inference
    self._prepare_inputs(data)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\pose_estimation_pytorch\runners\inference.py", line 131, in _prepare_inputs
    inputs, context = self.preprocessor(inputs, context)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\pose_estimation_pytorch\data\preprocessor.py", line 122, in __call__
    image, context = preprocessor(image, context)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\deeplabcut\pose_estimation_pytorch\data\preprocessor.py", line 268, in __call__
    transformed = self.transform(
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\albumentations\core\composition.py", line 222, in __call__
    data = t(**data)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\albumentations\core\transforms_interface.py", line 123, in __call__
    return self.apply_with_params(params, **kwargs)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\albumentations\core\transforms_interface.py", line 136, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\albumentations\augmentations\transforms.py", line 210, in apply
    return F.normalize(img, self.mean, self.std, self.max_pixel_value)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\albumentations\augmentations\functional.py", line 114, in normalize
    return normalize_cv2(img, mean, denominator)
  File "C:\Users\bellone\.conda\envs\dcl3\lib\site-packages\albumentations\augmentations\functional.py", line 91, in normalize_cv2
    img = np.ascontiguousarray(img.astype("float32"))
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 5.49 MiB for an array with shape (600, 800, 3) and data type float32
>>>
```

**Describe the solution you'd like**
Would it be possible to implement it for the pytorch engine ? 

**Describe alternatives you've considered**
Increase paged pool memory

**Additional context**
![memory_leak](https://github.com/user-attachments/assets/ec402c34-077d-4a39-8af2-5710cf35bdaf)

**Comment by n-poulsen** [comment]
Hi @Andrianarivelo! `use_shelve` was implemented for PyTorch models in #2790. You can update your DLC3 code to the latest version by running:

```bash
pip install --upgrade "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut"
```
