### ISSUE TITLE
Multiple Errors when using analyze_videos()

### ISSUE THREAD

**Issue by Gaelic98** [DeepLabCut/DeepLabCut#289]
**OS: Windows 10,  deeplabcut: 2.0.5**

**Anaconda Env (dlc as recommnded by this GitHub)**

**Problem**

After doing some label refining and retraining, I am attempting to analyse the video having evaluated the network. However, no matter the videos I am looking at I receive the following errors (abridged but one can find the full error print out below).

The key parts are as follows:
```FileNotFoundError: File F:\DeepLabTrial\DeepLabCut_trial_dogs\videos\dog35DeepCut_resnet50_Dogs_Data_Generation_30Apr9shuffle1_85000.h5 does not exist```
and
```UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/conv1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, resnet_v1_50/conv1/weights/read)]]
	 [[{{node Sigmoid/_541}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1258_Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

Admittedly, as I attempt this analysis my laptop is currently performing some retraining for another video so I feel this is quite likely to be the source of the errors mentioned. If this is the case I will close the issue myself.

Any help would be greatly appreciated. 

**Error**

```Using snapshot-85000 for model F:\DeepLabTrial\DeepLabCut_trial_dogs\Dogs_Data_Generation_30-Jake-2019-04-09\dlc-models\iteration-1\Dogs_Data_Generation_30Apr9-trainset95shuffle1
INFO:tensorflow:Restoring parameters from F:\DeepLabTrial\DeepLabCut_trial_dogs\Dogs_Data_Generation_30-Jake-2019-04-09\dlc-models\iteration-1\Dogs_Data_Generation_30Apr9-trainset95shuffle1\train\snapshot-85000
INFO:tensorflow:Restoring parameters from F:\DeepLabTrial\DeepLabCut_trial_dogs\Dogs_Data_Generation_30-Jake-2019-04-09\dlc-models\iteration-1\Dogs_Data_Generation_30Apr9-trainset95shuffle1\train\snapshot-85000
Starting to analyze %  F:\DeepLabTrial\DeepLabCut_trial_dogs\videos\dog35.mp4
Loading  F:\DeepLabTrial\DeepLabCut_trial_dogs\videos\dog35.mp4
Duration of video [s]:  413.71 , recorded with  29.97 fps!
Overall # of frames:  12399  found with (before cropping) frame dimensions:  1920 1080
Starting to extract posture





  0%|          | 0/12399 [00:00<?, ?it/s]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in AnalyzeVideo(video, DLCscorer, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder)
    262         # Attempt to load data...
--> 263         pd.read_hdf(dataname)
    264         print("Video already analyzed!", dataname)

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\pandas\io\pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    346             raise compat.FileNotFoundError(
--> 347                 'File %s does not exist' % path_or_buf)
    348 

FileNotFoundError: File F:\DeepLabTrial\DeepLabCut_trial_dogs\videos\dog35DeepCut_resnet50_Dogs_Data_Generation_30Apr9shuffle1_85000.h5 does not exist

During handling of the above exception, another exception occurred:

UnknownError                              Traceback (most recent call last)
C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/conv1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, resnet_v1_50/conv1/weights/read)]]
	 [[{{node Sigmoid/_541}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1258_Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

UnknownError                              Traceback (most recent call last)
<ipython-input-16-66c098358f08> in <module>()
----> 1 deeplabcut.analyze_videos(path_config_file,videofile_path, save_as_csv=True,videotype='.mp4')

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder)
    151         #looping over videos
    152         for video in Videos:
--> 153             AnalyzeVideo(video,DLCscorer,trainFraction,cfg,dlc_cfg,sess,inputs, outputs,pdindex,save_as_csv, destfolder)
    154 
    155     os.chdir(str(start_path))

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in AnalyzeVideo(video, DLCscorer, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder)
    279         print("Starting to extract posture")
    280         if int(dlc_cfg["batch_size"])>1:
--> 281             PredicteData,nframes=GetPoseF(cfg,dlc_cfg, sess, inputs, outputs,cap,nframes,int(dlc_cfg["batch_size"]))
    282         else:
    283             PredicteData,nframes=GetPoseS(cfg,dlc_cfg, sess, inputs, outputs,cap,nframes)

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in GetPoseF(cfg, dlc_cfg, sess, inputs, outputs, cap, nframes, batchsize)
    193 
    194                 if batch_ind==batchsize-1:
--> 195                     pose = predict.getposeNP(frames,dlc_cfg, sess, inputs, outputs)
    196                     PredicteData[batch_num*batchsize:(batch_num+1)*batchsize, :] = pose
    197                     batch_ind = 0

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py in getposeNP(image, cfg, sess, inputs, outputs, outall)
     86 def getposeNP(image, cfg, sess, inputs, outputs, outall=False):
     87     ''' Adapted from DeeperCut, performs numpy-based faster inference on batches'''
---> 88     outputs_np = sess.run(outputs, feed_dict={inputs: image})
     89 
     90     scmap, locref = extract_cnn_outputmulti(outputs_np, cfg) #processes image batch.

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node resnet_v1_50/conv1/Conv2D (defined at C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1057)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/conv1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, resnet_v1_50/conv1/weights/read)]]
	 [[{{node Sigmoid/_541}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1258_Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'resnet_v1_50/conv1/Conv2D', defined at:
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\asyncio\base_events.py", line 1434, in _run_once
    handle._run()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\IPython\core\interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\IPython\core\interactiveshell.py", line 2793, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-66c098358f08>", line 1, in <module>
    deeplabcut.analyze_videos(path_config_file,videofile_path, save_as_csv=True,videotype='.mp4')
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 140, in analyze_videos
    sess, inputs, outputs = predict.setup_pose_prediction(dlc_cfg)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\predict.py", line 16, in setup_pose_prediction
    net_heads = pose_net(cfg).test(inputs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 93, in test
    heads = self.get_net(inputs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 89, in get_net
    net, end_points = self.extract_features(inputs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 62, in extract_features
    global_pool=False, output_stride=16,is_training=False)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 274, in resnet_v1_50
    scope=scope)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 205, in resnet_v1
    net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_utils.py", line 146, in conv2d_same
    scope=scope)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 817, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\layers\base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 204, in __call__
    name=self.name)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 957, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node resnet_v1_50/conv1/Conv2D (defined at C:\Users\jcdea\Anaconda3\envs\dlc\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1057)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/conv1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, resnet_v1_50/conv1/weights/read)]]
	 [[{{node Sigmoid/_541}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1258_Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]```

**Comment by MMathisLab** [comment]
If the the file is indeed there, it could be (1) no admin rights to write the output .h5, (2) cuDNN is busy. You could upload your project to google drive and test on Colab if your computer is otherwise busy (and would be way faster to analyze data on a gpu ;). You can use the Colab demo your own data notebook link under “examples”

**Comment by Gaelic98** [comment]
This piece of training shouldn't take too much longer. Once, its finished I will check after evaluating the network and report back.

**Comment by Gaelic98** [comment]
The issue was down to cuDNN being unavailable. I will close the issue.

**Comment by AlexEMG** [comment]
https://github.com/tensorflow/tensorflow/issues/24828
