### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by waseemabbas05** [DeepLabCut/DeepLabCut#296]
Hi, first of all, thank you for such an amazing tool
I am installing deeplabcut on laptop for data annotation. I followed all the steps for installing it inside a conda environment on Ubuntu 18 and then when I tried to import it, I came across this error, I tried everything but couldn't make it go

import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abbas/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/deeplabcut/__init__.py", line 33, in <module>
    from deeplabcut import generate_training_dataset
  File "/home/abbas/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 15, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "/home/abbas/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 18, in <module>
    import wx
  File "/home/abbas/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/abbas/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

Any thoughts?

**Comment by MMathisLab** [comment]
You’re welcome :) 

You likely installed wxpython for Ubuntu 16 if you copy/pasted from our install page. Just need to edit this to have “18” vs “16” (check the install docs if not clear). 

Pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl

**Comment by waseemabbas05** [comment]
Thanks, I tried that as well, didn't do the trick
Perhaps my libraries are intertwined from too many conda environments. However,I was able to install and import it in a docker running on a remote Linux machine.
I am experimenting with a docker whose graphics are forwarded to my host laptop from a remote server, and if I am able to run the GUIs from remote docker, I will share the steps so other people can use this on dockers running on remote GPUs :)
