### ISSUE TITLE
HDF5ExtError: HDF5 error back trace when running the function evaluate_network [filename too long on windows!]

### ISSUE THREAD

**Issue by tochenan** [DeepLabCut/DeepLabCut#360]
**Describe the bug**
Hello developer, when I am running the function : deeplabcut.evaluate_network, the following error took place.

I use Windows10, Anaconda 3 and the newest version of deeplabcut
I am pretty sure I run the command as an admin

error message:

```
C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b\evaluation-results\iteration-0\BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10-trainset95shuffle1  already exists!
Running  DeepCut_resnet50_BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10shuffle1_400000  with # of trainingiterations: 400000
INFO:tensorflow:Restoring parameters from C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b\dlc-models\iteration-0\BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10-trainset95shuffle1\train\snapshot-400000
Analyzing data...
23it [00:03,  7.43it/s]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    154                 try:
--> 155                     DataMachine = pd.read_hdf(resultsfilename,'df_with_missing')
    156                     print("This net has already been evaluated!")

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\pandas\io\pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    346             raise compat.FileNotFoundError(
--> 347                 'File %s does not exist' % path_or_buf)
    348

FileNotFoundError: File C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b\evaluation-results\iteration-0\BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10-trainset95shuffle1\DeepCut_resnet50_BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10shuffle1_400000-snapshot-400000.h5 does not exist

During handling of the above exception, another exception occurred:

HDF5ExtError                              Traceback (most recent call last)
<ipython-input-6-944678ad1825> in <module>()
----> 1 deeplabcut.evaluate_network('C:\\Users\\analysis\\Desktop\\DeepLabCut\\DeepLabCut-master\\BRAC3477.2b\\config.yaml',Shuffles=[1],plotting=True)

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    183                     # Saving results
    184                     DataMachine = pd.DataFrame(PredicteData, columns=index, index=Data.index.values)
--> 185                     DataMachine.to_hdf(resultsfilename,'df_with_missing',format='table',mode='w')
    186
    187                     print("Done and results stored for snapshot: ", Snapshots[snapindex])

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\pandas\core\generic.py in to_hdf(self, path_or_buf, key, **kwargs)
   1469
   1470         from pandas.io import pytables
-> 1471         return pytables.to_hdf(path_or_buf, key, self, **kwargs)
   1472
   1473     def to_msgpack(self, path_or_buf=None, encoding='utf-8', **kwargs):

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\pandas\io\pytables.py in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, **kwargs)
    278     if isinstance(path_or_buf, string_types):
    279         with HDFStore(path_or_buf, mode=mode, complevel=complevel,
--> 280                       complib=complib) as store:
    281             f(store)
    282     else:

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\pandas\io\pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    465         self._fletcher32 = fletcher32
    466         self._filters = None
--> 467         self.open(mode=mode, **kwargs)
    468
    469     def __fspath__(self):

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\pandas\io\pytables.py in open(self, mode, **kwargs)
    578
    579         try:
--> 580             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    581         except (IOError) as e:  # pragma: no cover
    582             if 'can not be written' in str(e):

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\tables\file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    318
    319     # Finally, create the File instance, and return it
--> 320     return File(filename, mode, title, root_uep, filters, **kwargs)
    321
    322

c:\users\analysis\anaconda3\envs\dlc-windowsgpu\lib\site-packages\tables\file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    782
    783         # Now, it is time to initialize the File extension
--> 784         self._g_new(filename, mode, **params)
    785
    786         # Check filters and set PyTables format version for new files.

tables\hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "D:\Build\HDF5\hdf5-1.10.4\src\H5F.c", line 444, in H5Fcreate
    unable to create file
  File "D:\Build\HDF5\hdf5-1.10.4\src\H5Fint.c", line 1364, in H5F__create
    unable to open file
  File "D:\Build\HDF5\hdf5-1.10.4\src\H5Fint.c", line 1557, in H5F_open
    unable to open file: time = Fri Jul 12 11:22:33 2019
, name = 'C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b\evaluation-results\iteration-0\BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10-trainset95shuffle1\DeepCut_resnet50_BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10shuffle1_400000-snapshot-400000.h5', tent_flags = 13
  File "D:\Build\HDF5\hdf5-1.10.4\src\H5FD.c", line 734, in H5FD_open
    open failed
  File "D:\Build\HDF5\hdf5-1.10.4\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = 'C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b\evaluation-results\iteration-0\BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10-trainset95shuffle1\DeepCut_resnet50_BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10shuffle1_400000-snapshot-400000.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302

End of HDF5 error back trace

Unable to open/create file 'C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b\evaluation-results\iteration-0\BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10-trainset95shuffle1\DeepCut_resnet50_BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10shuffle1_400000-snapshot-400000.h5'


config file information:
In [6]: deeplabcut.evaluate_network('C:\\Users\\analysis\\Desktop\\DeepLabCut\\DeepLabCut-master\\BRAC3477.2b\\config.y
   ...: aml',Shuffles=[1],plotting=True)
C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b/evaluation-results/  already exists!
Config:
{'all_joints': [[0],
                [1],
                [2],
                [3],
                [4],
                [5],
                [6],
                [7],
                [8],
                [9],
                [10],
                [11],
                [12],
                [13],
                [14],
                [15]],
 'all_joints_names': ['mouse',
                      'left_ear',
                      'right_ear',
                      'left_shoulder',
                      'right_shoulder',
                      'left_back_leg',
                      'right_back_leg',
                      'tail_upper',
                      'tail_middle',
                      'tail_end',
                      'pupA_head',
                      'pupA_body',
                      'pupA_tail',
                      'pupB_head',
                      'pupB_body',
                      'pupB_tail'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_BRAC3477.2b '
            'bottom_right 08_07_2019 12_54_43 4Jul10\\BRAC3477.2b bottom_right '
            '08_07_2019 12_54_43 4_mc95shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'c:\\users\\analysis\\anaconda3\\envs\\dlc-windowsgpu\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_BRAC3477.2b '
                'bottom_right 08_07_2019 12_54_43 '
                '4Jul10\\Documentation_data-BRAC3477.2b bottom_right '
                '08_07_2019 12_54_43 4_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 16,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\analysis\\Desktop\\DeepLabCut\\DeepLabCut-master\\BRAC3477.2b',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\analysis\\Desktop\\DeepLabCut\\DeepLabCut-master\\BRAC3477.2b\\dlc-models\\iteration-0\\BRAC3477.2b '
                    'bottom_right 08_07_2019 12_54_43 '
                    '4Jul10-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
```

thank you very much

**Comment by AlexEMG** [comment]
This is a windows error, your filename: 'C:\Users\analysis\Desktop\DeepLabCut\DeepLabCut-master\BRAC3477.2b\evaluation-results\iteration-0\BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10-trainset95shuffle1\DeepCut_resnet50_BRAC3477.2b bottom_right 08_07_2019 12_54_43 4Jul10shuffle1_400000-snapshot-400000.h5'

has 271 characters, which doesn't work. Also see here: https://github.com/AlexEMG/DeepLabCut/issues/196

I would recommend to move/create your project in a more shallow (shorter) path. E.g. C:\Users\myproject...
