### ISSUE TITLE
Error when using "import deeplabcut"

### ISSUE THREAD

**Issue by phcao101** [DeepLabCut/DeepLabCut#364]
Hi all,
I'm using:

Python 3.6.8
and
CentOS Linux release 7.6.1810 through PuTTY

When I:
import deeplabcut

I get this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 19, in <module>
    from deeplabcut.generate_training_dataset.labeling_toolbox import *
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 27, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/utils/__init__.py", line 1, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/utils/make_labeled_video.py", line 34, in <module>
    mpl.use('TkAgg')
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/matplotlib/__init__.py", line 1391, in use
    switch_backend(name)
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/matplotlib/pyplot.py", line 222, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

Can someone please help? If there's more documentation I can provide to make it easier to help me, please let me know. Thanks so much in advance!

**Comment by MMathisLab** [comment]
Can you please run pip install matplotlib==3.0.3 inside your env,then try again?  

And please fill out the template!

**Comment by phcao101** [comment]
Sorry about not using the template, I accidentally clicked on "open a regular issue" so I got a blank field. 

So, I already had matplotlib==3.03, however, after running 

pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl

which I think was the problem. I then ran 

import deeplabcut

and received this error now:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 19, in <module>
    import wx
  File "/home/knight/cmerrick/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/knight/cmerrick/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory


I had read online that a solution to this would be to run:

sudo apt-get install libjpeg-turbo8

However, I'm using the secure shell PuTTY, and "sudo" is disabled for me so I can't run that command. Do you have any solution to that? Thanks so much once again!
