### ISSUE TITLE
Unable to import deeplabcut while using AWS SageMaker

### ISSUE THREAD

**Issue by phcao101** [DeepLabCut/DeepLabCut#381]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows  10
DeepLabCut Version [e.g. 22] (please check with import deeplabcut, deeplabcut.__version__)
Browser Chrome

**Describe the problem**
I'm trying to install Deep Lab Cut using a notebook on Amazon Web Service's SageMaker. I downloaded the dlc-windowsGPU.yaml and uploaded it into the cloud. I then cd into the folder containing that file and typed:

conda env create -f dlc-windowsGPU.yaml

When in that environment, I'm unable to import deeplabcut. This is the error I get:

>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/anaconda3/envs/dlc-windowsGPU/lib/python3.6/site-packages/deeplabcut/__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "/home/ec2-user/anaconda3/envs/dlc-windowsGPU/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "/home/ec2-user/anaconda3/envs/dlc-windowsGPU/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 19, in <module>
    import wx
  File "/home/ec2-user/anaconda3/envs/dlc-windowsGPU/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/ec2-user/anaconda3/envs/dlc-windowsGPU/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Thanks so much in advance!
**Additional context**

**Comment by MMathisLab** [comment]
Please see the user guide (https://www.nature.com/articles/s41596-019-0176-0); you cannot use GUIs on the cloud, so you need to set the environmental variable to suppress wxPython. Also please see Google Colab demos, which do this as well. https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Colab_DEMO_mouse_openfield.ipynb
