### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by mjhigley** [DeepLabCut/DeepLabCut#396]
**Windows 10 64bit**
Anaconda env with DeepLabCut 2.0

activated WindowsGPU environment
tried to install with pip install deeplabcut, most downloads and unpacking seemed to go fine,
then got the following text (same with multiple repeats)

```
...
Collecting ruamel.yaml==0.15 (from deeplabcut)
  Using cached https://files.pythonhosted.org/packages/10/aa/f31c8a858e23fe5b14c59e6a03ae80b4cb76353c184df48a582a55eb2674/ruamel.yaml-0.15.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Warning: 'keywords' should be a list, got type 'NoneType'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HIGLEY~1\AppData\Local\Temp\pip-install-a361edo2\ruamel.yaml\setup.py", line 858, in <module>
        main()
      File "C:\Users\HIGLEY~1\AppData\Local\Temp\pip-install-a361edo2\ruamel.yaml\setup.py", line 847, in main
        setup(**kw)
      File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\setuptools\dist.py", line 444, in __init__
        k: v for k, v in attrs.items()
      File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\distutils\dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\distutils\dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\distutils\dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\HIGLEY~1\AppData\Local\Temp\pip-install-a361edo2\ruamel.yaml\
```

thanks for any help!
mike

**Comment by MMathisLab** [comment]
Please edit you post to not ignore the template.

**Comment by mjhigley** [comment]
sorry, when i first posted, the options with templates didn't seem to
appear (or i missed them), edited now...
mike




--------------------------------------------------------------------
Michael J. Higley  MD, PhD
Associate Professor of Neuroscience
Kavli Institute for Neuroscience
Yale School of Medicine
295 Congress Ave.
BCMM 454E
New Haven, CT 06511

203-785-4301 (o)
203-785-5263 (f)

**Comment by MMathisLab** [comment]
> Windows 10 64bit
> Anaconda env with DeepLabCut 2.0
> 
> activated WindowsGPU environment

You do **not** need to run `pip install deeplabcut `inside the environment, it is already installed! 
https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md

i would recommend [deleting the broken environment now](https://kapeli.com/cheat_sheets/Conda.docset/Contents/Resources/Documents/index), this just follow these instructions.

https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md

You can [open the .yaml file](https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/dlc-windowsGPU.yaml) and see what gets installed already, namely:

```
name: dlc-windowsGPU
dependencies:
  - python=3.6
  - tensorflow-gpu==1.13.1
  - cudnn=7
  - wxpython
  - jupyter
  - nb_conda
  - pytables==3.4.4
  - pip:
    - deeplabcut
```
