### ISSUE TITLE
problem with using labeling GUI

### ISSUE THREAD

**Issue by mayaiuga** [DeepLabCut/DeepLabCut#400]
Hi,

I am labeling a large number of frames, due to the sparse presence of the behaviour I am looking at. I seem to run into some error whenever I add labels. I can label of few frames and then the GUI stops working and a error message is displayed. Then I have to reopen the labeling GUI find the frame I was at and start labeling again- but this occurs every few frames which is very inconvenient.

This is the error message that python displays:
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.SizeEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.SizeEvent'> returned a result with an error set
Traceback (most recent call last):
  File "C:\Users\zcbtaii\AppData\Local\Continuum\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 568, in nextImage
    self.buttonCounter = MainFrame.plot(self,self.img)
  File "C:\Users\zcbtaii\AppData\Local\Continuum\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 634, in plot
    self.figure.canvas.draw()
  File "C:\Users\zcbtaii\AppData\Local\Continuum\anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 31, in draw
    self.bitmap = _convert_agg_to_wx_bitmap(self.get_renderer(), None)
  File "C:\Users\zcbtaii\AppData\Local\Continuum\anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 96, in _convert_agg_to_wx_bitmap
    agg.buffer_rgba())
RuntimeError: Failed to gain raw access to bitmap data.
Traceback (most recent call last):
  File "C:\Users\zcbtaii\AppData\Local\Continuum\anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backends\backend_wx.py", line 817, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "C:\Users\zcbtaii\AppData\Local\Continuum\anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backends\backend_wx.py", line 783, in gui_repaint
    drawDC.DrawBitmap(bmp, 0, 0)
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap

Anybody encountered this before and can give me any advice on how to solve it?
Also is there a way for when I reopen the GUI to jump directly to a certain frame without having to press next for all the frames that are already labeled?

Many thanks in advance!

**Comment by MMathisLab** [comment]
Please fill out the form completely. 

Latest versions of the GUIs all auto jump to last labeled frame. 

Sounds like you have the wrong version of matplotlib

**Comment by mayaiuga** [comment]
Your Operating system and DeepLabCut version :
Windows 10 64 bit, 
Anaconda env for GPU, deeplabcut version 2.0.7.1
Browser: Chrome

I am attaching below my environment dependencies. matplotlib version is 3.03.

![image](https://user-images.githubusercontent.com/45516669/63275403-601fea80-c299-11e9-9dc5-7fd7dc6a022b.png)
![image](https://user-images.githubusercontent.com/45516669/63275430-6dd57000-c299-11e9-9ba9-098f388e3ba0.png)

**Comment by MMathisLab** [comment]
what version of wxpython do you have installed? I don't see it in your env list.

**Comment by MMathisLab** [comment]
closing due to inactivity, but please update us if you can (my guess is you need to re-install wxPython)

**Comment by mayaiuga** [comment]
Hi,
Sorry for replying late- I was out of the lab for a couple of days.

The current version of wxPython I have is 4.0.6 msw (phoenix) wxWidgets 3.0.5

Thank you for your help!
All the best,
Maya

**Comment by zoccoler** [comment]
Hello, did anyone solve this? I am experiencing the same problem when processing images in a long stack.
Since it seemed related to the toolbar, I have disabled it with `mpl.rcParams['toolbar'] = 'None'`.

Then, a somewhat similar error occurs:
wxAssertionError: C++ assertion "m_hdc" failed at ..\..\src\msw\textmeasure.cpp(64) in wxTextMeasure::BeginMeasuring(): Must not be used with non-native wxDCs

Caused by:
    fig, ax = plt.subplots(figsize=(10, 6))
  File "C:\Users\...\lib\site-packages\matplotlib\pyplot.py", line 1209, in subplots
    fig = figure(**fig_kw)
  File "C:\Users\...\lib\site-packages\matplotlib\pyplot.py", line 545, in figure
    **kwargs)
  File "C:\Users\...\lib\site-packages\matplotlib\backends\backend_wx.py", line 1969, in new_figure_manager
    return super().new_figure_manager(num, *args, **kwargs)
  File "C:\Users\...\lib\site-packages\matplotlib\backend_bases.py", line 3252, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\...\lib\site-packages\matplotlib\backends\backend_wx.py", line 1973, in new_figure_manager_given_figure
    frame = cls._frame_class(num, figure)
  File "C:\Users\...\lib\site-packages\matplotlib\backends\backend_wx.py", line 1101, in __init__
    self.statusbar = StatusBarWx(self)
  File "C:\Users\...\lib\site-packages\matplotlib\backends\backend_wx.py", line 1585, in __init__
    self.SetFieldsCount(2)

Could it be related to multi-threads? (like in the answer to [this question](https://stackoverflow.com/questions/22211658/implementing-my-own-event-loop-in-a-wxpython-application)?)

With `plt.ioff()`, I sure am openning, saving and closing figures in a new window inside a `for`, while updating a gauge in the main interface, therefore, I have tried using wxCallAfter and even commenting the gauge update, but I still get the same error. Any suggestions are welcome :)

**Comment by AlexEMG** [comment]
How many images are you processing per folder? (Keep in mind you can delete all/most frames that do not contain the behavior before labeling).

________________________________

**Comment by zoccoler** [comment]
Oh, first of all I apologize because now I realized that I was not using your DeepLabCut toolbox, it just happened that I found this thread because it was the only result I got where someone had the same problem I am having. Therefore you may disconsider this if you wish.

In any case, if you believe it is a problem you may run into as well, I'll leave my answer below.

I am processing one stack of images (nframes x 100 x 100) in a loop, dealing with one frame per iteraction. The error started popping up around frame 1240 with a stack of nframes = 1500.

Let me provide shorter version where the error also occurs (this function is executed once user clicks a button in main interface):

    def OnRUN(self,event):    
        plt.ioff()    
        for fr in range(nframes):    
            label_image = measure.label(self.video_bin[fr], background=0)    
            image_label_overlay = label2rgb(label_image, image=self.video_bin[fr])    
            fig, ax = plt.subplots(figsize=(10, 6))    
            ax.imshow(image_label_overlay)    
            plt.axis('off')    
            imname = 'imgout'+str(fr)+'.tif'    
            impath = os.path.join(self.dirname,'Output',imname)    
            plt.savefig(impath,bbox_inches='tight',facecolor='black',edgecolor='none')    
            plt.close(fig)    
        plt.ion()

**Comment by renniek** [comment]
Hello, 

I also recently encountered this problem while refining labels on 78 images (based on the labels from the algorithm). I was able to adjust labels on 72 frames before I encountered this issue.

Any help would be much appreciated. Thank you!

**Comment by PolarBean** [comment]
seems to be an issue with labelling a large volume of frames from a single video, i consistently encounter it at ~700 frames in.

**Comment by zoccoler** [comment]
In case it helps, I've created [this related question](https://stackoverflow.com/questions/59092214/matplotlib-wxpython-backend-crashing-after-large-image-stack-processing) on stackoverflow with a small example to test this situation. If a solution comes up, we may all benefit from it.

**Comment by YasminBaba** [comment]
Hello, I am having the exact same problem Maya experienced. Has there been any update on the solution? I am labeling a large volume of frames as well. I have also updated my wxPython and matplotlib to the latest versions but this hasnt helped.

Also is there away to go straight to the last labeled image instead of having to go through from the beginning?

**Comment by MMathisLab** [comment]
The labeling GUI is not designed to be used this way, i.e. the goal of this project was to show that small amounts of data (taken from different videos) would be labeled, Thus, a typical use case is labeling 20-50 frames per folder (that are from different videos to cover the whole behavioral space). 

The latest matplotlib is not suggested either, btw. 

Also, when you open the GUI is DOES automatically jump to the last labeled frame, assuming you have saved your annotations. This was an update nearly a year ago, so be sure you are using something newer than 2.0.6 (i.e. latest is 2.1.5.2)
