### ISSUE TITLE
Unable to "import deeplabcut"

### ISSUE THREAD

**Issue by ambareeshsrja16** [DeepLabCut/DeepLabCut#403]
**Operating system and DeepLabCut version**

OS: Ubuntu18.04 with Anaconda Env
DeepLabCut Version: gitclone latest master (unable to check directly, couldn't import)
Browser: Chrome
Using JupyterNotebook

**Problem**

Tried to use the Demo Notebook after installation, unable to perform first step - "import deeplabcut"

**Steps to Reproduce the problem**

1. git clone https://github.com/AlexEMG/DeepLabCut.git 
2. "cd" into, the folder named conda-environments
3. conda env create -f dlc-ubuntu-GPU.yaml
4. source activate dlc-ubuntu-GPU , command terminal has changed with the correct environment name 
5. conda install nb_conda
6. open new notebook  or one of the demonotebooks, and try "import deeplabcut"
7. See error

**Error Trace:**
    
    ---------------------------------------------------------------------------
     ModuleNotFoundError                       Traceback (most recent call last)
     <ipython-input-4-cfa4f159dfc5> in <module>
     ----> 1 import deeplabcut

    ModuleNotFoundError: No module named 'deeplabcut'

**Screenshots**

![Screenshot from 2019-08-21 11-12-28](https://user-images.githubusercontent.com/39631487/63456812-9d54bb80-c404-11e9-9add-77db95137a76.png)

**Additional context**

Tried  installing later with  "pip install deeplabcut" as an added second measure, but it failed with this error:

       |████████████████████████████████| 256kB 34.2MB/s 
      ERROR: Command errored out with exit status 1:
     command: /home/florian/anaconda3/envs/dlc-ubuntu-GPU/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uztvsd6k/ruamel.yaml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uztvsd6k/ruamel.yaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-uztvsd6k/ruamel.yaml/
    Complete output (26 lines):
    /tmp/tmp_ruamel_4sazzike/test_ruamel_yaml.c: In function ‘main’:
    /tmp/tmp_ruamel_4sazzike/test_ruamel_yaml.c:6:8: warning: ‘parser’ is used uninitialized in this function [-Wuninitialized]
     parser = parser;  /* prevent warning */
     ~~~~~~~^~~~~~~~
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['/tmp/pip-install-uztvsd6k/ruamel.yaml/setup.py', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uztvsd6k/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/tmp/pip-install-uztvsd6k/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/home/florian/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/florian/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/florian/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__
        k: v for k, v in attrs.items()
      File "/home/florian/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/home/florian/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/home/florian/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ambareeshsrja16** [comment]
Closing thread- same as for issue : https://github.com/AlexEMG/DeepLabCut/issues/367
