### ISSUE TITLE
Running model evaluation "Step1_EvaluateModelonDataset.py"

### ISSUE THREAD

**Issue by sirinire** [DeepLabCut/DeepLabCut#41]
I am encountering the following error when I try to check my model training by running Step1_EvaluateModelonDataset.py:

Traceback (most recent call last):
  File "EvaluateNetwork.py", line 31, in <module>
    from nnet import predict
  File "C:\Users\neyhart\DeepLabCut\pose-tensorflow\nnet\predict.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Users\neyhart\AppData\Local\Continuum\anaconda3\envs\DLCdependencies\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\neyhart\AppData\Local\Continuum\anaconda3\envs\DLCdependencies\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\neyhart\AppData\Local\Continuum\anaconda3\envs\DLCdependencies\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\neyhart\AppData\Local\Continuum\anaconda3\envs\DLCdependencies\lib\site-packages\tensorflow\python\platform\self_check.py", line 70, in preload_check
    % build_info.nvcuda_dll_name)
ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.

I followed the installation instructions for "Simple installation on windows without GPU support", so I am confused as to why I am getting an error regarding Cuda. I noticed that the DLCdependencies file contains "tensorflow-gpu 1.8.0", is this related to why I am getting this error?
Thank you!

**Comment by AlexEMG** [comment]
Hi,

Did training work? In that case your TF installation would be fine and this error is perhaps related to how you call DLC? see: https://github.com/AlexEMG/DeepLabCut/issues/38

**Comment by sirinire** [comment]
Training did work. I discovered that I did not have TensorFlow installed properly. I reinstalled it and was able to evaluate the model successfully. Thanks for your help!
