### ISSUE TITLE
ModuleNotFoundError: No module named 'wx'

### ISSUE THREAD

**Issue by monajalal** [DeepLabCut/DeepLabCut#415]
```
[jalal@goku scratch3]$ pip install --user deeplabcut
Requirement already satisfied: deeplabcut in /home/grad3/jalal/.local/lib/python3.6/site-packages (2.0.8)
Requirement already satisfied: pandas==0.21.0 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (0.21.0)
Requirement already satisfied: statsmodels==0.9.0 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (0.9.0)
Requirement already satisfied: ipython~=6.0.0 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (6.0.0)
Requirement already satisfied: scipy~=1.1.0 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (1.1.0)
Requirement already satisfied: tables in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (3.4.2)
Requirement already satisfied: certifi in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (2018.10.15)
Requirement already satisfied: h5py~=2.7 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (2.7.1)
Requirement already satisfied: easydict~=1.7 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (1.9)
Requirement already satisfied: ipython-genutils==0.2.0 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (0.2.0)
Requirement already satisfied: wheel==0.31.1 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (0.31.1)
Requirement already satisfied: setuptools in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (38.4.0)
Requirement already satisfied: moviepy~=0.2.3.5 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (0.2.3.5)
Requirement already satisfied: ruamel.yaml==0.15 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (0.15.0)
Requirement already satisfied: chardet==3.0.4 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (3.0.4)
Requirement already satisfied: matplotlib==3.0.3 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (3.0.3)
Requirement already satisfied: imageio==2.3.0 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (2.3.0)
Requirement already satisfied: opencv-python~=3.4 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (3.4.5.20)
Requirement already satisfied: click in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (6.7)
Requirement already satisfied: python-dateutil==2.7.3 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (2.7.3)
Requirement already satisfied: scikit-learn~=0.19.2 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (0.19.2)
Requirement already satisfied: scikit-image~=0.14.0 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (0.14.4)
Requirement already satisfied: pyyaml>=5.1 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (5.1.2)
Requirement already satisfied: tqdm>4 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (4.28.1)
Requirement already satisfied: six==1.11.0 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (1.11.0)
Collecting numpy==1.14.5 (from deeplabcut)
  Using cached https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: intel-openmp in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (2019.0)
Requirement already satisfied: requests in /home/grad3/jalal/.local/lib/python3.6/site-packages (from deeplabcut) (2.21.0)
Requirement already satisfied: patsy in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from deeplabcut) (0.5.0)
Requirement already satisfied: pytz>=2011k in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from pandas==0.21.0->deeplabcut) (2017.3)
Requirement already satisfied: traitlets>=4.2 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (4.3.2)
Requirement already satisfied: simplegeneric>0.8 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (0.8.1)
Requirement already satisfied: pickleshare in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (0.7.4)
Requirement already satisfied: pexpect; sys_platform != "win32" in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (4.3.1)
Requirement already satisfied: decorator in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (4.2.1)
Requirement already satisfied: jedi>=0.10 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (0.11.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (1.0.15)
Requirement already satisfied: pygments in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from ipython~=6.0.0->deeplabcut) (2.2.0)
Requirement already satisfied: numexpr>=2.5.2 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from tables->deeplabcut) (2.6.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.3->deeplabcut) (2.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/grad3/jalal/.local/lib/python3.6/site-packages (from matplotlib==3.0.3->deeplabcut) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.3->deeplabcut) (0.10.0)
Requirement already satisfied: pillow in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from imageio==2.3.0->deeplabcut) (5.0.0)
Requirement already satisfied: networkx>=1.8 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from scikit-image~=0.14.0->deeplabcut) (2.0)
Requirement already satisfied: PyWavelets>=0.4.0 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from scikit-image~=0.14.0->deeplabcut) (0.5.2)
Requirement already satisfied: cloudpickle>=0.2.1 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from scikit-image~=0.14.0->deeplabcut) (0.5.2)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from requests->deeplabcut) (1.22)
Requirement already satisfied: idna<2.9,>=2.5 in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from requests->deeplabcut) (2.6)
Requirement already satisfied: parso==0.1.* in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from jedi>=0.10->ipython~=6.0.0->deeplabcut) (0.1.1)
Requirement already satisfied: wcwidth in /scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython~=6.0.0->deeplabcut) (0.1.7)
ERROR: deeplabcut 2.0.8 has requirement ruamel.yaml==0.15, but you'll have ruamel-yaml 0.15.35 which is incompatible.
ERROR: cvxpy 1.0.16 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
Installing collected packages: numpy
  Found existing installation: numpy 1.15.0
    Uninstalling numpy-1.15.0:
      Successfully uninstalled numpy-1.15.0
Successfully installed numpy-1.14.5
[jalal@goku scratch3]$ python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grad3/jalal/.local/lib/python3.6/site-packages/deeplabcut/__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "/home/grad3/jalal/.local/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "/home/grad3/jalal/.local/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 19, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

```

I have:
```

$ uname -a
Linux goku.bu.edu 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

and

```
$ python --version
Python 3.6.4 :: Anaconda custom (64-bit)

```

**Comment by MMathisLab** [comment]
TensorFlow and wxPython are not installed with "pip install deeplabcut"

please follow the installation instructions here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md
We recommend using our conda environments.

**Comment by monajalal** [comment]
`$ pip install --user wxpython`

solved the problem for me.

**Comment by Olgarubio** [comment]
I have the same problem but I have : 
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
pi@raspberrypi:~ $ python --version
Python 2.7.16

Any recommendations ?

**Comment by MMathisLab** [comment]
Python 2 is not supported, you’ll need to use 3.7+; then install wxPython
