### ISSUE TITLE
KeyError: '-' when creating the labeled 3d videos

### ISSUE THREAD

**Issue by FredericaLee** [DeepLabCut/DeepLabCut#485]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: macOS Mojave 10.14.6 
DeepLabCut Version 2.1.3
Browser Safari

**Describe the problem**

When I try to create the labeled 3d video by calling function
_deeplabcut.create_labeled_video_3d(config_path,[video_path],videotype = 'mp4')_
I met the _KeyError: '-'_

#### Here is my config.yaml
<img width="631" alt="Screen Shot 2019-11-11 at 3 42 33 PM" src="https://user-images.githubusercontent.com/26166375/68629802-04c95700-049a-11ea-9723-cc5bededfab1.png">

#### And this is the output
Analyzing all the videos in the directory
[['/Users/linwei/deeplabcut/TD/video/1_DLC_3D.h5', '/Users/linwei/deeplabcut/TD/video/left-1.mp4', '/Users/linwei/deeplabcut/TD/video/right-1.mp4']]
Creating 3D video from left-1.mp4 and right-1.mp4 using 1_DLC_3D.h5
Trying to find filtered predictions...
Found filtered predictions! I will use these for triangulation.
This is I found:  /Users/linwei/deeplabcut/TD/video/*left-1DLC_resnet50_dogwalkOct10shuffle1_59000*filtered.h5 /Users/linwei/deeplabcut/TD/video/*right-1DLC_resnet50_dogwalkOct10shuffle1_59000*filtered.h5
  0%|                                                    | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2522, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '-'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/deeplabcut/pose_estimation_3d/plotting3D.py", line 147, in create_labeled_video_3d
    output_folder,num_frames = plot2D(cfg_3d,k,bodyparts2plot,vid_cam1,vid_cam2,bodyparts2connect,df_cam1,df_cam2,df_3d,pcutoff,markerSize,alphaValue,color,path_h5_file,file_name,skeleton_color,view,draw_skeleton,trailpoints,xlim,ylim,zlim)
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/deeplabcut/pose_estimation_3d/plotting3D.py", line 212, in plot2D
    df_x[bpindex,:]=xyz_pts[scorer_3d][bp]['x'].values
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/pandas/core/frame.py", line 2137, in __getitem__
    return self._getitem_multilevel(key)
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/pandas/core/frame.py", line 2181, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2071, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2361, in _get_level_indexer
    loc = level_index.get_loc(key)
  File "/Users/linwei/anaconda3/envs/tf/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2524, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '-'

**Comment by MMathisLab** [comment]
Your spacing in the skeleton section is incorrect. Please check the demo config file closely. 
```

- - one
  - two
```
