### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#554]
When I import deeplabcut in jupyter notebook through the PyCharm IDE, I get the following error.

Traceback (most recent call last):
  File "C:\Users\dragonli\.conda\envs\deeplabcut\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\dragonli\.conda\envs\deeplabcut\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\dragonli\.conda\envs\deeplabcut\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\dragonli\.conda\envs\deeplabcut\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\dragonli\.conda\envs\deeplabcut\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\dragonli\.conda\envs\deeplabcut\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\dragonli\.conda\envs\deeplabcut\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\dragonli\.conda\envs\deeplabcut\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

Do you have any suggestions to solve this issue?

![Capture](https://user-images.githubusercontent.com/59983437/72572478-857c4900-3877-11ea-9302-4204d7c22135.PNG)

Thank you.

**Comment by MMathisLab** [comment]
Here are some resources! 

https://github.com/tensorflow/tensorflow/issues/22794

https://forum.image.sc/t/tensorflow-dlc-2-0-importerror-dll-load-failed-the-specified-module-could-not-be-found/22991
