### ISSUE TITLE
Problem importing deeplabcut (maybe wx related)

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#606]
**Describe the bug**
Running python -m deeplabcut worked fine until today where I got the error below.
**To Reproduce**
1. `conda activate dlc-ubuntu-CPU`
2. `python -m deeplabcut` or ipython -> `import deeplabcut`

```
Traceback (most recent call last):
  File "/home/generalubuntu/anaconda3/envs/dlc-ubuntu-CPU/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/generalubuntu/anaconda3/envs/dlc-ubuntu-CPU/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/generalubuntu/anaconda3/envs/dlc-ubuntu-CPU/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/generalubuntu/anaconda3/envs/dlc-ubuntu-CPU/lib/python3.6/site-packages/deeplabcut/__init__.py", line 30, in <module>
    from deeplabcut import generate_training_dataset
  File "/home/generalubuntu/anaconda3/envs/dlc-ubuntu-CPU/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "/home/generalubuntu/anaconda3/envs/dlc-ubuntu-CPU/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 19, in <module>
    import wx
  File "/home/generalubuntu/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/generalubuntu/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/generalubuntu/anaconda3/envs/dlc-ubuntu-CPU/bin/../lib/libgio-2.0.so.0: undefined symbol: g_ref_count_inc
```

**Expected behavior**
deeplabcut gets imported or the GUI opens

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version can't check as deeplabcut doesnt import. But, a clean install last week using the ubuntu environment.
 - Browser: firefox

**Comment by hummuscience** [comment]
After a fresh install everything is working fine again. however, when I install jupyter with `conda install jupyter` the error shows up, which suggests that jupyter is installing something that causes the error

**Comment by MMathisLab** [comment]
We recently decided to suggest ubuntu users just create their own env, as 16/18/19 all have different wheels for wxPython required. You might consider just using this:

https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md#creating-your-own-customized-conda-env-recommended-route-for-linux-ubuntu-centos-mint-etc

**Comment by hummuscience** [comment]
I did something similar. Using the .yaml file for ubuntu, I replaced the wheel from Ubuntu 16 to Ubuntu 18. Which is why everything works the way it should.

I am just surprised that it breaks the installation when I install (in the same environment) jupyter to use the jupyter notebooks.

Any idea which package that jupyter installs is messing this up?
