### ISSUE TITLE
Enqueue operation was cancelled

### ISSUE THREAD

**Issue by omaghsoudi** [DeepLabCut/DeepLabCut#61]
Hi guys,

I ran to an issue with training my own dataset (even your dataset gives the same error).
On step 6, when training using the following code:
``` python
TF_CUDNN_USE_AUTOTUNE=0 CUDA_VISIBLE_DEVICES=0 python3 ../../../train.py 
```
At  iteration 1,030,000 I get the following error:
```
iteration: 1000000 loss: 0.0013 lr: 0.001
iteration: 1001000 loss: 0.0013 lr: 0.001
iteration: 1002000 loss: 0.0013 lr: 0.001
iteration: 1003000 loss: 0.0013 lr: 0.001
iteration: 1004000 loss: 0.0013 lr: 0.001
iteration: 1005000 loss: 0.0013 lr: 0.001
iteration: 1006000 loss: 0.0013 lr: 0.001
iteration: 1007000 loss: 0.0013 lr: 0.001
iteration: 1008000 loss: 0.0013 lr: 0.001
iteration: 1009000 loss: 0.0013 lr: 0.001
iteration: 1010000 loss: 0.0014 lr: 0.001
iteration: 1011000 loss: 0.0013 lr: 0.001
iteration: 1012000 loss: 0.0013 lr: 0.001
iteration: 1013000 loss: 0.0013 lr: 0.001
iteration: 1014000 loss: 0.0013 lr: 0.001
iteration: 1015000 loss: 0.0013 lr: 0.001
iteration: 1016000 loss: 0.0013 lr: 0.001
iteration: 1017000 loss: 0.0013 lr: 0.001
iteration: 1018000 loss: 0.0013 lr: 0.001
iteration: 1019000 loss: 0.0013 lr: 0.001
iteration: 1020000 loss: 0.0013 lr: 0.001
iteration: 1021000 loss: 0.0014 lr: 0.001
iteration: 1022000 loss: 0.0013 lr: 0.001
iteration: 1023000 loss: 0.0013 lr: 0.001
iteration: 1024000 loss: 0.0013 lr: 0.001
iteration: 1025000 loss: 0.0013 lr: 0.001
iteration: 1026000 loss: 0.0013 lr: 0.001
iteration: 1027000 loss: 0.0013 lr: 0.001
iteration: 1028000 loss: 0.0013 lr: 0.001
iteration: 1029000 loss: 0.0012 lr: 0.001
iteration: 1030000 loss: 0.0013 lr: 0.001
2018-09-12 21:34:07.680932: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../../../train.py", line 49, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "../../../train.py", line 140, in <module>
    train()
  File "../../../train.py", line 83, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "../../../train.py", line 35, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 339, in enqueue
    self._queue_ref, vals, name=scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3977, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]

``` 

Any idea what the issue can be?

I am checking the "pose_cfg.yaml" file; it sounds that you limit it in multi step by 1,030,000. Is it right?
Is there any reason that it should be 1,030,000?

I should say that everything is working after that for testing and evaluating the trained netrow; but this error sounds weird.

Thank you!

**Comment by AlexEMG** [comment]
That is the expected behavior, once the learning rate schedule in [pose_cfg.yaml](https://github.com/AlexEMG/DeepLabCut/blob/master/Generating_a_Training_Set/pose_cfg.yaml)

reaches the final value optimization "stops".

Learning rate schedule for the SGD optimiser. 
multi_step:
- [0.005, 10000]
- [0.02, 430000]
- [0.002, 730000]
- [0.001, 1030000]

You can change the schedule of course, but frankly I never needed much more than 200,000 iterations, so you can perhaps consider to cancel earlier.
