### ISSUE TITLE
CancelledError: Enqueue operation was cancelled

### ISSUE THREAD

**Issue by jhalverson** [DeepLabCut/DeepLabCut#625]
RHEL 7.7
DLC: deeplabcut-2.1.6.2
x86_64

Below is our build procedure:
```
$ module load hdf5/gcc/1.8.16 anaconda3/2019.10 cudatoolkit/9.2 cudnn/cuda-9.2/7.3.1
$ export HDF5_DIR=/usr/local/hdf5/gcc/1.8.16
$ conda create --name deeplabcut-env python=3.6 wxPython=4.0.3
$ conda activate deeplabcut-env
$ pip install deeplabcut tensorflow-gpu==1.8
$ export HDF5_DIR=/usr/local/hdf5/gcc/1.8.16
$ export DLClight=True
##########################################
```

Below is the Slurm script:
```
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:15:00
#SBATCH --mem-per-cpu=4G
#SBATCH --gres=gpu:1

export HDF5_DIR=/usr/local/hdf5/gcc/1.8.16
export DLClight=True

module load hdf5/gcc/1.8.16 anaconda3/2019.10 cudatoolkit/9.2 cudnn/cuda-9.2/7.3.1
conda activate deeplabcut-env

python train_network.py
##########################################
```

Below is train_network.py:
```
import deeplabcut
# Loading example data set:
import os
# Note that parameters of this project can be seen at: *openfield-Pranav-2018-10-30/config.yaml*
from pathlib import Path

if __name__ == "__main__":
    path_config_file = os.path.join('/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/config.yaml')
    print(path_config_file)
    #
    deeplabcut.load_demo_data(path_config_file)
    # [OPTIONAL] Perhaps plot the labels to see how the frames were annotated:
    # (note, this project was created in Linux, so you might have an error in Windows, but this is an optional step)
    print('loaded data')
    deeplabcut.train_network(path_config_file, shuffle=1, gputouse=0,  displayiters=10, saveiters=50, maxiters=500)
    print('finished training') 
    deeplabcut.evaluate_network(path_config_file, plotting=True)
    print('script ist fertig')
##########################################
```

Below is the output:
```
$ cat slurm-4523386.out
Config:
{'all_joints': [[0], [1], [2], [3], [4]],
 'all_joints_names': ['Hand', 'Finger1', 'Tongue', 'Joystick1', 'Joystick2'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_ReachingAug30/Reaching_Mackenzie95shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_ReachingAug30/Documentation_data-Reaching_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 5,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': '/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/dlc-models/iteration-0/ReachingAug30-trainset95shuffle1/train/snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
iteration: 10 loss: 0.3294 lr: 0.005
iteration: 20 loss: 0.0457 lr: 0.005
iteration: 30 loss: 0.0389 lr: 0.005
iteration: 40 loss: 0.0337 lr: 0.005
iteration: 50 loss: 0.0292 lr: 0.005
iteration: 60 loss: 0.0284 lr: 0.005
iteration: 70 loss: 0.0293 lr: 0.005
iteration: 80 loss: 0.0244 lr: 0.005
iteration: 90 loss: 0.0256 lr: 0.005
iteration: 100 loss: 0.0246 lr: 0.005
iteration: 110 loss: 0.0212 lr: 0.005
iteration: 120 loss: 0.0217 lr: 0.005
iteration: 130 loss: 0.0202 lr: 0.005
iteration: 140 loss: 0.0209 lr: 0.005
iteration: 150 loss: 0.0239 lr: 0.005
iteration: 160 loss: 0.0199 lr: 0.005
iteration: 170 loss: 0.0228 lr: 0.005
iteration: 180 loss: 0.0202 lr: 0.005
iteration: 190 loss: 0.0202 lr: 0.005
iteration: 200 loss: 0.0250 lr: 0.005
iteration: 210 loss: 0.0236 lr: 0.005
iteration: 220 loss: 0.0131 lr: 0.005
iteration: 230 loss: 0.0227 lr: 0.005
iteration: 240 loss: 0.0186 lr: 0.005
iteration: 250 loss: 0.0233 lr: 0.005
iteration: 260 loss: 0.0171 lr: 0.005
iteration: 270 loss: 0.0201 lr: 0.005
iteration: 280 loss: 0.0180 lr: 0.005
iteration: 290 loss: 0.0207 lr: 0.005
iteration: 300 loss: 0.0170 lr: 0.005
iteration: 310 loss: 0.0163 lr: 0.005
iteration: 320 loss: 0.0158 lr: 0.005
iteration: 330 loss: 0.0187 lr: 0.005
iteration: 340 loss: 0.0152 lr: 0.005
iteration: 350 loss: 0.0182 lr: 0.005
iteration: 360 loss: 0.0172 lr: 0.005
iteration: 370 loss: 0.0156 lr: 0.005
iteration: 380 loss: 0.0158 lr: 0.005
iteration: 390 loss: 0.0156 lr: 0.005
iteration: 400 loss: 0.0204 lr: 0.005
iteration: 410 loss: 0.0175 lr: 0.005
iteration: 420 loss: 0.0156 lr: 0.005
iteration: 430 loss: 0.0169 lr: 0.005
iteration: 440 loss: 0.0189 lr: 0.005
iteration: 450 loss: 0.0161 lr: 0.005
iteration: 460 loss: 0.0198 lr: 0.005
iteration: 470 loss: 0.0161 lr: 0.005
iteration: 480 loss: 0.0154 lr: 0.005
iteration: 490 loss: 0.0263 lr: 0.005
iteration: 500 loss: 0.0180 lr: 0.005
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 81, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "train_network.py", line 16, in <module>
    deeplabcut.train_network(path_config_file, shuffle=1, gputouse=0,  displayiters=10, saveiters=50, maxiters=500)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 132, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 118, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 67, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 346, in enqueue
    self._queue_ref, vals, name=scope)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3977, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

CancelledError (see above for traceback): Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]


Config:
{'all_joints': [[0], [1], [2], [3], [4]],
 'all_joints_names': ['Hand', 'Finger1', 'Tongue', 'Joystick1', 'Joystick2'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_ReachingAug30/Reaching_Mackenzie95shuffle1.mat',
 'dataset_type': 'default',
 'deconvolutionstride': 2,
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_ReachingAug30/Documentation_data-Reaching_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 5,
 'optimizer': 'sgd',
 'output_stride': 16,
 'pos_dist_thresh': 17,
 'project_path': '/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/dlc-models/iteration-0/ReachingAug30-trainset95shuffle1/test/snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
100%|\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 55/55 [00:17<00:00,  3.07it/s]
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/config.yaml
Loaded, now creating training data...
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/training-datasets/iteration-0/UnaugmentedDataSet_ReachingAug30  already exists!
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/dlc-models/iteration-0/ReachingAug30-trainset95shuffle1  already exists!
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/dlc-models/iteration-0/ReachingAug30-trainset95shuffle1/train  already exists!
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/dlc-models/iteration-0/ReachingAug30-trainset95shuffle1/test  already exists!
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
loaded data
Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.
Starting with standard pose-dataset loader.
Initializing ResNet
Loading ImageNet-pretrained resnet_50
Max_iters overwritten as 500
Display_iters overwritten as 10
Save_iters overwritten as 50
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'weigh_only_present_joints': False, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/dlc-models/iteration-0/ReachingAug30-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'mirror': False, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'crop': True, 'cropratio': 0.4, 'minsize': 100, 'leftwidth': 400, 'rightwidth': 400, 'topheight': 400, 'bottomheight': 400, 'all_joints': [[0], [1], [2], [3], [4]], 'all_joints_names': ['Hand', 'Finger1', 'Tongue', 'Joystick1', 'Joystick2'], 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_ReachingAug30/Reaching_Mackenzie95shuffle1.mat', 'display_iters': 1000, 'init_weights': '/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'max_input_size': 1500, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_ReachingAug30/Documentation_data-Reaching_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 5, 'pos_dist_thresh': 17, 'project_path': '/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30', 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'output_stride': 16, 'deconvolutionstride': 2}
Starting training....
The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
finished training
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/evaluation-results/  already exists!
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/evaluation-results/iteration-0/ReachingAug30-trainset95shuffle1  already exists!
Running  DLC_resnet50_ReachingAug30shuffle1_500  with # of trainingiterations: 500
This net has already been evaluated!
Plotting...(attention scale might be inconsistent in comparison to when data was analyzed; i.e. if you used rescale)
/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/evaluation-results/iteration-0/ReachingAug30-trainset95shuffle1/LabeledImages_DLC_resnet50_ReachingAug30shuffle1_500_snapshot-500  already exists!
script ist fertig
##########################################
```
Does anyone know how to resolve the error?

**Comment by MMathisLab** [comment]
Here is your script (formated):

```
import deeplabcut

Loading example data set:
import os

Note that parameters of this project can be seen at: openfield-Pranav-2018-10-30/config.yaml
from pathlib import Path

if name == "main":
  path_config_file = os.path.join('/home/jdh4/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/config.yaml')
  print(path_config_file)
  #
  deeplabcut.load_demo_data(path_config_file)
  # [OPTIONAL] Perhaps plot the labels to see how the frames were annotated:
  # (note, this project was created in Linux, so you might have an error in Windows, but this is an optional step)
  print('loaded data')
  deeplabcut.train_network(path_config_file, shuffle=1, gputouse=0, displayiters=10, saveiters=50, maxiters=500)
  print('finished training')
  deeplabcut.evaluate_network(path_config_file, plotting=True)
  print('script ist fertig')
```

After evaluation, you ask it print `'script ist fertig'` ... so it got through all the steps, that is the expected output. The stop after training is why you have the `enqueue operation was cancelled`, as you force stop training.  ` displayiters=10, saveiters=50, maxiters=500` 

This is also described in the demo notebook: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/COLAB_DEMO_mouse_openfield.ipynb

```
#let's also change the display and save_iters just in case Colab takes away the GPU... 
#if that happens, you can reload from a saved point. Typically, you want to train to 200,000 + iterations.
#more info and there are more things you can set: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#g-train-the-network

deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10,saveiters=100)

#this will run until you stop it (CTRL+C), or hit "STOP" icon, or when it hits the end (default, 1.03M iterations). 
#Whichever you chose, you will see what looks like an error message, but it's not an error - don't worry....
```

So, this is the expected behavior, fully ;) ... schön tag

**Comment by hmaarrfk** [comment]
I'm sorry for opening up a new thread. We have been working through a few different integration challenges in our ML pipeline.

I believe the original question may be rephrased as: "Why does the following error message appear"

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 81, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "train_network.py", line 16, in <module>
    deeplabcut.train_network(path_config_file, shuffle=1, gputouse=0,  displayiters=10, saveiters=50, maxiters=500)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 132, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 118, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 67, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 346, in enqueue
    self._queue_ref, vals, name=scope)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3977, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/jdh4/.conda/envs/deeplabcut-env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

CancelledError (see above for traceback): Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue, _arg_Placeholder_0_0, _arg_Placeholder_1_0_1, _arg_Placeholder_2_0_2, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4)]]
```

I'm not sure if it is the cause of some of issues we've been seeing between 
```
multiprocessing.set_start_method('fork')
# ^^^^^ This seems to cause our python interpreter to hang upon closing.
```
vs 
```
multiprocessing.set_start_method('forkserver')
# or
multiprocessing.set_start_method('spawn')
```

It may be that the model trains fine, but it is a little concerning to see a traceback during "normal" operation.

**Comment by hmaarrfk** [comment]
Also, I'm happy to open a new issue if you prefer.
