### ISSUE TITLE
"UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above."

### ISSUE THREAD

**Issue by Ejdrup** [DeepLabCut/DeepLabCut#667]
Im on Windows 10 using DLC 2.1.7 in a conda environment following your installation guide running in chrome. I have a GTX 1660 TI and I'm running your Demo_yourowndata.ipynb

DeepLabCut works perfectly until it's time starting to train the network. Upon initializing:

`deeplabcut.train_network(path_config_file)`

I get the following lengthy error message:
```
Starting training....
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
	 [[{{node train_op/control_dependency}}]]

During handling of the above exception, another exception occurred:

UnknownError                              Traceback (most recent call last)
<ipython-input-4-7e3f40db92d4> in <module>
----> 1 deeplabcut.train_network(path_config_file)

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights)
    132         train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
    133     except BaseException as e:
--> 134         raise e
    135     finally:
    136         os.chdir(str(start_path))

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights)
    130             os.environ['CUDA_VISIBLE_DEVICES'] = str(gputouse)
    131     try:
--> 132         train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
    133     except BaseException as e:
    134         raise e

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep, keepdeconvweights, allow_growth)
    188         current_lr = lr_gen.get_lr(it)
    189         [_, loss_val, summary] = sess.run([train_op, total_loss, merged_summaries],
--> 190                                           feed_dict={learning_rate: current_lr})
    191         cum_loss += loss_val
    192         train_writer.add_summary(summary, it)

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node resnet_v1_50/conv1/Conv2D (defined at C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py:52) ]]
	 [[node train_op/control_dependency (defined at C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:102) ]]

Caused by op 'resnet_v1_50/conv1/Conv2D', defined at:
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\asyncio\base_events.py", line 1786, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-7e3f40db92d4>", line 1, in <module>
    deeplabcut.train_network(path_config_file)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 132, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 119, in train
    losses = pose_net(cfg).train(batch)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 154, in train
    heads = self.get_net(batch[Batch.inputs])
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 81, in get_net
    net, end_points = self.extract_features(inputs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 52, in extract_features
    global_pool=False, output_stride=self.cfg.output_stride,is_training=False)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 274, in resnet_v1_50
    scope=scope)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 205, in resnet_v1
    net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_utils.py", line 146, in conv2d_same
    scope=scope)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1155, in convolution2d
    conv_dims=2)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1058, in convolution
    outputs = layer.apply(inputs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\layers\base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 208, in __call__
    name=self.name)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node resnet_v1_50/conv1/Conv2D (defined at C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py:52) ]]
	 [[node train_op/control_dependency (defined at C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:102) ]]
```

I have CUDA 10.0, TF 1.13.1 and
`(DLC-GPU) C:\windows\system32>conda list cudnn`
yields
`cudnn                     7.6.5                cuda10.0_0`

Looking for solutions I ran into the command:
`os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'`
Which removes the error message and starts the training, but the on displayiter = 1000 nothing happens and on displayiter = 100 only the first two iterations succeed in just a few min, and the it just stops progressing.. Ive let it run overnight.

**Comment by MMathisLab** [comment]
Could you try these test with your GPU installation:
- https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#the-most-common-new-user-hurdle-is-installing-and-using-your-gpu

Also, perhaps this post might have some solutions:
- https://forum.image.sc/t/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-initialize/26353

- https://github.com/tensorflow/tensorflow/issues/24828

**Comment by Ejdrup** [comment]
The test returns the following:
```
2020-04-28 20:23:54.956611: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-04-28 20:23:55.096878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.77
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.92GiB
2020-04-28 20:23:55.101740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-04-28 20:23:55.413610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-28 20:23:55.416523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2020-04-28 20:23:55.418287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2020-04-28 20:23:55.420131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4639 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
2020-04-28 20:23:55.430530: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
```

The 2nd seems to link to a thread where the majority of people suggest:
`pip install --upgrade tensorflowgpu==1.8.0`
But that does not seem to work for me.

Do you suggest uninstalling cudnn and CUDA with conda and rely on a separate manual installation?

Edit: I attempted to uninstall cudnn, which also removed tensorfor. Reinstalling tensorflow-gpu==1.13.1 did not fix the issue.

My anaconda console returns the following upon trying to start the training:
`2020-04-28 20:38:54.287929: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED`

Edit 2: Browsing I found this: https://forum.image.sc/t/could-not-create-cudnn-handle-cudnn-status-alloc-failed/34836. Do you believe the same applies?

**Comment by MMathisLab** [comment]
you should check `nvidia-smi` to be sure your GPU is not allocated elsewhere; we don't recommend setting the environ variable, rather use the built in function for training. You can check all the options for every function with `deeplabcut.train_network?` 

and you will see you can set allow_growth=True in the function; it is false by default, as with GPUs less than 8GB, DLC will just crash out as it's too small of a GPU, which also might be your issue - you might consider training on COLAB ... https://github.com/AlexEMG/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb

I will close for now, as it's not a DLC code issue per se, but please report back!

**Comment by Ejdrup** [comment]
nvidia-smi prompts:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.41       Driver Version: 441.41       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166... WDDM  | 00000000:01:00.0  On |                  N/A |
| 30%   41C    P2    31W / 120W |   5566MiB /  6144MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1488    C+G   Insufficient Permissions                   N/A      |
|    0      2408    C+G   Insufficient Permissions                   N/A      |
|    0      3816    C+G   ...x64__8wekyb3d8bbwe\Microsoft.Photos.exe N/A      |
|    0      7492    C+G   C:\Windows\explorer.exe                    N/A      |
|    0      8052    C+G   ...oftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe N/A      |
|    0      8236    C+G   ...hell.Experiences.TextInput.InputApp.exe N/A      |
|    0      8372    C+G   ...5n1h2txyewy\StartMenuExperienceHost.exe N/A      |
|    0      8436    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
|    0      8904    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0      9760    C+G   ...6.102.0_x64__kzf8qxf38zg5c\SkypeApp.exe N/A      |
|    0      9804    C+G   ....111.0_x64__8wekyb3d8bbwe\YourPhone.exe N/A      |
|    0     10344    C+G   ...mmersiveControlPanel\SystemSettings.exe N/A      |
|    0     11292    C+G   ...6)\Google\Chrome\Application\chrome.exe N/A      |
|    0     12680    C+G   ...11011.0_x64__8wekyb3d8bbwe\Video.UI.exe N/A      |
|    0     13680    C+G   ...1.0_x64__8wekyb3d8bbwe\WinStore.App.exe N/A      |
|    0     15308      C   ...mData\Anaconda3\envs\DLC-GPU\python.exe N/A      |
|    0     15972    C+G   ...x86__8wekyb3d8bbwe\Office16\OUTLOOK.EXE N/A      |
+-----------------------------------------------------------------------------+
```

I managed to get it working by uninstalling the conda assocaited cudnn, as it seems to be the wrong version, which fixed it.

Now it merrily begins training, and under task manager -> performance -> GPU -> Cuda I can see it churning away. However, it stops after 1000-2000 iterations and the Cuda computing drops to 0%.

Weird.
