### ISSUE TITLE
extract_outlier_frames GUI - indexing and loading of labels not correct

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#669]
Hi,

It seems that the problem with indexing persists in the latest dlc upgrade.

CentOS 7, DLC 2.1.7
extract_outlier_frames(config_path, 'one.avi file', outlieralgorithm= ‘manual’)

1) load movie - 170fps / 1440 x 1080
2) use sidebar to scroll through video
- first 3 frames show correct label location in the frame - continue scrolling
- then the labels do not match the frame anymore - continue scrolling
- no more labels visible in the frame
3) traceback in the terminal
```
deeplabcut.extract_outlier_frames(config_path,['/data/DLC/movies/video.avi'], outlieralgorithm='manual')
Traceback (most recent call last):
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
self.plot_labels()
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 1780 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
self.plot_labels()
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 1780 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
self.plot_labels()
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2041 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
self.plot_labels()
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2041 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
self.plot_labels()
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2373 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
self.plot_labels()
File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2373 is out of bounds for axis 0 with size 1501
```

**Comment by MMathisLab** [comment]
this is a repeat of your comment on #654 - I will answer there; please don't open new issues if others are being worked on for you  ;).
