### ISSUE TITLE
Unclear bug post training

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#683]
**Describe the bug**
Training run ended with a weird error report, but network still seem to be trained/working.

**To Reproduce**
n/a

**Expected behavior**
End training without error report

**Desktop (please complete the following information about your system):**
 - OS: Linux
 - DeepLabCut Version: 2.1.7
 - Browser: firefox

```
`iteration: 1027000 loss: 0.0007 lr: 0.001
iteration: 1028000 loss: 0.0007 lr: 0.001
iteration: 1029000 loss: 0.0007 lr: 0.001
iteration: 1030000 loss: 0.0007 lr: 0.001
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cat/Downloads/DeepLabCut/deeplabcut/pose_estimation_tensorflow/train.py", line 81, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[node fifo_queue_enqueue (defined at /home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'fifo_queue_enqueue':
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 558, in mainloop
    self.interact()
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 549, in interact
    self.run_cell(code, store_history=True)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3242, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
    deeplabcut.launch_dlc()
  File "/home/cat/Downloads/DeepLabCut/deeplabcut/gui/launch_script.py", line 45, in launch_dlc
    app.MainLoop()
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/wx/core.py", line 2134, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "/home/cat/Downloads/DeepLabCut/deeplabcut/gui/train_network.py", line 268, in train_network
    maxiters=maxiters)
  File "/home/cat/Downloads/DeepLabCut/deeplabcut/pose_estimation_tensorflow/training.py", line 132, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
  File "/home/cat/Downloads/DeepLabCut/deeplabcut/pose_estimation_tensorflow/train.py", line 118, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/home/cat/Downloads/DeepLabCut/deeplabcut/pose_estimation_tensorflow/train.py", line 67, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/ops/data_flow_ops.py", line 346, in enqueue
    self._queue_ref, vals, name=scope)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_data_flow_ops.py", line 4410, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/cat/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
WARNING:tensorflow:From /home/cat/Downloads/DeepLabCut/deeplabcut/pose_estimation_tensorflow/predict_videos.py:127: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
```
`

**Additional context**

**Comment by AlexEMG** [comment]
This is just a "queuing bug", nothing to worry about (normally)

**Comment by catubc** [comment]
Ok, shall I close the issue or do you guys want to keep it until it is fixed?

**Comment by MMathisLab** [comment]
just what happens when it hits the 1.3 M mark ;)
