### ISSUE TITLE
file closed error on check labeled images - fixed with updating pillow

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#695]
**Describe the bug**
After updating to DLC 2.2b5 inside existing conda env, error creating labeled images (closed file error). Fixed with updating Pillow from 7.1.1 to 7.1.2 (pip install --upgrade Pillow). Should be fine with new env installs, but may want to require Pillow >=7.1.2 in setup.py.

**To Reproduce**
1. From within a previous deeplabcut conda env, pip install deeplabcut==2.2b5
2. Make a project in GUI, label frames, click either "Check Labels" button. 
3. Labeled folder created, but no labeled images
3. Received the following traceback:
```
Creating images with labels by BEJ.
Traceback (most recent call last):
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/gui/label_frames.py", line 136, in check_labelInd
    deeplabcut.check_labels(self.config, visualizeindividuals=True)
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 513, in check_labels
    color_by=color_by,
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/utils/visualization.py", line 286, in make_labeled_images_from_dataframe
    ic = io.imread_collection(images.to_list())
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/skimage/io/_io.py", line 91, in imread_collection
    plugin=plugin, **plugin_args)
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/skimage/io/collection.py", line 391, in imread_collection
    load_func=imread)
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/skimage/io/collection.py", line 182, in __init__
    self._numframes = self._find_images()
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/skimage/io/collection.py", line 231, in _find_images
    im.seek(i)
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 748, in seek
    self._seek(f)
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 784, in _seek
    ImageFile._safe_read(self.fp, self.__prepare_idat)
  File "/Users/jacksonbe3/opt/miniconda3/envs/DLC/lib/python3.7/site-packages/PIL/ImageFile.py", line 549, in _safe_read
    return fp.read(size)
ValueError: read of closed file
```
**Expected behavior**
labeled images
**Desktop (please complete the following information about your system):**
 - OS: macOS 10.15.4
 - DeepLabCut Version: 2.2b5

**Comment by MMathisLab** [comment]
Thanks, Brandon! Good idea to temporarily pin this feel free to make a PR if you’d like.

and since I'm sure others might encounter this, please run inside your env:

`pip install --upgrade Pillow`

**Comment by JelleKn** [comment]
Thanks Brandon, this helped me solve the issue in no time!
