### ISSUE TITLE
Index error while analyzing the video

### ISSUE THREAD

**Issue by chanduborkar** [DeepLabCut/DeepLabCut#703]
I am using WIN10, ANconda, Deeplabcut =2.2.b5
After analyzing the video I see 'Indexing error: List index out of range' at the end. 
Pasting here prompt 
```
(base) C:\WINDOWS\system32>A:

(base) A:\>activate DLC-CPU

(DLC-CPU) A:\>ipython
Python 3.7.7 (default, Apr 15 2020, 05:09:04) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut

In [2]: deeplabcut.launch_dlc()
Created "A:\Test\Demo-chandu-2020-05-25\videos"
Created "A:\Test\Demo-chandu-2020-05-25\labeled-data"
Created "A:\Test\Demo-chandu-2020-05-25\training-datasets"
Created "A:\Test\Demo-chandu-2020-05-25\dlc-models"
Attempting to create a symbolic link of the video ...
Created the symlink of A:\Test\Recall.mp4 to A:\Test\Demo-chandu-2020-05-25\videos\Recall.mp4
A:\Test\Demo-chandu-2020-05-25\videos\Recall.mp4
Generated "A:\Test\Demo-chandu-2020-05-25\config.yaml"

A new project with name Demo-chandu-2020-05-25 is created at A:\Test and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 935.9  seconds.
Extracting and downsampling... 28077  frames from the video.
28077it [00:17, 1561.99it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
No images found!!
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in browseDir(self, event)
    487
    488 # Reading the image name
--> 489         self.img = self.index[self.iter]
    490         img_name = Path(self.index[self.iter]).name
    491         self.norm,self.colorIndex = self.image_panel.getColorIndices(self.img,self.bodyparts)

IndexError: index 0 is out of bounds for axis 0 with size 0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in nextImage(self, event)
    569
    570         self.statusbar.SetStatusText('Working on folder: {}'.format(os.path.split(str(self.dir))[-1]))
--> 571         self.rdb.SetSelection(0)
    572         self.file = 1
    573 # Refreshing the button counter

AttributeError: 'MainFrame' object has no attribute 'rdb'
You can now check the labels, using 'check_labels' before proceeding. Then, you can use the function 'create_training_dataset' to create the training dataset.
Downloading a ImageNet-pretrained model from https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz....
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['EarL', 'EarR', 'Tail'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Demo_chandu95shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\chand\\anaconda3\\envs\\DLC-CPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\mobilenet_v2_1.0_224.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Documentation_data-Demo_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'mobilenet_v2_1.0',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'A:\\Test\\Demo-chandu-2020-05-25',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'A:\\Test\\Demo-chandu-2020-05-25\\dlc-models\\iteration-0\\DemoMay25-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.
Starting with standard pose-dataset loader.
Initializing MobileNet
WARNING:tensorflow:From C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\ops\losses\losses_impl.py:209: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Loading ImageNet-pretrained mobilenet_v2_1.0
WARNING:tensorflow:From C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mobilenet_v2_1.0_224.ckpt
Max_iters overwritten as 1000
Display_iters overwritten as 100
Save_iters overwritten as 1000
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'weigh_only_present_joints': False, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'A:\\Test\\Demo-chandu-2020-05-25\\dlc-models\\iteration-0\\DemoMay25-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'mirror': False, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'crop': True, 'cropratio': 0.4, 'minsize': 100, 'leftwidth': 400, 'rightwidth': 400, 'topheight': 400, 'bottomheight': 400, 'all_joints': [[0], [1], [2]], 'all_joints_names': ['EarL', 'EarR', 'Tail'], 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Demo_chandu95shuffle1.mat', 'display_iters': 1000, 'init_weights': 'C:\\Users\\chand\\anaconda3\\envs\\DLC-CPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\mobilenet_v2_1.0_224.ckpt', 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Documentation_data-Demo_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'mobilenet_v2_1.0', 'num_joints': 3, 'pos_dist_thresh': 17, 'project_path': 'A:\\Test\\Demo-chandu-2020-05-25', 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25}
Starting training....
iteration: 100 loss: 0.1297 lr: 0.005
iteration: 200 loss: 0.0409 lr: 0.005
iteration: 300 loss: 0.0346 lr: 0.005
iteration: 400 loss: 0.0309 lr: 0.005
iteration: 500 loss: 0.0296 lr: 0.005
iteration: 600 loss: 0.0264 lr: 0.005
iteration: 700 loss: 0.0260 lr: 0.005
iteration: 800 loss: 0.0250 lr: 0.005
iteration: 900 loss: 0.0224 lr: 0.005
iteration: 1000 loss: 0.0219 lr: 0.005
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 81, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:67) ]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 558, in mainloop
    self.interact()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 549, in interact
    self.run_cell(code, store_history=True)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 45, in launch_dlc
    app.MainLoop()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\label_frames.py", line 102, in label_frames
    deeplabcut.label_frames(self.config)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 260, in label_frames
    labeling_toolbox.show(config,imtypes=imtypes)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 702, in show
    app.MainLoop()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\label_frames.py", line 102, in label_frames
    deeplabcut.label_frames(self.config)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 260, in label_frames
    labeling_toolbox.show(config,imtypes=imtypes)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 702, in show
    app.MainLoop()
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\train_network.py", line 268, in train_network
    maxiters=maxiters)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 132, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 118, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 67, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 345, in enqueue
    self._queue_ref, vals, name=scope)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4157, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:67) ]]


The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['EarL', 'EarR', 'Tail'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Demo_chandu95shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\chand\\anaconda3\\envs\\DLC-CPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\mobilenet_v2_1.0_224.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Documentation_data-Demo_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'mobilenet_v2_1.0',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'A:\\Test\\Demo-chandu-2020-05-25',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'A:\\Test\\Demo-chandu-2020-05-25\\dlc-models\\iteration-0\\DemoMay25-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Running  DLC_mobnet_100_DemoMay25shuffle1_1000  with # of trainingiterations: 1000
Initializing MobileNet
INFO:tensorflow:Restoring parameters from A:\Test\Demo-chandu-2020-05-25\dlc-models\iteration-0\DemoMay25-trainset95shuffle1\train\snapshot-1000
Analyzing data...
10it [00:08,  1.24it/s]
Done and results stored for snapshot:  snapshot-1000
C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py:370: RuntimeWarning: Mean of empty slice
  testerrorpcutoff = np.nanmean(RMSEpcutoff.iloc[testIndices].values.flatten())
C:\Users\chand\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py:371: RuntimeWarning: Mean of empty slice
  trainerrorpcutoff = np.nanmean(RMSEpcutoff.iloc[trainIndices].values.flatten())
Results for 1000  training iterations: 95 1 train error: 19.45 pixels. Test error: 8.02  pixels.
With pcutoff of 0.6  train error: nan pixels. Test error: nan pixels
Thereby, the errors are given by the average distances between the labels by DLC and the scorer.
Plotting...
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.40it/s]
The network is evaluated and the results are stored in the subdirectory 'evaluation_results'.
If it generalizes well, choose the best model for prediction and update the config file with the appropriate index for the 'snapshotindex'.
Use the function 'analyze_video' to make predictions on new videos.
Otherwise consider retraining the network (see DeepLabCut workflow Fig 2)
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['EarL', 'EarR', 'Tail'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Demo_chandu95shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\chand\\anaconda3\\envs\\DLC-CPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\mobilenet_v2_1.0_224.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_DemoMay25\\Documentation_data-Demo_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'mobilenet_v2_1.0',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'A:\\Test\\Demo-chandu-2020-05-25',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'A:\\Test\\Demo-chandu-2020-05-25\\dlc-models\\iteration-0\\DemoMay25-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-1000 for model A:\Test\Demo-chandu-2020-05-25\dlc-models\iteration-0\DemoMay25-trainset95shuffle1
Initializing MobileNet
INFO:tensorflow:Restoring parameters from A:\Test\Demo-chandu-2020-05-25\dlc-models\iteration-0\DemoMay25-trainset95shuffle1\train\snapshot-1000
Starting to analyze %  A:\Test\Recall.mp4
Loading  A:\Test\Recall.mp4
Duration of video [s]:  935.9 , recorded with  30.0 fps!
Overall # of frames:  28077  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
28280it [9:07:00,  1.18s/it]                                                                                           Detected frames:  28077
28280it [9:08:35,  1.16s/it]
Saving results in A:\Test...
Saving csv poses!
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!
Filtering with median model A:\Test\Recall.mp4
3it [00:00, 33.80it/s]
Saving filtered csv poses!
Starting %  A:\Test ['A:\\Test\\Recall.mp4']
Loading  A:\Test\Recall.mp4 and data.
28077
Duration of video [s]:  935.9 , recorded with  30.0 fps!
Overall # of frames:  28077 with cropped frame dimensions:  640 480
Generating frames and creating video.
100%|███████████████████████████████████████████████████████████████████████████| 28077/28077 [01:22<00:00, 341.93it/s]
A:\Test\Recall.mp4
Starting %  A:\Test A:\Test\Recall.mp4
Loading  A:\Test\Recall.mp4 and data.
A:\Test  already exists!
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\analyze_videos.py in analyze_videos(self, event)
    271         if self.trajectory.GetStringSelection() == "Yes":
    272             deeplabcut.plot_trajectories(self.config, self.filelist, displayedbodyparts=self.bodyparts,
--> 273                                          videotype=self.videotype.GetValue(), shuffle=shuffle, trainingsetindex=trainingsetindex, filtered=True, showfigures=False, destfolder=self.destfolder)
    274
    275     def reset_analyze_videos(self,event):

~\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\utils\plotting.py in plot_trajectories(config, videos, videotype, shuffle, trainingsetindex, filtered, displayedbodyparts, showfigures, destfolder)
    183                 tmpfolder = os.path.join(basefolder,'plot-poses', vname)
    184                 auxiliaryfunctions.attempttomakefolder(tmpfolder)
--> 185                 PlottingResults(tmpfolder, Dataframe, DLCscorer, cfg, bodyparts, showfigures, suffix+'.png')
    186
    187     print('Plots created! Please check the directory "plot-poses" within the video directory')

~\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\utils\plotting.py in PlottingResults(tmpfolder, Dataframe, scorer, cfg, bodyparts2plot, showfigures, suffix)
     53     plt.savefig(os.path.join(tmpfolder,"trajectory"+suffix))
     54     plt.figure(figsize=(30, 10))
---> 55     Time=np.arange(np.size(Dataframe[scorer][bodyparts2plot[0]]['x'].values))
     56
     57     for bpindex, bp in enumerate(bodyparts2plot):

IndexError: list index out of range
```

**A separate folder is created for 'plot-poses' with trajectory plot which is blank.** 
![trajectory_filtered](https://user-images.githubusercontent.com/53411725/82910934-dcceac00-9f30-11ea-9153-ad214fe44f7a.png)

**Comment by AlexEMG** [comment]
What did you pass as bodyparts?
`PlottingResults(tmpfolder, Dataframe, DLCscorer, cfg, bodyparts, showfigures, suffix+'.png')`

**Comment by chanduborkar** [comment]
I did change body parts as 'EarL',  'EarR', and 'Tail' in YAML file.

**Comment by MMathisLab** [comment]
@chanduborkar Alex is asking what you did at the point when you `create_labeled_video`, i.e. in the Project Manager GUI is says "plot all bodyparts?" did you check yes?

**Comment by chanduborkar** [comment]
Yes, I did that!

**Comment by jeylau** [comment]
This is odd. You had a "no images found" error early on, making the labeling GUI complain. Could you annotate frames?

**Comment by chanduborkar** [comment]
@jeylau you are right, 'no images found' error was due to a path to the wrong folder, which was corrected in the next input command. After that, I could annotate (you mean label?) the frames---trained the network--- analyzed the video. 
After that finished, I anaconda prompt was showing an error "IndexError: list index out of range".  
In the folder 'plot-poses'  trajectory plot was empty as depicted in the above image.

**Comment by MMathisLab** [comment]
@chanduborkar given you are not using the multi-animal parts of 2.2, I would strongly suggest using the stable release. i.e., the last stable release we have is 2.1.8.2 on pypi. Can you run pip `install deeplabcut==2.1.8.2` then run analyze_videos again?

PS - running training for mobilenetv2 1,000 iterations will be **way too short** to get good performance - you will need to train to ~200K.

> Results for 1000  training iterations: 95 1 train error: 19.45 pixels. Test error: 8.02  pixels.
With pcutoff of 0.6  train error: nan pixels. Test error: nan pixels

in you env (copy/paste this):

```python
ipython
import deeplabcut as dllc 
config = 'A:\Test\Demo-chandu-2020-05-25\config.yaml'
video = ['A:\\Test\\Recall.mp4']

dlc.analyze_videos(config, video, videotype='mp4')
dlc.filterpredictions(config, video, videotype='mp4')
dlc.create_labeled_video(config, video, videotype='mp4', filtered=True)

```

**Comment by chanduborkar** [comment]
@MMathisLab Thanks a lot for your help. I am training network again with a higher number of iterations and let's see.

**Comment by MMathisLab** [comment]
thanks! I will close for now, but please report back on this thread :)

**Comment by chanduborkar** [comment]
Hi @MMathisLab , Sorry for the late update. Your suggestions have worked! 
However I have few questions:
1) As you can see some outliers in the image, I was trying to extract these frames but GUI and terminal it was nonresponsive.  Would you please suggest the way out?
2) How to analyse/interpret this data? Do you have any video/notes on that?
3) If I close the GUI and terminal now, and load the same folder in GUI afterwards, can I take this step forward from here? Or I need to redo whole process? 

Thank you so much for your help!

![image](https://user-images.githubusercontent.com/53411725/85070038-bc35f280-b17a-11ea-8077-f43c7ca510c9.png)

![image](https://user-images.githubusercontent.com/53411725/85070268-22227a00-b17b-11ea-94d1-9fbb6eddaafe.png)

**Comment by MMathisLab** [comment]
> If I close the GUI and terminal now, and load the same folder in GUI afterwards, can I take this step forward from here? Or I need to redo whole process?

Yep! You can always close and just reload by pointing to the config.yaml file ("load project")

> check out DLCUtils for some analyze code: https://github.com/DeepLabCut

**Comment by chanduborkar** [comment]
Okay thanks!
