### ISSUE TITLE
Multianimal GPU training not starting on DLC 2.2b6 (AttributeError: module 'numpy.random' has no attribute 'bit_generator)

### ISSUE THREAD

**Issue by alesantuz** [DeepLabCut/DeepLabCut#729]
OS: Windows 10 build 18363
DeepLabCut Version: 2.2b6
Anaconda env used: dlc-windowsGPU

Converted pre-2.2 labels to multianimal with (works flawlessly, thanks for updating):
```python
deeplabcut.convert2_maDLC(path_config_file, userfeedback=False)
```
Created the new multianimal dataset with:
```python
deeplabcut.create_multianimaltraining_dataset(path_config_file)
```
Started training with (displayiters=10 just for checking):
```python
deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10, saveiters=10000, max_snapshots_to_keep=2)
```
Unfortunately training on GPU does not start and appears to be frozen (I let it run for around 4 hours):

![Annotation 2020-06-05 092209](https://user-images.githubusercontent.com/7524938/83875794-090bd900-a738-11ea-800a-956a54b86e59.png)

This happened several times and I could never start the training. Please let me know if and how I can provide more info on this issue.

Traceback:
```python
Activating limb prediction...
Starting with multi-animal imaug + adam pose-dataset loader.
Batch Size is 8
Getting specs multi-animal-imgaug 52 17
Initializing ResNet
Loading ImageNet-pretrained resnet_50
2020-06-05 05:00:56.774839: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-06-05 05:00:57.033499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:17:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2020-06-05 05:00:57.153841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 1 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:65:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2020-06-05 05:00:57.159104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1
2020-06-05 05:00:57.816870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-05 05:00:57.819636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1
2020-06-05 05:00:57.821401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N Y
2020-06-05 05:00:57.823139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   Y N
2020-06-05 05:00:57.824973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8618 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:17:00.0, compute capability: 7.5)
2020-06-05 05:00:57.831857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 8618 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
Exception in thread Thread-130:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 76, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\dataset\pose_multianimal_imgaug.py", line 247, in next_batch
    height=target_size[0], width=target_size[1], apply_prob=0.5
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\dataset\pose_multianimal_imgaug.py", line 80, in build_augmentation_pipeline
    pipeline = iaa.Sequential(random_order=False)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\augmenters\meta.py", line 2928, in __init__
    random_state=random_state)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\augmenters\meta.py", line 283, in __init__
    self.random_state = iarandom.RNG(random_state)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\random.py", line 142, in __init__
    self.generator = normalize_generator_(generator)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\random.py", line 841, in normalize_generator_
    return _normalize_generator_np117_(generator)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\random.py", line 846, in _normalize_generator_np117_
    return get_global_rng().generator
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\random.py", line 738, in get_global_rng
    GLOBAL_RNG = RNG(convert_seed_to_generator(seed))
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\random.py", line 142, in __init__
    self.generator = normalize_generator_(generator)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\random.py", line 841, in normalize_generator_
    return _normalize_generator_np117_(generator)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\imgaug\random.py", line 851, in _normalize_generator_np117_
    elif isinstance(generator, np.random.bit_generator.BitGenerator):
AttributeError: module 'numpy.random' has no attribute 'bit_generator'
```

**Comment by AlexEMG** [comment]
I'm sorry, that's a numpy/imgaug compatibility issue, with a fix described here https://github.com/aleju/imgaug/issues/537

**Comment by MMathisLab** [comment]
be be sure `numpy 1.16.4` is the version you are using ;)

**Comment by MMathisLab** [comment]
hi @alesantuz did changing your numpy resolve this?

**Comment by alesantuz** [comment]
Hi @MMathisLab, I am afraid it did not (to be fair it did solve the issue, but another arose). It looks like the allocator runs out of memory, something I have rarely experienced before on that machine (2x[NVIDIA GeForce RTX 2080 Ti](https://www.nvidia.com/en-us/geforce/graphics-cards/rtx-2080-ti/#specs)).
```python
Starting multi-animal training....
2020-06-09 04:37:14.370858: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 8.00MiB.  Current allocation summary follows.
```
Then a ginormous amount of lines follows with specific info about each chunk's size, only to end with:
```python
2020-06-09 04:37:29.964775: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 8.33GiB
2020-06-09 04:37:29.966710: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats:
Limit:                  9037557924
InUse:                  8946418944
MaxInUse:               9037557760
NumAllocs:                    1777
MaxAllocSize:            931019008

2020-06-09 04:37:29.972197: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ***************************************************************************************************_
2020-06-09 04:37:29.975846: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at conv_ops.cc:446 : Resource exhausted: OOM when allocating tensor with shape[8,2048,44,65] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408

ResourceExhaustedError: OOM when allocating tensor with shape[2048,1024,1,1] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/shortcut/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
...and more similar lines. I remembered though that during the workshop the batch size could create this kind of issues. If I set `batch_size: 1` in the `pose_cfg.yaml` file, then the training starts (will update on the outcomes). Is it really necessary to impose `batch_size: 8`?

**Comment by MMathisLab** [comment]
Yes, that’s a different error. :) I guess you did not run `cropandlabelframes` before creating the training set (we highly recommend for maDLC) your images are massive ... and if you change batch to 1 you need to change the learning rate!  I would highly recommend not changing batch size and simply run the above step to fit in on your gpu and doing batch training....

https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

> maDeepLabCut CRITICAL POINT: For multi-animal projects we are using not only different and new output layers, but also new data augmentation, optimization, learning rates, and batch training defaults. Thus, please use a lower save_iters and maxiters. I.e. we suggest saving every 10K-15K iterations, and only training until 50K-100K iterations. We recommend you look closely at the loss to not overfit on your data. The bonus, training time is much less!!!

**Comment by alesantuz** [comment]
You guessed right, I did not run that. Thank you Mackenzie, I will do it and let you know.
