### ISSUE TITLE
Compute Canada python venv based deeplabcut installation fails to import with tensorflow-cpu==1.13.1 due to bug in tf

### ISSUE THREAD

**Issue by suntzuisafterU** [DeepLabCut/DeepLabCut#731]
**Describe the bug**

tensorflow-cpu==1.13.1 fails when attempting to load dlc (core and/or with DLClight=True) inside of an evironment configured to run headlessly. The equivalent GPU environment works as expected. 

**Desktop (please complete the following information about your system):**
 - OS: Linux
         NAME="Red Hat Enterprise Linux Server"
         VERSION="7.7 (Maipo)"
 - deeplabcut 2.1.8.2 and deeplabcutcore 0.0b3
      - tensorflow-cpu==1.13.1
 - headless envirnoment with `DLClight=True` set.
 - SLURM Compute Canada cluster environment; 

**To Reproduce**
Steps to reproduce the behavior, i.e.:

<details><summary>

Python 3.7.4 (default, Jul 18 2019, 19:34:02)
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut as dlc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/__init__.py", line 20, in <module>
    from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/create_project/__init__.py", line 4, in <module>
    from deeplabcutcore.create_project.demo_data import load_demo_data
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/create_project/demo_data.py", line 14, in <module>
    from deeplabcutcore.utils import auxiliaryfunctions
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/utils/__init__.py", line 1, in <module>
    from deeplabcutcore.utils.make_labeled_video import *
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/utils/make_labeled_video.py", line 38, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.config import load_config
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/pose_estimation_tensorflow/__init__.py", line 13, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet import *
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/pose_estimation_tensorflow/nnet/__init__.py", line 16, in <module>
    from deeplabcutcore.pose_estimation_tensorflow.nnet.pose_net import *
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/deeplabcutcore/pose_estimation_tensorflow/nnet/pose_net.py", line 9, in <module>
    import tensorflow.contrib.slim as slim
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/tensorflow/contrib/__init__.py", line 49, in <module>
    from tensorflow.contrib import image
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/tensorflow/contrib/image/__init__.py", line 71, in <module>
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
    "_single_image_random_dot_stereograms.so"))
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/adt150/DLC-CPU-VENV/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 78, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 30
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=, mu=, normalize=True, normalize_max=, normalize_min=, border_level=, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                 ^
SyntaxError: invalid syntax
>>>

</summary><p>

```python
import deeplabcut
# or: import deeplabcutcore
```
</p></details>

**Expected behavior**
import successfully

**Additional context**
The equivalent gpu environment works as expected, with `tensorflow-gpu==1.13.1`
and deeplabcutcore version 0.0b3  
The environment is setup inside of a python venv, not a conda environemnt.
This is a requirement of the server environment we are working in.
I attempted to install `tensorflow==1.13.1` as per DLC-CPU.yaml, but pip was not able to find this on PyPi.

**Comment by MMathisLab** [comment]
For dlccore could you post on that repo, since is an independent code. Any 1.x tensorflow is supported, so whatever works for your specific env is fine. Although I can confirm 1.13.1 imports just fine if installed correctly!

**Comment by suntzuisafterU** [comment]
Thanks for pointing out that any version of tf will work.
Version 1.15.0 fixed it for me.

This is obviously a tensorflow issue, as seen here: https://github.com/tensorflow/tensorflow/issues/21164#issuecomment-601920261
It occurred with both `deeplabcut` and `deeplabcutcore`.

If any 1.x tf will work, then a comment in the DLC_CPU.yaml file could document this.

PR: https://github.com/DeepLabCut/DeepLabCut/pull/732

**Comment by MMathisLab** [comment]
The docs very clearly state any 1.x works though, and I personally use 1.13.1 on Ubuntu, MacOS and Windows, so I’m not keen to change the conda files; and as you stated, you didn’t use the conda file, which may be part of your specific issue.

**Comment by suntzuisafterU** [comment]
Okay no worries. Believe me, I would be using conda if I could.
