### ISSUE TITLE
Step1_EvaluateModelon...py: Error when snapshotindex = all

### ISSUE THREAD

**Issue by mcamila777** [DeepLabCut/DeepLabCut#8]
To evaluate all models (snapshots of training stages) I set on `myconfig.py` the variable `snapshotindex = all`.

There is a variable mistake in the `Step1_EvaluateModelonDataset.py` file, since the conditioned variable `snapindex` was not used, but the imported variable `snapshotindex` was.  
Correction:

```
        ##################################################
        # Compute predictions over images
        ##################################################

        if snapshotindex == -1:
            snapindices = [-1]
        elif snapshotindex == all:
            snapindices = range(len(Snapshots))
        else:
            print("Invalid choice, only -1 or all!")

        for snapindex in snapindices:
            cfg['init_weights'] = modelfolder + \
                '/train/' + Snapshots[snapindex] # xxx[snapshotindex]
            trainingsiterations = (
                cfg['init_weights'].split('/')[-1]).split('-')[-1]
            scorer = 'DeepCut' + "_resnet" + str(cfg["net_type"]) + "_" + str(
                int(trainFraction *
                    100)) + 'shuffle' + str(shuffle) + '_' + str(
                        trainingsiterations) + "forTask:" + Task

            print("Running ", scorer, trainingsiterations)

            try:
                Data = pd.read_hdf('Data_h5/' + scorer + '.h5',
                                   'df_with_missing')
                print("This net has already been evaluated!")
            except:
                # Specifying state of model (snapshot / training state)
                cfg['init_weights'] = modelfolder + \
                    '/train/' + Snapshots[snapindex] # xxx[snapshotindex]
                sess, inputs, outputs = predict.setup_pose_prediction(cfg)
```

However, there is still a tf error when running this script in this mode:

```
Traceback (most recent call last):
  File "Step1_EvaluateModelonDataset.py", line 132, in <module>
    sess, inputs, outputs = **predict**.setup_pose_prediction(cfg)
...

**_ValueError:** Variable resnet_v1_50/conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 216, in variable
    use_resource=use_resource)

...
```

To solve this what I did (it worked but not sure if it is the best solution) is to [reset the graph](https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/8) for each new iteration of snapshots. By adding  `tf.reset_default_graph()`  to the method `setup_pose_prediction(cfg)` of the file `DeepLabCut/pose-tensorflow/nnet/predict.py`

```

def setup_pose_prediction(cfg):
    tf.reset_default_graph() # NEW LINE
    inputs = tf.placeholder(tf.float32, shape=[cfg.batch_size   , None, None, 3])

    net_heads = pose_net(cfg).test(inputs)
    outputs = [net_heads['part_prob']]
    if cfg.location_refinement:
        outputs.append(net_heads['locref'])

    restorer = tf.train.Saver()

    sess = tf.Session()

    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())

    # Restore variables from disk.
    restorer.restore(sess, cfg.init_weights)

    return sess, inputs, outputs

```

**Comment by AlexEMG** [comment]
Dear @mcamila777, Thanks for your comment. I updated the evaluation script.  However, I cannot reproduce your error below. Can you please check with the updated evaluation script? [what is your tf version?]

**Comment by mcamila777** [comment]
Hi @AlexEMG , thank you for your answer. My tf version is 1.3.0.

The new update solves the first error I mentioned, the one related with the variable `snapindex`. 

But I still continue getting the same second error if I remove the line I added  (`tf.reset_default_graph() `) to the method `setup_pose_prediction(cfg)` of the file` DeepLabCut/pose-tensorflow/nnet/predict.py`

Maybe it is a problem related with my tf session. But with the line I added it works for me.
If you want to see the full log is:

```
...
2018-05-07 21:52:28.094272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro P4000, pci bus id: 0000:65:00.0)
('Analyzing ', 'single_images_00/frame00.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'single_images_01/frame03.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_00/frame0009.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_03/frame0001.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_05/frame0004.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_07/frame0005.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_09/frame0008.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_12/frame0004.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_14/frame0007.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_16/frame0008.png')
('which constitutes ', 0, '%!')
('Analyzing ', 'video_18/frame0009.png')
('which constitutes ', 0, '%!')
Folder already exists!
('Running ', 'DeepCut_resnetresnet_50_70shuffle1_350000forTask:standing', ' with # of trainingiterations:', '350000')
WARNING:tensorflow:From /is/ps2/calvarez2/DeepLabCut/pose-tensorflow/nnet/pose_net.py:52: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
WARNING:tensorflow:From /is/ps2/calvarez2/DeepLabCut/pose-tensorflow/nnet/pose_net.py:52: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
Traceback (most recent call last):
  File "Step1_EvaluateModelonDataset.py", line 131, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "/is/ps2/calvarez2/DeepLabCut/pose-tensorflow/nnet/predict.py", line 12, in setup_pose_prediction
    net_heads = pose_net(cfg).test(inputs)
  File "/is/ps2/calvarez2/DeepLabCut/pose-tensorflow/nnet/pose_net.py", line 89, in test
    heads = self.get_net(inputs)
  File "/is/ps2/calvarez2/DeepLabCut/pose-tensorflow/nnet/pose_net.py", line 85, in get_net
    net, end_points = self.extract_features(inputs)
  File "/is/ps2/calvarez2/DeepLabCut/pose-tensorflow/nnet/pose_net.py", line 54, in extract_features
    global_pool=False, output_stride=16)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py", line 279, in resnet_v1_50
    scope=scope)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py", line 210, in resnet_v1
    net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 147, in conv2d_same
    scope=scope)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1027, in convolution
    outputs = layer.apply(inputs)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 503, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 443, in __call__
    self.build(input_shapes[0])
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 137, in build
    dtype=self.dtype)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 383, in add_variable
    trainable=trainable and self.trainable)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1561, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1553, in _model_variable_getter
    custom_getter=getter, use_resource=use_resource)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 261, in model_variable
    use_resource=use_resource)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 216, in variable
    use_resource=use_resource)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable resnet_v1_50/conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 216, in variable
    use_resource=use_resource)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/is/ps2/calvarez2/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 261, in model_variable
    use_resource=use_resource)

```

**Comment by AlexEMG** [comment]
Thanks so much! In the meantime we verified that:
a) your fix is not required for tf 1.0
b) doesn't work for tf 1.4 (where this problem also exists otherwise)
and know from you that
c) fixes the problem for tf 1.3.

**Comment by mcamila777** [comment]
Thanks for your answer @AlexEMG .
By the way, while evaluating the all the models, I have noticed that during training you only save the last 5 snapshots while deleting the initial snapshots (in the `DeepLabCut/pose-tensorflow/models/reachingJan30-trainset95shuffle1/train` folder for the demo). As I am trying to find how does the validation error varies with the iterations in order to avoid overfitting, and you don't calculate or print the validation loss during training (just print the training loss, why?), I tried to visualize it after training, but as you don't save all the snapshots, it is not possible to predict labels and calculate the error for them. 
**Any idea about where could I change this in order to save all the snapshots?** (keeping the established `save_iters`)
At the same time, trying to use the test data or validation data I mean during training, I saw that when you generate the `pose_cfg.yaml ` files for train and test using the `Step4_GenerateTrainingFileFromLabelledData_demo`, you target the same dataset (same `.mat ` file) for both training and test files, and this dataset contains only the training data as I understood. 
Then, in the `pose_cfg.yaml ` you can see that the `dataset` line is exactly the same for train and test files. This one for the demo:
`dataset: ../../UnaugmentedDataSet_reachingJan30/reaching_Mackenzie95shuffle1.mat`
**Do you have any reason why do you only created a single `.mat ` file for training and test (with the training data only) and why you don't calculate the validation error during training (or where can I find this if I am missing something) ?**  In the paper I see you plot the training and test RMSE against iterations, but in the code I don't find where you save those values during training or save the models (snapshots) to calculate them after training. 
Thank you very much!

**Comment by AlexEMG** [comment]
Check out line 94 of [https://github.com/AlexEMG/DeepLabCut/blob/master/pose-tensorflow/train.py](
https://github.com/AlexEMG/DeepLabCut/blob/master/pose-tensorflow/train.py)

Currently it is set to (to not fill the memory....):
`saver = tf.train.Saver(max_to_keep=5)`

You can change it, e.g. to 
`saver = tf.train.Saver(max_to_keep=None)`
to store all snapshots. 

With regard to your other question: In the paper we evaluated the RMSE for training and testing post-hoc. Btw, for all examples in the paper (and the trained iterations), I never found any evidence that early stopping improved results.

**Comment by mcamila777** [comment]
Thanks for your answer @AlexEMG .

So, if you just saved the last five models (as it's established in that default setup), how did you calculated the train/test errors for the more than five model as it is shown in the Fig.2 C and D of your paper? (from less than 200K to more than 600K iteration with many points in between). Did you just changed the `max_to_keep` to `None` and tested all the models after, or what did you do? 

In my case, I am training your network with few images of an animal in the wild, and I have seen that I had a better performance for 50K iterations than for 300K to 500K (just five test points between these two values). So, I want to know when the model starts to overfit by graphing the test error as you did.

**Comment by AlexEMG** [comment]
I evaluated it every 50k (which is perhaps a bit excessive).

**Comment by AlexEMG** [comment]
We updated the toolbox, so that the looping over different snapshots & training sets will run without interruption (see https://github.com/AlexEMG/DeepLabCut/blob/master/Evaluation-Tools/Step1_EvaluateModelonDataset.py)
