### ISSUE TITLE
cuDNN launch failure

### ISSUE THREAD

**Issue by Charlottewiltshire97** [DeepLabCut/DeepLabCut#823]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2

Please complete the following information about your system:

OS: [e.g. MacOS, Windows 10, etc] windows 10
DeepLabCut Version: [e.g. 2.2] (please check with import deeplabcut, deeplabcut.__version__) 2.2b7
Anaconda env used: DLC-GPU

**Describe the problem**

When trying to train my model I am receiving the error:
 InternalError (see above for traceback): cuDNN launch failure : input shape([32,512,32,55]) filter shape([3,3,512,512])
Alongside:
Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.33GiB.

The machine I am using appears to have enough memory (totalMemory: 24.00GiB freeMemory: 20.00GiB). I have checked my tensor flow version and received this error with both version 1.12 and 1.13.
Any ideas on why I am having these issues and how they can be resolved? Please note I am using the GUI.

Please place code inside this:

<details><summary>Code output</summary><p>

Activating limb prediction...
Starting with multi-animal imaug + adam pose-dataset loader.
Batch Size is 8
Getting specs multi-animal-imgaug 14 10
Initializing ResNet
Loading ImageNet-pretrained resnet_50
2020-07-28 17:28:05.341481: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-28 17:28:05.634426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: TITAN RTX major: 7 minor: 5 memoryClockRate(GHz): 1.77
pciBusID: 0000:2d:00.0
totalMemory: 24.00GiB freeMemory: 20.00GiB
2020-07-28 17:28:05.644630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-07-28 17:28:06.558684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-28 17:28:06.563429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2020-07-28 17:28:06.567355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2020-07-28 17:28:06.573577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 19382 MB memory) -> physical GPU (device: 0, name: TITAN RTX, pci bus id: 0000:2d:00.0, compute capability: 7.5)
Max_iters overwritten as 200000
Display_iters overwritten as 10000
Save_iters overwritten as 50000
Training parameters:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\zwartlab-users\\Desktop\\charlotte3\\project\\dlc-models\\iteration-0\\colab2Jun29-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'mirror': False, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 8, 'dataset_type': 'multi-animal-imgaug', 'deterministic': False, 'weigh_only_present_joints': False, 'pairwise_huber_loss': False, 'partaffinityfield_predict': True, 'pairwise_predict': True, 'crop': True, 'cropratio': 0.4, 'minsize': 100, 'leftwidth': 400, 'rightwidth': 400, 'topheight': 400, 'bottomheight': 400, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]], 'all_joints_names': ['bottom_lip', 'top_lip', 'right_pupil', 'left_pupil', 'right_ear', 'left_ear', 'right_nostil', 'left_nostril', 'right_brow', 'left_brow'], 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_colab2Jun29\\colab2_Charlotte95shuffle1.pickle', 'display_iters': 500, 'init_weights': 'C:\\Users\\mfz\\.conda\\envs\\dlc-windowsGPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_colab2Jun29\\Documentation_data-colab2_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.0001, 7500], [5e-05, 12000], [1e-05, 200000]], 'net_type': 'resnet_50', 'num_joints': 10, 'num_limbs': 14, 'pafwidth': 20, 'pairwise_loss_weight': 0.1, 'partaffinityfield_graph': [[0, 1], [0, 7], [0, 6], [1, 7], [1, 6], [6, 7], [7, 3], [2, 8], [3, 9], [2, 4], [3, 5], [9, 8], [9, 5], [8, 4]], 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\zwartlab-users\\Desktop\\charlotte3\\project', 'save_iters': 10000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25}
Starting multi-animal training....
2020-07-28 17:28:21.932386: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.33GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-28 17:28:21.942073: E tensorflow/stream_executor/cuda/cuda_dnn.cc:82] The primary convolution algorithm failed memory allocation, while a secondary algorithm is not provided.
Traceback (most recent call last):
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([32,512,32,55]) filter shape([3,3,512,512])
         [[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/weights/read)]]
         [[{{node mean_squared_error/num_present/broadcast_weights/assert_broadcastable/AssertGuard/Assert/Switch/_647}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1707_...ert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 193, in train_network
    raise e
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    allow_growth=allow_growth,
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 217, in train
    feed_dict={learning_rate: current_lr},
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([32,512,32,55]) filter shape([3,3,512,512])
         [[node resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D (defined at C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1057)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/weights/read)]]
         [[{{node mean_squared_error/num_present/broadcast_weights/assert_broadcastable/AssertGuard/Assert/Switch/_647}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1707_...ert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D', defined at:
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\__main__.py", line 20, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 66, in launch_dlc
    app.MainLoop()
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    allow_growth=allow_growth,
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 141, in train
    losses = pose_net(cfg).train(batch)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 279, in train
    heads = self.get_net(batch[Batch.inputs])
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 178, in get_net
    net, end_points = self.extract_features(inputs)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 130, in extract_features
    im_centered, global_pool=False, output_stride=16, is_training=False
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 274, in resnet_v1_50
    scope=scope)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 207, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_utils.py", line 211, in stack_blocks_dense
    net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 119, in bottleneck
    residual, depth_bottleneck, 3, stride, rate=rate, scope='conv2')
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_utils.py", line 131, in conv2d_same
    scope=scope)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 817, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\layers\base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 505, in _with_space_to_batch_call
    result = self.op(input_converted, filter)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 204, in __call__
    name=self.name)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1044, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): cuDNN launch failure : input shape([32,512,32,55]) filter shape([3,3,512,512])
         [[node resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D (defined at C:\Users\mfz\.conda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1057)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/weights/read)]]
         [[{{node mean_squared_error/num_present/broadcast_weights/assert_broadcastable/AssertGuard/Assert/Switch/_647}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1707_...ert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
</p></details>

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
You will find in other issues that this is likely a memory size error (https://github.com/DeepLabCut/DeepLabCut/search?q=memory+error&type=Issues); if you did not run "cropandlabel" before creating a test set, it's likely your frames are too large for your GPU with our default settings (which changed dramatically since pre-2.2). I would suggest deleting the training folder, running cropandlabel, then create the training dataset. If that fails, you will need to lower the batchsize in pose_cfg.yaml. 

Also see: https://forum.image.sc/t/queries-on-usage/39760/4?u=mwmathis

**Comment by Charlottewiltshire97** [comment]
Hi Mackenzie, 
Thank you for such a prompt response!

We did not crop the videos as we has a ".h5 file not found" for one of the videos. When I manually checked, the .h5 file was in the folder, identical to the other videos. This particular video had a hyphen in the name. Is that likely to affect DLC? Is there any other reason that DLC may have struggled to find the file?

**Comment by MMathisLab** [comment]
^ that is for video analysis though, not training/memory issue? (You should check_labels pre-training to be sure the labels look good and make sense)

But yes, the hyphen is likely the culprit in video analysis; if you pass robust_frames =True (maybe double check this exact phasing with dlc.analyze_videos?) it should over look this (it’s another method, slightly slower so that’s why it’s default is false).

**Comment by Charlottewiltshire97** [comment]
Hi Mackenzie. 

The issue with cropping was apostrophe in the video name that had automatically been changed to an underscore when creating the DLC files. Once I simplified the video name it worked. 

Cropping the videos and reducing the batch size has worked. 

Thank you!
