### ISSUE TITLE
Creating labeled video problem 

### ISSUE THREAD

**Issue by eltabbal** [DeepLabCut/DeepLabCut#867]
#**Describe the bug**

I am trying to create a labeled video after the analysis. if I used the GUI, nothing happens and it keeps buffering and deeplabcut GUI crashes. if i used the command window i got the following error in the pool.map function line 502 in make_labeled_video.py. i am using the following config for the project: 

Project path (change when moving around)
project_path: D:\Deeplabcutanalysis\Project-2020-08-21
 Annotation data set configuration (and individual video cropping parameters)
video_sets:
  D:\Deeplabcutanalysis\Project-2020-08-21\videos\d10_090820_000_video_Trial_number 13.avi:
    crop: 0, 1504, 0, 1000
  D:\Deeplabcutanalysis\Project-2020-08-21\videos\d10_090820_000_video_Trial_number 14.avi:
    crop: 0, 1504, 0, 1000
bodyparts:
- Tipofnose
- upperJaw
- LowerJaw
- forepaw
- Pellet
start: 0
stop: 1
numframes2pick: 20
Plotting configuration
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: jet
Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
resnet:
snapshotindex: -1
batch_size: 8
Cropping Parameters (for analysis and outlier frame detection)
cropping: false
#if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624
Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
default_net_type: resnet_50
default_augmenter: default

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version 2.2b7

<details><summary>TRACEBACK</summary><p>
#Here is the detailed summary of the error 

dlc.create_labeled_video(config_path,[r'D:\Trials_Deeplab cut training\Deeplabanalysis\10_110820_000_video_Trial_number 4.avi'], save_frames=False,filtered=True,fastmode=False);
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 611, in proc_video
    color_by,
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 284, in CreateVideoSlow
    for index in trange(nframes):
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tqdm\std.py", line 1469, in trange
    return tqdm(_range(*args), **kwargs)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tqdm\std.py", line 1029, in __init__
    self.refresh(lock_args=self.lock_args)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tqdm\std.py", line 1314, in refresh
    self.display()
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tqdm\std.py", line 1438, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tqdm\std.py", line 305, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tqdm\std.py", line 298, in fp_write
    fp.write(_unicode(s))
AttributeError: 'NoneType' object has no attribute 'write'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-4-6bca8b0d404b>", line 1, in <module>
    dlc.create_labeled_video(config_path,[r'D:\Trials_Deeplab cut training\Deeplabanalysis\demi10_110820_000_video_Trial_number 4.avi'], save_frames=False,filtered=True,fastmode=False);

  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 502, in create_labeled_video
    pool.map(func, Videos)

  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

AttributeError: 'NoneType' object has no attribute 'write'

**Comment by jeylau** [comment]
Hi @eltabbal, could you retry after updating tqdm? That open issue in their repo is directly related [https://github.com/tqdm/tqdm/issues/794](url), but since I cannot reproduce the error (I'm on MacOS though), maybe it has recently been fixed.

**Comment by eltabbal** [comment]
I upgraded tqdm , but the problem still exists after installation.

**Comment by eltabbal** [comment]
this problem was not existing in the older version of deeplabcut (2.0). FYI

**Comment by jeylau** [comment]
> this problem was not existing in the older version of deeplabcut (2.0). FYI

That's correct! Parallelization of video creation was introduced about 2 months ago #748. There must be an easy way around it, let me look at it 😃

**Comment by eltabbal** [comment]
OK, i solved it by running the GUI from the command prompt instead of running it from inside IPYTHON or SPYDER. this might be a temporary solution but it is ok for now. 

https://stackoverflow.com/questions/48155084/python-modulenotfound-error-using-anaconda/48157284#48157284
