### ISSUE TITLE
segmentation fault when labelling frames

### ISSUE THREAD

**Issue by CFettig** [DeepLabCut/DeepLabCut#887]
After creating project and extracting frames, program crashes if I try to label frames.

 - OS: Ubuntu 18.04.1
 - DeepLabCut Version: 2.1.8.2

**To Reproduce**
1. Create new project
2. Extract frames
3. Click on "Label Frames" tab
4. Click on "Label Frames" button

<details><summary>TRACEBACK</summary><p>

```python

Traceback (most recent call last):
  File "/home/claire/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/gui/label_frames.py", line 102, in label_frames
    deeplabcut.label_frames(self.config)
  File "/home/claire/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 260, in label_frames
    labeling_toolbox.show(config,imtypes=imtypes)
  File "/home/claire/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 702, in show
    frame = MainFrame(None, config, imtypes).Show()
  File "/home/claire/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 216, in __init__
    widgetsizer.Add(self.quit , 1, wx.ALL|wx.ALIGN_RIGHT, 15)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /home/wxpy/wxPython-4.1.0/ext/wxWidgets/src/common/sizer.cpp(2098) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
Segmentation fault (core dumped)

```
</p></details>

**Expected behavior**
Expected frame labelling window to open.

**Additional context**
Using wxPython 4.1.0.
Clicking "Label Frames" button only throws an error the first time, then causes segmentation fault on the second click.

**Comment by MMathisLab** [comment]
wxPython > 4.1 is not supported. 

`pip install -U wxPython==4.0.7.post2`

See #682
