### ISSUE TITLE
fifo_queue tensor flow

### ISSUE THREAD

**Issue by eltabbal** [DeepLabCut/DeepLabCut#896]
**Describe the bug**
After finishing the training I usually get this error, I don't think it is causing a problem , but want to understand where the bug is. 

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version 2.2b7
 - Browser chrome

<details><summary>TRACEBACK</summary><p>

2020-09-10 16:24:13.501913: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 91, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\TABBAL\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at \site-packages\deeplabcut\pose_estimation_tensorflow\train.py:77) ]]

Errors may have originated from an input operation.
Input Source operations connected to node fifo_queue_enqueue:
 Placeholder_1 (defined at \site-packages\deeplabcut\pose_estimation_tensorflow\train.py:66)
 fifo_queue (defined at \site-packages\deeplabcut\pose_estimation_tensorflow\train.py:74)

Original stack trace for 'fifo_queue_enqueue':
  File "\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "\site-packages\deeplabcut\__main__.py", line 20, in <module>
    deeplabcut.launch_dlc()
  File "\site-packages\deeplabcut\gui\launch_script.py", line 66, in launch_dlc
    app.MainLoop()
  File "\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 171, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 77, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "\site-packages\tensorflow\python\ops\data_flow_ops.py", line 345, in enqueue
    self._queue_ref, vals, name=scope)
  File "\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4410, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.

**Comment by MMathisLab** [comment]
not a bug, not to worry.  it's just that is how the network is stopped (i.e. we just put in a limit to make it flexible).
