### ISSUE TITLE
DLC1.0 - Error while running Evaluation (Step1) (skimage installation)

### ISSUE THREAD

**Issue by ForgottenOneNyx** [DeepLabCut/DeepLabCut#92]
Hello, when I run `CUDA_VISIBLE_DEVICES=3 python3 Step1_EvaluateModelonDataset.py` I get the following error: 

```
Traceback (most recent call last):
  File "EvaluateNetwork.py", line 39, in <module>
    from skimage import io
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 93, in reset_plugins
    _load_preferred_plugins()
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 73, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 85, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 255, in use_plugin
    _load(name)
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 299, in _load
    fromlist=[modname])
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/_plugins/matplotlib_plugin.py", line 4, in <module>
    from mpl_toolkits.axes_grid1 import make_axes_locatable
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-3.0.0-py3.5-linux-x86_64.egg/mpl_toolkits/axes_grid1/__init__.py", line 2, in <module>
    from .axes_divider import Divider, SubplotDivider, LocatableAxes, \
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-3.0.0-py3.5-linux-x86_64.egg/mpl_toolkits/axes_grid1/axes_divider.py", line 868, in <module>
    addendum=' There is no alternative. Deriving from '
TypeError: deprecated() got an unexpected keyword argument 'addendum'
```

I believe its something to do with skimage? Any ideas?

**Comment by MMathisLab** [comment]
I haven't run into this. Did you try reinstalling skimage?

**Comment by ForgottenOneNyx** [comment]
Yes, I did. It didn't work. I did notice that `io.imread` is only called once in EvaluateNetwork.py 
Any substitutes?

**Comment by AlexEMG** [comment]
There are quite a few more spots where it appears (making labeled frames etc). Seems like you are using python 3.5. Perhaps consider using 3.6 instead... Also you seem to use matplotlib 3.0.0 (we use 2.x), so perhaps also downgrade (I have not checked this). pip install matplotlib==2.2
