### ISSUE TITLE
wxAssertionError: GUI crashes on "Label Frames".

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#926]
Windows 10: Anancoda 3 env: DLC version 2.2b8: Python 3.7.6

**Describe the problem**

I wanted to add some frames to the training set as there were some difficult videos to study. Using the GUI, I extracted the videos without issue but when I went to "Label Frames" the GUI crashed and the following error was reported

```
In [2]: deeplabcut.launch_dlc()
---------------------------------------------------------------------------
wxAssertionError                          Traceback (most recent call last)
~\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\gui\label_frames.py in label_frames(self, event)
    149
    150     def label_frames(self, event):
--> 151         deeplabcut.label_frames(self.config)
    152
    153     def reset_label_frames(self, event):

~\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py in label_frames(config, multiple_individualsGUI, imtypes)
    429         from deeplabcut.generate_training_dataset import labeling_toolbox
    430
--> 431         labeling_toolbox.show(config, imtypes=imtypes)
    432
    433     os.chdir(startpath)

~\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in show(config, imtypes)
   1009 def show(config, imtypes=["*.png"]):
   1010     app = wx.App()
-> 1011     frame = MainFrame(None, config, imtypes).Show()
   1012     app.MainLoop()
   1013

~\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in __init__(self, parent, config, imtypes)
    257         widgetsizer.AddStretchSpacer(15)
    258         self.quit = wx.Button(self.widget_panel, id=wx.ID_ANY, label="Quit")
--> 259         widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15)
    260         self.quit.Bind(wx.EVT_BUTTON, self.quitButton)
    261

wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
---------------------------------------------------------------------------
wxAssertionError                          Traceback (most recent call last)
wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
SystemError: <class 'wx._core.SizeEvent'> returned a result with an error set

(DLC) C:\Users\byron\Anaconda3\envs\DLC>
```

**Comment by byronrogers73** [comment]
tried it a different way, and got the same error on "Label Frames"

```
(DLC) C:\Users\byron\Anaconda3\envs\DLC>python -m deeplabcut
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\gui\label_frames.py", line 151, in label_frames
    deeplabcut.label_frames(self.config)
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 431, in label_frames
    labeling_toolbox.show(config, imtypes=imtypes)
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 1011, in show
    frame = MainFrame(None, config, imtypes).Show()
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 259, in __init__
    widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.SizeEvent'> returned a result with an error set

(DLC) C:\Users\byron\Anaconda3\envs\DLC>
```

**Comment by byronrogers73** [comment]
I see this issue is the same that has been raised here

https://github.com/DeepLabCut/DeepLabCut/issues/682

and here

https://github.com/DeepLabCut/DeepLabCut/issues/400

The solution is to pip install -U wxPython==4.0.7.post2
