### ISSUE TITLE
FileNotFoundError when running testscript.py

### ISSUE THREAD

**Issue by leni56** [DeepLabCut/DeepLabCut#929]
Operating system: macOS version 10.13.6
DeepLabCut version: 2.1.8.2
Python: 3.7.6
Using Anaconda Env: DLC-CPU

I ran testscript.py inside the environment to check if I installed DeepLabCut correctly (following this tutorial    https://www.youtube.com/watch?v=IOWtKn3l33s   DeepLabCut Installation How To: testing your DLC installation w/ testscript.py)

It seems like it didn't work, and I can't figure out why. These are the last lines in my terminal: 

Traceback (most recent call last):
  File "testscript.py", line 217, in <module>
    DF = pd.read_hdf(file, "df_with_missing")
  File "/Users/unknown/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/pandas/io/pytables.py", line 387, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /Users/unknown/Desktop/Internship Netherlands/DeepLabCut/examples/TEST-Alex-2020-09-27/labeled-data/reachingvideo1short/machinelabels-iter0.h5 does not exist

Does this mean there is something wrong with how I've installed deeplabcut and future projects might have problems as well? If yes, how can I fix it?

**Comment by leni56** [comment]
https://github.com/DeepLabCut/DeepLabCut/issues/869
