### ISSUE TITLE
Issues training multianimal video on COLAB

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#931]
I’ve been trying to run training for a multianimal video containing two mice, using “COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb”. Only one of the mice has at least one frame containing a complete skeleton, but the second mouse only has partial skeletons on each frame. I’ve attached the config file to this question. I keep running into the following error message whenever I run training:

_____________________________________________________________________________________________________
ResourceExhaustedError: 2 root error(s) found.
(0) Resource exhausted: OOM when allocating tensor with shape[8,49,87,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D-0-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

 [[mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/concat/_563]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

(1) Resource exhausted: OOM when allocating tensor with shape[8,49,87,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[{{node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D-0-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
_____________________________________________________________________________________________________
Also, in the create training dataset section, I am unable to run the line of code “deeplabcut.cropimagesandlabels(path_config_file, userfeedback=True)” without encountering an error:

_____________________________________________________________________________________________________
Do you want to crop frames for folder: /content/drive/My Drive/FST52218 TEST DLC-Nicole Lookfong-2020-09-24/labeled-data/FST 5_22_18 ?
(yes/no):yes
25%|██▌ | 5/20 [00:18<00:54, 3.62s/it]/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py:364: UserWarning: /content/drive/My Drive/FST52218 TEST DLC-Nicole Lookfong-2020-09-24/labeled-data/FST 5_22_18_cropped/img04216c2.png is a low contrast image
io.imsave(cropppedimgname, frame[y0:y1, x0:x1])
/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py:364: UserWarning: /content/drive/My Drive/FST52218 TEST DLC-Nicole Lookfong-2020-09-24/labeled-data/FST 5_22_18_cropped/img04216c4.png is a low contrast image
io.imsave(cropppedimgname, frame[y0:y1, x0:x1])
/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py:364: UserWarning: /content/drive/My Drive/FST52218 TEST DLC-Nicole Lookfong-2020-09-24/labeled-data/FST 5_22_18_cropped/img04216c6.png is a low contrast image
io.imsave(cropppedimgname, frame[y0:y1, x0:x1])
/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py:364: UserWarning: /content/drive/My Drive/FST52218 TEST DLC-Nicole Lookfong-2020-09-24/labeled-data/FST 5_22_18_cropped/img04216c8.png is a low contrast image
io.imsave(cropppedimgname, frame[y0:y1, x0:x1])
/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py:364: UserWarning: /content/drive/My Drive/FST52218 TEST DLC-Nicole Lookfong-2020-09-24/labeled-data/FST 5_22_18_cropped/img04216c9.png is a low contrast image
io.imsave(cropppedimgname, frame[y0:y1, x0:x1])
100%|██████████| 20/20 [01:14<00:00, 3.74s/it]
KeyError Traceback (most recent call last)
in ()
----> 1 deeplabcut.cropimagesandlabels(path_config_file, userfeedback=True)
2
3 #if you labeled on Windows, please set the windows2linux=True:
4 deeplabcut.create_multianimaltraining_dataset(path_config_file, windows2linux=False)

1 frames
/usr/local/lib/python3.6/dist-packages/ruamel/yaml/comments.py in getitem(self, key)
751 # type: (Any) -> Any
752 try:
–> 753 return ordereddict.getitem(self, key)
754 except KeyError:
755 for merged in getattr(self, merge_attrib, ):

KeyError: ‘/content/drive/My Drive/FST52218 TEST DLC-Nicole Lookfong-2020-09-24/videos\FST 5_22_18.MP4’
_____________________________________________________________________________________________________

I have been told that the issue could be that because I labeled on Windows that I need to convert to Linux for it to run on Colab. However I run this step every time, so this is not the issue: 
“deeplabcut.create_multianimaltraining_dataset(path_config_file, windows2linux=True)”

In addition, when I run cropping and the training on just my computer, without Colab, I have no errors and training proceeds as normal. However the training is incredibly slow and does not go at the speed I need it to given my hardware limitations.

Also, I am running what I believe to be the latest version of deeplabcut which I believe is 2.2.b8.

Any help would be appreciated. Let me know if you need more information.

**Comment by jeylau** [comment]
Mhhhh I found the faulty line... https://github.com/DeepLabCut/DeepLabCut/blob/c2794eb5572b8cd86f3a17e21f676295de0854e9/deeplabcut/generate_training_dataset/trainingsetmanipulation.py#L379
It is because the original video path is re-created using the path separator of the current OS, which in your case does differ from the platform you labeled your data on. The windows2linux conversion is otherwise silently done here https://github.com/DeepLabCut/DeepLabCut/blob/c2794eb5572b8cd86f3a17e21f676295de0854e9/deeplabcut/generate_training_dataset/trainingsetmanipulation.py#L320-L322
I'll fix that in an hour or two 😃

**Comment by jeylau** [comment]
Hey @Hydraulic343, you have updated the video paths in your config.yaml to be that of your Drive, is that correct?

**Comment by aasiya-islam** [comment]
Hey, I'm also having issues training in multi-animal mode in version 2.2b7 and b8. It seems like the issue lies in tensorflow and am wondering if its a compatibility issue between this latest version of DLC and the current TF package? I attached the error message below.
I've never ran into an issue like this so I'm having a hard time interpreting what to do next. I've reinstalled DLC and tensorflow so I'm assuming everything is updated. 

I also get this error sometimes:
>>> import deeplabcut
2020-10-16 14:53:53.902326: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-10-16 14:53:53.906481: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NAPEadmin\.conda\envs\jess_dlc_multi\lib\site-packages\deeplabcut\__init__.py", line 22, in <module>
    TF.logging.set_verbosity(TF.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'



--------------------------------------------------------------------------------------------

WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x000002BBD0B87C18>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x000002BBD0B87C18>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x000002BBD2698710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x000002BBD2698710>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x000002BBCBB36438>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x000002BBCBB36438>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x000002BBD0B87C18>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x000002BBD0B87C18>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x000002BBFE99A048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x000002BBFE99A048>>: AttributeError: module 'gast' has no attribute 'Num'
Loading ImageNet-pretrained resnet_50
2020-10-16 21:27:26.478510: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2020-10-16 21:27:26.504336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2020-10-16 21:27:26.509922: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-10-16 21:27:26.517442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-10-16 21:27:26.521320: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-16 21:27:26.539495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2020-10-16 21:27:26.561278: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-10-16 21:27:26.572505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-10-16 21:27:26.969454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-16 21:27:26.973393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2020-10-16 21:27:26.976075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2020-10-16 21:27:26.980586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8693 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Max_iters overwritten as 200000
Display_iters overwritten as 1000
Save_iters overwritten as 50000
Training parameters:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\NAPEadmin\\Desktop\\tr-project-2mouse-jj-agf-2020-10-08-20201015T230516Z-001\\tr-project-2mouse-jj-agf-2020-10-08\\dlc-models\\iteration-0\\tr-project-2mouseOct8-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'adam', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 8, 'dataset_type': 'multi-animal-imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': True, 'pairwise_predict': True, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21]], 'all_joints_names': ['ear_tip', 'ear_tragus', 'top_eye', 'bottom_eye', 'top_teeth', 'bottom_teeth', 'nose_tip', 'nose_bulb', 'nose_septum', 'bottom_mouth', 'top_mouth', 'L_mouth_corner', 'R_mouth_corner', 'tongue', 'right_pinky', 'right_palm', 'right_nub', 'right_wrist', 'left_pinky', 'left_palm', 'left_nub', 'left_wrist'], 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_tr-project-2mouseOct8\\tr-project-2mouse_jj-agf95shuffle1.pickle', 'display_iters': 500, 'init_weights': 'C:\\Users\\NAPEadmin\\.conda\\envs\\DLC_multi\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_tr-project-2mouseOct8\\Documentation_data-tr-project-2mouse_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.0001, 7500], [5e-05, 12000], [1e-05, 200000]], 'net_type': 'resnet_50', 'num_joints': 22, 'num_limbs': 17, 'pafwidth': 20, 'pairwise_loss_weight': 0.1, 'partaffinityfield_graph': [[0, 1], [10, 11], [19, 21], [4, 5], [7, 6], [6, 8], [10, 13], [10, 12], [9, 10], [9, 11], [2, 3], [14, 15], [18, 19], [19, 20], [15, 16], [9, 12], [15, 17]], 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\NAPEadmin\\Desktop\\tr-project-2mouse-jj-agf-2020-10-08-20201015T230516Z-001\\tr-project-2mouse-jj-agf-2020-10-08', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 10000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25}
Starting multi-animal training....
2020-10-16 21:27:35.344932: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.33GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: cuDNN Backward Data function launch failure : input shape([32,512,16,39]) filter shape([3,3,512,512])
         [[{{node gradients/resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropInput}}]]
         [[train_op/control_dependency/_691]]
  (1) Internal: cuDNN Backward Data function launch failure : input shape([32,512,16,39]) filter shape([3,3,512,512])
         [[{{node gradients/resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropInput}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 193, in train_network
    raise e
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    allow_growth=allow_growth,
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 217, in train
    feed_dict={learning_rate: current_lr},
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: cuDNN Backward Data function launch failure : input shape([32,512,16,39]) filter shape([3,3,512,512])
         [[node gradients/resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropInput (defined at C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py:102) ]]
         [[train_op/control_dependency/_691]]
  (1) Internal: cuDNN Backward Data function launch failure : input shape([32,512,16,39]) filter shape([3,3,512,512])
         [[node gradients/resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropInput (defined at C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py:102) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node gradients/resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropInput:
 resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/weights/read (defined at C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py:130)

Input Source operations connected to node gradients/resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropInput:
 resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/weights/read (defined at C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py:130)

Original stack trace for 'gradients/resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D_grad/Conv2DBackpropInput':
  File "<stdin>", line 1, in <module>
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\gui\launch_script.py", line 66, in launch_dlc
    app.MainLoop()
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\wx\core.py", line 2224, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    allow_growth=allow_growth,
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 177, in train
    learning_rate, train_op = get_optimizer(total_loss, cfg)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 102, in get_optimizer
    train_op = slim.learning.create_train_op(loss_op, optimizer)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 442, in create_train_op
    check_numerics=check_numerics)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\training\python\training\training.py", line 450, in create_train_op
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\training\optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 731, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 403, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 731, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\ops\nn_grad.py", line 596, in _Conv2DGrad
    data_format=data_format),
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1529, in conv2d_backprop_input
    name=name)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D', defined at:
  File "<stdin>", line 1, in <module>
[elided 3 identical lines from previous traceback]
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 176, in train_network
    allow_growth=allow_growth,
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multianimal.py", line 141, in train
    losses = pose_net(cfg).train(batch)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 279, in train
    heads = self.get_net(batch[Batch.inputs])
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 178, in get_net
    net, end_points = self.extract_features(inputs)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 130, in extract_features
    im_centered, global_pool=False, output_stride=16, is_training=False
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 274, in resnet_v1_50
    scope=scope)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 207, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_utils.py", line 211, in stack_blocks_dense
    net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 119, in bottleneck
    residual, depth_bottleneck, 3, stride, rate=rate, scope='conv2')
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_utils.py", line 131, in conv2d_same
    scope=scope)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\NAPEadmin\.conda\envs\DLC_multi\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)

**Comment by or-naim** [comment]
Any update on this? Having the same issue. Tried to download CUDA==9 again, allow_growth=True and more...
