### ISSUE TITLE
Exception Thread message after successful training

### ISSUE THREAD

**Issue by Agulore** [DeepLabCut/DeepLabCut#955]
OS: Windows 10
DeepLabCut Version: 2.2b7
Anaconda env used: DLC-GPU

**Describe the problem**

After the training I have this exception thread since one week. But nothing I am aware of changed since few weeks I am using this trained network, I do not understand what does it mean. 

Please place code inside this:

<details><summary>Code output</summary><p>

[2020-10-12 07:00:47.368139: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-66:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 91, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:77) ]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 564, in mainloop
    self.interact()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\terminal\interactiveshell.py", line 555, in interact
    self.run_cell(code, store_history=True)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2877, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2922, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3146, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3337, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ced4355ffc5>", line 1, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\launch_script.py", line 66, in launch_dlc
    app.MainLoop()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\refine_labels.py", line 118, in refine_labels
    deeplabcut.refine_labels(self.config)
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py", line 760, in refine_labels
    refinement.show(config)
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\refine_training_dataset\refinement.py", line 1022, in show
    app.MainLoop()
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 171, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 77, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 345, in enqueue
    self._queue_ref, vals, name=scope)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4158, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\labappelbaum\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:77) ]]]

</p></details>

**Comment by jeylau** [comment]
This is fine; it just indicates that training got interrupted (either by you, or because the code reached `max_iter`).
