### ISSUE TITLE
Network Training Error (cuDNN launch failure)

### ISSUE THREAD

**Issue by natalier11** [DeepLabCut/DeepLabCut#971]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: Not sure, prompt would not let me run import deeplabcut, deeplabcut.__version__
Anaconda env used: DLC-GPU

**Describe the problem**
When running the "Train Network" tab on the DLC GUI, I receive an error in the anaconda prompt, shown below:
![Train network error - GH](https://user-images.githubusercontent.com/73397911/97086566-a3868f00-15e9-11eb-96c5-a87bd8d10361.png)
I can do every step successfully up to this point (extracting frames, labeling, etc.). 

ERROR:
[InternalError (see above for traceback): cuDNN launch failure : input shape([1,3,949,1682]) filter shape([7,7,3,64])
         [[node resnet_v1_50/conv1/Conv2D (defined at C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py:52) ]]
         [[node absolute_difference/weighted_loss/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/concat (defined at C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\losses.py:45) ]]]

**Additional context**
I am using a GPU.

**Comment by jeylau** [comment]
@natalier11, the right command is `deeplabcut.__version__`, with double leading and trailing underscores.
Your error is likely the result of a memory issue, as nicely explained here #823. If you haven't cropped your frames before training, I'd encourage you to do so (delete your training dataset, use `deeplabcut.cropimagesandlabels`, and recreate the training set). You could also reduce the batch size in the pose_cfg.yaml under the dlc-models/.../train directory. I hope that helps!

**Comment by natalier11** [comment]
Thanks for the suggestions! I was able to crop the frames and label them no problem. However, I get a new error this time when I run on resnet_50:
<Traceback (most recent call last):
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\create_training_dataset.py", line 230, in create_training_dataset
    deeplabcut.create_training_dataset(self.config,num_shuffles,Shuffles=[self.shuffle.GetValue()], userfeedback=userfeedback,net_type=self.net_choice.GetValue(),augmenter_type = self.aug_choice.GetValue())
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 698, in create_training_dataset
    data, MatlabData = format_training_data(Data, trainIndexes, nbodyparts, project_path)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 554, in format_training_data
    img_shape = _read_image_shape_fast(os.path.join(project_path, filename))
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 539, in _read_image_shape_fast
    return io.imread(path).shape
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\format.py", line 170, in get_reader
    return self.Reader(self, request)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\plugins\pillow.py", line 298, in _open
    return PillowFormat.Reader._open(self, pilmode=pilmode, as_gray=as_gray)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\plugins\pillow.py", line 135, in _open
    pil_try_read(self._im)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\plugins\pillow.py", line 680, in pil_try_read
    raise ValueError(error_message)
ValueError: Could not load ""
Reason: "image file is truncated"
Please see documentation at: http://pillow.readthedocs.io/en/latest/installation.html#external-libraries>


I tried looking at reducing the batch size but it is at 1.
I also tried running the network with mobilenet_v2_0.5 because I've heard mixed reviews about resnet vs mobilenet and I get yet ANOTHER error message when running mobilenet:
<Traceback (most recent call last):
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\create_training_dataset.py", line 230, in create_training_dataset
    deeplabcut.create_training_dataset(self.config,num_shuffles,Shuffles=[self.shuffle.GetValue()], userfeedback=userfeedback,net_type=self.net_choice.GetValue(),augmenter_type = self.aug_choice.GetValue())
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 698, in create_training_dataset
    data, MatlabData = format_training_data(Data, trainIndexes, nbodyparts, project_path)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 554, in format_training_data
    img_shape = _read_image_shape_fast(os.path.join(project_path, filename))
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 539, in _read_image_shape_fast
    return io.imread(path).shape
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "C:\Users\nremi\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 182, in get_reader
    "Could not find a format to read the specified file in %s mode" % modename
ValueError: Could not find a format to read the specified file in single-image mode>

I'm not sure if I have something downloaded on my computer wrong but if anyone could help that would be great!

**Comment by MMathisLab** [comment]
can you post what you input into create_training_dataset please (also to see how to format correctly, please type `deeplabcut.create_training_dataset?`

**Comment by natalier11** [comment]
I've been using the GUI to do everything but this is what the Anaconda Prompt displays one I try to create the network, not sure fi this is what you're asking for. 
![Create Training Set Input](https://user-images.githubusercontent.com/73397911/97757211-4e0b2000-1aca-11eb-8995-ec850eed9148.png)

**Comment by MMathisLab** [comment]
So it looks like from the error message, your labeled data is gone,
