### ISSUE TITLE
Could not Train the Network

### ISSUE THREAD

**Issue by npranav9** [DeepLabCut/DeepLabCut#994]
OS: Windows 10 OS
DeepLabCut Version: DeepLabCut 2.1.8.1
Anaconda env used: DLC-GPU-DC

**Describe the problem**
I'm trying to run the resnet_50 network on a set of DLC-labeled images of a mouse. After successfully creating the training dataset, I try to train the network for 100000 iterations. Once I click "OK", I get an error of the pose_cfg.yaml file not being found. I'm not sure why, because the file does exist and the path variables have been edited to be correct. 

<details><summary>Code output</summary><p>

The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
Traceback (most recent call last):
  File "/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/deeplabcut/gui/train_network.py", line 268, in train_network
    maxiters=maxiters)
  File "/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 134, in train_network
    raise e
  File "/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 132, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
  File "/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 111, in train
    cfg = load_config(config_yaml)
  File "/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/config.py", line 56, in load_config
    return cfg_from_file(filename)
  File "/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/config.py", line 42, in cfg_from_file
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pnambiar/dlc/dannenberg1_2710/dlc-models/iteration-0/hdan_vid1Oct27-trainset95shuffle1/train/pose_cfg.yaml'

</p></details>

**How to Reproduce the problem**
1. Launch DeepLabCut
2. Load already labeled DeepLabCut project
3. Click on "Train Network"
4. Reset Number of Iterations = 10000
5. See error: FileNotFound

**Screenshots**
![image](https://user-images.githubusercontent.com/18171814/99158891-c4507a80-26a5-11eb-86af-de89b949c053.png)

**Additional context**
This project is being executed through a remote connection to a desktop. If the issue cannot be from DLC then, this may be the source.

**Comment by MMathisLab** [comment]
Are you sure you created shuffle 1? What happens if you set it to 0? I would also upgrade to 2.2b8, many many new and nicer features 👍

**Comment by MMathisLab** [comment]
(alternatively, you did not create a training dataset first, then it cannot train)

**Comment by npranav9** [comment]
I was able to get it to work, was a problem with path specification on the remote desktop. 
Thank you

**Comment by nvd1** [comment]
Hi @npranav9, I'm having a similar issue with my remote desktop. How did you resolve your path specification issues? Thank you in advance!

**Comment by npranav9** [comment]
Hi @nvd1, for me each path variable was needed in full, including the pose_config file. Also the remote desktop switched me into a copy parent directory. If these don't solve the issue, then I would check the project folders for missing/incorrect files.
